### ISSUE TITLE
Position Bubble label on top left corner when hovering

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#100]
When hovering a non sleeted bubble, the hover text label should show to the top left, (currently it his hidden under the cursor. Makes it's appearance identical in fontsize and position, to the selected label that will stick, if I click the bubble,
![image](https://cloud.githubusercontent.com/assets/496398/7145404/57ae7bfa-e2ec-11e4-8109-d86e7480e96f.png)

**Comment by arthurcamara1** [comment]
Similar to Gapminder World (top left of bubble when hovering india):

![image](https://cloud.githubusercontent.com/assets/3584238/8519028/96e789dc-23cf-11e5-9dc8-1825013071ff.png)
