### ISSUE TITLE
v0.8.9_07: Option does not match with the available dropdown 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1000]
**SEVERITY:**  Minor

**MODULE:** Bubble chart

**Platform:**  Windows 7 / Chrome 46.0

**RELEASE:** v0.8.9

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.8.9/preview/bubblechart.html
2)	Bubble chart will be loaded.
3)	Click “Full” under RESPONSIVENESS
4)	Click “Color”
5)	Click dropdown box. Tree menu is displayed.
6)	Select “constant”.
7)	Again click “Color” and drop down and select “Region”
8)	Note that pop up screen of color remains on a while and in that screen option does not match with the available dropdown

**ACTUAL RESULTS:**
Option does not match with the available dropdown

**EXPECTED RESULTS:**
After changing the dropdown options, the change should be appeared on the pop up screen instantly

**SCREENSHOT:**

![v0 8 9_07](https://cloud.githubusercontent.com/assets/9950837/11335671/018f3c50-9200-11e5-8a36-09dcdcb3c5ae.png)

**Comment by angieskazka** [comment]
couldn't reproduce. is this still an issue?

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Testing Environment:** http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html
