### ISSUE TITLE
v0.8.9_11: ‘Log’ option is not selectable

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1006]
**SEVERITY:** Major

**MODULE:** Bubble Chart

**Platform:** MAC / Safari 9.0

**RELEASE:** v0.8.9

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.9/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Click Y axis description
4)	Click ‘log’ option which is given on right top corner of the pop up screen
5)	Note that ‘Log’ option is not selectable

**ACTUAL RESULTS:**
‘Log’ option is not selectable 

**EXPECTED RESULTS:** 
‘Log’ option should be selectable 

**SCREENSHOT:**

![v0 8 9_11](https://cloud.githubusercontent.com/assets/9950837/11366330/7be3bffc-92ce-11e5-8537-207618de9957.png)

**Comment by angieskazka** [comment]
couldn't reproduce, sorry

**Comment by angieskazka** [comment]
@dab2000 can you please check that for bar chart?

**Comment by angieskazka** [comment]
ok, fixed for bar chart too
