### ISSUE TITLE
v0.8.9_12: ‘Constant’ option is truncated in landscape view

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1007]
**SEVERITY:** Major

**MODULE:** Bubble Chart

**Platform:** MAC / Safari 9.0

**RELEASE:** v0.8.9

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.9/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Click “Landscape” view under RESPONSIVENESS
4)	Click “Color” options
5)	Note that ‘Constant’ option is truncated

**ACTUAL RESULTS:**
‘Constant’ option is truncated in landscape view

**EXPECTED RESULTS:** 
‘Constant’ option should not truncate in landscape view

**SCREENSHOT:**

![v0 8 9_12](https://cloud.githubusercontent.com/assets/9950837/11366366/a81f9596-92ce-11e5-83ad-5da28576a63a.png)

**Comment by angieskazka** [comment]
that looks very wrong ))) maybe we can `overflow: scroll` it together with the accordeon?
