### ISSUE TITLE
v0.8.9_13: Slider bar is disturbed by changing orientation of screen

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1008]
**SEVERITY:** Major

**MODULE:** Bubble Chart

**Platform:** MAC / Safari 9.0

**RELEASE:** v0.8.9

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.9/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Select a country. For example we select China
4)	Click Play
5)	Click “Landscape” view under RESPONSIVENESS without stopping the Pause button
6)	Note that slider bar is disturbed

**ACTUAL RESULTS:**
Slider bar is disturbed by changing orientation of screen 

**EXPECTED RESULTS:** 
Slider bar should not be disturbed by changing orientation of screen 

**SCREENSHOT:**

![v0 8 9_13](https://cloud.githubusercontent.com/assets/9950837/11366401/de850df0-92ce-11e5-8a45-9cfa58c55492.png)

**Comment by angieskazka** [comment]
can not reproduce. can anyone?

**Comment by k6Labz** [comment]
Retest Result: Pass

Platform: MAC / Safari 9.0

Testing Environment: http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html

@angieskazka 
But this bug can still reproduceable on MAC / Safari 8.0.
