### ISSUE TITLE
hover selected bubble label, show deselect cross

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#101]
When hovering a label of a selected trail7bubble, show a deselect cross that can be pressed to deselect that entity. The cross should be at the end of the name,
![image](https://cloud.githubusercontent.com/assets/496398/7145460/979da966-e2ec-11e4-8459-e397c392eb92.png)

**Comment by angieskazka** [comment]
Good. it's a better idea than double clicking the label, which i use now
(it requires distinguishing "click" and "double click" which is not done, so it's not working ;)

**Comment by angieskazka** [comment]
done
