### ISSUE TITLE
v0.8.9_15: Cross symbol ‘x’ is missing

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1010]
**SEVERITY:** Major

**MODULE:** Mountain Chart

**Platform:** MAC / Safari 9.0

**RELEASE:** v0.8.9

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.9/preview/mountainchart.html 
2)	Mountain chart page will be loaded
3)	Select a country. For example we select China. 
4)	Selected country is shown on top left with the population of that country
5)	Take the mouse to the population. A small circle is shown to remove this population
6)	Note that cross symbol ‘x’ is missing there

**ACTUAL RESULTS:**
Cross symbol ‘x’ is missing on population of the country

**EXPECTED RESULTS:** 
Cross symbol ‘x’ should be there for better understanding to deselect the country

**SCREENSHOT:**

![v0 8 9_15](https://cloud.githubusercontent.com/assets/9950837/11366480/4c35ceac-92cf-11e5-8f13-0ea44a0d62f0.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1042
