### ISSUE TITLE
v0.8.9_16: Axis values are not shown on proper place

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1011]
**SEVERITY:** Minor

**MODULE:** Line Chart

**Platform:** MAC / Safari 9.0

**RELEASE:** v0.8.9

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.9/preview/linechart.html 
2)	Line chart page will be loaded
3)	Take the mouse to the year which is shown at the end on the X axis, which is 2012.
4)	Note that on the top of the Y axis, the values are shown there for a while

**ACTUAL RESULTS:**
By hovering the country year on X axis, the values are shown there for a while on the top of the Y axis

**EXPECTED RESULTS:** 
Axis value should not appear on the top of y axis but it should be on its proper place on the axis

**SCREENSHOT:**

![v0 8 9_16](https://cloud.githubusercontent.com/assets/9950837/11366503/7a233908-92cf-11e5-9b77-0c3da12eafeb.png)

**Comment by angieskazka** [comment]
@k6Labz still an issue?

**Comment by k6Labz** [comment]
**Retest Result:** Fail

**Testing Environment:** http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html

**Platform:** MAC / Safari 9.0

**Comment by sergey-filipenko** [comment]
@k6Labz tested on different macs bu can not reproduce on develop (partially reproduced on v.0.8.9). Please provide more information how I can debug this

**Comment by k6Labz** [comment]
@sergey-filipenko 
**Platform:** MAC OS X El Captain (10.11.1) / Safari 9.0

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.9/preview/linechart.html 
2)	Line chart page will be loaded
3)	**Take the mouse to** the year which is shown at the **end of the X axis**, which is 2012.
4)	Note that **on the top of the Y axis, the values are shown there just for a while**

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1292

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Platform:** iPhone-4G(iOS 7.1.2)/ Safari

**Testing Environment:** http://static.gapminderdev.org/vizabi/develop/preview/bubblemap.html
