### ISSUE TITLE
v0.8.9_17: ‘Present’ button is faded out and not functional 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1015]
**SEVERITY:**  Major

**MODULE:** Bubble map chart

**Platform:**  
* Windows 7 / Chrome 46.0
* MAC / Chrome 46.0

**RELEASE:** Develop

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/develop/preview/bubblemap.html 
2)	Bubble map chart will be loaded.
3)	Note that ‘Present’ button is faded out
4)	Now click on ‘Present’ button
5)	Note that ‘Present’ button is not functional

**ACTUAL RESULTS:**
‘Present’ button is faded out and not functional 

**EXPECTED RESULTS:**
‘Present’ button should not faded out and should be functional after loading 

**SCREENSHOT:**

![v0 8 9_17](https://cloud.githubusercontent.com/assets/9950837/11390310/b4dc1470-936a-11e5-8b73-ddf66728ef9e.png)

**Comment by angieskazka** [comment]
it’s ok, we disable it in small profile
