### ISSUE TITLE
v0.8.9_18: Tool tip is truncated by hovering the bubble  

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1016]
**SEVERITY:**  Major

**MODULE:** Bubble map chart

**Platform:**  
* Windows 7 / Chrome 46.0
* MAC / Chrome 46.0

**RELEASE:** Develop

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/develop/preview/bubblemap.html 
2)	Bubble map chart will be loaded.
3)	Take mouse to the biggest green bubble which represents ‘Unite States’
4)	Note that tool tip of ‘United States’ is truncated by hovering effect or by selecting it

**ACTUAL RESULTS:**
Tool tip of ‘United States’ is truncated by hovering effect or by selecting it

**EXPECTED RESULTS:**
Tool tip of ‘United States’ should not be truncated by hovering effect or by selecting it 

**SCREENSHOT:**

![v0 8 9_18](https://cloud.githubusercontent.com/assets/9950837/11390321/d5b1fac0-936a-11e5-819a-863b28ad1f91.png)

**Comment by angieskazka** [comment]
Make tooltip positioned relative to bubble, not to cursor. Avoid awkward positioning
See bubble chart
