### ISSUE TITLE
v0.8.9_19: Selected countries are not arranged according to the population or regions  

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1017]
**SEVERITY:**  Minor

**MODULE:** Bubble map chart

**Platform:**  
* Windows 7 / Chrome 46.0
* MAC / Chrome 46.0

**RELEASE:** Develop

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/develop/preview/bubblemap.html 
2)	Bubble map chart will be loaded.
3)	Select many countries from different regions. Selected countries are shown on left side with the population
4)	Note that selected countries are not arranged according to the population or regions  

**ACTUAL RESULTS:**
Selected countries are not arranged according to the population or regions  

**EXPECTED RESULTS:**
Selected countries should be arranged according to the population or regions  

**SCREENSHOT:**

![v0 8 9_19](https://cloud.githubusercontent.com/assets/9950837/11390335/f79419d4-936a-11e5-941b-86060af79a85.png)

**Comment by angieskazka** [comment]
We've discarded the select list for now
