### ISSUE TITLE
v0.8.9_20: Slider bar for opacity of non-selected bubbles , is not functional

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1018]
**SEVERITY:**  Major

**MODULE:** Bubble map chart

**Platform:**  
* Windows 7 / Chrome 46.0
* MAC / Chrome 46.0

**RELEASE:** Develop

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/develop/preview/bubblemap.html 
2)	Bubble map chart will be loaded.
3)	Click Expand
4)	Select a country bubble
5)	A slider bar for opacity of non-selected bubbles is shown under ‘Find’ option
6)	Drag the slider ball from that slider bar to change the opacity of non-selected bubbles
7)	Note that Slider bar for opacity of non-selected bubbles, is not functional

**ACTUAL RESULTS:**
Slider bar for opacity of non-selected bubbles, is not functional 

**EXPECTED RESULTS:**
Slider bar for opacity of non-selected bubbles should be functional 

**SCREENSHOT:**

![v0 8 9_20](https://cloud.githubusercontent.com/assets/9950837/11390346/1ad9cba0-936b-11e5-9c1d-87471eddc377.png)

**Comment by angieskazka** [comment]
the event listener is missing (see bubble chart for example)
