### ISSUE TITLE
v0.8.9_21: Menu tree is truncated

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1019]
**SEVERITY:**  Major

**MODULE:** Bubble map chart

**Platform:**  
* Windows 7 / Chrome 46.0
* MAC / Chrome 46.0

**RELEASE:** Develop

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/develop/preview/bubblemap.html 
2)	Bubble map chart will be loaded.
3)	Click ‘Size’. A small pop up screen is displayed
4)	Click the drop down and select ‘log’, which is available on right top of the pop up screen
5)	Now take mouse to the ‘Wealth’ or ‘Health’ option
6)	Note that menu tree is truncated

**ACTUAL RESULTS:**
Menu tree is truncated by changing the size from ‘linear’ to ‘log’

**EXPECTED RESULTS:**
Menu tree should not truncate in any case 

**SCREENSHOT:**

![v0 8 9_21](https://cloud.githubusercontent.com/assets/9950837/11390363/395155d0-936b-11e5-82fa-d62d99b35177.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1027
