### ISSUE TITLE
v0.8.9_22: Selected bubble is slightly truncated 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1020]
**SEVERITY:**  Minor

**MODULE:** Bubble map chart

**Platform:**  
* Windows 7 / Chrome 46.0
* MAC / Chrome 46.0

**RELEASE:** Develop

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/develop/preview/bubblemap.html 
2)	Bubble map chart will be loaded.
3)	Click ‘Find’ and select “Fiji”
4)	Click ‘Size’. A small pop up screen is displayed
5)	Click ‘Health’
6)	Select ‘Child mortality rate’
7)	Click OK
8)	Note that selected bubble is slightly truncated

**ACTUAL RESULTS:**
Selected bubble is slightly truncated by changing the size

**EXPECTED RESULTS:**
Any bubble should not be truncated in any case

**SCREENSHOT:**

![v0 8 9_22](https://cloud.githubusercontent.com/assets/9950837/11390377/554622e8-936b-11e5-812e-64421180f420.png)

![image](https://cloud.githubusercontent.com/assets/3648190/11447357/39365f74-9545-11e5-9dee-774154d2faa5.png)

**Comment by angieskazka** [comment]
make a slightly bigger right margin. top and bottom margins can be a bit smaller

**Comment by angieskazka** [comment]
see also #1039
