### ISSUE TITLE
v0.8.9_23: Tool tip is shown twice for a bubble  

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1021]
**SEVERITY:**  Minor

**MODULE:** Bubble map chart

**Platform:**  
* Windows 7 / Chrome 46.0
* MAC / Chrome 46.0

**RELEASE:** Develop

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/develop/preview/bubblemap.html 
2)	Bubble map chart will be loaded.
3)	Select any country. A tooltip is shown for the selected country
4)	Take mouse to that country bubble
5)	Note that Tool tip is shown twice for a bubble 

**ACTUAL RESULTS:**
Tool tip is shown twice for a bubble. One tool tip is for selected bubble and the other one is for hovering effect 

**EXPECTED RESULTS:**
Only one tooltip should be shown. Hovering tooltip should be there but when we select any bubble then for that bubble the hovering tooltip should be disable because there is already a tooltip for that selected bubble

**SCREENSHOT:**

![v0 8 9_23](https://cloud.githubusercontent.com/assets/9950837/11390476/577b468c-936c-11e5-88c5-d13646441d3c.png)

**Comment by angieskazka** [comment]
don't show tooltip on a selected bubble
