### ISSUE TITLE
v0.8.9_24: Slider ball should be there on slide bar instead of rectangle

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1022]
**SEVERITY:**  Minor

**MODULE:** Bubble map chart

**Platform:**  Windows 7 / Chrome 46.0

**RELEASE:** Develop

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/develop/preview/bubblemap.html 
2)	Bubble map chart will be loaded.
3)	Click ‘Find’
4)	Select a country from given countries
5)	After selecting a country a slider bar is shown under the find option, to control the opacity of non-selected country bubbles
6)	Note that there is rectangle on that slider bar instead of slider ball  

**ACTUAL RESULTS:**
There is rectangle on slider bar instead of slider ball  

**EXPECTED RESULTS:**
Slider ball should be there on the slide bar instead of rectangle  

**SCREENSHOT:**

![v0 8 9_24](https://cloud.githubusercontent.com/assets/9950837/11390578/5f98fa8e-936d-11e5-9dc6-84559e8dfed7.png)

**Comment by angieskazka** [comment]
slider CSS changed somehow, so now it doesn't work on windows

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1028
