### ISSUE TITLE
v0.8.9_26: OK is missing on pop up of Y-axis 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1026]
**SEVERITY:** Major

**MODULE:** Bubble Chart

**Platform:** 
* Windows 7 / Chrome 46.0
* Windows 7 / Firefox 43.0
* iPad Air 2 iOS(9.1) / Chrome 43.0

**RELEASE:** v0.8.9

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.9/preview/popbyage.html  
2)	Bubble chart page will be loaded
3)	Click X axis or Y-axis description. A pop up screen is displayed
4)	Note that OK is missing on that pop up screen

**ACTUAL RESULTS:**
OK is missing on pop up of Y-axis and X-axis

**EXPECTED RESULTS:** 
OK should be there on pop up of Y-axis 

**SCREENSHOT:**

![v0 8 9_26](https://cloud.githubusercontent.com/assets/9950837/11416945/3288d16e-9434-11e5-95f3-93c64d984dd7.png)

**Comment by angieskazka** [comment]
we were not supposed to have it either. but perhaps we need to make this popup look like a combobox list more than like a dialog
