### ISSUE TITLE
v0.8.9_27: Bubbles sizes are not changed according to the year

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1029]
**SEVERITY:** Major

**MODULE:**  Bubble map Chart

**Platform:** iPhone-4G(iOS 7.1.2)/ Safari

**RELEASE:**  Develop

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/develop/preview/bubblemap.html
2)	Bubble map chart page will be loaded
3)	Select a country
4)	Tap play. Let the slider ball reached the end
5)	Tap again on play
6)	Note that bubbles sizes are not changed according to the year

**ACTUAL RESULTS:**
Bubbles sizes are not changed according to the year 

**EXPECTED RESULTS:** 
Bubbles sizes should be changed according to the year

**SCREENSHOT:**

![v0 8 9_27](https://cloud.githubusercontent.com/assets/9950837/11422119/4641059c-945b-11e5-924d-3d0f58df2e4b.PNG)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1105

**Comment by k6Labz** [comment]
**Retest Result:** Fail

**Platform:** iPhone-4G(iOS 7.1.2)/ Safari

**Testing Environment:** http://static.gapminderdev.org/vizabi/develop/preview/bubblemap.html

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1115

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Platform:** iPhone-4G(iOS 7.1.2)/ Safari

**Testing Environment:** http://static.gapminderdev.org/vizabi/develop/preview/bubblemap.html

**Comment by k6Labz** [comment]
@angieskazka 
**Retest Result:** Pass

**Platform:** iPhone-4G(iOS 7.1.2)/ Safari

**Testing Environment:** http://stage-tools.gapminderdev.org/tools/map

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1226

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1289

**Comment by jdk137** [comment]
I've tested on mac's safari and chrome, the bug does not show. Could the bug only show in iphone or the bug is an illusion caused by data. Because in the first 100 years, only European countries change a little, most countries like China and India only change apparently in the last 100 years.

**Comment by sergey-filipenko** [comment]
@jdk137 Bug show on slow devices like iPhone4G

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1289

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Platform:** iPhone-4G(iOS 7.1.2)/ Safari

**Testing Environment:** http://static.gapminderdev.org/vizabi/develop/preview/bubblemap.html
