### ISSUE TITLE
v0.8.9_28: Drop down box is truncated from upper side

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1030]
**SEVERITY:** Minor

**MODULE:**  Bubble map Chart

**Platform:** iPhone-4G(iOS 7.1.2)/ Safari

**RELEASE:**  Develop

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi /preview/bubblemap.html 
2)	Bubble map chart page will be loaded
3)	Tap “Find”
4)	Note that drop down box for search is truncated from upper side

**ACTUAL RESULTS:**
Drop down box for search is truncated from upper side 

**EXPECTED RESULTS:** 
Drop down box for search should not be truncated 

**SCREENSHOT:**

![v0 8 9_28](https://cloud.githubusercontent.com/assets/9950837/11422146/7f26ff74-945b-11e5-8634-638e26e90a26.PNG)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1074
