### ISSUE TITLE
v0.8.9_30: Options are truncated on small screen

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1032]
**SEVERITY:** Minor

**MODULE:**  Bubble map Chart

**Platform:**
* Windows 7 / Chrome 46.0
* iPhone-4G(iOS 7.1.2)/ Safari

**RELEASE:**  Develop

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi /preview/bubblemap.html 
2)	Bubble map chart page will be loaded
3)	Tap “Color”. Click drop down box and tap “Properties”
4)	Note that options are truncated from bottom

**ACTUAL RESULTS:**
Options are truncated on small screen 

**EXPECTED RESULTS:** 
A scroll bar should be available to view the truncated options

**SCREENSHOT:**

![v0 8 9_30](https://cloud.githubusercontent.com/assets/9950837/11422185/be30d668-945b-11e5-8f30-90087ff864cf.PNG)

**Comment by angieskazka** [comment]
same as #1007, fixed now
