### ISSUE TITLE
v0.9.0_01: Tooltip cross symbol ‘x’ is overlapping with the text 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1035]
**SEVERITY:** Minor

**MODULE:** Stage 

**Platform:** 
* Windows 7 / Chrome 46.0
* Windows 7 / Firefox 43.0
* MAC / Safari 9.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: https://stage-tools.gapminderdev.org/tools/ 
2)	Tools page is loaded.
3)	Select a country. For example we select “China”
4)	Drag the tooltip to the right most to the text on the chart
5)	By hovering effect the cross symbol is displayed
6)	Note that tooltip cross symbol ‘x’ is overlapping with the text

**ACTUAL RESULTS:**
Tooltip cross symbol ‘x’ is overlapping with the text 

**EXPECTED RESULTS:** 
Tooltip cross symbol ‘x’ should not overlap with the text 

**SCREENSHOT:**

![v0 9 0_01](https://cloud.githubusercontent.com/assets/9950837/11435185/2c732804-94f9-11e5-918b-fe2bbf3d0d89.png)

**Comment by angieskazka** [comment]
only happens on hover. not bad enough to care )
