### ISSUE TITLE
States are too verbos.. 

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#1048]
Currently the states contain properties and values which are identical to the default state. Before the state gets serialized into the url, it shoul dbe strippe dof any value which is identical to the default.

http://www.gapminder.org/tools/mountain#_entities_select@_geo=chl&labelOffset@:0&:0;;&_geo=khm&labelOffset@:0&:0;;&_geo=bwa&labelOffset@:0&:0;;;&needUpdate_;;&marker_axis%2F_y_min:0&max:2568192312.136342&fakeMin:0&fakeMax:2568192312.136342;&axis%2F_x_fakeMin:0.11&fakeMax:500;&color_palette_asi=%23FF5872&eur=%23FFE700&ame=%237FEB00&afr=%2300D5E9&%2F_default=%23ffb600

**Comment by arthurcamara1** [comment]
That's funny, this should be fixed already

**Comment by angieskazka** [comment]
Should have been re-fixed by the Yule goat
