### ISSUE TITLE
Massive refactoring of buttonlist and dialog styles [in testing]

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#1049]
there is a complicated mess with dialog styles:

some styles are in respective .scss files, like _colors.scss
some styles are in _dialog.scss
some are in _buttonlist.scss
some are in _main.scss

everything is so complicated a devil can break a leg if going there

please refactor all the styles so that they become more logical and clean
specific styles should be in separate files
generic styles for dialog should be in dialog, separate from the buttonlist, also not in main
buttonlist should only have styles for buttonlist

also try to carefully keep all the bug fixes we did in the last month, so that nothing breaks during this magical refactoring

https://pbs.twimg.com/tweet_video/CShZFMeUwAA1CZF.mp4

**Comment by k6Labz** [comment]
**SUMMARY:**  Tree menu is missing on full screen

**SEVERITY:**  Major

**MODULE:** Mountain chart

**Platform:**  Windows 7 / Chrome 46.0

**RELEASE:** Develop

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/develop/preview/mountainchart.html 
2)	Mountain chart will be loaded.
3)	Click “Full” under RESPONSIVENESS
4)	Click “Color”
5)	Click drop down box
6)	Click Properties or wealth.
7)	Note that tree menu is not displayed

**ACTUAL RESULTS:**
Tree menu is not displayed 

**EXPECTED RESULTS:**
Tree menu should be available 

**SCREENSHOT:**

![v0 9 0_14](https://cloud.githubusercontent.com/assets/9950837/11498914/32fc995a-9844-11e5-866a-4653d130a92a.png)

**Comment by angieskazka** [comment]
this happened (chrome 46 / mac)

![image](https://cloud.githubusercontent.com/assets/3648190/11499171/66f4fb1e-9824-11e5-92f3-7b789894b3d4.png)

**Comment by k6Labz** [comment]
**SUMMARY:**  Color scale is missing on expanded screen
**SEVERITY:**  Major
**MODULE:** Mountain chart
**Platform:**  Windows 7 / Chrome 46.0
**RELEASE:** Develop
**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/develop/preview/mountainchart.html 
2)	Mountain chart will be loaded.
3)	Click “Expand”
4)	Note that color scale is missing on expanded screen
**ACTUAL RESULTS:**
Color scale is missing on expanded screen 
**EXPECTED RESULTS:**
Color scale should not miss on expanded screen 
**SCREENSHOT:**
![v0 9 0_15](https://cloud.githubusercontent.com/assets/9950837/11499190/17f2aeb8-9846-11e5-8a32-aa675cda1bbb.png)

**Comment by k6Labz** [comment]
**SUMMARY:** “Deselect All” and “OK” are missing
**SEVERITY:**  Major
**MODULE:** Mountain chart
**Platform:**  Windows 7 / Chrome 46.0
**RELEASE:** Develop
**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/develop/preview/mountainchart.html 
2)	Mountain chart will be loaded.
3)	Click “Expand”
4)	Select countries
5)	Note that “Deselect All” and “OK” are missing
**ACTUAL RESULTS:**
“Deselect All” and “OK” are missing 
**EXPECTED RESULTS:**
“Deselect All” and “OK” should be available
**SCREENSHOT:**
![v0 9 0_16](https://cloud.githubusercontent.com/assets/9950837/11499283/c9d05fcc-9846-11e5-9813-d230a0f2c8cb.png)

**Comment by k6Labz** [comment]
I think this issue is reproduced again after refactoring

![comment 1049](https://cloud.githubusercontent.com/assets/9950837/11499540/8f96f12a-9848-11e5-93fb-2c9660d0f094.png)

**Comment by k6Labz** [comment]
**SUMMARY:** Text is truncated

**SEVERITY:**  Minor

**MODULE:** Mountain chart

**Platform:**  Windows 7 / Chrome 46.0

**RELEASE:** Develop

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/develop/preview/mountainchart.html 
2)	Mountain chart will be loaded
3)	Click data warning
4)	Scroll down
5)	Note that  text is truncated

**ACTUAL RESULTS:**
Text is truncated on data warning pop up

**EXPECTED RESULTS:**
Text should not be truncated

**SCREENSHOT:**

![v0 9 0_17](https://cloud.githubusercontent.com/assets/9950837/11499680/a104e538-9849-11e5-966f-05959f66d480.png)

**Comment by k6Labz** [comment]
**SUMMARY:** Pop up screen is truncated on landscape 

**SEVERITY:**  Major

**MODULE:** Mountain chart

**Platform:**  Windows 7 / Chrome 46.0

**RELEASE:** Develop

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/develop/preview/mountainchart.html 
2)	Mountain chart will be loaded
3)	Click “Landscape” button under REPONSIVENESS
4)	Click “Show”
5)	Note that pop up screen is truncated on landscape

**ACTUAL RESULTS:**
Pop up screen is truncated on landscape 

**EXPECTED RESULTS:**
Pop up screen should not be truncated in any case

**SCREENSHOT:**
![v0 9 0_18](https://cloud.githubusercontent.com/assets/9950837/11499980/d70a80a0-984b-11e5-8a44-3946daebe942.png)

**Comment by k6Labz** [comment]
**SUMMARY:** Text is overlapping 

**SEVERITY:**  Minor

**MODULE:** Bubble map chart

**Platform:**  Windows 7 / Chrome 46.0

**RELEASE:** Develop

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/develop/preview/bubblemap.html 
2)	Bubble map chart will be loaded
3)	Click “Color”
4)	Click dropdown then “Wealth” and select “GDP per capita”
5)	Note that text is overlapping on Y axis description

**ACTUAL RESULTS:**
Text is overlapping on Y axis description 

**EXPECTED RESULTS:**
Text should not overlap in any case

**SCREENSHOT:**

![v0 9 0_19](https://cloud.githubusercontent.com/assets/9950837/11500212/77a143ea-984d-11e5-9bfa-2d81c1ccf2f0.png)

**Comment by k6Labz** [comment]
**SUMMARY:** Text is overlapping with search bar on landscape

**SEVERITY:**  Minor

**MODULE:** Bubble map chart

**Platform:**  Windows 7 / Chrome 46.0

**RELEASE:** Develop

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/develop/preview/bubblemap.html 
2)	Bubble map chart will be loaded
3)	Click “Landscape” button under REPONSIVENESS
4)	Click “Find”
5)	Scroll down 
6)	Note that all the countries which have long names, are overlapping with the search bar

**ACTUAL RESULTS:**
All the countries which have long names, are overlapping with the search bar on landscape

**EXPECTED RESULTS:**
Text should not overlap in any case

**SCREENSHOT:**

![v0 9 0_20](https://cloud.githubusercontent.com/assets/9950837/11500544/9bcb6e56-984f-11e5-8536-83519a1e1cc0.png)

**Comment by k6Labz** [comment]
**SUMMARY:** X axis options are not functional

**SEVERITY:**  Critical

**MODULE:** Pop by age chart

**Platform:**  Windows 7 / Chrome 46.0

**RELEASE:** Develop

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/develop/preview/popbyage.html 
2)	Pop by age map chart will be loaded
3)	Click X-axis description
4)	Click any option in tree menu
5)	Note that X axis options are not functional

**ACTUAL RESULTS:**
X axis options are not functional 

**EXPECTED RESULTS:**
X axis options should be functional 

**SCREENSHOT:**

![v0 9 0_21](https://cloud.githubusercontent.com/assets/9950837/11500780/1befa61e-9851-11e5-953d-a015ebafd6d0.png)
