### ISSUE TITLE
v0.9.0_07: Values for min and max on size scale are missing

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1050]
**SEVERITY:**  Minor

**MODULE:** Bubble chart

**Platform:**  Windows 7 / Chrome 46.0

**RELEASE:** v0.9.0

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.9.0/preview/bubblechart.html
2)	Bubble chart will be loaded.
3)	Click “Full” under RESPONSIVENESS
4)	Click “Size”
5)	Note that values are missing for min and max size

**ACTUAL RESULTS:**
Values are missing for min and max size

**EXPECTED RESULTS:**
Values should be available for min and max size

**SCREENSHOT:**

![v0 9 0_07](https://cloud.githubusercontent.com/assets/9950837/11464983/bc3313dc-9756-11e5-9084-512870192110.png)

**Comment by angieskazka** [comment]
promise is resolved before "afterLoad" action finished sometimes on some machines
(it's true. if i switch the two i can reproduce the bug exactly)

![image](https://cloud.githubusercontent.com/assets/3648190/11719748/74f119f2-9f5c-11e5-952c-a17ce263d36d.png)

**Comment by jheeffer** [comment]
Hmm, that would mean there is some async code in afterLoad, other promises or async loading? That's not the case is it?

**Comment by angieskazka** [comment]
it has Events.unfreezeAll(), and that might contain hell knows what, anything of what you named

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1138

**Comment by angieskazka** [comment]
yes!
