### ISSUE TITLE
v0.9.0_09: Population should be available for selected country like Mountain chart 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1052]
**SEVERITY:**  Minor

**MODULE:** Bubble map chart

**Platform:**  Windows 7 / Chrome 46.0

**RELEASE:** v0.9.0

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.9.0/preview/bubblemap.html 
2)	Bubble map chart will be loaded.
3)	Click “Full” under RESPONSIVENESS
4)	Select any country 
5)	Note that no population is available for selected country

**ACTUAL RESULTS:**
No population is available for selected country 

**EXPECTED RESULTS:**
Population should be available for selected country like Mountain chart 

**SCREENSHOT:**

![v0 9 0_09](https://cloud.githubusercontent.com/assets/9950837/11465717/d653409c-975c-11e5-804c-75bdcb3244e4.png)

**Comment by angieskazka** [comment]
@k6Labz thanks for insisting! 
@olarosling doesn't want the select list, but we can do the following:

![x7vt5zg2x8](https://cloud.githubusercontent.com/assets/3648190/11471167/919bb19e-9763-11e5-9224-313b2f1b40be.gif)
