### ISSUE TITLE
v0.9.0_13: Drop down arrow is over lapping with the color picker  

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1060]
**SEVERITY:** Major

**MODULE:**  Pop by age Chart

**Platform:** 
* iPad Air 2 iOS(9.1) / Chrome 43.0
* Nexus 9 (5.1) / Chrome 46.0
* Windows 7 / Chrome 46.0
* Windows 7 / Firefox 43.0

**RELEASE:** v0.9.0

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL: http://static.gapminderdev.org/vizabi/release/v0.9.0/preview/popbyage.html
2)	Pop by age chart will be loaded.
3)	Tap “Color”
4)	Tap Drop down and select “Constant”
5)	Again tap “Color”
6)	Tap colored circle to change the color. 
7)	Color picker is displayed
8)	Note that drop down arrow is over lapping with the color picker  

**ACTUAL RESULTS:**
Drop down arrow is over lapping with the color picker  

**EXPECTED RESULTS:**
 Drop down arrow should not overlap with the color picker    

**SCREENSHOT:**

![v0 9 0_13](https://cloud.githubusercontent.com/assets/9950837/11494039/98a76024-9820-11e5-8a45-e5883647f192.png)

**Comment by angieskazka** [comment]
fixed in 31a5623e97a4edbe4ff7072daf6c933abba92535
