### ISSUE TITLE
Bubble map performance // Delayed Dragging Time slider for map

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#1062]
When pulling the timeslider-knowb the map bubbles, update slower than the other charts. There's a feeling of heavy burden, when pulling time back and for on the map.

**Comment by angieskazka** [comment]
@jdk137 start from not rebinding the .data(items) every time (see other charts)
then the further optimisation is to request all data for all years when indicator is changed and operate with it locally (see bubble chart)

![image](https://cloud.githubusercontent.com/assets/3648190/11496079/00a72d0a-9810-11e5-9a55-a57687c47bfc.png)
