### ISSUE TITLE
v0.9.0_22: Large extra space is there on expanded screen

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1076]
**SEVERITY:**  Minor

**MODULE:** Mountain chart

**Platform:**  Windows 7 / Chrome 46.0

**RELEASE:** Develop

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/develop/preview/mountainchart.html 
2)	Mountain chart will be loaded
3)	Click “Expand”
4)	Note that large extra space is there on the right panel on expanded screen

**ACTUAL RESULTS:**
Large extra space is there on the right panel on expanded screen 

**EXPECTED RESULTS:**
No extra space should be there

**SCREENSHOT:**

![v0 9 0_22](https://cloud.githubusercontent.com/assets/9950837/11523311/1ad107ea-98e3-11e5-9c5b-3dfdcd5ab6f8.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1085
