### ISSUE TITLE
v0.9.0_24: ‘Pin’ and ‘Drag’ icons are missing on “Stack” pop up screen

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1078]
**SEVERITY:**  Major

**MODULE:** Mountain chart

**Platform:**  Windows 7 / Chrome 46.0

**RELEASE:** Develop

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/develop/preview/mountainchart.html 
2)	Mountain chart will be loaded
3)	Click “Expand”
4)	Click “Stack”
5)	Note that ‘Pin’ and ‘Drag’ icons are missing on “Stack” pop up screen

**ACTUAL RESULTS:**
‘Pin’ and ‘Drag’ icons are missing on “Stack” pop up screen 

**EXPECTED RESULTS:**
‘Pin’ and ‘Drag’ icons should be available on “Stack” pop up screen 

**SCREENSHOT:**

![v0 9 0_24](https://cloud.githubusercontent.com/assets/9950837/11523348/677d7cd6-98e3-11e5-9bcc-c4b2daa465e1.png)

**Comment by sergey-filipenko** [comment]
related to https://github.com/Gapminder/vizabi/issues/1076
