### ISSUE TITLE
v0.9.0_25: Pop up screen is disturbed by clicking ‘Restore’

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1079]
**SEVERITY:**  Major

**MODULE:** Mountain chart

**Platform:**  Windows 7 / Chrome 46.0

**RELEASE:** Develop

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/develop/preview/mountainchart.html 
2)	Mountain chart will be loaded
3)	Click “Expand”
4)	Click “Stack”
5)	Click Play
6)	Again click “Stack”
7)	Click “Restore”
8)	Note that pop up screen is disturbed by clicking ‘Restore’

**ACTUAL RESULTS:**
Pop up screen is disturbed by clicking ‘Restore’

**EXPECTED RESULTS:**
Pop up screen should not disturb by clicking ‘Restore’

**SCREENSHOT:**

![v0 9 0_25](https://cloud.githubusercontent.com/assets/9950837/11523357/8cab7d6e-98e3-11e5-942c-ac9547925273.png)

**Comment by sergey-filipenko** [comment]
related to https://github.com/Gapminder/vizabi/issues/1076
