### ISSUE TITLE
v0.9.0_26: Curves are not selectable after clicking play

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1080]
**SEVERITY:**  Major

**MODULE:** Mountain chart

**Platform:**  Windows 7 / Chrome 46.0

**RELEASE:** Develop

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/develop/preview/mountainchart.html 
2)	Mountain chart will be loaded
3)	Click play
4)	Select any curve
5)	Note that curves are selectable after clicking play

**ACTUAL RESULTS:**
Curves are not selectable after clicking play

**EXPECTED RESULTS:**
Curves should be selectable after clicking play 

**SCREENSHOT:**

![v0 9 0_26](https://cloud.githubusercontent.com/assets/9950837/11523382/bd425042-98e3-11e5-9863-0e1da9012596.png)

**Comment by angieskazka** [comment]
that's right, they aren't (because they are merged during play)
