### ISSUE TITLE
v0.9.0_27: Size values should change according to its movement

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1081]
**SEVERITY:**  Minor

**MODULE:** Bubble chart

**Platform:**  Windows 7 / Chrome 46.0

**RELEASE:** Develop

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html 
2)	Bubble chart will be loaded
3)	Click “Size”
4)	Change the size of the bubble through size scale
5)	Note that the values are not changing whether e increase or decrease the size of bubbles

**ACTUAL RESULTS:**
The values are not changing whether e increase or decrease the size of bubbles 

**EXPECTED RESULTS:**
Size values should change according to its movement 

**SCREENSHOT:**

![v0 9 0_27](https://cloud.githubusercontent.com/assets/9950837/11523408/ecbaed70-98e3-11e5-8f25-a8ae9343f521.png)

**Comment by angieskazka** [comment]
if you mean 0 and 550, they shouldn't change: 0 is this big and 550 i this big
