### ISSUE TITLE
v0.9.0_28: Scroll bar is not working

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1082]
**SEVERITY:** Major

**MODULE:**  Bubble Chart

**Platform:** Nexus-5 (6.0) / Chrome 46.0

**RELEASE:** v0.9.0

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL: http://static.gapminderdev.org/vizabi/release/v0.9.0/preview/bubble.html
2)	Bubble chart will be loaded.
3)	Tap on “Options” icon. Small pop up screen is displayed
4)	Tap on “Color” from pop up screen
5)	Scroll down to view all options on pop up screen
6)	Note that scroll down is not working

**ACTUAL RESULTS:**
Scroll down is not working on small pop up screen of “Options”

**EXPECTED RESULTS:**
Scroll down should work properly

**SCREENSHOT:**

![v0 9 0_28](https://cloud.githubusercontent.com/assets/9950837/11524496/12309588-98ed-11e5-829c-694bc1581092.png)

**Comment by angieskazka** [comment]
can not reproduce on my nexus 5 (6.0) / chrome 46

**Comment by angieskazka** [comment]
can reproduce on @jheeffer Nexus 4 (5.1.1) / chrome 46

**Comment by angieskazka** [comment]
ok… it’s a chrome bug. solution: reopen a tab =/
