### ISSUE TITLE
Speed up bubble resizing, zooming, panning (easier redraw function)

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#109]
I am going to make a lighter function that would redraw bubbles using stashed data and without requesting data from the model if only scale range is changing

Resizing, zooming, panning, should get faster

@arthurcamara1  did you have any comments on it?

**Comment by arthurcamara1** [comment]
Ok, some improvement was achieved. However, the performance still does not seem to be the optimal.

Consideration: `clearHighlighted` is very expensive for some reason. It was taking 8ms of execution alone. Removed it from zoomer, which brought back bug #175 (we have now to fix it in some other way)

Result: execution time improved from 48-54ms down to 6-21ms on my browser.
