### ISSUE TITLE
v0.9.1_04: ‘?’ is not aligned with Y-axis description after clicking “Present”

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1093]
**SEVERITY:** Minor

**MODULE:** Stage 

**Platform:** 
* Windows 7 / Chrome 46.0
* Windows 7 / Firefox 43.0
* MAC / Safari 9.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: https://stage-tools.gapminderdev.org/tools/ 
2)	Tools page is loaded.
3)	Select bubble map chart
4)	Click “Present” icon which is at right bottom
5)	Note that ‘?’ is not aligned with Y-axis description after clicking “Present”

**ACTUAL RESULTS:**
‘?’ is not aligned with Y-axis description after clicking “Present”

**EXPECTED RESULTS:** 
‘?’ should be aligned with Y-axis description after clicking “Present”

**SCREENSHOT:**

![v0 9 1_04](https://cloud.githubusercontent.com/assets/9950837/11553442/92cf434c-99b0-11e5-927c-947cb859db08.png)

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Platform:** Windows 7 / Chrome 46.0

**Testing Environment:** http://static.gapminderdev.org/vizabi/develop/preview/bubblemap.html

**Comment by k6Labz** [comment]
@angieskazka 
This issue can be reproduced.

**Module:** Bubble map chart

**Platform:** Nexus 9 (5.1) / Chrome 47.0

**Testing Environment:** http://static.gapminderdev.org/vizabi/release/v0.9.2/preview/bubblemap.html

**Comment by angieskazka** [comment]
@jdk137 see how the alignment is done in mountain chart and just copy the solution (with constants in sizing profiles in updateSize method). it should work even if not reproduced =)

(try many contexts, like browsers and OS)
