### ISSUE TITLE
Ugly overlapping in "find" menu on Safari

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#1099]
Mac El Capitan / Safari 9.0 
iPad Air 2 iOS(9.1) / Safari (Expanded Screen / Landscape orientation)

Profile: large

![image](https://cloud.githubusercontent.com/assets/3648190/11570726/0df3c802-99f9-11e5-9ea9-06bea35394bf.png)

**Comment by k6Labz** [comment]
@angieskazka 
I think this issue is related to 8th comment under #1049. Please have a look there.

**Comment by sergey-filipenko** [comment]
related to https://github.com/Gapminder/vizabi/issues/1102
