### ISSUE TITLE
Reloading example does not reload the state

### ISSUE THREAD

**Issue by amytych** [Gapminder/vizabi#11]
Live reloading is a great help when developing tools for Vizabi, no question about it. But I was stuck many times because it doesn't refresh the url with the state. I changed the state while initialising my tool, the page refreshed as expected, but nothing changed. It took me a while to realize that it was because the state was cached in the url.

**Comment by angieskazka** [comment]
For now we made a button in the top left corner of a preview page template, that button would reload the page with resetting the state.

So just press that button instead of your browser refresh button when you know that the old state is not needed anymore.

Do we need to keep this issue?

**Comment by arthurcamara1** [comment]
No, we can close it

On Monday, March 23, 2015, Angie the Fairytale <notifications@github.com>
wrote:

> For now we made a button in the top left corner of a preview page
> template, that button would reload the page with resetting the state.
>
> So just press that button instead of your browser refresh button when you
> know that the old state is not needed anymore.
>
> Do we need to keep this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Gapminder/vizabi/issues/11#issuecomment-84934082>.
>


-- 

*Arthur Camara*
*Software Engineer*
Gapminder Foundation
www.gapminder.org
