### ISSUE TITLE
v0.9.1_08: “Deselect All” and “OK” are missing on Safari

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1102]
**SEVERITY:** Major

**MODULE:** Bubble Chart

**Platform:**  iPad Air 2 iOS(9.1) / Safari

**RELEASE:** v0.9.1

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.9.1/preview/bubblechart.html  
2)	Bubble chart page will be loaded
3)	Click “Expand”
4)	Change the orientation of the iPad to landscape
5)	Select any country
6)	Note that “Deselect All” and “OK” are missing

**ACTUAL RESULTS:**
“Deselect All” and “OK” are missing 

**EXPECTED RESULTS:** 
“Deselect All” and “OK” options should be available after selecting a country 

**SCREENSHOT:**

![v0 9 1_08](https://cloud.githubusercontent.com/assets/9950837/11584427/ba6f6730-9a85-11e5-9ab3-b816ce6eb943.PNG)

**Comment by k6Labz** [comment]
@angieskazka  : This issue is reported earlier, under #1049 as 3rd comment issue

**Comment by angieskazka** [comment]
and also the top of the countries list gets disturbed

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1125
