### ISSUE TITLE
v0.9.1_09: There is no space between axis values

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1103]
**SEVERITY:** Minor

**MODULE:** Line Chart

**Platform:**  iPad Air 2 iOS(9.1) / Safari

**RELEASE:** v0.9.1

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.9.1/preview/linechart.html
2)	Line chart page will be loaded
3)	Click “Expand”
4)	Change the orientation of the iPad to landscape
5)	Note that  there is no space between axis values

**ACTUAL RESULTS:**
There is no space between axis values 

**EXPECTED RESULTS:** 
Space should be there between axis values 

**SCREENSHOT:**

![v0 9 1_09](https://cloud.githubusercontent.com/assets/9950837/11584500/3727a1f2-9a86-11e5-9dde-03d4a20937ad.PNG)

**Comment by angieskazka** [comment]
need to better parametrise the axis labeler in linechart-component.js

**Comment by sergey-filipenko** [comment]
Tested on iPad 3 IOS 8.4, can not reproduce? retest please

**Comment by angieskazka** [comment]
this should be related to a very certain resolution. you can reproduce it on a PC by resizing a window.
for example 1008 x 732

problem axis labeler is not shifting 64000 away from 128k
