### ISSUE TITLE
Behavior of "follow bubbles with zoom" feature

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#1107]
### "follow bubbles with zoom"

The idea with follow bubbles with zoom is that it will change it's behavior. Because now it jumps back and forward, bubbles just dance in the same spot and axes ticks are shifting. One can’t grasp what’s going on, the story breaks. But if the change is only one-directional, we can both utilize the space nicely and also keep the visual story coherent.

### Behavior when checkbox in more options is OFF
Zoom does not change when bubbles drag or play. Only the user changes the zoom with mousewheel.

### Behavior when checkbox in more options is ON
On load or on changing indicator or on changing entities we zoom in so that bubbles fit the screen.
On drag or play we zoom out so that we track bubbles as they need more space. We don't zoom back in.

### Action when the checkbox is turned OFF
Zoom fully out

### Action when the checkbox is turned ON
Zoom in so that bubbles fit the screen.

***
The picture that explains how scaling works in bubble chart

![image](https://cloud.githubusercontent.com/assets/3648190/11611144/34ce39d2-9bbe-11e5-9e43-5a8a00a0327f.png)

https://docs.google.com/drawings/d/12Z_W_YfeaibNGgvtrYzDDQyW_hs9_Ls1ybUK7B43uls

**Comment by plward11** [comment]
Pull request https://github.com/Gapminder/vizabi/pull/1191

**Comment by angieskazka** [comment]
Looks done to me

**Comment by plward11** [comment]
I misunderstood, thank you for clarifying over Slack that we were concerned with dragging the time slider causes the canvas to expand as needed. Glad that it's already fixed! :)
