### ISSUE TITLE
label leash to label center 

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#111]
Make leash always aim at center of label text. Never to corner
![image](https://cloud.githubusercontent.com/assets/496398/7555302/374054f0-f747-11e4-8994-8a233427b692.png)

**Comment by angieskazka** [comment]
how about this case @olarosling?
attaching leash to middle of the text would look strange

![image](https://cloud.githubusercontent.com/assets/3648190/7555435/ba429db4-f74b-11e4-83c4-8bee0a0d1332.png)

Gapminder world cheats this by always showing white box (which is not that elegant, i think)

**Comment by arthurcamara1** [comment]
Fixed by 5510cf6
