### ISSUE TITLE
Trails-status (on/off) fails in url-state

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#1116]
1. Cretae a chart with trails
2. Click the trails button to turn trails off: The trails dissapear from the chart view.
3. Copy the url
http://www.gapminder.org/tools/bubbles#_entities_select@_geo=nga&labelOffset@:-0.02937706553533473&:-0.05514996824338488;&trailStartTime=1919;&_geo=ago&labelOffset@:0.12730251615363636&:-0.04852258133274488;&trailStartTime=1919
4. Paste in new browser tab
5. The chart shows trails, but it shouldn't

**Comment by angieskazka** [comment]
@arthurcamara1 @jheeffer can you help with it? the trails flag is not showing up in URL after it's modified -- neither on tools page, nor on static

why do the other changes of state modify URL and how does it happen?

**Comment by jheeffer** [comment]
will most likely be fixed with #936

**Comment by jheeffer** [comment]
Fixed with https://github.com/Gapminder/vizabi/commit/e942f03007299f397d71e5578f37b14feed04185
