### ISSUE TITLE
Panels should popup next to their buttons.

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#1117]
When I click the size button, I want the Size panel to popup above it. So probably there should be some kind of locaiton parameter with this: panel.show(triggered_from_btn_rect) 
Why I suggest passing a rectangle: The panel can then adjust it's relative position, depending on the rest of the window. And find a place to the left or top, which fits the screen, depending on the landscape and device environment.
 
![image](https://cloud.githubusercontent.com/assets/496398/11653472/cc18e79c-9d9e-11e5-9432-c5891bdf277e.png)

**Comment by angieskazka** [comment]
Phase 1 is done. Phase 2 is made to a separate issue #1314
