### ISSUE TITLE
Hidden play button in iphone 6 Safari expanded landscape mode

### ISSUE THREAD

**Issue by natali-abyss** [Gapminder/vizabi#1118]
Steps to reproduce:
1) You should open vizabi on the iPhone 6 when it is in the landscape mode.
2) Then click the 'Expand' button

![img_0046](https://cloud.githubusercontent.com/assets/7370255/11657372/f378b29c-9dc4-11e5-9117-3531e044f182.PNG)
and vizabi-tools-page 
![img_0048](https://cloud.githubusercontent.com/assets/7370255/11657522/f0c0771e-9dc5-11e5-86a1-3a8c20b5961a.PNG)

**Comment by angieskazka** [comment]
the issue is possibly related to special treatment of fullscreen in Safari
remember we made a hack when we saw that fullscreen on Safari disables text input

so we made it pseudo-fullscreen
but it looks like vizabi is assuming the full screen height instead of the one minus toolbar height
