### ISSUE TITLE
continues color scale gradient 

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#112]
When color by indicator (continues) 
Instead of this discrete color groups: 
![image](https://cloud.githubusercontent.com/assets/496398/7555306/705834e2-f747-11e4-816d-93574068571a.png)
1) display a color- gradient following a colorwheel with colors that we can easily adhust later 
2) Make it posible to set the numeric-scale of lin or log, applied before scaling to the gradient.

**Comment by angieskazka** [comment]
also map picture for geo.regions

**Comment by angieskazka** [comment]
done
