### ISSUE TITLE
v0.9.1_15: Slide bars are slightly disturbed on Firefox

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1121]
**SEVERITY:**  Minor

**MODULE:** Bubble chart

**Platform:**  Windows 7 / Firefox 43.0

**RELEASE:** v0.9.1

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.9.1/preview/bubblechart.html
2)	Bubble chart will be loaded.
3)	Click “Options”
4)	Click “Opacity” from pop up screen
5)	Note that  slide bars are slightly disturbed

**ACTUAL RESULTS:**
Slide bars are slightly disturbed on Firefox 

**EXPECTED RESULTS:**
Slide bars should not be disturbed on Firefox. These should be properly shown like on Chrome 

**SCREENSHOT:**

![v0 9 1_15](https://cloud.githubusercontent.com/assets/9950837/11681964/ff71650c-9e83-11e5-9150-ff77afabe8f0.png)

**Comment by angieskazka** [comment]
@dab2000 let it use input[type=range] selectors from _main.scss as much as possible,
that would make some or most of the code in _simpleslider.scss unnecessary

also this effect on firefox focus will disappear

![image](https://cloud.githubusercontent.com/assets/3648190/11692917/55b4d3f4-9ea2-11e5-9ce1-27b72cf25837.png)
