### ISSUE TITLE
v0.9.1_16: Vizabi container is disturbed by clicking “Restore” on Firefox

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1122]
**SEVERITY:**  Major

**MODULE:** Bubble chart

**Platform:**  Windows 7 / Firefox 43.0

**RELEASE:** v0.9.1

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.9.1/preview/bubblechart.html
2)	Bubble chart will be loaded.
3)	Click “Expand”
4)	Click “Restore”
5)	Note that chart is disturbed by clicking “Restore”

**ACTUAL RESULTS:**
Chart is disturbed by clicking “Restore” on Firefox 

**EXPECTED RESULTS:**
Chart should not disturb by clicking “Restore” 

**SCREENSHOT:**

![v0 9 1_16](https://cloud.githubusercontent.com/assets/9950837/11681994/30dcfe94-9e84-11e5-8674-314171693ce1.png)

**Comment by angieskazka** [comment]
@k6Labz still an issue?

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Testing Environment:** http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html

**Platform:** Windows 7 / Firefox 44.0
