### ISSUE TITLE
v0.9.1_18: Small pop up screen is truncated on landscape

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1124]
**SEVERITY:**  Minor

**MODULE:** Line chart

**Platform:**  Windows 7 / Firefox 43.0

**RELEASE:** v0.9.1

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.9.1/preview/linechart.html
2)	Line chart will be loaded.
3)	Click “Color”
4)	Select “Constant”
5)	Select small colored ball to change the constant color
6)	Click “Landscape”
7)	Note that small pop up screen is truncated

**ACTUAL RESULTS:**
Small pop up screen is truncated on landscape 

**EXPECTED RESULTS:**
Small pop up screen should not truncate 

**SCREENSHOT:**

![v0 9 1_18](https://cloud.githubusercontent.com/assets/9950837/11682056/72af876a-9e84-11e5-9359-d5f79d86fb5c.png)

**Comment by angieskazka** [comment]
because the color picker doesn't have a resize method when it would adjust for changes
need to refactor the color picker: divide init method code into init and resize, call resize from the parent dialog when it needs resize

**Comment by angieskazka** [comment]
also make the code of color picker pretty, because @arthurcamara1 once dropped an uglifier nuke on it :-P
