### ISSUE TITLE
v0.9.2_01: bubbles don't trigger mouseout event when they are moved away from under the cursor // Hover effect is not working properly

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1131]
**SEVERITY:** Major

**MODULE:** Stage 

**Platform:**  Windows 7 / Chrome 47.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: https://stage-tools.gapminderdev.org/tools/ 
2)	Tools page is loaded.
3)	Click Play
4)	Take mouse to any bubble, tooltip for that country is available
5)	Don’t move the mouse and let the slider ball reach the end
6)	Note that tooltip is still there at the start while the hovered bubble reached the end.

**ACTUAL RESULTS:**
Hover effect is not working properly. Tooltip is still there at the start while the hovered bubble reached the end.

**EXPECTED RESULTS:** 
Tooltip should disappear when the bubble cross the cursor. And it should not highlighted too after crossing the cursor

**SCREENSHOT:**

![v0 9 2_01](https://cloud.githubusercontent.com/assets/9950837/11736682/e52c089e-9ff2-11e5-9282-db0062ba1e3b.png)

**Comment by angieskazka** [comment]
bubbles don't trigger mouseout event when they are moved away from under the cursor

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1295

**Comment by angieskazka** [comment]
the best solution is given in PR #1295. 
but that's way too much of complexity for a very rare bug. you have to hold your mouse perfectly still over the graph

let's not do anything with it until users encounter that problem.
