### ISSUE TITLE
v0.9.2_02: No chart is visible on expanded screen

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1132]
**SEVERITY:** Critical

**MODULE:** Stage 

**Platform:** 
* Windows 7 / Chrome 47.0
* MAC / Safari 9.0
* iPhone 6(iOS 8.3) / Safari 

**STEPS TO REPRODUCE:**
1)	Navigate to URL: https://stage-tools.gapminderdev.org/tools/ 
2)	Tools page is loaded.
3)	Click “Expand”
4)	Note that no expanded chart is visible on **Chrome and MAC.** 

**ACTUAL RESULTS:**
No chart is visible on expanded screen

**EXPECTED RESULTS:** 
Chart should be visible on expanded screen

**SCREENSHOT:**

![v0 9 2_02](https://cloud.githubusercontent.com/assets/9950837/11736691/15b8be26-9ff3-11e5-8bf3-7bb2499b533c.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1136

**Comment by jheeffer** [comment]
closed with https://github.com/Gapminder/vizabi/commit/82808ab124f36fd013a1587feb8cba5a6894b54c
