### ISSUE TITLE
v0.9.2_03: Y-axis description is overlapping with ‘?’

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1133]
**SEVERITY:** Minor

**MODULE:** Stage 

**Platform:**  MAC / Safari 9.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: https://stage-tools.gapminderdev.org/tools/ 
2)	Tools page is loaded.
3)	Click “Present”
4)	Take mouse to any bubble. Tooltip for that bubble is shown
5)	Take away the mouse from bubble
6)	Note that Y-axis description is overlapping with ‘?’

**ACTUAL RESULTS:**
Y-axis description is overlapping with ‘?’

**EXPECTED RESULTS:** 
Text should not overlap

**SCREENSHOT:**

![v0 9 2_03](https://cloud.githubusercontent.com/assets/9950837/11737945/0f0e815c-a000-11e5-8f27-cf21fa68a6f3.png)

**Comment by jdk137** [comment]
I can not reproduce on OSX Yosemite 10.10.5, safari version 9.0.2.

**Comment by angieskazka** [comment]
i couldn't reproduce it on the following platforms
mac safari 9
mac chrome
mac firefox
win7 firefox
win7 chrome
