### ISSUE TITLE
Data is absent on the bubblechart

### ISSUE THREAD

**Issue by natali-abyss** [Gapminder/vizabi#1135]
<b>SEVERITY</b>: MAJOR
<b>MODULE</b>: Stage

<b>Platform</b>: iPhone 6/Safari

<b>Steps to reproduce</b>: 
1) Got to stage: http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html
2) Data is absent on the bubblechart

<b>ACTUAL RESULTS</b>:
Data is absent on the bubblechart

<b>EXPECTED RESULTS</b>:
Data should be rendered on the bubblechart
<b>SCREENSHOT</b>
![img_0050](https://cloud.githubusercontent.com/assets/7370255/11742053/a194cb62-a005-11e5-8251-2b321d744081.PNG)

**Comment by jheeffer** [comment]
This míght have to do with caching. Not saying it is, but I had similar problems why I merged the 0.9.2 in my feature branch and clearing the cache worked.

**Comment by angieskazka** [comment]
looks like it... because the data files changed...

**Comment by natali-abyss** [comment]
now all right for iphone 6, thanks
