### ISSUE TITLE
v0.9.2_04: Chart is disappeared by Taping “Expand” on Ipad

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1140]
**SEVERITY:** Critical

**MODULE:**  
* Bubble Chart
* Mountain Chart
* Bubble map Chart
* Line Chart
*Pop by age Chart
* Bar Chart

**Platform:**  iPad Air 2 iOS(9.1) / Safari

**RELEASE:** v0.9.2

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL: http://static.gapminderdev.org/vizabi/release/v0.9.2/preview/bubblechart.html
2)	Bubble chart will be loaded.
3)	Tap on “Expand” 
4)	Note that the page is still there but just chart is disappeared

**ACTUAL RESULTS:**
Page is still there but just chart is disappeared by Taping “Expand”

**EXPECTED RESULTS:**
Page should be expanded by Taping “Expand”

**SCREENSHOT:**

![v0 9 2_04](https://cloud.githubusercontent.com/assets/9950837/11775249/035d89f0-a25f-11e5-9969-cf8ee938d80b.PNG)

**Comment by sergey-filipenko** [comment]
already fixed
