### ISSUE TITLE
v0.9.2_06: Scroll bar is missing on small pop screen 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1142]
**SEVERITY:** Minor

**MODULE:** 
* Bubble Chart
* Mountain Chart
* Bubble map Chart

**Platform:**  iPad Air 2 iOS(9.1) / Safari

**RELEASE:** v0.9.2

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL: http://static.gapminderdev.org/vizabi/release/v0.9.2/preview/bubblechart.html
2)	Bubble chart will be loaded.
3)	Tap on “Landscape” under RESPONSIVENESS on right panel 
4)	Tap “Color” on the chart
5)	Tap any option to view sub options
6)	Note that scroll bar is missing

**ACTUAL RESULTS:**
Scroll bar is missing on small pop screen 

**EXPECTED RESULTS:**
Scroll bar should be there on small pop screen

**SCREENSHOT:**

![v0 9 2_06](https://cloud.githubusercontent.com/assets/9950837/11775288/597d8cfe-a25f-11e5-9a52-b9e5eaa146a9.PNG)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1240
