### ISSUE TITLE
v0.9.2_07: The chart title is not changing to show the exact values.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1143]
**SEVERITY:** Minor

**MODULE:**  Bubble map Chart

**Platform:**  
* iPad Air 2 iOS(9.1) / Safari
* Nexus 9 (5.1) / Chrome 47.0

**RELEASE:** v0.9.2

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL: http://static.gapminderdev.org/vizabi/release/v0.9.2/preview/bubblemap.html
2)	Bubble map chart will be loaded.
3)	Tap on any bubble
4)	Note that the chart title is not changing to show the exact values.

**ACTUAL RESULTS:**
The chart title is not changing to show the exact values.

**EXPECTED RESULTS:**
The chart title should change to show the exact values while hovering.

**SCREENSHOT:**

![v0 9 2_07](https://cloud.githubusercontent.com/assets/9950837/11775314/a1c80926-a25f-11e5-9d7e-40bbc42bd29e.PNG)

**Comment by jdk137** [comment]
The chart title only change when hover on a bubble, not select a bubble,  because multi bubbles could be selected, only one value could be shown.

**Comment by jheeffer** [comment]
Should the title show the total population of all countries selected if not hovering?

**Comment by angieskazka** [comment]
me on slack: 

maybe we can do this:
on desktop we can show precise numbers on hover (and time update while hovering)
on touch device we can show precise numbers when only one bubble is selected (and time update while one is selected)
when multiple bubbles are selected, we just show title

@jheeffer aggregation is a bit harder. For lex you will need to show a weighted average... The aggregations are not very apparent and would be hard to figure out.
