### ISSUE TITLE
v0.9.2_08: Heading is missing on small pop up screen

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1144]
**SEVERITY:** Minor

**MODULE:**  Mountain  Chart

**Platform:** iPhone-4G(iOS 7.1.2)/ Safari

**RELEASE:**  v0.9.2

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.9.2/preview/mountainchart.html 
2)	Mountain chart page will be loaded
3)	Tap “X and Y”
4)	Note that heading is missing on small pop up screen

**ACTUAL RESULTS:**
Heading is missing on small pop up screen of “X and Y”

**EXPECTED RESULTS:** 
“X and Y” should be written as heading on the top left of small pop up screen of “X and Y”

**SCREENSHOT:**

![v0 9 2_08](https://cloud.githubusercontent.com/assets/9950837/11804903/3e266f00-a329-11e5-8552-c36730880410.PNG)

**Comment by angieskazka** [comment]
we removed this popup now :fire:
