### ISSUE TITLE
v0.9.2_09: Bubble is overlapping with data warning text

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1145]
**SEVERITY:** Minor

**MODULE:**  Bubble map  Chart

**Platform:** iPhone-4G(iOS 7.1.2)/ Safari

**RELEASE:**  v0.9.2

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.9.2/preview/bubblemap.html 
2)	Bubble map chart page will be loaded
3)	Tap “Size” and drag both the pointers to the maximum side to increase the bubble size and tap OK
4)	Note that bubble is overlapping with data warning text after increasing the bubble size

**ACTUAL RESULTS:**
Bubble is overlapping with data warning text after increasing the bubble size 

**EXPECTED RESULTS:** 
Bubble should not overlap with any text on the chart after increasing the bubble size 

**SCREENSHOT:**

![v0 9 2_09](https://cloud.githubusercontent.com/assets/9950837/11804915/5f30fb48-a329-11e5-8bdf-964825396164.PNG)

**Comment by angieskazka** [comment]
it's a very extreme case, don't worry =)
