### ISSUE TITLE
v0.9.2_10: Place of tooltip is disturbed

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1146]
**SEVERITY:** Minor

**MODULE:**  Line  Chart

**Platform:** iPhone-4G(iOS 7.1.2)/ Safari

**RELEASE:**  v0.9.2

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.9.2/preview/linechart.html 
2)	Line chart page will be loaded
3)	Tap any line. Tooltip is displayed
4)	Tap play
5)	Note that tooltip is still there but the lines are at the start place

**ACTUAL RESULTS:**
Place of tooltip is disturbed after play

**EXPECTED RESULTS:** 
Tooltip should disappear when we tap play

**SCREENSHOT:**

![v0 9 2_10](https://cloud.githubusercontent.com/assets/9950837/11804935/983eaff2-a329-11e5-9a0d-81596aed6be5.PNG)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1249
