### ISSUE TITLE
New preview page blocks interaction with html slider and select elements

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#117]
I can not open any of select elements in the dialogs. Neither does the size slider respond to interaction.

![image](https://cloud.githubusercontent.com/assets/3648190/7617744/72204f0e-f9ad-11e4-8bac-8ed982fdbae1.png)

However `on("click")`event is being called if i attach the listener to the selector

Furthermore, the selector would not open even if i manually remove div `vzb-tool` and add the selector html into `vzbp-placeholder` so that it would look like this:

![image](https://cloud.githubusercontent.com/assets/3648190/7617832/1bcaf3ec-f9ae-11e4-8a48-e2017cfbc2db.png)

Neither it does if i remove all the classes from `vzbp-placeholder` div

![image](https://cloud.githubusercontent.com/assets/3648190/7617870/56912438-f9ae-11e4-947c-4309764ba63a.png)

Now, if i remove the div and make select inherited directly by `<div id="vzbp-main">`
![image](https://cloud.githubusercontent.com/assets/3648190/7617883/6e135838-f9ae-11e4-9c4b-b149a161e149.png)

The selector finally opens
![image](https://cloud.githubusercontent.com/assets/3648190/7617947/ed2a0e82-f9ae-11e4-95bf-db456b56d219.png)

I suspect that some javascript code attached to `vzb-placeholder` prevents inhereted selector from opening (not CSS because i deleted all the classes and unselected all CSS properties)

**Comment by arthurcamara1** [comment]
Blocker solved and I'll bring back resize :)
