### ISSUE TITLE
Bubblechart: Linear/log switch is broken

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#1174]
Switch Y axis to Population

Switch to log -- bubble stay as they were, axis labels are disturbed

![image](https://cloud.githubusercontent.com/assets/3648190/11985953/4f58a886-a9ca-11e5-8716-666377c0c6e0.png)

Switch to linear -- bubbles stay as they were (correct now), axis labels are disturbed

![image](https://cloud.githubusercontent.com/assets/3648190/11985954/59c47804-a9ca-11e5-8ba9-147f7b61ecd3.png)

Switch to log again -- bubbles change to log (correct now), axis labels are disturbed

![image](https://cloud.githubusercontent.com/assets/3648190/11985970/913ac6ee-a9ca-11e5-9da3-fd59edf18e39.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1179

**Comment by angieskazka** [comment]
#1180 might be a root cause

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1197
