### ISSUE TITLE
Root problem: when calling model.set(), the events are triggered before waiting when all params are set

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#1180]
dab:
if i use this.model.state.marker.set(obj)  for example and obj is {stack: {which: 'all', use: 'constant'}} then i get  change:marker.stack after when 'which' is changed but 'use' is not change yet

jasper:
the error in getFrames is caused by something in the events. Stack is set with an object { use: 'constant', which: 'none' }. Stack.use is changed first, which triggers event handlers to be executed while stack.which hasn't changed yet (but it should first, before the handlers fire).

**Comment by jheeffer** [comment]
Events are fixed, but still things break.

dataId of hooks seem to be mismatched

**Comment by jheeffer** [comment]
There are two eventHandlers that cause the error.

1. in MountainChartComponent `on('change:marker.stack')` which redraws the chart
2. in Model (hook part) `this.on('change:which')` which loads new data. 

With previous code, the order of firing was 2, 1. So first load, then redraw. Because first hook.which was changed, then hook.use. Now the order is 1, 2. First redraw then load. That's where it goes wrong.

The fact that this kind of randomness can break the chart is not good. Chart redraw should be triggered after data has been loaded.

**Comment by angieskazka** [comment]
There are two problems i can see:
the commit 53e461113b4c6a78bc82a337900057e5fd89fa38 caused unpleasant experience when switching "color" to constant. For a second or two all strings in color dialog look not translated, also a very surprising scale when switching "color" to `time`

the next commit 3085685cbe2a98454c7c1bac92a6187740bbf369 the crash in event system when switching first to `constant`, then to `time` or vice versa

**Comment by jheeffer** [comment]
Yes, I'll look into it after new years probably. I wonder if it's the event system or the hacks in color model/dialogue (it seems to be a particularly hacky part of the codebase).

**Comment by angieskazka** [comment]
![8tevikzgfz](https://cloud.githubusercontent.com/assets/3648190/12064042/6064ba3a-afb9-11e5-8dec-511f1448be76.gif)

**Comment by angieskazka** [comment]
@jheeffer i found another problem which also belongs here: when setting multiple parameters to model, the events are triggered before model validation is complete

we should wait until the entire validation tree is resolved, only then unfreeze the events

**Comment by sergey-filipenko** [comment]
fixed by https://github.com/Gapminder/vizabi/pull/1197

**Comment by angieskazka** [comment]
That fixed indeed, but now we have another problem:
when we change some properties during validation, model becomes unfreezed and all triggers are call before validation completed

**Comment by jheeffer** [comment]
Fixed that too with 08f95d27fa0489c92f8885629180a1ec862c6226
