### ISSUE TITLE
Bubblechart throws an error when changing time while following bubbles

### ISSUE THREAD

**Issue by plward11** [Gapminder/vizabi#1185]
**MODULE:** Bubble Chart

**Platform:**  Windows 7 / Chrome 47.0

**STEPS TO REPRODUCE:** 
1)	On Bubblechart in the "Options" menu under the "X and Y" submenu, click "Follow bubbles with zoom" and click "OK"
2)	Choose any time besides the current time in the time slider

**ACTUAL RESULTS:**
The time appears to change correctly, but an error is emitted in the console.

In Chrome, an error appears in the console log `TypeError: Cannot read property 'max' of undefined`.

In Firefox, the error reads `TypeError: _this.xyMaxMinMean.s[_this.time] is undefined`.

**EXPECTED RESULTS:**
No errors are produced when changing time with the "Follow bubbles with zoom" checkbox checked.

**Comment by angieskazka** [comment]
i know why, time point should be rounded
