### ISSUE TITLE
Freezing effect when dragging time slider. Probably utils.throttle()

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#1187]
Steps to reproduce: take develop branch, open bubble map and start dragging time slider back and forth you’ll see the chart freezes sometimes...

can be reproduced on bubble chart too, however you need to drag harder and longer
and not on mountain chart, which is strange

what i found is that in timeslider.js
the function before throttling is called as expected (line 346)
the function body inside throttling is sometimes never called (line 411) -- when freezing happens

throttling is linked on line 143 in timeslider.js

might be of course some bubble-map problem that i fail to see. but this easy test above with two console logs can show that throttling looks broken

**Comment by dab2000** [comment]
So timeslider uses d3.brush and handle is dragged then all settimeout's are stacked and executed after dragend.
