### ISSUE TITLE
Bubble chart options menu does not display correctly in landscape view

### ISSUE THREAD

**Issue by plward11** [Gapminder/vizabi#1188]
**MODULE:** Bubble chart

**Platform:**  Windows 7 / Chrome 47.0

**STEPS TO REPRODUCE:** 
1)	Set BubbleChart to landscape mode (width 568, height 320)
2)	Click the "Options" menu

**ACTUAL RESULTS:**
Options menu does not display properly on http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html

![optionsmenubug](https://cloud.githubusercontent.com/assets/1934849/12069525/df85a4a2-afe9-11e5-86bc-35e1a8cc2291.png)

**EXPECTED RESULTS:**
The options menu should display its submenu titles correctly.

**Comment by angieskazka** [comment]
true. @dab2000 can you please check it?
