### ISSUE TITLE
Rectangle zoom incorrectly ignores the "Follow bubbles with zoom" option

### ISSUE THREAD

**Issue by plward11** [Gapminder/vizabi#1198]
**MODULE:** Bubble chart

**Platform:**  Windows 7 / Chrome 47.0

**STEPS TO REPRODUCE:** 
1)	Drag time slider to 1800
2)	Enable the "Follow bubbles with zoom" option under the "X and Y" Options menu
3)	Rectangle zoom on any region in the chart
4)	Either play the time, or drag the time slider forward to the year 2015

**ACTUAL RESULTS:**
The canvas does not expand to fit the moving bubbles. The "Follow bubbles with zoom" option is still enabled under the "X and Y" Options menu.

**EXPECTED RESULTS:**
The canvas still expands to fit the moving bubbles.

**Comment by angieskazka** [comment]
@plward11 can't reproduce. Looks good to me, the canvas expands. Although it does it sharply, without animation, and i would prefer with

![xxcg30v7l8](https://cloud.githubusercontent.com/assets/3648190/12186325/e64ee2ae-b5a1-11e5-88fe-3985da4f4fce.gif)

**Comment by plward11** [comment]
@angieskazka Sorry, I did not word the issue correctly. The time should play or the time slider be dragged out to the year 2015. I'll fix the steps to reproduce.

I made a separate issue for the canvas expanding without animation here https://github.com/Gapminder/vizabi/issues/1213.

**Comment by plward11** [comment]
Pull request https://github.com/Gapminder/vizabi/pull/1223.

**Comment by olarosling** [comment]
I'd rather dissable this feature for now.

**Comment by angieskazka** [comment]
Which feature? Rectangle zoom or following bubbles? 

 following bubbles with zoom is off by default and hard to enable through menus
