### ISSUE TITLE
Wrong events dispatched (looks like only if state modified via sidebar)

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#120]
I was struggling with this :beetle: while refactoring color models, and it added a lot of mysteries, but i was not sure what to blame. Now i managed to set up an experiment, so that the :beetle: becomes visible.

1. uncomment the event printouts in bubble chart
2. open the right sidebare (state) and change manually `"time": { "adaptMinMaxZoom": 0}`: set 0 or 1

the expected events are:
EVENT change:time:adaptMinMaxZoom
EVENT ready (should be fired but suppressed by a workaround line 99)

the actually dispatched events are:
EVENT change:time:value
EVENT change:marker:label
EVENT change:entities:show
EVENT ready

everything else but not the right one :-/

**Comment by arthurcamara1** [comment]
I think what might be happening is that ```setOptions``` is resetting the whole thing and in a wrong way. I am working on some major changes to simplify all these problems once for all and will share them soon

**Comment by arthurcamara1** [comment]
Meanwhile, try to change `"time": { "adaptMinMaxZoom": 0}` through a button. Is the result the same?

**Comment by angieskazka** [comment]
i guess it's only right panel messing up the state (but have not tested otherwise)

**Comment by arthurcamara1** [comment]
I believe this might not be an issue anymore. @angieskazka

**Comment by angieskazka** [comment]
yes, could not reproduce now. hope it's gone

**Comment by angieskazka** [comment]
@arthurcamara1  
no, it still is. please repeat the exact sequence as it was described in the first post

i set time:adaptMinMaxZoom: 1,

these events were called 

![image](https://cloud.githubusercontent.com/assets/3648190/8092077/cde20ea2-0fb7-11e5-9ed6-d3e016be947d.png)
