### ISSUE TITLE
v0.12.0_02: “Merge Mountain” radio buttons are missing. (Unable to see world population in 2015 as 7.3B)

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1202]
**SEVERITY:** Major

**MODULE:** Stage 

**Platform:**  Windows 7 / Chrome 47.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://stage-tools.gapminderdev.org/tools/mountain 
2)	Tools page is loaded.
3)	Note that “Merge Mountain” radio buttons are missing So that we can’t see the world population as 7.3B in 2015

**ACTUAL RESULTS:**
“Merge Mountain” radio buttons are missing. So that we can’t see the world population as 7.3B in 2015

**EXPECTED RESULTS:** 
“Merge Mountain” radio buttons should be there to see the world population as 7.3B in 2015 after merging the world as one curve.

**SCREENSHOT:**

![stage_02](https://cloud.githubusercontent.com/assets/9950837/12162934/1eea8988-b52a-11e5-9fb8-fcc43ea86651.png)

**Comment by angieskazka** [comment]
@k6Labz From now on, some buttons may hide in side bar or popup dialogs, but they are supposed to still be available under more options.

![image](https://cloud.githubusercontent.com/assets/3648190/12172962/4b5bca70-b554-11e5-9667-3f4f16e7f845.png)

![image](https://cloud.githubusercontent.com/assets/3648190/12172970/58387d9c-b554-11e5-9be7-3a1daffd7dc4.png)
