### ISSUE TITLE
v0.12.0_04: ‘log’ button is not working on first click

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1204]
**SEVERITY:** Minor

**MODULE:** Stage 

**Platform:**  Windows 7 / Chrome 47.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://stage-tools.gapminderdev.org/tools/ 
2)	Tools page is loaded.
3)	Click Y axis description. Small pop up screen is displayed
4)	Click ‘log’ which is available on the right top on the small pop up screen
5)	Note that  ‘log’ button is not working on first click

**ACTUAL RESULTS:**
‘log’ button is not working on first click which is available on the right top on the small pop up screen after clicking Y axis description.

**EXPECTED RESULTS:** 
‘log’ button should work on first click 

**SCREENSHOT:**

![stage_04](https://cloud.githubusercontent.com/assets/9950837/12163971/9812a378-b533-11e5-8299-9c04a64418b5.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1239
