### ISSUE TITLE
v0.12.0_07: Y axis value is truncated

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1207]
**SEVERITY:** Minor

**MODULE:** Stage 

**Platform:**  Windows 7 / Chrome 47.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://stage-tools.gapminderdev.org/tools/ 
2)	Tools page is loaded.
3)	Click Options
4)	Click X and Y
5)	Click check box of Follow bubble with zoom
6)	Note that the Y axis value is truncated

**ACTUAL RESULTS:**
Y axis value is truncated by clicking check box of Follow bubble with zoom

**EXPECTED RESULTS:** 
Y axis value should not be truncated by clicking check box of Follow bubble with zoom

**SCREENSHOT:**

![v0 12 0_07](https://cloud.githubusercontent.com/assets/9950837/12168307/18d6a440-b553-11e5-93e4-8fd95bb03a47.png)

**Comment by angieskazka** [comment]
It's expected. But we should make the zoom-in action more visible, so that one can see why
