### ISSUE TITLE
v0.12.0_08: Color picker is not extending to fill the options dialog. // Text is hidden under color picker

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1208]
**SUMMARY:**  
**1)** Text is hidden under color picker
**2)** OK is not functional
 
**SEVERITY:** Minor

**MODULE:** Stage 

**Platform:** 
* Windows 7 / Chrome 47.0
* MAC / Safari 9.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://stage-tools.gapminderdev.org/tools/ 
2)	Tools page is loaded.
3)	Click Options
4)	Click Color
5)	Click drop down in color and Change the option to GDP per capita
6)	Click value which is given with the color scale
7)	Note that Text is hidden under color picker and OK is not functional

**ACTUAL RESULTS:**
Text is hidden under color picker and OK is not functional

**EXPECTED RESULTS:** 
Text should not be hidden under color picker and OK button should be functional  

**SCREENSHOT:**

![v0 12 0_08](https://cloud.githubusercontent.com/assets/9950837/12169046/eec4c8ee-b557-11e5-9e6a-bf12154ef1bb.png)

**Comment by angieskazka** [comment]
get color picker white background cover the entire popup dialog, so color picker should become modal dialog within a dialog.

**Comment by angieskazka** [comment]
We put a modal dialog in modal dialog, so your interaction would be blocked while your interaction is blocked! 
<img width="955" alt="screen shot 2016-01-07 at 15 50 04" src="https://cloud.githubusercontent.com/assets/3648190/12173546/b87374a2-b557-11e5-8e3a-ad299a10c5f6.png">

**Comment by k6Labz** [comment]
**SUMMARY:** Chart is disturbed

**STEPS TO REPRODUCE:** 
Same as above

**Platform:**  Windows 7 / Chrome 47.0

**Screenshot:**

![3](https://cloud.githubusercontent.com/assets/9950837/12191321/f96b5734-b5f4-11e5-812f-a4a992113ab1.png)

**Comment by sergey-filipenko** [comment]
color picker changed in https://github.com/Gapminder/vizabi/issues/1259
