### ISSUE TITLE
Time model ready not being called after something else is listening to time

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#121]
The bug is possibly produced by event optimisation, ready can be called once per frame

**Comment by arthurcamara1** [comment]
@angieskazka Is this still happening?
If so, "not being called after something else is listening to time" means that if you bind 2 functions to time, only one of them is being called?

**Comment by arthurcamara1** [comment]
Tried to reproduce and couldn't. Considering it solved after recent release.
