### ISSUE TITLE
v0.12.0_10: Tooltip is overlapping with the text

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1215]
**SEVERITY:** Minor

**MODULE:** Stage 

**Platform:**  Windows 7 / Chrome 47.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://stage-tools.gapminderdev.org/tools/mountain 
2)	Tools page is loaded.
3)	Hover the top cure of the mountain which is china
4)	Note that Tooltip is overlapping with the text

**ACTUAL RESULTS:**
Tooltip is overlapping with the text

**EXPECTED RESULTS:** 
Tooltip should not overlapping with the text 

**SCREENSHOT:**

![v0 12 0_10](https://cloud.githubusercontent.com/assets/9950837/12192260/dcb76894-b5fe-11e5-995b-3dca86c12a61.png)

**Comment by angieskazka** [comment]
@k6Labz as far as i understand the issue is solved by slightly moving the cursor 
should not be a problem then, as both pieces of information are accessible.
