### ISSUE TITLE
v0.12.0_11: Increase options text are not synced with each other

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1216]
**SEVERITY:** Minor

**MODULE:** Stage 

**Platform:**  Windows 7 / Chrome 47.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://stage-tools.gapminderdev.org/tools/mountain 
2)	Tools page is loaded.
3)	Click PRESENT. Text size is increased
4)	Click Options and click PRESENT on the small pop up
5)	Uncheck the increase text, text increase is disable
6)	Note that PRESENT icon is still highlighted
 
**ACTUAL RESULTS:**
Increase options text are not synced with each other

**EXPECTED RESULTS:** 
Increase options should be synced with each other 

**SCREENSHOT:**

![v0 12 0_11](https://cloud.githubusercontent.com/assets/9950837/12192897/d0d0b0fc-b604-11e5-9f8d-ffc97a9be4fb.png)

**Comment by angieskazka** [comment]
approach should be similar to how "trails" and "lock" buttons are updated in the buttonlist
