### ISSUE TITLE
Locked bubbles won't work on splash load (of course)

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#1217]
@dab2000 reported

Steps to reproduce:
1. load develop: static.gapminderdev.org/vizabi/develop/preview/bubblechart.html
2. select china
3. lock bubbles in 2015
4. select time 1900
5. refresh page
6. See exeption in getFrame

Explanation: 
The chart loads first only 1 year of data (the year that refers to selected bubbles)
It can't find the data for the other bubbles and crashes

Severity
Minor, because very far from common use case

Solution: 
I would expect locked bubbles to behave as they don't have data at all when loaded: they will not show up on splash load. When more data arrives let them appear

**Comment by olarosling** [comment]
The Splash-query-construction  must be way smarter. For now, you can make it smarter, by skipping splash, if state uses locked.
