### ISSUE TITLE
Y-axis style must allow smaller padding between numbers

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#1219]
Way more Y axis numbers could fit, if only the padding allowed was smaller.

Steps to reproduce:
Happens when in medium profile and reducing height of the chart. Axis ticks disappear too quickly
Y axis should show population on linear scale

![image](https://cloud.githubusercontent.com/assets/496398/12215283/bb07263c-b6b5-11e5-87f7-025a8f5f90eb.png)

**Comment by angieskazka** [comment]
![y5dh7hpgmt](https://cloud.githubusercontent.com/assets/3648190/12484898/ac11d2ca-c05c-11e5-85f6-28dc494ea428.gif)
