### ISSUE TITLE
v0.12.0_13: Color scale is showing invalid values before it switches

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1222]
**SEVERITY:** Major

**MODULE:** Stage 

**Platform:** 
* Windows 7 / Chrome 47.0
* MAC / Safari 9.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://stage-tools.gapminderdev.org/tools/map
2)	Tools page is loaded.
3)	Click Color
4)	Click drop down of color options
5)	Change color options from “Region” to “Child mortality rate”
6)	Note that Color scale is showing invalid values for a while.

**ACTUAL RESULTS:**
Color scale is showing invalid values

**EXPECTED RESULTS:** 
“Child mortality rate “option should be selected without any delay and color scale should not show invalid values for a while.

**SCREENSHOT:**

![v0 12 0_13](https://cloud.githubusercontent.com/assets/9950837/12229352/b9745934-b868-11e5-8a73-4474c251fb16.png)

**Comment by angieskazka** [comment]
@jheeffer should have fixed it (but i didn't know when)
