### ISSUE TITLE
v0.12.0_14: Some bubbles are not according to the color scale

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1224]
**SEVERITY:** Major

**MODULE:** Stage 

**Platform:** 
* Windows 7 / Chrome 47.0
* MAC / Safari 9.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://stage-tools.gapminderdev.org/tools/map
2)	Tools page is loaded.
3)	Click Color
4)	Click drop down of color options
5)	Change color options from “Region” to “Child mortality rate”
6)	Note that Some bubbles are not according to the color scale

**ACTUAL RESULTS:**
Some bubbles are not according to the color scale

**EXPECTED RESULTS:** 
All the bubbles color should be according to the selected color scale

**SCREENSHOT:**

![v0 12 0_14](https://cloud.githubusercontent.com/assets/9950837/12229785/bd1f63c2-b86c-11e5-9312-073536d263cc.png)

**Comment by angieskazka** [comment]
Yes, that means data for color is missing, but size and position are ok. We need to find a better way to show this (or not show these bubbles at all)

**Comment by jheeffer** [comment]
Add missing data color to color dialogue (if measure)?

**Comment by angieskazka** [comment]
Let's go for transparent color when there is no data for color

![image](https://cloud.githubusercontent.com/assets/3648190/12294786/31d648ca-b9fd-11e5-8c89-3bef997221a0.png)
