### ISSUE TITLE
v0.12.0_15: ‘x’ symbol is not available by tapping the tooltip

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1225]
**SEVERITY:** Major

**MODULE:** Stage 

**Platform:**  iPad Air 2 iOS(9.1) / Safari 

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://stage-tools.gapminderdev.org/tools
2)	Tools page is loaded.
3)	Select a country. Country is selected and tooltip is available
4)	Tap the tooltip to deselect the selected country
5)	Note that ‘x’ symbol is not available by tapping the tooltip

**ACTUAL RESULTS:**
‘x’ symbol is not available by tapping the tooltip

**EXPECTED RESULTS:** 
‘x’ symbol should be available by tapping the tooltip 

**SCREENSHOT:**

![v0 12 0_15](https://cloud.githubusercontent.com/assets/9950837/12233223/33b378ba-b887-11e5-8b5e-e309ce62510e.PNG)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1247

**Comment by k6Labz** [comment]
@angieskazka 
This issue is reproduced with same steps to reproduced and same device but on different chart (bubble map chart)
https://tools-stage.gapminderdev.org/tools/map

**Comment by angieskazka** [comment]
fixed in fb6be41ab231cd833f7c46bae0e947369c23fa72
