### ISSUE TITLE
v0.12.0_16: Charts are not loading

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1229]
**SEVERITY:**  Critical

**MODULE:**
* Bubble chart
* Mountain chart
* Bubble Map chart
* Pop by Age chart

**Platform:**  Windows 7 / Chrome 47.0

**RELEASE:** v0.12.0

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.12.0/preview/bubblechart.html
2)	Chart is not loading

**ACTUAL RESULTS:**
Charts are not loading

**EXPECTED RESULTS:**
Charts should be loaded

**SCREENSHOT:**

![v0 12 0_16](https://cloud.githubusercontent.com/assets/9950837/12254803/8d0929aa-b90e-11e5-96c9-74cdcd7bb735.png)

![v0 12 0_16 2](https://cloud.githubusercontent.com/assets/9950837/12254850/1e500fc8-b90f-11e5-863c-d51f28624025.png)

![v0 12 0_16 3](https://cloud.githubusercontent.com/assets/9950837/12254895/a7035c6c-b90f-11e5-8abd-64dd706c4ba0.png)

**Comment by angieskazka** [comment]
@k6Labz all the old releases will break now because of the wrong links to the data server, it’s expected =) we’ll work with develop for now, and v0.12.1 will come with the updated links
