### ISSUE TITLE
depth of trail bubbles

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#123]
![image](https://cloud.githubusercontent.com/assets/496398/7722860/3c7c0618-fee4-11e4-8ed2-a5c5af0970e8.png)
small trail bubbles must be in front of large non-selected
![image](https://cloud.githubusercontent.com/assets/496398/7722905/a499ac32-fee4-11e4-81b7-d3d440d0e3d5.png)

**Comment by angieskazka** [comment]
completed in the above a90a14d
