### ISSUE TITLE
Enabling "Follow bubbles with zoom" option does not zoom correctly

### ISSUE THREAD

**Issue by plward11** [Gapminder/vizabi#1230]
**MODULE:** Bubble chart

**Platform:**  Windows 7 / Chrome 47.0

**STEPS TO REPRODUCE:** 
1)	Enable the "Follow bubbles with zoom" option under the "X and Y" Options menu

**ACTUAL RESULTS:**
The canvas does not expand to fit the moving bubbles. It zooms too far in.

**EXPECTED RESULTS:**
The canvas correctly expands to fit the moving bubbles.

**Comment by plward11** [comment]
The most recent commit https://github.com/Gapminder/vizabi/commit/c2ea09ae8e5a8c115da479ef6566f433a6382218 seems to cause the issue. If I revert that commit, then the issue is fixed.

**Comment by angieskazka** [comment]
this commit is as unrelated as it can be. if there is a connection it must be very indirect
