### ISSUE TITLE
v0.12.0_17: No bars are available from 1800 to 1949

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1231]
**SEVERITY:**  Major

**MODULE:** Bar chart

**Platform:**  Windows 7 / Chrome 47.0

**RELEASE:** v0.12.0

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.12.0/preview/barchart.html
2)	Bar chart is loaded
3)	Drag the slider ball to the start
4)	Click play
5)	Note that no bars are available from 1800 to 1949

**ACTUAL RESULTS:**
No bars are available from 1800 to 1949. But after 1949 bars are available

**EXPECTED RESULTS:**
Bars should be available from start (1800) to the end (2012).

**SCREENSHOT:**

![v0 12 0_17](https://cloud.githubusercontent.com/assets/9950837/12256652/cc728804-b920-11e5-8e0a-637619807eaa.png)

**Comment by sergey-filipenko** [comment]
works well for me on develop, retest please

**Comment by jheeffer** [comment]
Fixed by latest bugfixing in formatting
