### ISSUE TITLE
v0.12.0_18: Click is not working on the slider bar

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1232]
**SUMMARY:**
**1)**  Click is not working on the slider bar
**2)**  Play icon is not working

**SEVERITY:** Major

**MODULE:** Stage 

**Platform:**  Windows 7 / Chrome 47.0 

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://tools-stage.gapminderdev.org/tools/bubbles 
2)	Tools page is loaded.
3)	Click Options. Small pop up screen is displayed.
4)	Click Speed and drag the slider ball to the maximum 
5)	Click play
6)	Let the slider ball reach at the mid of the slider bar
7)	Now click on the slider bar (from start to the place of slider ball)
8)	Note that slider ball is not moving to the place where we clicked on the slider bar.
9)	Repeat first five points and let the slider ball reach the end
10)	Now click the play icon which is actually pause icon at that time
11)	Note that play icon is not clickable

**ACTUAL RESULTS:**
Slider ball is not moving to the place where we clicked on the slider bar and Play icon is not working when slider ball reach the end

**EXPECTED RESULTS:** 
Play icon should be clicked any time and slider ball should also move on the slider bar according to click on the slider bar

**This issue is not reproducing frequently**

**SCREENSHOT:**

![v0 12 0_18](https://cloud.githubusercontent.com/assets/9950837/12261137/1096087e-b941-11e5-8cd6-2d659a89cf28.png)

**Comment by sergey-filipenko** [comment]
@k6Labz can not reproduce on Windows 7 / Chrome 47.0. Please retest

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Testing Environment:** https://tools-stage.gapminderdev.org/tools 

**Platform:** Windows 7 / Chrome 47.0
