### ISSUE TITLE
Improve style of panels Fontsizes 

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#1234]
The word Size should be smaller (bold) while the word Population can have larger fontsize and darker color.
(Same goes for all panel headers)
![image](https://cloud.githubusercontent.com/assets/496398/12263637/23009ea8-b931-11e5-9098-007d5194192f.png)

**Comment by angieskazka** [comment]
Here is the before-after image

![image](https://cloud.githubusercontent.com/assets/3648190/12580705/f45cbf4e-c431-11e5-98c5-3fa8010ada38.png)

![image](https://cloud.githubusercontent.com/assets/3648190/12580680/c77390de-c431-11e5-9dc8-4a998803b967.png)
