### ISSUE TITLE
Label-leash should go behind trail bubbles

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#124]
![image](https://cloud.githubusercontent.com/assets/496398/7723147/ca842448-fee6-11e4-9904-0870ef1fec82.png)

**Comment by arthurcamara1** [comment]
Info: this will simply require a layer for the label lines (label-leash)

**Comment by arthurcamara1** [comment]
Fixed by 8d3e016

<img width="336" alt="screen shot 2015-07-23 at 4 00 41 pm" src="https://cloud.githubusercontent.com/assets/3584238/8852184/f97c31b0-3153-11e5-9c08-639acabd371a.png">
