### ISSUE TITLE
v0.12.0_20: URL link fail:Chart is not loading

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1243]
**SEVERITY:** Critical

**MODULE:** Stage 

**Platform:**  
* Windows 7 / Chrome 47.0 
* MAC / Safari 9.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://tools-stage.gapminderdev.org/tools/bubbles 
2)	Tools page is loaded.
3)	Click Color. Small pop up screen is displayed.
4)	Click drop down and change the option from “Region” to “Constant”
5)	Copy the URL and paste in another tab
6)	Note that chart is not loading

**ACTUAL RESULTS:**
Chart is not loading after refreshing the page with some changes

**EXPECTED RESULTS:** 
Chart should be loaded in any case

**SCREENSHOT:**

**Screenshot 1:**
![v0 12 0_20](https://cloud.githubusercontent.com/assets/9950837/12288249/39e34094-b9f4-11e5-8311-f0abe1de52da.png)

**Screenshot 2:**
![v0 12 0_20](https://cloud.githubusercontent.com/assets/9950837/12288209/efbd7886-b9f3-11e5-8986-a301d5cde62f.png)

**Comment by angieskazka** [comment]
Fixed in v.0.12.1

**Comment by k6Labz** [comment]
@angieskazka 
Same issue is reproduced on the following link with same steps to reproduce
https://tools-stage.gapminderdev.org/tools/map

**Comment by angieskazka** [comment]
fixed with waffle server update
