### ISSUE TITLE
example pages: resize window should resize charts

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#125]
![image](https://cloud.githubusercontent.com/assets/496398/7745934/0d5b938c-ffaf-11e4-92bb-66f1f386c98d.png)

**Comment by arthurcamara1** [comment]
Fixed

**Comment by angieskazka** [comment]
Reopening, unfortunately. 
launch vizabi. 
press ![image](https://cloud.githubusercontent.com/assets/3648190/7908097/9d7b5d18-0841-11e5-8e57-d7779a3f4bf1.png)

Decrease width — placeholder size follows as needed
![image](https://cloud.githubusercontent.com/assets/3648190/7908113/c32e12da-0841-11e5-95d4-d1871ac5746a.png)

Now increase width — placeholder is stuck behind in its smallest size
![image](https://cloud.githubusercontent.com/assets/3648190/7908136/e534c9d2-0841-11e5-877e-4a0c2c8eb370.png)

same effect for height
