### ISSUE TITLE
v0.12.1_01: United States bubble is missing

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1257]
**SEVERITY:**  Critical

**MODULE:**  Bubble chart

**Platform:**  Windows 7 / Chrome 47.0

**RELEASE:** v0.12.1

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.12.1/preview/bubblechart.html 
2)	Bubble Chart will be loaded.
3)	Click “Find”
4)	Write ‘United States’ in search bar
5)	Note that there is no result shown

**ACTUAL RESULTS:**
United States bubble is missing 

**EXPECTED RESULTS:**
United States bubble should be there

**Many other countries are also missing like Zimbabwe and Zambia**

**SCREENSHOT:**

![v0 12 1_01](https://cloud.githubusercontent.com/assets/9950837/12385007/f09b39a2-bdd9-11e5-856b-e136a62f4eee.png)

**Comment by angieskazka** [comment]
should be fixed with reverting population data

**Comment by valorkin** [comment]
fixed
