### ISSUE TITLE
v0.12.1_02: Y axis description is truncated 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1258]
**SEVERITY:**  Major

**MODULE:**  Bubble chart

**Platform:**  Windows 7 / Chrome 47.0

**RELEASE:** v0.12.1

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.12.1/preview/bubblechart.html 
2)	Bubble Chart will be loaded.
3)	Increase the chart width by clicking increasing pointer (holding the click till width reach 600)  of the width input box which is available under RESPONSIVENESS
4)	Note that Y axis description is truncated from right side

**ACTUAL RESULTS:**
Y axis description is truncated from right side by increasing chart width

**EXPECTED RESULTS:**
Axis description should not be truncated from any side

**SCREENSHOT:**

![v0 12 1_02](https://cloud.githubusercontent.com/assets/9950837/12385790/684eebae-bde1-11e5-8f1c-5cc1d7e231a9.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1281
