### ISSUE TITLE
v0.12.1_03: Color picker is shown twice 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1259]
**SEVERITY:**  Major

**MODULE:**  Bubble chart

**Platform:**  Windows 7 / Chrome 47.0

**RELEASE:** Stage

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools/bubbles 
2)	Bubble Chart will be loaded.
3)	Click “Expand”
4)	Click “Options”. Small pop up screen is displayed
5)	Click ‘Color’ and change the option to “GDP per capita”
6)	 There are two color scales on the screen 
7)	Click any value from both the color scale
8)	Note that there are two color picker shown on the screen

**ACTUAL RESULTS:**
There are two color pickers shown on the screen

**EXPECTED RESULTS:**
Only one color picker should be there on screen at a time

**SCREENSHOT:**

![v0 12 1_03](https://cloud.githubusercontent.com/assets/9950837/12390863/68c670e2-be05-11e5-82ad-728bc4e71590.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1268
