### ISSUE TITLE
v0.12.1_04: No country is available on small pop up of Show icon 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1260]
**SEVERITY:**  Critical

**MODULE:**  Mountain Chart

**Platform:**  Windows 7 / Chrome 47.0

**RELEASE:** Stage

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools/mountain
2)	Click show icon
3)	Note that there is no country available on the pop up of show

**ACTUAL RESULTS:**
There is no country available on the pop up of show 

**EXPECTED RESULTS:**
All countries should be there on the pop up of show icon

**SCREENSHOT:**

![v0 12 1_04](https://cloud.githubusercontent.com/assets/9950837/12412521/0e26bfb2-bea9-11e5-9822-2d62455c0cdb.png)

**Comment by valorkin** [comment]
fixed
