### ISSUE TITLE
v0.12.1_05: Percentage on poverty line is not according to defined range

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1261]
**SEVERITY:**  Critical

**MODULE:**  Mountain Chart

**Platform:**  Windows 7 / Chrome 47.0

**RELEASE:** Stage

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools/mountain 
2)	Note that percentage on poverty line is not according to defined range.

**ACTUAL RESULTS:**
Note that Percentage on poverty line is not according to defined range 

**EXPECTED RESULTS:**
Note that Percentage on poverty line should be 11.5 ± 0.3%

**SCREENSHOT:**

![v0 12 1_05](https://cloud.githubusercontent.com/assets/9950837/12415750/28b3060e-bebf-11e5-9739-eed5130c2fc0.png)

**Comment by valorkin** [comment]
fixed
