### ISSUE TITLE
Crazy stuff in the URL when selecting entity on mountain chart

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#1262]
Steps to reproduce:

Open http://static.gapminderdev.org/vizabi/develop/preview/mountainchart.html
Select an entity
Observe crazy url:

http://static.gapminderdev.org/vizabi/develop/preview/mountainchart.html#_lang=en&width:320&height:534&fullscreen:false&bodyC=vzbp-nav-state-editor&resp-sect:true&info-sect:true&butt-sect:true&state_entities_select@_geo=ind&labelOffset@:0&:0;;;&highlight@_geo=ind&KEY=function%20()%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20this%5B/_this.KEY%5D/;%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D&sortValue@:1311050527&:3;&aggrLevel:0&hidden:false&yMax:1396423270.3464482;;;&marker_axis/_y_min:0&max:1947225432.6887364&fakeMin:0&fakeMax:1947225432.6887364

**Comment by valorkin** [comment]
not crazy, just function to string in state :)

**Comment by jheeffer** [comment]
It's this function

https://github.com/Gapminder/vizabi/blame/develop/src/tools/mountainchart/mountainchart-component.js#L535-L537

When an entity was highlighted, it's entire object, including that function, was added to the highlight-state. I think just adding its ID/value is enough. Can't imagine or find anything that breaks when I do for now.

**Comment by jheeffer** [comment]
Still there's confusing use of d.KEY() and d.key in mountain chart.

**Comment by jheeffer** [comment]
Digging in this also made me remember this: https://github.com/Gapminder/vizabi/issues/1282
