### ISSUE TITLE
v0.12.1_06: Present options is overlapping with the color picker

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1266]
**SEVERITY:**  Major

**MODULE:**  Bubble Map chart

**Platform:**  Windows 7 / Chrome 47.0

**RELEASE:** Stage

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools/map
2)	Bubble map Chart will be loaded.
3)	Click “Expand”
4)	Click “Options”. Small pop up screen is displayed
5)	Click ‘Color’ and change the option to “GDP per capita”
6)	 There are two color scales on the screen 
7)	Click any value from the color scale on small pop up screen
8)	Click Present drop down option on the small pop up screen
9)	Note that Present options is overlapping with the color picker

**ACTUAL RESULTS:**
Present options is overlapping with the color picker 

**EXPECTED RESULTS:**
Overlapping should not be there in any case

**SCREENSHOT:**

![v0 12 1_06](https://cloud.githubusercontent.com/assets/9950837/12442060/8bfc28bc-bf6e-11e5-92ab-7df5f63df9f5.png)

**Comment by angieskazka** [comment]
closed with #1268

**Comment by k6Labz** [comment]
@angieskazka 
The issue is reproduced again
Ans another issue is reproduced by following the same steps to reproduced.
**New issue: Bubbles have no color after chaging the color option to "GDP per capita"**
