### ISSUE TITLE
Can't scroll anything on mobile

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#1270]

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1271

**Comment by angieskazka** [comment]
Update: on Nexus 5 Android 6.0.1, Google Chrome 47.0.2526.83 
i can scroll only when USB debugging was connected during page load 
influence of observer

Others with the same platform were unable to reproduce the issue. We blame google chrome
