### ISSUE TITLE
v0.12.2_02: Lock and Trails options are not available after selecting a bubble

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1277]
**SEVERITY:**  Major

**MODULE:**  Bubble chart

**Platform:**  Nexus-5 (6.0) / Chrome 47.0

**RELEASE:** Stage

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools
2)	Bubble Chart will be loaded.
3)	Select a bubble
4)	Note that Lock and Trails options are not available after selecting a bubble

**ACTUAL RESULTS:**
Lock and Trails options are not available after selecting a bubble 

**EXPECTED RESULTS:**
Lock and Trails options should be available after selecting a bubble

**Comment by angieskazka** [comment]
it's expected. buttons hide because they don't fit (but we should still have them in more options)
