### ISSUE TITLE
v0.12.2_03: Show option is missing

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1278]
**SEVERITY:**  Major

**MODULE:**  Mountain chart

**Platform:**  Nexus-5 (6.0) / Chrome 47.0

**RELEASE:** Stage

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools
2)	Bubble Chart will be loaded.
3)	Note that Show option is missing

**ACTUAL RESULTS:**
Show option is missing 

**EXPECTED RESULTS:**
Show option should be there

**Comment by angieskazka** [comment]
we never had "show" option on bubble chart
on mountain chart mobile this may happen because show didn't fit, so it disappeared as the least-important

**Comment by k6Labz** [comment]
@angieskazka 
Thanks for the correction.
The issue was found on mountain chart but bubble chart was mentioned mistakenly. Will be careful next time.
