### ISSUE TITLE
v0.12.2: More than one chart + resize problem

### ISSUE THREAD

**Issue by buchslava** [Gapminder/vizabi#1280]
steps to reproduce

run this chromeapp (vizabi offline):

1. open a BubbleChart
![screenshot from 2016-01-22 16 47 40](https://cloud.githubusercontent.com/assets/6974213/12513940/4165443e-c129-11e5-9205-cac244cf8681.png)
![screenshot from 2016-01-22 16 47 51](https://cloud.githubusercontent.com/assets/6974213/12513941/4166b9ea-c129-11e5-9065-48046c961300.png)

2. create a new tab
![screenshot from 2016-01-22 16 47 55](https://cloud.githubusercontent.com/assets/6974213/12513959/539a91e0-c129-11e5-81b3-00f126fc8cd2.png)

3. open a new BubbleMap
![screenshot from 2016-01-22 16 48 03](https://cloud.githubusercontent.com/assets/6974213/12513972/67178e62-c129-11e5-91d0-8a891a0c0f80.png)
![screenshot from 2016-01-22 16 48 14](https://cloud.githubusercontent.com/assets/6974213/12513971/67143c3a-c129-11e5-8969-50af66defc75.png)

4. go to first tab (with BubbleChart)
![screenshot from 2016-01-22 16 48 20](https://cloud.githubusercontent.com/assets/6974213/12513990/81e29624-c129-11e5-88d5-9286be7d9bca.png)

5. go to second tab (BubbleMap) and after - change its size (resize for chromeapp window)
![screenshot from 2016-01-22 16 48 26](https://cloud.githubusercontent.com/assets/6974213/12514018/ade13e10-c129-11e5-81ba-4f6a04525728.png)

6. go to first tab:
![screenshot from 2016-01-22 16 48 34](https://cloud.githubusercontent.com/assets/6974213/12514024/c445902a-c129-11e5-84e4-051d6af7285e.png)

**Comment by buchslava** [comment]
steps to reproduce are next:

**Comment by buchslava** [comment]
run this chromeapp:
[vizabi-tools-offline.zip](https://github.com/Gapminder/vizabi/files/100925/vizabi-tools-offline.zip)

1. open a BubbleChart
![screenshot from 2016-01-22 16 47 40](https://cloud.githubusercontent.com/assets/6974213/12513940/4165443e-c129-11e5-9205-cac244cf8681.png)
![screenshot from 2016-01-22 16 47 51](https://cloud.githubusercontent.com/assets/6974213/12513941/4166b9ea-c129-11e5-9065-48046c961300.png)

2. create a new tab
![screenshot from 2016-01-22 16 47 55](https://cloud.githubusercontent.com/assets/6974213/12513959/539a91e0-c129-11e5-81b3-00f126fc8cd2.png)

3. open a new BubbleMap
![screenshot from 2016-01-22 16 48 03](https://cloud.githubusercontent.com/assets/6974213/12513972/67178e62-c129-11e5-91d0-8a891a0c0f80.png)
![screenshot from 2016-01-22 16 48 14](https://cloud.githubusercontent.com/assets/6974213/12513971/67143c3a-c129-11e5-8969-50af66defc75.png)

4. go to first tab (with BubbleChart)
![screenshot from 2016-01-22 16 48 20](https://cloud.githubusercontent.com/assets/6974213/12513990/81e29624-c129-11e5-88d5-9286be7d9bca.png)

5. go to second tab (BubbleMap) and after - change its size (resize for chromeapp window)
![screenshot from 2016-01-22 16 48 26](https://cloud.githubusercontent.com/assets/6974213/12514018/ade13e10-c129-11e5-81ba-4f6a04525728.png)

6. go to first tab:
![screenshot from 2016-01-22 16 48 34](https://cloud.githubusercontent.com/assets/6974213/12514024/c445902a-c129-11e5-84e4-051d6af7285e.png)

**Comment by buchslava** [comment]
I reproduced this issue with another solution (https://github.com/valor-software/vizabi-tools-ddf-csv-reader)

![screenshot from 2016-01-22 17 03 30](https://cloud.githubusercontent.com/assets/6974213/12514086/20cdba2a-c12a-11e5-8fab-ba7a97cc9408.png)

I can add more information about this solution on Monday

**Comment by buchslava** [comment]
you can reproduce it in online mode: http://vizabi-tools-ddf-csv-reader.gapminderdev.org/tools/

![screenshot from 2016-01-25 12 01 40](https://cloud.githubusercontent.com/assets/6974213/12547927/bd20789e-c35b-11e5-9974-2e08de009d1e.png)

steps to reproduce are same

**Comment by jheeffer** [comment]
Running multiple instances of Vizabi, or multiple graphs in one instance is not something we have looked at at all yet as far as I know. And this is even more specific since it's in different tabs. (i.e. the other instance is not visible at that time). Is this very necessary? One tab might suffice for now?

**Comment by angieskazka** [comment]
@jheeffer many tabs is necessary
we are doing the same thing (or we were doing) on tools page: many vizabi charts at once, but only one is visible
we are doing the same thing on vizabi docs website (but i think there is no resizing)

**Comment by angieskazka** [comment]
Solved.
The problem was happening because all SVG positioning in vizabi depends on width, height of a container, and for `display: none` width and height are `auto` which turned into NaN after measuring it with `parseInt(this.element.style("height"), 10)`.

This is now changed to the following:
```
height = (parseInt(this.element.style("height"), 10)) || height || 0;
width = (parseInt(this.element.style("width"), 10)) || width || 0;
if(height<=0 || width<=0) return utils.warn("Chart resize() abort: vizabi container is too little or has display:none");
```

This means the chart can not be resized when inside a `display: none` container (but it won't flood you with errors any longer if you try to). The problem is that after container is displayed again, the chart is going to be broken or incorrectly resized. I can suggest one of the two solutions to this:

1. For the hidden tab, use `visibility: hidden` instead of `display: none`. 
(i tried to modify it in vizabi-tools-offline: main.scss L53 but it didn't do anything)

or

2. Force-resize the tab after selecting it. I was able to fix it like this: vizabi-tools-offline: controller.js L98 
```
        $scope.setTab = function (tabId) {
          //set current tab id and get current graph object
          $scope.currentTab = tabId;
          $scope.selectedGraph = _.findWhere($scope.tabs, {id: tabId}).graphName;
          $scope.forceResizeEvt();
        };
          
        $scope.forceResizeEvt = function () {
          //force resize
          $timeout(function () {
            var event = document.createEvent("HTMLEvents");
            event.initEvent("resize", true, true);
            event.eventName = "resize";
            window.dispatchEvent(event);
          }, 0);  
        };
```
