### ISSUE TITLE
Highlight gets in to the URL state without being persistent

### ISSUE THREAD

**Issue by jheeffer** [Gapminder/vizabi#1282]
When selecting an entity, which is a persistent action, your mouse is over it, thus it's also highlighted. Because selecting is persistent, it fires of a persistentChange event, correctly. However, the state will also include the highlight state, which should not ever end up in the URL.

So, it seems persistent changes can make unpersistent changes end up in the URL. I know @arthurcamara1 is of the opinion the state should not ever contain something inpersistent, right?
To me the state is the state, i.e. the model should always reflect the state of the application (otherwise, how are we going to communicate the changing highlight state between components?).

At the moment, only the events are labelled for persistence. I propose to **Label each leaf if its current value is persistent.** If the current value is not persistent, it should also have saved the old, persistent, value. When Vizabi is asked for the state, it should return the latest persistent state. I.e. leafs with a inpersistent current value should be represented with their latest persistent values.

This can also replace persistent-property of events. This can be done without the external page losing knowledge if a change was persistent. Instead of looking at the event-property, it can just look at the event-source property. That always points to the leaf, which then will have a persistent property. We can also still support a persistentChange fired by Vizabi by doing the same internally on Tool-level, where the persistentChange-event is generated.

**Comment by jheeffer** [comment]
I made the changes already, so you can check it out in practice. Wonder if you see any downsides?

**Comment by angieskazka** [comment]
@jheeffer : @arthurcamara1 
highlight should not be in state - yes, because it's very volatile and temporary and we don't want it to end up in URL
and NO, because if we will want to have 2 vizabi tools on one page and have them as connected views, then we need them to communicate highlighting via state

**Comment by jheeffer** [comment]
we have to make sure we talk about the same state

the state of Vizabi is the model-tree, where models can listen to. It captures the actual state of Vizabi at a certain moment in time. Including default and (in my opinion) non-persistent state.
I would not call what is in the url simply 'the state' (although I know it is called that often within gapminder). If anything it's the persistent part of the state which is different from the default state. Maybe url-state for short ; )
