### ISSUE TITLE
Bubbles in the correct places

### ISSUE THREAD

**Issue by valorkin** [Gapminder/vizabi#1284]
# Description 
You see the bubbles in the correct places (picture)

# Actual result 
Testing

# Other information 
Reported by: Abid Ali 

Test case number: TC01 

Test run: [https://valorsoftware.testlodge.com/projects/15827/runs/189523?tab=2&run_section_id=162283&executed_case_id=9196558#executed_case_9196558](https://valorsoftware.testlodge.com/projects/15827/runs/189523?tab=2&run_section_id=162283&executed_case_id=9196558#executed_case_9196558)

**Comment by k6Labz** [comment]
Just for testing lodge itself :)
