### ISSUE TITLE
Only Afghanistan is visible after switching indicators

### ISSUE THREAD

**Issue by valorkin** [Gapminder/vizabi#1287]
# Description 
Axis option can be changed by clicking Axis description(Bubble , Bubble_Map)

# Actual result 
**SUMMARY:**  Chart is disturbed by selecting “GDP per capita”

**SEVERITY:**  Critical

**MODULE:**  Bubble Map chart

**Platform:** 
* Windows 7 / Chrome 47.0 
* MAC / Safari 9.0

**RELEASE:** Stage

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools/map
2)	Bubble Map Chart will be loaded.
3)	Click on Y axis description
4)	Hover the Wealth option and Select “GDP per capita”
5)	Note that Chart is disturbed by selecting “GDP per capita”

**ACTUAL RESULTS:**
Chart is disturbed by selecting “GDP per capita”

**EXPECTED RESULTS:**
Chart should not disturb in any case

# Other information 
Reported by: Abid Ali 

Test case number: TC69 

Test run: [https://valorsoftware.testlodge.com/projects/15827/runs/189933?tab=2&run_section_id=162891&executed_case_id=9210263#executed_case_9210263](https://valorsoftware.testlodge.com/projects/15827/runs/189933?tab=2&run_section_id=162891&executed_case_id=9210263#executed_case_9210263)

**Comment by sergey-filipenko** [comment]
@k6Labz Can not reproduce. Please retest
