### ISSUE TITLE
There is extra-large space on full screen

### ISSUE THREAD

**Issue by valorkin** [Gapminder/vizabi#1293]
# Description 
On large screen there is a side panel with color controls and list of countries.

# Actual result 
**SUMMARY:**  There is extra-large space on full screen

**SEVERITY:**  Major

**MODULE:** 
•	Bubble chart
•	Bubble Map Chart
•	Mountain Chart

**Platform:**  Windows 7 / Chrome 47.0

**RELEASE:** v0.12.4

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.12.4/preview/bubblemap
2)	Bubble Map Chart will be loaded.
3)	Click Expand
4)	Note that there is extra-large space on full screen

 **ACTUAL RESULTS:**
There is extra-large space on full screen 

**EXPECTED RESULTS:**
There should no extra space on the chart

# Other information 
Reported by: Abid Ali 

Test case number: TC33 

Test run: [https://valorsoftware.testlodge.com/projects/15827/runs/190325?tab=2&run_section_id=163698&executed_case_id=9232235#executed_case_9232235](https://valorsoftware.testlodge.com/projects/15827/runs/190325?tab=2&run_section_id=163698&executed_case_id=9232235#executed_case_9232235)

![image](https://cloud.githubusercontent.com/assets/3648190/12713089/fa9d3006-c8cc-11e5-967c-a799f1ec18e6.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1306
