### ISSUE TITLE
URL link fail: Presentation mode never gets to the URL, because ui model is not exposed in url

### ISSUE THREAD

**Issue by valorkin** [Gapminder/vizabi#1294]
# Description 
URL persistency: set time slider to some point, refresh, timeslider should keep the point you gave it, and chart should load at the state of that point.
URL persistency: select a few entities, refresh, entities should be selected.

# Actual result 
**SUMMARY:**  URL link fail: Present icon deactivated 

**SEVERITY:**  Major

**MODULE:** 
•	Bubble Map Chart
•	Mountain Chart

**Platform:**  Windows 7 / Chrome 47.0

**RELEASE:** v0.12.4

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.12.4/preview/bubblemap
2)	Bubble Map Chart will be loaded.
3)	Click “Full” icon under RESPONSIVENESS
4)	Click “Present icon” on the chart
5)	Copy the URL and paste it in another tab
6)	Note that Present icon is not active any more

**ACTUAL RESULTS:**
URL link fail: Present icon deactivated on refreshing the page

**EXPECTED RESULTS:**
Changes should be saved instantly

# Other information 
Reported by: Abid Ali 

Test case number: TC34 

Test run: [https://valorsoftware.testlodge.com/projects/15827/runs/190325?tab=2&run_section_id=163698&executed_case_id=9232236#executed_case_9232236](https://valorsoftware.testlodge.com/projects/15827/runs/190325?tab=2&run_section_id=163698&executed_case_id=9232236#executed_case_9232236)

**Comment by jheeffer** [comment]
So right now the ui-model is a child of the base toolmodel. We should move it to be a child of model.state.

**Comment by jheeffer** [comment]
Fixed with ec71ee2a380c67ad185fe78354c716d37928cedc

API change! Vizabi.getMinState() now returns the full `ToolModel`, instead of `ToolModel.state`.
I.e. it includes `lang`, `data` and `ui`.
