### ISSUE TITLE
Chart fails to resize correctly on load // URL persistency

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1299]
# Description 
URL persistency: set time slider to some point, refresh, timeslider should keep the point you gave it, and chart should load at the state of that point.
URL persistency: select a few entities, refresh, entities should be selected.

# Actual result 
**Logging this issue on Github as an experiment**
**SUMMARY:**  URL link fail: Chart size changes

**SEVERITY:**  Major

**MODULE:**  Bubble Map Chart

**Platform:**  Windows 7 / Chrome 47.0

**RELEASE:** Stage

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : https://tools-stage.gapminderdev.org/tools 
2)	Bubble Chart will be loaded.
3)     Scroll down and select Bubble Map chart
4)     Copy the URL and paste it in another tab of same browser
5)     Compare the charts of both tabs
6)     Note that Chart size is different on same URL

**ACTUAL RESULTS:**
URL link fail: Chart size changes

**EXPECTED RESULTS:**
Chart should remain fine and same after refreshing the URL

# Other information 
Reported by: Abid Ali 

Test case number: TC34 

Test run: [https://valorsoftware.testlodge.com/projects/15827/runs/190556?tab=2&run_section_id=164273&executed_case_id=9244277#executed_case_9244277](https://valorsoftware.testlodge.com/projects/15827/runs/190556?tab=2&run_section_id=164273&executed_case_id=9244277#executed_case_9244277)

![image](https://cloud.githubusercontent.com/assets/3648190/12711645/e0c3af8a-c8c1-11e5-8980-88ef56761c3e.png)

![image](https://cloud.githubusercontent.com/assets/3648190/12711659/f1f6a38e-c8c1-11e5-95bc-1bd2206ed702.png)

**Comment by angieskazka** [comment]
seems to be connected to #1293
