### ISSUE TITLE
URL link fail: Mountain chart desn't save changes in the url on tools page

### ISSUE THREAD

**Issue by natali-abyss** [Gapminder/vizabi#1300]
## Description
Don't save change in the URL

<b>SEVERITY:</b> Major

<b>MODULE:</b> 
• Mountain Chart

<b>Platform:</b> mac os x 10.10 / Chrome 47.0

<b>RELEASE:</b> v0.12.5

<b>STEPS TO REPRODUCE: </b>
1) Navigate to the URL : https://tools-dev.gapminderdev.org/tools/mountain
2) Click on options -> stack.
3) Change first options
4) Refresh page 

<b>ACTUAL RESULTS:</b>
After reloading the page - chart returned to the default value

**Comment by angieskazka** [comment]
it works on [vanilla vizabi](http://static.gapminderdev.org/vizabi/develop/preview/mountainchart.html), so my best guess is that the bug is the same as #1274

**Comment by angieskazka** [comment]
needs a retest, but i just tried it and it worked fine
