### ISSUE TITLE
Tools page is not using new Vizabi minModel API

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1315]
# Description 
URL persistency: set time slider to some point, refresh, timeslider should keep the point you gave it, and chart should load at the state of that point.
URL persistency: select a few entities, refresh, entities should be selected.

# Actual result 
**SUMMARY:**  URL link fails: Country is unselected and trails are disappeared

**SEVERITY:**  Major

**MODULE:**  Bubble chart

**Platform:**  Windows 7 / Chrome 47.0 

**RELEASE:** Stage

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools
2)	Bubble Chart will be loaded.
3)	Select a Country
4)	Click Play
5)	Drag the slider to the center of slide bar
6)	Copy the URL and paste it in another tab
7)	Note that Country is unselected and trails are disappeared in new tab

**ACTUAL RESULTS:**
Country is unselected and trails are disappeared on refreshing the page. URL is changed in new tab.

**EXPECTED RESULTS:**
Changes should remain saved even after refreshing the page

# Other information 
Reported by: Abid Ali 

Test case number: TC34 

Test run: [https://valorsoftware.testlodge.com/projects/15827/runs/191323?tab=2&run_section_id=165641&executed_case_id=9269124#executed_case_9269124](https://valorsoftware.testlodge.com/projects/15827/runs/191323?tab=2&run_section_id=165641&executed_case_id=9269124#executed_case_9269124)

**SCREENSHOT:**

![v0 12 5_01 1](https://cloud.githubusercontent.com/assets/9950837/12805849/aabe261a-cb21-11e5-9ee1-7d537e9ecf75.png)

![v0 12 5_01 2](https://cloud.githubusercontent.com/assets/9950837/12805850/aabe2df4-cb21-11e5-9835-a1717509a1e3.png)

![v0 12 5_01 3](https://cloud.githubusercontent.com/assets/9950837/12806431/d26da900-cb27-11e5-93d1-327b5da325cc.png)

![v0 12 5_01 4](https://cloud.githubusercontent.com/assets/9950837/12806432/d26e806e-cb27-11e5-809f-d1cafa86b4f8.png)

**Comment by jheeffer** [comment]
Expected because tools page does not support new api yet. I can fix this

**Comment by angieskazka** [comment]
waat? _state_state_state? :monkey:

**Comment by jheeffer** [comment]
closed with https://github.com/Gapminder/gapminder-tools-vizabi/commit/2571149a4d9076f75736ba0f0bd73a8216f7cc43

Also fixes this state_state_state thing ; )
