### ISSUE TITLE
Numeric identifiers for entities should be allowed?

### ISSUE THREAD

**Issue by jheeffer** [Gapminder/vizabi#1318]
At the moment we're only showing geo's which have string identifiers.

Question is if it should be possible to use numeric identifiers? At the moment Vizabi breaks with numeric geo-identifiers because css-classes can't start with numbers.

Why should we allow it? Because many organisations use numeric identifiers for their entities and want to use their data as is instead of having to change it. This issue popped up when @cjbackman wanted to import a local swedish dataset with kommuner and basområder, which had numeric identifiers.

**Comment by angieskazka** [comment]
we should support numeric identifiers.
if it's only a css problem then just prepend the class with "id_" or something when assigning (and selecting later on)

**Comment by angieskazka** [comment]
48aa1682b7a8ccd97640096330d845e045fb1e08

**Comment by valorkin** [comment]
I would propose to use scope dependable prefixes
`geo_` for geo ids
`year_` for year 
and so on
taking in count that concept ids and ids inside of concepts unique
it will give completely unique id

**Comment by valorkin** [comment]
until same data point will appear several times :D
