### ISSUE TITLE
Expand button is truncated on resizing the window

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1333]
# Description 
If you resize the window, the picture is not messed up, but adapts nicely.

# Actual result 
**SUMMARY:**  Expand button is truncated on resizing the window

**SEVERITY:**  Minor

**MODULE:**  Bubble chart

**Platform:** 
* Windows 7 / Chrome 47.0 
* MAC / Safari 9
* Nexus-5 (6.0) / Chrome 47.0

**RELEASE:** Stage

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools
2)	Bubble Chart will be loaded.
3)	Resize the window
4)	Note that expand button is truncated on resizing the window
5)     To reproduce it on mobile device, just change the orientation of the moblie

**ACTUAL RESULTS:**
Expand button is truncated on resizing the window

**EXPECTED RESULTS:**
No button should be truncated in any case

# Other information 
Reported by: Abid Ali 

Test configuration: Chrome, Desktop PC 

Test case number: TC02 

Test run: [https://valorsoftware.testlodge.com/projects/15827/runs/192615?tab=2&run_section_id=168040&executed_case_id=9321185#executed_case_9321185](https://valorsoftware.testlodge.com/projects/15827/runs/192615?tab=2&run_section_id=168040&executed_case_id=9321185#executed_case_9321185)

**SCREENSHOT:**

![v0 12 6_02](https://cloud.githubusercontent.com/assets/9950837/12969624/e5d027d4-d0a4-11e5-93e4-f1a408c8d8d1.png)

![v0 12 6_02 2](https://cloud.githubusercontent.com/assets/9950837/12971537/fa3fdff2-d0bd-11e5-93d7-f2c2e2c7ca13.png)

**Comment by angieskazka** [comment]
fixed with changing the container size on tools page
