### ISSUE TITLE
Block page scrolling when dragging time slider

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#1340]
When I slide timeslider, and drag down window, the pages scrolls down. 
We don't want to loose the chart from sight, if mouseDown happened inside charts

This happens on scrollable pages like http://tools-dev.gapminderdev.org/
Not only happens on touch device but also on desktop with Apple magic mouse where button is also a scrolling surface

**Comment by angieskazka** [comment]
kind of got it working

**Comment by angieskazka** [comment]
scrolling on drag beyond the edge of the screen should be prevented too

![ow5ccvm1ma 1](https://cloud.githubusercontent.com/assets/3648190/13814035/ffc952d2-eb84-11e5-9ae2-c41c11f5fc0d.gif)

**Comment by plward11** [comment]
Pull request - https://github.com/Gapminder/vizabi/pull/1522

**Comment by angieskazka** [comment]
YES! you nailed it
