### ISSUE TITLE
We don't want lin / log option on Size - picker

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#1347]
![image](https://cloud.githubusercontent.com/assets/3648190/12979027/ded64226-d0d4-11e5-8bfd-de9a83fa45aa.png)

That means, for size: always use "lin" with the square root scale for circle area.

**Comment by jheeffer** [comment]
Why not? If a measure is logarithmic (like income?) you'd want it to be log, no?

**Comment by angieskazka** [comment]
@jheeffer agree. but doing is probably easier than trying to convince Ola that it's useful

**Comment by angieskazka** [comment]
Not agree because log scale on size is a nice possibility
Agree because it's a very advanced one and you have  to be aware what you're doing. 
I removed it and we move on
Just so you know, allowed scales is part of hook configuration and can be super easily configured from either vizabi or tools page
