### ISSUE TITLE
Max size of GDP is not working. The largest bubbles should be way larger

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#1348]
![image](https://cloud.githubusercontent.com/assets/3648190/12979042/f419560a-d0d4-11e5-9460-3c72da4980cd.png)

I guess this is another hardcoded max-value right?

http://tools-dev.gapminderdev.org/tools/bubbles#_state_marker_color_use=constant&palette_%2F_default=%23c9edf5;&which=%2F_default;&size_which=gdp%2F_const%2F_ppp2011%2F_dollar;;&entities_select@_geo=usa&labelOffset@:0&:0;&trailStartTime=2015;&_geo=chn&labelOffset@:0&:0;&trailStartTime=2015

**Comment by jheeffer** [comment]
most likely metadata domain right?
