### ISSUE TITLE
 Pop by age chart is not loading

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1358]
**SEVERITY:**  Critical

**MODULE:**  Pop by Age Chart

**Platform:**  Windows 7 / Chrome 47.0

**RELEASE:** v0.12.6

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.12.6/preview/popbyage.html
2)	Line Chart will not be loaded.

**ACTUAL RESULTS:**
Pop by age chart is not loading 

**EXPECTED RESULTS:**
Chart should be loaded properly

**SCREENSHOT:**

![v0 12 6_05](https://cloud.githubusercontent.com/assets/9950837/13045076/3b6f23b0-d3f3-11e5-82e1-4b1c11ccdb25.png)

**Comment by angieskazka** [comment]
fixed on develop
