### ISSUE TITLE
All options are localized by switching language

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1360]
**SEVERITY:**  Minor

**MODULE:** 
* Bubble Chart
* Bubble Map Chart
* Mountain Chart

**Platform:**  Windows 7 / Chrome 47.0

**RELEASE:** v0.12.6

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.12.6/preview/bubblechart.html
2)	Bubble Chart will be loaded.
3)	Click options icon on the chart
4)	Click switch language button 
5)	Note that on the small pop up of options , PRESENT is not localized

**ACTUAL RESULTS:**
On the small pop up of options, PRESENT is not localized by switching language

**EXPECTED RESULTS:**
All the options should be localized by switching language

**SCREENSHOT:**

![v0 12 6_07](https://cloud.githubusercontent.com/assets/9950837/13048478/e52c2150-d407-11e5-95eb-8afeaa415c6d.png)

**Comment by angieskazka** [comment]
"present" is ok for now, i didn't come up with a better wording. It should be "Presentera", but it's too long
