### ISSUE TITLE
Vizabi component templates are spilling to an external page

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#1362]
If you open HTML tree you will see vizabi elements outside vizabi container
Dima and the team are troubled by this:

![image](https://cloud.githubusercontent.com/assets/3648190/13113582/e88dbc76-d58f-11e5-897a-23468a787563.png)

Why we need templates on the page - to load them fast, we need to preload them and append.
Arthur says they are loaded outside the placeholder but could as well be inside. Let's move them inside placeholder. (gulpfile.js line 192-206)

***
improvement: only add the ones needed for the current viz (example, the ones needed for bubble chart only - we havent done that yet because with the number of vizs we have now and most templates being common, the improvement is not so big yet, but it will be when we have lots of visualizations)

**Comment by angieskazka** [comment]
done
![image](https://cloud.githubusercontent.com/assets/3648190/14441510/5b16d97e-0035-11e6-9b15-23a64715706d.png)

**Comment by valorkin** [comment]
@angieskazka is there are a PR I can take a look on?

**Comment by angieskazka** [comment]
@valorkin see the commit history above, particularly this:
one: 7cef39c42308f20b7d2cbf96243ffc745185d90d
two: fc22b769efc5f5133dfbc35c7e953c45fb84bfa2
