### ISSUE TITLE
Amount of people living in the extreme poverty

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1364]
# Description 
In 2015 there is roughly the same amount of people living in the extreme poverty as there was in 1800 (827 and 812 Millions). Hover the X Axis to check the number of people.

# Actual result 
**SUMMARY:**  Poverty line is not showing exact values

**SEVERITY:**  Major

**MODULE:**  Mountain chart

**Platform:**  Windows 7 / Chrome 47.0 

**RELEASE:** Stage

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools/mountain
2)	Mountain Chart will be loaded.
3)	Hover the X axis to see the poverty line values
4)	Note that there are 826M people living in extreme poverty instead of 827M at 2015 
5)	Also note that there are 811M people living in extreme poverty instead of 812M at 2015

**ACTUAL RESULTS:**
Poverty line is not showing exact values.

**EXPECTED RESULTS:**
Poverty line should show exact expected values which are 827M and 812M (in 2015 and 1800)

# Other information 
Reported by: Abid Ali 

Test configuration: Chrome, Desktop PC 

Test case number: TC20 

Test run: [https://valorsoftware.testlodge.com/projects/15827/runs/193777?tab=2&run_section_id=170488&executed_case_id=9365296#executed_case_9365296](https://valorsoftware.testlodge.com/projects/15827/runs/193777?tab=2&run_section_id=170488&executed_case_id=9365296#executed_case_9365296)

**SCREENSHOT:**

![v0 12 7_01 1](https://cloud.githubusercontent.com/assets/9950837/13140133/0c87fb38-d652-11e5-9bf6-92c204c96570.png)

![v0 12 7_01 2](https://cloud.githubusercontent.com/assets/9950837/13140135/0caa8978-d652-11e5-9fb2-dbc3b670c9a7.png)

**Comment by angieskazka** [comment]
oh i know why! it was a good puzzle but there was a minor change which makes it expected. take it easy

REASON: only `geo.cat=unstate` countries are requested, before it was `geo.cat=unstate,country`
