### ISSUE TITLE
Fullscreen presentation mode is broken on reload, for utils.extend() uses shallow extend

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#1365]
@dab2000:

1) load develop-preview (bubblechart)
2) click full size in  responsiveness;
3) select options-present-increase text size...
4) reload

after reload I've gotten exeption in buttonlist init because config.ui have missed buttons and dialogs properties.
little debug and I found problem in bubblechart.html:81.
Vizabi.utils.extend(VIZABI_MODEL, URL.model);
URL.model have property ui.presentation and utils.extend overwrite VIZABI_MODEL properties(buttons and dialogs) with ui.presentation.
I think utils.extend must be smarter.

@jheeffer: 
ah, good, yes, it should be, it should use deepextend, not extend
extend is shallow, only first level

**Comment by jheeffer** [comment]
https://github.com/Gapminder/vizabi/blob/develop/preview/_partials/toolscript.jade#L82
this should be
`Vizabi.utils.deepExtend(VIZABI_MODEL, URL.model);`

**Comment by jheeffer** [comment]
Closed by https://github.com/Gapminder/vizabi/commit/5462e40a67a0d1b2d218d0798649abb8a08513df
