### ISSUE TITLE
How to modify several model properties together (sync/async problem)?

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#137]
in this code for `what = INDICATOR` i need to set which, use, unit, scaleType all in one action without `validate` being called in between or `change` events triggered. 
After all variables are set let `validate` and events trigger as they should

```
        _setModel: function(what, value) {
            var mdl = this.model.axis;
            mdl[what] = value;

            if (what == INDICATOR) {
                mdl.use = availOpts[value].use;
                mdl.unit = availOpts[value].unit;

                if (availOpts[value].scales.indexOf(mdl.scaleType) == -1) {
                    mdl.scaleType = availOpts[value].scales[0];
                }
            }
        }
```

(otherwise the model triggers `scale rebuild` before `scaletype` is set. wrong `scaletype` is applied and everything gets screwed)

**Comment by arthurcamara1** [comment]
A method for the described situation was just introduced now.
This will block validation and freeze events between assignments:

```javascript
model.atomic();
model.field1 = "test";
model.field2 = "test two";
model.atomic(false);
```

So your code would look like this:

```javascript
_setModel: function(what, value) {
    var mdl = this.model.axis;

    mdl.atomic(); //this will block validation and freeze events

    mdl[what] = value;

    if (what == INDICATOR) {
        mdl.use = availOpts[value].use;
        mdl.unit = availOpts[value].unit;

        if (availOpts[value].scales.indexOf(mdl.scaleType) == -1) {
            mdl.scaleType = availOpts[value].scales[0];
        }
    }

    mdl.atomic(false); //this will trigger validation and all the events
}
```

**Comment by angieskazka** [comment]
Did as you say, on `mdl.atomic(false)` validation was triggered, but not the `change` event in bubble chart

**Comment by arthurcamara1** [comment]
Sorry @angieskazka, my solution was misleading. I just pushed aa4edd64b1c990ae0f05063b424358aadcf98ad7 removing the ```atomic``` method because a solution for that was already in place and it's way more obvious. It's simply using ```set```.

So the code should look like this:

```javascript
mdl.set({
     property1: "value1",
     property2: "value2"
});
```

Validation will only be called after both are in place.

So now it's correct: https://github.com/Gapminder/vizabi/blob/aa4edd64b1c990ae0f05063b424358aadcf98ad7/src/components/_gapminder/indicatorpicker/indicatorpicker.js#L154
