### ISSUE TITLE
Find the way to export bubble map as two svg's or better as a single svg

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#1378]
solution: optionally add class `vzb-svg-exportable` to the svg elements we would want to export, in every chart
when running the exporting script (_interaction.js:54), download each `vzb-svg-exportable` element.
if there is no `vzb-svg-exportable` element then download the first one, as it's done now

advanced: pack all `vzb-svg-exportable` elements into one svg before download, and get that one.

why don't we just put bubble map's SVGs under one parent svg? it works perfectly but slows down fps on timeslider drag for some reason, even though only the bubbles are being redrawn according to green chrome rectangles. maybe you can find the way so it doesn't slow down. see commits in #1374 

this issue follows #1374

**Comment by dab2000** [comment]
I think we need fork svg-crowbar and update it for our purposes.
1. Now if 'Download' is pressed we have all svg with inline styles...
2. Scan is needed for div>svg selector
3. We can add ability append a few svg in one if they have same parent div

**Comment by angieskazka** [comment]
agree but afraid of running into maintenance issues when NYTimes would update theirs

you can give it a try:
https://github.com/Gapminder/svg-crowbar
