### ISSUE TITLE
Fullscreen infinite recursion

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#138]
feature/restructure-vizabi
Entering fullscreen, exiting fullscreen and resizing the window in fullscreen makes this happen:

![image](https://cloud.githubusercontent.com/assets/3648190/7903359/08e650f2-07da-11e5-88ea-aa38fe351d2e.png)

**Comment by arthurcamara1** [comment]
Fixed with commit 320a62b5801d1e3e927bd42f79c9d5429a6dc045
