### ISSUE TITLE
Cross of tooltip is overlapping with the size:population

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1387]
**SEVERITY:**  Minor

**MODULE:**  Bubble Map chart

**Platform:**  Windows 7 / Chrome 48.0 

**RELEASE:** Stage

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools/map 
2)	Bubble Map Chart will be loaded.
3)	Select “Unite States”
4)	Drag the tooltip of selected country under the size:population
5)	Hover the tooltip to get cross sign on it
6)	Note that cross of tooltip is overlapping with the size:population 

**ACTUAL RESULTS:**
Cross of tooltip is overlapping with the size:population

**EXPECTED RESULTS:**
No overlapping should be there on the chart

**SCREENSHOT:**

![v0 12 8_04](https://cloud.githubusercontent.com/assets/9950837/13485411/4b5e6590-e129-11e5-9d8e-4086a1437d95.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1414
