### ISSUE TITLE
Tooltip is disappeared on Firefox

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1390]
**SEVERITY:**  Major

**MODULE:**  Bubble Map chart

**Platform:**  Windows 7 / Firefox  44.0

**RELEASE:** Stage

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools/map 
2)	Bubble Chart will be loaded.
3)	Click “United States” bubble
4)	Tooltip is shown on the left top corner
5)	Drag the tooltip near to the selected bubble
6)	Note that tooltip of selected country is disappeared. 

**ACTUAL RESULTS:**
Tooltip of selected country is disappeared by dragging the tooltip

**EXPECTED RESULTS:**
Tooltip of selected country should be should be visible properly

**SCREENSHOT:**

![v0 12 8_07](https://cloud.githubusercontent.com/assets/9950837/13487707/cd0210c4-e13d-11e5-850c-a3907e3faabf.png)

**Comment by angieskazka** [comment]
fixed by 881e8b89a8a77ffd075e39975496ac7311bed1ca
same as #1384 #1385 #1386
