### ISSUE TITLE
Multiple bubbles cannot be selected 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1391]
**SEVERITY:**  Major

**MODULE:**  Bubble Map chart

**Platform:** 
* Windows 7 / Firefox  44.0
* Windows 7 / Chrome 48.0

**RELEASE:** Stage

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools/map 
2)	Bubble Chart will be loaded.
3)	Click “United States” bubble
4)	Tooltip is shown on the left top corner
5)	Select India
6)	Note that previous tooltip is overlapped with India tooltip but bubble is not selected

**ACTUAL RESULTS:**
After selecting India bubble, previous tooltip is overlapped with India tooltip but bubble is not selected 

**EXPECTED RESULTS:**
Many bubble can be selected

**SCREENSHOT:**

![v0 12 8_08](https://cloud.githubusercontent.com/assets/9950837/13487898/50c381da-e13f-11e5-828f-f1b71686f0bd.png)

**Comment by angieskazka** [comment]
fixed by 881e8b89a8a77ffd075e39975496ac7311bed1ca
same as #1384 #1385 #1386
