### ISSUE TITLE
There is no American Samoa country at the map

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1398]
**SEVERITY:** Minor

**MODULE:** Map

**PLATFORM:** Any

**RELEASE:** Stage

**STEPS TO REPRODUCE:**
1) Navigate to the URL : http://tools-stage.gapminderdev.org/tools/map
2) Map will be loaded.
3) Select American Samoa country at the Find panel.

**ACTUAL RESULTS:**
This country will be labeled at some point on the map but there is no such a bubble.

**EXPECTED RESULTS:**
There should be such a bubble on the map.

**SCREENSHOT:**
![snap37](https://cloud.githubusercontent.com/assets/16382915/13495509/cf34918a-e153-11e5-8c9b-503af0b0868b.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1413
