### ISSUE TITLE
Firefox: Presentation mode is not changing font size

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1405]
# Description 
Text on chart is more visible by clicking Present

# Actual result 
**SUMMARY:**  Text is not highlighted by clicking “Present” 

**SEVERITY:**  Major

**MODULE:**  Mountain chart

**Platform:**  Windows 7 / Firefox  44.0

**RELEASE:** Stage

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools/mountain 
2)	Mountain Chart will be loaded.
3)	Click “Present” icon
4)	Note that all the text is not highlighted on the chart

**ACTUAL RESULTS:**
Text is not highlighted by clicking “Present” 

**EXPECTED RESULTS:**
All the text should be highlighted by clicking “Present”

# Other information 
Reported by: Abid Ali 

Test configuration: Firefox, Desktop PC 

Test case number: TC64 

Test run: [https://valorsoftware.testlodge.com/projects/15827/runs/196555?tab=2&run_section_id=176920&executed_case_id=9472949#executed_case_9472949](https://valorsoftware.testlodge.com/projects/15827/runs/196555?tab=2&run_section_id=176920&executed_case_id=9472949#executed_case_9472949)

**SCREENSHOT:**

![v0 12 8_09](https://cloud.githubusercontent.com/assets/9950837/13525016/707b92ba-e220-11e5-9f25-e587b1fe794b.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1412
also fixed for bubblechart
