### ISSUE TITLE
Firefox: Massive color picker consuming all available space and more

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1406]
# Description 
I can choose any color from color picker

# Actual result 
**SUMMARY:**  Chart is disturbed by changing color 

**SEVERITY:**  Critical

**MODULE:**  Mountain chart

**Platform:**  Windows 7 / Firefox  44.0

**RELEASE:** Stage

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools/mountain 
2)	Mountain Chart will be loaded.
3)	Click “color” icon
4)	Click drop down to change the color option
5)	Select individual by hovering properties on pop up
6)	Click any colored bubble to change the color through color picker
7)	Note that chart is disturbed by changing color

**ACTUAL RESULTS:**
Chart is disturbed by changing color 

**EXPECTED RESULTS:**
Chart should not be disturbed in any case

# Other information 
Reported by: Abid Ali 

Test configuration: Firefox, Desktop PC 

Test case number: TC68 

Test run: [https://valorsoftware.testlodge.com/projects/15827/runs/196555?tab=2&run_section_id=176920&executed_case_id=9472953#executed_case_9472953](https://valorsoftware.testlodge.com/projects/15827/runs/196555?tab=2&run_section_id=176920&executed_case_id=9472953#executed_case_9472953)

**SCREENSHOT:**

![v0 12 8_10](https://cloud.githubusercontent.com/assets/9950837/13525468/e7bb584a-e222-11e5-9597-cfdb1027d097.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1411
