### ISSUE TITLE
Color is not changed according to color scale

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1407]
# Description 
On entering the text in field of Search(size,color), shows expected search hits

# Actual result 
**SUMMARY:**  Color is not changed according to color scale 

**SEVERITY:**  Major

**MODULE:**  Bubble chart

**Platform:**  MAC (10.11.1) / Safari 9.0

**RELEASE:** Stage

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools 
2)	Bubble Chart will be loaded.
3)	Click “color” icon
4)	Click drop down to change the color option
5)	Select GDP total by hovering wealth on pop up
6)	**Note that bubbles color is not changed**
7)	Click any digit on the color scale  to change the color through color picker
8)	**Also note that color is not changed by changing color from color scale**

**ACTUAL RESULTS:**
Color is not changed according to color scale 

**EXPECTED RESULTS:**
Color should be changed according to color scale

# Other information 
Reported by: Abid Ali 

Test configuration: Safari 9, MAC 

Test case number: TC57 

Test run: [https://valorsoftware.testlodge.com/projects/15827/runs/196555?tab=2&run_section_id=176921&executed_case_id=9472970#executed_case_9472970](https://valorsoftware.testlodge.com/projects/15827/runs/196555?tab=2&run_section_id=176921&executed_case_id=9472970#executed_case_9472970)

**SCREENSHOT:**

![v0 12 8_11](https://cloud.githubusercontent.com/assets/9950837/13526259/af07b2b8-e228-11e5-941e-487ad214901f.png)

**Comment by k6Labz** [comment]
Closing as not reproduceable
