### ISSUE TITLE
MS Edge: Mountain chart have visual defects

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1410]
# Steps to reproduce issue 
Go to {tools-page}/tools/mountain.

# Expected result 
Mountain chart shouldn't have any visual defects.

# Actual result 
There are visual defects on chart.

![alt text](http://i.piccy.info/i9/e00e21e15aa7d92f6792c4eacfd29fdd/1457094617/18776/1010584/Snap40.png)

# Other information 
Reported by: Valeriy Trots 

Test configuration: Edge, Win10, PC 

Test case number: TC75 

Test run: [https://valorsoftware.testlodge.com/projects/15827/runs/196595?tab=2&run_section_id=176998&executed_case_id=9473539#executed_case_9473539](https://valorsoftware.testlodge.com/projects/15827/runs/196595?tab=2&run_section_id=176998&executed_case_id=9473539#executed_case_9473539)

**Comment by angieskazka** [comment]
why wouldn't microsoft just please stop making browsers?

**Comment by dab2000** [comment]
I don't have any visual defects on tool-stage (edge,w10). Looking like line antialiasing problem.

**Comment by angieskazka** [comment]
it's possible to try the following options in _mountainchart.scss line 18:

```
.vzb-mc-mountain {
        shape-rendering: auto; 
```

try: auto | optimizeSpeed | crispEdges | geometricPrecision

**Comment by TValeriy** [comment]
I think we can close it for now.
I have another VM (VMWare instead of VirtualBox) and it looks without defects.

![snap52](https://cloud.githubusercontent.com/assets/16382915/13662985/18447eb4-e6a7-11e5-8fde-4ec44fe321e1.png)
