### ISSUE TITLE
Make bubble chart ratain zoom on refresh

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#1415]
Now when we refresh the page we loose the zoom as well (see _panZoom.reset() in `ready` and `readyOnce` methods)

We need to restore zoom from axis_x.zoomedMin/Max axis_y.zoomedMin/Max which are recorded in URL
```
    //this._panZoom.reset();  // not anymore
    this._panZoom.zoomToMaxMin(
       this.model.marker.axis_x.zoomedMin,
       this.model.marker.axis_x.zoomedMax,
       this.model.marker.axis_y.zoomedMin,
       this.model.marker.axis_y.zoomedMax
    )
```

Same should work when switch indicators (`ready` method) size, color, label size

If we change X or Y then zoom can reset of course, but that would also go through zoomedMin/Max, which would be first reset to null and then validated back from scale.domain()

**Comment by plward11** [comment]
Pull request - https://github.com/Gapminder/vizabi/pull/1418
