### ISSUE TITLE
Bubblechart: Unwanted zoom-in (zoom-to-visible) when switching Y axis to log scale

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1420]
**SEVERITY:**  Major

**MODULE:**  Bubble chart

**Platform:** 
* Windows 7 / Chrome 48.0
* Windows 7 / Firefox  44.0
* MAC (10.11.1) / Safari 9.0
* Nexus-5 (6.0) / Chrome 48.0
* iPad Air 2 iOS(9.2.1) / Safari

**RELEASE:** Stage

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools 
2)	Bubble Chart will be loaded.
3)	Click y axis description
4)	Click on “log” which is available on the small pop up screen
5)	Drag the slider to the start at year 1800
6)	Note that bubbles are truncated from upper side
7)	Also note that axis starting digit is truncated 
         (on Nexus-5 (6.0) / Chrome 48.0 and iPad Air 2 iOS(9.2.1) / Safari)

**ACTUAL RESULTS:**
Bubbles are truncated by clicking on log.

**EXPECTED RESULTS:**
Bubbles should not be truncated

**SCREENSHOT:**

![v0 12 8_12](https://cloud.githubusercontent.com/assets/9950837/13562742/73bc55a6-e45d-11e5-9985-90efb4e07aef.png)

**Comment by angieskazka** [comment]
this got fixed together with #1415
