### ISSUE TITLE
Selecting on the Linear or Log

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1421]
# Description 
Linear and log options on pop up of color and size are working acordingly

# Other information 
Reported by: Abid Ali 

Test configuration: Safari 9, iPad Air 2 

Test case number: TC67 

Test run: [https://valorsoftware.testlodge.com/projects/15827/runs/196555?tab=2&run_section_id=176922&executed_case_id=9473008#executed_case_9473008](https://valorsoftware.testlodge.com/projects/15827/runs/196555?tab=2&run_section_id=176922&executed_case_id=9473008#executed_case_9473008)

**Comment by k6Labz** [comment]
Closing as duplicate of #1420
