### ISSUE TITLE
 Label zoom value is different on different platforms  

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1423]
**SEVERITY:**  Minor

**MODULE:**  Bubble chart

**Platform:**  iPhone-4G(iOS 7.1.2)/ Safari 

**RELEASE:** Stage

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools 
2)	Bubble Chart will be loaded.
3)	Tap “Options” 
4)	Tap “Labels” on the small pop up of “Options”
5)	Drag the pointer to the maximum side and note the value which is 19
6)	Repeat the same steps for windows 7 / chrome 48 and note the value which is 26

**ACTUAL RESULTS:**
Label zoom value is different on different platforms  

**EXPECTED RESULTS:**
Label zoom value should be same on different platforms  

**SCREENSHOT:**

![v0 12 8_13 1](https://cloud.githubusercontent.com/assets/9950837/13598449/a630c08e-e53f-11e5-94f7-a010f12fe802.png)

![v0 12 8_13 2](https://cloud.githubusercontent.com/assets/9950837/13598450/a656e854-e53f-11e5-83b5-19717ec2e50f.PNG)

**Comment by angieskazka** [comment]
this is expected because we have different profiles, so we want different label size
![xh9jmk1gat](https://cloud.githubusercontent.com/assets/3648190/13602528/7075e5a8-e537-11e5-8486-63871648e63d.gif)

**Comment by angieskazka** [comment]
added a unit suffix now

![image](https://cloud.githubusercontent.com/assets/3648190/13603123/41f62086-e53b-11e5-8a9f-b8cabf732733.png)
