### ISSUE TITLE
iPhone-4G(iOS 7.1.2)/ Safari: Chart is disturbed on tapping “Expand”  

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1424]
**SEVERITY:**  Major

**MODULE:**  Bubble chart

**Platform:**  iPhone-4G(iOS 7.1.2)/ Safari 

**RELEASE:** Stage

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools 
2)	Bubble Chart will be loaded.
3)	Tap “Expand”
4)	Note that chart is disturbed 

**ACTUAL RESULTS:**
Chart is disturbed on tapping “Expand”  

**EXPECTED RESULTS:**
Chart should not be disturbed on tapping “Expand”  

**SCREENSHOT:**

![v0 12 8_14](https://cloud.githubusercontent.com/assets/9950837/13598663/e1ba4264-e540-11e5-875e-be96ef3595a6.PNG)

**Comment by sergey-filipenko** [comment]
works well for me now, please retest
