### ISSUE TITLE
Bubble label stuck in the splash-load position and doesn't jump to the beginning of the trail

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1437]
# Description 
URL persistency: set time slider to some point, refresh, timeslider should keep the point you gave it, and chart should load at the state of that point.
URL persistency: select a few entities, refresh, entities should be selected.

# Actual result 
**SUMMARY:**  URL link fails: position of tooltip and slider ball is changed after refreshing the page 

**SEVERITY:**  Major

**MODULE:**  Bubble chart

**Platform:**  
* Windows 7 / Chrome 48.0 
* Windows 7 / Firefox 44.0 
* MAC (10.11.1) / Safari 9.0
* MAC (10.11.1) / Chrome 48.0

**RELEASE:** Stage

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools/bubbles
2)	Bubble Chart will be loaded.
3)	Select United States bubble
4)	Drag the slider ball to the start 
5)	Click play and let the slider reach at the center approximately 
6)	Click pause
7)	Copy the URL and paste it in another tab
8)	Compare both tabs
9)	Note that position of tooltip and slider ball is changed on both tabs
**Only tooltip issue is reproducing on Firefox and MAC**

**ACTUAL RESULTS:**
Position of tooltip and slider ball is changed after refreshing the page 

**EXPECTED RESULTS:**
Changes should remain saved after refreshing the page

# Other information 
Reported by: Abid Ali 

Test configuration: Chrome, Desktop PC 

Test case number: TC34 

Test run: [https://valorsoftware.testlodge.com/projects/15827/runs/197531?tab=2&run_section_id=178836&executed_case_id=9502280#executed_case_9502280](https://valorsoftware.testlodge.com/projects/15827/runs/197531?tab=2&run_section_id=178836&executed_case_id=9502280#executed_case_9502280)

**SCREENSHOT:**

![v0 13 0_01 1](https://cloud.githubusercontent.com/assets/9950837/13661310/6aa68150-e6b3-11e5-9e7f-a6a3660602e6.png)

![v0 13 0_01 2](https://cloud.githubusercontent.com/assets/9950837/13661309/6aa61b52-e6b3-11e5-83d3-398a7fdc4745.png)

**Comment by k6Labz** [comment]
Closing as it is bug of the other link : tools-stage.gapminderdev.org/tools/bubbles

**Comment by k6Labz** [comment]
@angieskazka 
This issue is reproduced on the following link : http://tools-stage.gapminderdev.org/tools/bubbles 

**Platform:**  Windows 7 / Chrome 48.0 

**Release:**  v0.13.1
