### ISSUE TITLE
Year should be available on tooltip 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1439]
**SEVERITY:**  Minor

**MODULE:**  Bubble map chart

**Platform:**
* Windows 7 / Chrome 48.0 
* Windows 7 / Firefox 44.0 

**RELEASE:** Stage

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://178.62.135.203:8081/tools/map
2)	Bubble map Chart will be loaded.
3)	Select a country
4)	Note that no year is available on the tooltip

**ACTUAL RESULTS:**
No year is available on the tooltip after selecting a bubble

**EXPECTED RESULTS:**
Year should be available on tooltip for selected bubble like year in bubble chart

**SCREENSHOT:**

![v0 13 0_03 1](https://cloud.githubusercontent.com/assets/9950837/13661327/954d3af2-e6b3-11e5-93db-94ea615433cb.png)

![v0 13 0_03 2](https://cloud.githubusercontent.com/assets/9950837/13661326/953fb5ee-e6b3-11e5-83e0-e0e1b70e6f15.png)

**Comment by angieskazka** [comment]
no. you can't have many years together on bubble map
