### ISSUE TITLE
Search bar is not shown properly 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1442]
**SEVERITY:**  Minor

**MODULE:**  Mountain chart

**Platform:**  MAC (10.11.1) / Safari

**RELEASE:** Stage

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://178.62.135.203:8081/tools/mountain
2)	Mountain Chart will be loaded
3)	Click “Show”
4)	Note that Search bar is not shown properly

**ACTUAL RESULTS:**
Search bar is not shown properly 

**EXPECTED RESULTS:**
Search bar should be shown properly 

**SCREENSHOT:**

![v0 13 0_06](https://cloud.githubusercontent.com/assets/9950837/13661356/c3bca3a0-e6b3-11e5-9c3e-bdc3bccb853f.png)

**Comment by angieskazka** [comment]
this happened after i replaced input type "text" with input type "search". i must have missed out safari
see commit 4604a9ef26244efa44af72e1de9e3a1ca7f4ecea

**Comment by angieskazka** [comment]
Looks better now but it's still smaller than the one in chrome

![image](https://cloud.githubusercontent.com/assets/3648190/13797636/4ae1138e-eb0f-11e5-8fc1-cf036487ffbd.png)
