### ISSUE TITLE
Zoom controls via buttons part 2: Bubble chart panZoom

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#1458]
part 1 in #1457

Depending on the "ui.cursorMode" change cursor over the bubble chart to plus or minus. We have plus on [control] hold now.

Plus cursor should work same as zoom with [ctrl] key: allow to select a rectangle, but with no key hold.
Minus cursor should work on click and zoom out the chart predictably.

Disable zoom on scrolling via option ui.zoomOnScrolling. Page should scroll instead. This should not affect mobile zoom-pinch though. Test both true and false defaults.

Let panning work as it does, on touch too.

**Comment by plward11** [comment]
Pull request https://github.com/Gapminder/vizabi/pull/1474

Adds support for the "plus", "minus", and `ui.zoomOnScrolling` options.
