### ISSUE TITLE
Validating time boundaries for the sparse datasets

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#1461]
Right now time start and end boudaries validate (tool.js: 255-256) to the limits of one request. This means that time validates to the broadest of indicators availability in this request.

Make sure getLimits() look into all hooks and their data (except ignoreAvailability) within one request. So that time validates to the narrowest of the data of all indicators. See below examples of availability:

```
now:
   ---------          axis x data
         ------------ axis y data
result:
   <       >



    
should be:
   ---------          axis x data
         ------------ axis y data
result:
         < >
             
also:
   ---------------    axis x data
         --------     axis y data
result
         <      >   
    
also:
   ----               axis x data
         --------     axis y data
result
       null (don't modify time boundaries)   
```

Add a field to the color hook: let color model have "color.ignoreAvailability" . skip it when calculating intersections

**Comment by jheeffer** [comment]
Will now be solved by adding `availability` as concept property to metadata.json.

This is a temporary solution. Availability is not a concept property but part of availability query. It is a property of a key-value pair.

The following are examples that don't work with availability as a concept property of population.

SG has population for 1800-2000
GW has popuatlion for 1900-2015

population by geo/year is 1800-2000
population by geo/year/gender is 1850-1900

So what we need is to put it in DDFQL and request it from readers.

**Comment by jheeffer** [comment]
Let's keep it open so we don't forget this is a temporary solution.
