### ISSUE TITLE
Load, change time, refresh, get empty screen for all years 

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#1464]
likely the same getFrames bug somewhere in the promise bush )

![ktzlmkmcwc](https://cloud.githubusercontent.com/assets/3648190/13699614/c6117bbc-e77b-11e5-82a1-5143b94d1e47.gif)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1466
