### ISSUE TITLE
Events that depend on the result of getFrame come before getFrame

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#1483]
Bubble chart:
updateMarkerSizeLimits() is called before ready(). 
This can happen if events get unfrozen and getFrame() still didn't return data"

i added a warning to indicate when it happens

Switch to reading the data file basic-indicators.csv

in vizabi-gapminder.js change the following:

```
BubbleChart.define('default_model', {
  state: {
    time: {
      start: "1990",
      end: "2014",
      value: "2000"
    },
    entities: {
      show: {
        _defs_: {
          "geo": ["africa", "asia", "europe", "americas"]
        }
      }
    }
  },
  data: {
    reader: "csv",
    path: globals.gapminder_paths.baseUrl + "data/waffles/basic-indicators.csv",
    splash: false
  },
```

**Comment by sergey-filipenko** [comment]
upd in vizabi-gapminder.js
`entities: {
      dim: "geo",
      show: {
        _defs_: {
          "geo": ["africa", "asia", "europe", "americas"]
        }
      }
    },`
https://github.com/Gapminder/vizabi/pull/1489
