### ISSUE TITLE
Can't save time objects in time model and pass them through URL

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1485]
# Description 
URL persistency: set time slider to some point, refresh, timeslider should keep the point you gave it, and chart should load at the state of that point.
URL persistency: select a few entities, refresh, entities should be selected.

# Actual result 

**SUMMARY:**  After selecting few entities, refresh, The chart did not load properly.

**SEVERITY:**  Major

**MODULE:**  
* Bubble Chart
* Mountain Chart
* Bubble Map

**Platform:**
* Windows 7 / Chrome 49.0
* Windows 7 / Firefox 45.0
* iPad Air 2 iOS(9.2.1) / Safari

**RELEASE:** v0.13.2

**STEPS TO REPRODUCE:**
1) Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.13.2/preview/
2) Bubble Chart will be loaded.
3) Select some entities / bubbles
4) Refresh the page 

**ACTUAL RESULTS:**
The chart did not loaded after refreshing the page 

**EXPECTED RESULTS:**
The chart should be loaded properly

# Other information 
Reported by: Abid Ali 

Test configuration: Chrome, Desktop PC 

Test case number: TC34 

Test run: [https://valorsoftware.testlodge.com/projects/15827/runs/198361?tab=2&run_section_id=180819&executed_case_id=9537708#executed_case_9537708](https://valorsoftware.testlodge.com/projects/15827/runs/198361?tab=2&run_section_id=180819&executed_case_id=9537708#executed_case_9537708)

**SCREENSHOT:**

![load](https://cloud.githubusercontent.com/assets/9950837/13768884/8dd9726c-ea9c-11e5-9f1d-2d6be340513e.png)

**Comment by angieskazka** [comment]
![image](https://cloud.githubusercontent.com/assets/3648190/13816478/d9eb2a7c-eb8e-11e5-931f-3bc62e1273b0.png)
