### ISSUE TITLE
Mountain chart, URL persistency: Scale is being reset after refreshing the page

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1498]
SEVERITY: Major

MODULE: Mountain Chart

PLATFORM: Any

RELEASE: v0.13.3

STEPS TO REPRODUCE:
1) Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.13.3/preview/mountainchart.html .
2) Click [Show] and select "Ukraine".
3) Select 1943 year on time bar for example.
4) Refresh the page.

ACTUAL RESULTS:
Scale will be reset.
![snap63](https://cloud.githubusercontent.com/assets/16382915/13806353/e095baf2-eb63-11e5-96c6-e22f406b7fe5.png)

EXPECTED RESULTS:
Scale of chart shouldn't be reset.
![snap62](https://cloud.githubusercontent.com/assets/16382915/13806363/eb9b043e-eb63-11e5-87ab-c65f4ced552f.png)

**Comment by sergey-filipenko** [comment]
Can not reproduce, please retest

**Comment by TValeriy** [comment]
Retested. Doesn't happen on v0.13.5.
