### ISSUE TITLE
After selecting country from show option,  whole mountain got disappeared

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1500]
**SEVERITY:**  Major

**MODULE:** Mountain Chart

**Platform:**
1) Nexus-5 (6.0) / Chrome 48.0
2) Nexus 9 (5.1) / Chrome 48.0
3) iPad Air 2 iOS(9.2.1) / Safari

**RELEASE:** v0.13.3

**STEPS TO REPRODUCE:**
1) Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.13.3/preview/mountainchart.html 
2) Mountain Chart will be loaded.
3) Tap on show from options 
4) Select countries and tap ok

**ACTUAL RESULTS:**
When user select country from show option instead of appearing that country, the whole mountain got disappeared

**EXPECTED RESULTS:**
The mountain should not disappeared from the chart after selecting country from show option

**NOTE:** When the user expand the screen or play or drag the slider the mountain appears 

**SCREENSHOT:**

![img_0435](https://cloud.githubusercontent.com/assets/9950837/13810438/a6b19fb2-eb91-11e5-945a-14839584ed75.PNG)
![img_0436](https://cloud.githubusercontent.com/assets/9950837/13810439/a6bbe896-eb91-11e5-953d-98df0d653806.PNG)

**Comment by angieskazka** [comment]
can't reproduce on desktops and nexus 5
