### ISSUE TITLE
Dataset: South Sudan should be in Africa

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#1504]
The country must have a value in Systema Globalis to belong to the world_4region = Africa (to not be white) 

![image](https://cloud.githubusercontent.com/assets/496398/13823847/b7ac83c6-ebab-11e5-9138-016dedb97f15.png)

**Comment by angieskazka** [comment]
i suspect the issue involves renaming the ID of south sudan from "sds" to "ssd" which happened in SG but not in GW data. so when converting data from GW, ssd might have not been found in the geo.region data

**Comment by jheeffer** [comment]
South Sudan did not have any region in GW data

https://github.com/semio/ddf--gapminder_world/blob/master/output/ddf--entities--geo--country.csv 

at the bottom. There is other countries/territories too. Wonder what to with these?
