### ISSUE TITLE
Dataset: Income mountains don't show but data is there somehow?  

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#1505]
https://tools-dev.gapminderdev.org/tools/mountain
![image](https://cloud.githubusercontent.com/assets/496398/13823956/2daa385c-ebac-11e5-9edb-788e3a4a034d.png)

**Comment by angieskazka** [comment]
Gini data is not available from ws (measure name "inequality_index_gini")

it is likely that no such data existed in GW because we produced it specifically for vizabi tools. Maybe need to import that data from SG (where it is called just "gini")

**Comment by jheeffer** [comment]
There is GINI data but it's way less rich than in SG:

https://docs.google.com/spreadsheets/u/1/d/1Iztdl7Ddaz77K3HheGpkvQ1o_ui_L1s-sze_ZpTM0F0/pub
https://github.com/semio/ddf--gapminder_world/blob/master/output/ddf--datapoints--inequality_index_gini--by--geo--time.csv

Could that be reason why it's not showing, @angieskazka ?

**Comment by angieskazka** [comment]
Mountain chart data can't exist for regions because their shapes are combined from data.
So: move gini data from SG to GW, that should do the trick, can be under a different id (gini)

**Comment by angieskazka** [comment]
GW data is only for 1978 to 2010 and very sparse. Let's replace it with SG data 
![v85znsvqfa](https://cloud.githubusercontent.com/assets/3648190/13832265/dcb06366-ebda-11e5-9c51-7d5b9b360b80.gif)

**Comment by jheeffer** [comment]
Yes, for sure, I'm just wondering why there's no income mountain at all now? There ís data, it's just sparse?
