### ISSUE TITLE
The x-axis label, shouldn't show ugly "unit/"

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#1506]
Most measures are missing Unit. (Then don't show the id )
![image](https://cloud.githubusercontent.com/assets/496398/13824010/7fa2dfce-ebac-11e5-8a6d-a12e32618fa7.png)

![image](https://cloud.githubusercontent.com/assets/496398/13824859/24147f74-ebb0-11e5-826f-5f70d3fa1014.png)

https://tools-dev.gapminderdev.org/tools/bubbles#_state_marker_axis%2F_x_domainMin:142&domainMax:182700&zoomedMin:142&zoomedMax:182700;&axis%2F_y_which=improved%2F_water%2F_source%2F_rural%2F_access%2F_percent&domainMin:1&domainMax:100&zoomedMin:1&zoomedMax:100;&size_domainMin:50&domainMax:1376000000&zoomedMin:50&zoomedMax:1376000000;&size%2F_label_which=%2F_default&extent@:0&:0.33;;&color_palette_americas@=%237feb00&=%235de200&=%2381f201&=%2300b900&=%23b5ea32&=%23008d36;&africa@=%2300d5e9&=%2300c8ec&=%2300e1ec&=%230098df&=%2377dff7&=%230586c6;&%2F_default@=%23ffb600&=%23ffaa14&=%23ffc500&=%23fb6d19&=%23ffb600&=%239b4838;&asia@=%23ff5872&=%23ff5178&=%23ff658a&=%23da0025&=%23fa4e73&=%23b2043a;&europe@=%23ffe700&=%23fbdd00&=%23fff400&=%23fbaf09&=%23ffe700&=%23b17f4a;;;;&time_value=2010&start=1991&end=2010&startOriginal_utc=function%20toUTCString()%20%7B%20%5Bnative%20code%5D%20%7D;&endOriginal_utc=function%20toUTCString()%20%7B%20%5Bnative%20code%5D%20%7D

**Comment by jheeffer** [comment]
In GW data units are included in the indicator name, so there's no separate translations for units.

Options:
1) if no translation, don't show id
2) make all unit translations empty strings.

**Comment by angieskazka** [comment]
3) rewrite many names to split them into name and unit part, so that they have unit field

we take approach 1+3
