### ISSUE TITLE
Bubble chart should have generic access to entities dimension

### ISSUE THREAD

**Issue by arthurcamara1** [Gapminder/vizabi#151]
If dim is different than "geo", bubble chart should still work.

https://github.com/Gapminder/vizabi/blob/develop/src/tools/bubblechart/bubblechart-component.js#L485

**Comment by angieskazka** [comment]
Now it does, and so does line chart, collision resolver, color legend and entity finder
However time remains a problem

I always request, for example, values from the model, be calling getValue({key: d[KEY], time: time})
