### ISSUE TITLE
x-axis numeric labels are cropped 

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#1510]
![image](https://cloud.githubusercontent.com/assets/496398/13824459/6e82b46a-ebae-11e5-93fb-d58236650fe7.png)
![image](https://cloud.githubusercontent.com/assets/496398/13824517/a449ebd6-ebae-11e5-801a-374c77fa3cd9.png)

**Comment by angieskazka** [comment]
closing as duplicate of #103
