### ISSUE TITLE
Treemenu: extra layer of depth

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#1511]
Add an extra level of depth. Basically like the colum-navigaiotn of folders on Mac: where the deepest level is the leaf (the document)  and then you click OK, under that deepest leaf which can write out the complete measure name.  

like this 
![image](https://cloud.githubusercontent.com/assets/496398/13824646/34437ee6-ebaf-11e5-89f5-f927c4231aaa.png)

**Comment by angieskazka** [comment]
styling and interactivity improvements: 1bbbc07ab440712e2fc2e4a1ab473610dc88ae5e
