### ISSUE TITLE
Treemenu: fail when screen is not wide enough

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#1512]
![image](https://cloud.githubusercontent.com/assets/496398/13824717/8683da7a-ebaf-11e5-83a7-fb9e01bc0963.png)

In this case, wee need a iPhone-menu strategy: like clicking back one level up, in top left corner
![image](https://cloud.githubusercontent.com/assets/496398/13824775/d65c4e56-ebaf-11e5-9126-978283bc613c.png)

**Comment by angieskazka** [comment]
It's much better now, but i could still produce an occasion where the items go beyond the screen and are not clickable
container is 612x744, clicked options, then size selector


![image](https://cloud.githubusercontent.com/assets/3648190/14046984/33980e4c-f2a5-11e5-910e-3fdfaec37a32.png)

**Comment by angieskazka** [comment]
passed
