### ISSUE TITLE
After generating trails when user change the color from color options, the trails got disaapeared

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1520]
**SEVERITY:**  Major

**MODULE:** Bubble Chart

**Platform:**
1) Windows 7 / Chrome 49.0
2) Windows 7 / Firefox 45.0
3) MAC (10.11.1) / Safari 9.0
4) MAC (10.11.1) / Chrome 49.0

**RELEASE:** v0.13.3

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools/bubbles
2) Bubble Chart will be loaded
3) Click china and USA bubble
4) Click play button and don’t pause until the slider reach to the year 2015
5) Click on color icon
6) Select any color from color options

**ACTUAL RESULTS:**
After selecting other color from color options the generated trails got disappeared from the chart

**EXPECTED RESULTS:**
Only the color should change according to option but the trails should not get disappeared from the chart 

**SCREENSHOT:**

![b4](https://cloud.githubusercontent.com/assets/9950837/13845574/a0c33526-ec62-11e5-8367-22509a6fd96e.png)

![after](https://cloud.githubusercontent.com/assets/9950837/13845578/a7f2bdb2-ec62-11e5-9090-4b08529158ea.png)

**Comment by k6Labz** [comment]
@angieskazka 

**Retest result:** Fail

**AUT:** http://tools-stage.gapminderdev.org/tools/bubbles

**Platform:** 
* Windows 7 / Chrome 48.0
* Windows 7 / Firefox 45.0

**Screenshot:**

![25_2](https://cloud.githubusercontent.com/assets/9950837/14038675/ee50ebf8-f275-11e5-8912-1290af04b382.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1595
