### ISSUE TITLE
The trails generated are not proper when user expand the page

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1523]
**SEVERITY:**  Major

**MODULE:** Bubble Chart

**Platform:**
1) Windows 7 / Chrome 49.0
2) Windows 7 / Firefox 45.0
3) MAC (10.11.1) / Safari 9.0
4) MAC (10.11.1) / Chrome 49.0

**RELEASE:** v0.13.3

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools/bubbles
2) Bubble Chart will be loaded
3) Click china and USA bubble
4) Click play button and don’t pause until the slider reach to the year 2015
5) Click on color icon
6) Select any color from color options
7) Drag the slider ball from 2015 to 1800 and then drag it again from 1800 to 2015
8) Click on expand icon

**ACTUAL RESULTS:**
The trails generated are not proper when user expand the page

**EXPECTED RESULTS:**
Trails should be properly visible even user expand the page

**SCREENSHOT:**

![expand](https://cloud.githubusercontent.com/assets/9950837/13876218/5fbf0eac-ed24-11e5-930f-caf9c263ce64.png)

**Comment by angieskazka** [comment]
this was also fixed by 47ef22f6cdfcc4378c6dbad13000d79358edf3a7 together with #1520 #1521

**Comment by k6Labz** [comment]
@angieskazka

**Retest result:** Fail

**AUT:** http://tools-stage.gapminderdev.org/tools/bubbles

**Platform:**
Windows 7 / Chrome 48.0
Windows 7 / Firefox 45.0

**Screenshot:**

![25_4](https://cloud.githubusercontent.com/assets/9950837/14039152/484f86c8-f27b-11e5-8e24-cf27019a09c7.png)
![25_4_a](https://cloud.githubusercontent.com/assets/9950837/14039153/4851c1d6-f27b-11e5-9155-9bff1e32685b.png)

**Comment by k6Labz** [comment]
@angieskazka

**Retest result:** Fail

**AUT:** http://tools-stage.gapminderdev.org/tools/bubbles

**Platform:**
Windows 7 / Chrome 48.0
Windows 7 / Firefox 45.0

**Screenshot:**

![25_4](https://cloud.githubusercontent.com/assets/9950837/14039152/484f86c8-f27b-11e5-8e24-cf27019a09c7.png)
![25_4_a](https://cloud.githubusercontent.com/assets/9950837/14039153/4851c1d6-f27b-11e5-9155-9bff1e32685b.png)
