### ISSUE TITLE
New data: It's unlikely that Brunei had 252 tonnes per person CO2 emissions in 1949

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1530]
Because of this X-axis has long scale and all of countries are at the left part of the chart.

![snap70](https://cloud.githubusercontent.com/assets/16382915/13917552/4c68cbb6-ef6a-11e5-9591-ba68a6956ca1.png)

**Comment by jheeffer** [comment]
[google spreadsheet data source](https://docs.google.com/spreadsheets/u/1/d/1RjqGm7RG82GGVf7E4RXPPwFF7O1So6T0SFx2fVfcUJA/pub)

**Comment by angieskazka** [comment]
see also this article http://ceunbin.weebly.com/

**Comment by mattiaslindgren** [comment]
It fits the original source, but if that is correct i do not know. 
Bruneui is a small country so it is expected that the data fluctuates more

**Comment by jheeffer** [comment]
Can't find this anomaly in the original souce

http://cdiac.ornl.gov/CO2_Emission/timeseries/national
http://cdiac.ornl.gov/trends/emis/tre_coun.html

**Comment by mattiaslindgren** [comment]
The total emission show this peak. The per capita emission is set to zero in the original source before 1950 due to lack of population data (see the notes to the dataset)
