### ISSUE TITLE
New data: "GDP total, yearly growth" and "GDP per capita, yearly growth" doesn't have measurement unit

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1534]
%? B$? M$?

![snap76](https://cloud.githubusercontent.com/assets/16382915/13921912/e1c3aa4c-ef82-11e5-9bad-d1309bea1288.png)

![snap75](https://cloud.githubusercontent.com/assets/16382915/13921915/e5872b5e-ef82-11e5-85ea-77654d38f4e4.png)

**Comment by jheeffer** [comment]
According to metadata it's percent:
https://docs.google.com/spreadsheets/u/1/d/1LklNUuBgFLNcGyG63kqjyze7N8_fDlNLAWZG4YKwJXc/pub#
https://docs.google.com/spreadsheets/u/1/d/1tAnT0EeP67_DoOJCXb3Wd0hqjVMe0KWHPwUH22-BNmQ/pub#
(tab `about`)
So I added it to [graph_settings](https://docs.google.com/spreadsheets/d/192pjt2vtwAQzi154LJ3Eb5RF8W9Fx3ZAiUZy-zXgyJo/edit#gid=3) table

**Comment by jheeffer** [comment]
```
GDP total yearly growth  percent of total GDP
GDP/capita yearly growth percent of GDP
```

**Comment by angieskazka** [comment]
I confirm, it's so clear we don't need Mattias to help us on this.
i further shortened the units:
```
GDP total yearly growth	% of total GDP
GDP/capita yearly growth	% of GDP/capita
```
