### ISSUE TITLE
New data: It's unlikely that Indonesia had year-by-year deaths growth caused by Tsunami

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1535]
![snap77](https://cloud.githubusercontent.com/assets/16382915/13922452/0d69c846-ef85-11e5-9286-5d20fe7038b7.png)

**Comment by jheeffer** [comment]
Is this a interpolation error @angieskazka ?

**Comment by angieskazka** [comment]
excellent example! no, we don't have that option yet

**Comment by mattiaslindgren** [comment]
documentation is unclear, but i suppose this an old version of world population prospects, which used to provide only smoothed data (i.e. yearly fluctuations are smoothed out). Anyways, the effect on the total population is after all probably quite minor from such a disisaster (e.g. lex drops 1 year during 2004, and the age distribution of deaths were probably relatively spread). In summary, the data is probably in line with the original source (but the indicator, as many others, is in need of an update)

**Comment by angieskazka** [comment]
it will now be like this

![image](https://cloud.githubusercontent.com/assets/3648190/13966726/180a20f8-f074-11e5-9e2f-7558b5d95677.png)
