### ISSUE TITLE
New data: China coal consumption amount in 2011?

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1536]
According to https://www.eia.gov/todayinenergy/detail.cfm?id=9751 China's coal consumption is 3.8B tons.

![snap79](https://cloud.githubusercontent.com/assets/16382915/13922707/265d5aa6-ef86-11e5-91c5-484f7f859c98.png)

Compare to gapminder data.

![snap78](https://cloud.githubusercontent.com/assets/16382915/13922722/3693768a-ef86-11e5-9d4f-f7ee618a9ad2.png)

**Comment by jheeffer** [comment]
http://www.bp.com/content/dam/bp/en/corporate/pdf/bp-statistical-review-of-world-energy-2015-full-report.pdf

Data should come from the 2012 equivalent of this report (this is 2015 version).

this report shows China in 2011: 1896.0 million tonnes oil equivalent coal consumption.

**Comment by mattiaslindgren** [comment]
The explanation is, I presume that, that the unit is different:
In the BP data, and in our data (that use BP) the unit is: (million) tonnes **oil equivalent**
whereas in the figure from eia.org the unit is simply: billion tonnes

**Comment by jheeffer** [comment]
Makes sense to me : )
