### ISSUE TITLE
Missing 0 on a log scale when many countries actually reach values very close to 0

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1538]
"Dollar billionaires per million people" - incorrect X-axis values
X-axis should start from 0 at least.

![snap80](https://cloud.githubusercontent.com/assets/16382915/13944921/04816c4c-f012-11e5-8428-011aea23a7b2.png)

**Comment by mattiaslindgren** [comment]
The original data contains many zero values:
http://spreadsheets.google.com/pub?key=tAQpQeQkuyA1-ZovdDJ7JAw&output=xls

**Comment by TValeriy** [comment]
The same for "Sulfur emission, kilotons" and "Sulfur emissions per person, kg".

![snap91](https://cloud.githubusercontent.com/assets/16382915/13984427/d6b8e4a0-f0fe-11e5-9214-0141ba75c14e.png)
