### ISSUE TITLE
Error when selecting bubble with no data in find dialog

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#154]
I can add protection when the bubble is selected, so that bubble chart will reset it if it has no data.
However the problem is deeper than it seems to be. Bubbles with no data should not be possible to select in the first place. They should be greyed out or removed from finder dialog list

**Comment by angieskazka** [comment]
this was a double post, sorry

**Comment by arthurcamara1** [comment]
What if they exist only in a few years? They should still be selectable. If China only exists between 1900-2000 and the dataset covers 1800-2015, one should be able to select China and see the trails between 1900-2000, right?
