### ISSUE TITLE
There is an icon appear on the size pop up screen 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1542]
**SEVERITY:**  Major

**MODULE:**  Bubble chart

**Platform:**
* Windows 7 / Chrome 49.0
* Windows 7 / Firefox 45.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL : http://tools-dev.gapminderdev.org/tools/bubbles
2) Bubble Chart will be loaded.
3) Click on size icon
4) Click on population dropdown 
5) Observe the popup 

**ACTUAL RESULTS:**
There is an unwanted icon on the size popup screen 

**EXPECTED RESULTS:**
There should not any icon on that pop up  

**SCREENSHOT:**

![icon](https://cloud.githubusercontent.com/assets/9950837/13949886/7dc7ff3a-f049-11e5-9634-656ea11e4998.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1549
