### ISSUE TITLE
Incorrect data or measurement unit for "Number of people in poverty"-axis

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1546]
If it is amount of people in poverty then how it could be not integer?

![snap87](https://cloud.githubusercontent.com/assets/16382915/13951538/44dbe006-f03a-11e5-80e9-bb8de2d9f9f4.png)

According to "Poverty, % people below $2 a day" there are 0.2% of people for Ukraine.

![snap88](https://cloud.githubusercontent.com/assets/16382915/13951582/a2cd8962-f03a-11e5-84db-fcadf7dd03ee.png)

So there 45M x 0.2% = 90k people in poverty.
What "0.03" value is about?

**Comment by angieskazka** [comment]
thanks, i fixed the unit to say "millions", as per data description
