### ISSUE TITLE
Trail breaks if bubble is only available for 1 year in all data

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#1548]
Add exception so no trail segments would be displayed in that case

set Y axis to Tsunami deaths
Find India at year 2004

drag time slider forward. One bubble is stuck without label (sometimes with) and looks weird: 

![image](https://cloud.githubusercontent.com/assets/3648190/13994192/f358a454-f123-11e5-9231-566722b1ed53.png)

Drag timeslider backwards: sometimes label is stuck alone

![image](https://cloud.githubusercontent.com/assets/3648190/13994244/35eea462-f124-11e5-8b78-eca0c8ba9356.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1594
