### ISSUE TITLE
There is no data for "Life expectancy, Years" measurement

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1550]
Note that there are two almost the same measurements.
1. "Life expectancy" at the root.
2. "Life expectancy" under "Health" branch - there is no data for this measurement.

http://tools-dev.gapminderdev.org/tools/bubbles#_state_marker_axis%2F_x_which=life%2F_expectancy&domainMin:10&domainMax:83&zoomedMin:10&zoomedMax:83&scaleType=linear

![snap89](https://cloud.githubusercontent.com/assets/16382915/13982856/f3fbb614-f0f4-11e5-88e2-c4f87a9cdf63.png)

**Comment by TValeriy** [comment]
The same for pairs of: 
**"Health"->"Child mortality rate"** and **"root"->"Child mortality rate"**
**"Health"->"Babies per woman"** and **"root"->"Babies per woman"** .

**Comment by angieskazka** [comment]
fixed by removing wrong entries from metadata.json
