### ISSUE TITLE
Indicator description visibility toggle can be reversed

### ISSUE THREAD

**Issue by jheeffer** [Gapminder/vizabi#1554]
1) Go to http://tools-stage.gapminderdev.org/tools/bubbles#_
2) Hover with your mouse over ? next to indicator
3) refresh page without moving your mouse (f5)
4) wait for page to load completely
5) move mouse off and on ? and notice how description visibility toggle is reversed.

expected behaviour: mouse off is not visible, mouse on is visible

**Comment by angieskazka** [comment]
ahhahahah! nice bug. i wonder what made you find it

**Comment by jheeffer** [comment]
Murphy's law ; )
![image](https://cloud.githubusercontent.com/assets/1596071/14017078/f0dd28c0-f1c4-11e5-8c48-f4975b277457.png)

**Comment by angieskazka** [comment]
Little improvements needed for data-notes: 
Unpin when clicking again on question mark (looks like can be solved by datanotes.js: 146 pin = ​˜true˜​ !pin)
When datanotes is pinned at one place and you want to hover/pin it at another question mark it should close and reopen (nothing happens now) (edited)
