### ISSUE TITLE
When user clicks on color drop down from color menu the color options appeared behind the color option panel 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1555]
**SEVERITY:**  Major

**MODULE:**  Bubble chart

**Platform:**
* Windows 7 / Firefox 45.0
* Nexus 9 (5.1) / Chrome 48.0
* iPad Air 2 iOS(9.2.1) / Safari

**Realease:** V0.13.4

**STEPS TO REPRODUCE:**
1) Navigate to the URL : http://tools-stage.gapminderdev.org/
2) Bubble Chart will be loaded.
3) Click on color icon 
4) Click on drop down 

**ACTUAL RESULTS:**
The color options appeared behind the color panel 

**EXPECTED RESULTS:**
The color options should appear in front of the color panel

**NOTE:** The functionality is working fine in chrome 

**SCREENSHOT:**

![drop down 24](https://cloud.githubusercontent.com/assets/9950837/14011343/a2188072-f1bf-11e5-8be6-6f4caf6008df.png)

**Comment by angieskazka** [comment]
it's part of fixing the data on waffle server (although vizabi could have been more crash-resistant when the data is incorrect)
