### ISSUE TITLE
The text inside the box is not properly visible when user hover mouse on “?” question mark symbol 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1559]
**SEVERITY:**  Major

**MODULE:**  Bubble chart

**Platform:**
* Windows 7 / Firefox 45.0
* Windows 7 / Chrome 49.0 

**RELEASE:** V0.13.4

**STEPS TO REPRODUCE:**
1) Navigate to the URL : http://tools-stage.gapminderdev.org/
2) Bubble Chart will be loaded.
3) Hover mouse on “?” sign adjacent to population and region  

**ACTUAL RESULTS:**
The text inside the box is not properly visible while visible when user clicks the icon instead of hover 

**EXPECTED RESULTS:**
The text should be clear and visible 

**SCREENSHOT:**

![no text](https://cloud.githubusercontent.com/assets/9950837/14017275/3948c646-f1e8-11e5-8a5f-d75bb897759a.png)

**Comment by angieskazka** [comment]
fixed by 0bc5b1e5aedc9d2e1a1f08ace517bea21d3642a3, together with #1558
