### ISSUE TITLE
Reduce one level in entities model in order to simplify state

### ISSUE THREAD

**Issue by arthurcamara1** [Gapminder/vizabi#156]
Currently we typically have `state.entities` like this:

```javascript
entities: {
      show: {
            dim: 'geo',
            filter: {
                  'geo': ['swe', 'fin', 'nor']
            }
      },
      select: [{...}, {...} ... ],
      brush: [{...}, {...} ... ],
}
```

The following seems more intuitive and simpler

```javascript
entities: {
      dim: 'geo',
      show: {
            'geo': ['swe', 'fin', 'nor']
      },
      select: [{...}, {...} ... ],
      brush: [{...}, {...} ... ],
}
```

**Comment by angieskazka** [comment]
Even shorter: show = [" ", " ", " " ... " "]

**Comment by arthurcamara1** [comment]
We need to have support for other filters like `geo.cat` and so on, that's why it can't be an array

**Comment by olarosling** [comment]
Arthur is right. Show, Select and Brush can not refer to different dimensions. Select & Brush, must be subset of  Show.

**Comment by arthurcamara1** [comment]
It's done already
