### ISSUE TITLE
On zoom panel the icon still selected even the user selected outside the icon 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1570]
**SEVERITY:** Minor

**MODULE:** Bubble Chart

**Platform:**
* Windows 7 / Firefox 45.0
* Windows 7 / Chrome 49.0

**RELEASE:** v0.13.4-4

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools/bubbles
2) Bubble Chart will be loaded.
3) Hover the mouse below the zoom in icon
4) Click and observe the icon gets selected 

**ACTUAL RESULTS:**
The icon gets selected when user clicks under the zoom in or zoom out button 

**EXPECTED RESULTS:**
The icon should only be selected if the mouse is over the icon and user clicked

**SCREENSHOT:**

![pointer](https://cloud.githubusercontent.com/assets/9950837/14073704/c847f250-f4e4-11e5-8bbd-2bd3972373ef.png)

**Comment by angieskazka** [comment]
it's a feature!
the click areas are a little bigger, so we don't require user to perform a precise action 
it helps especially on touch devices if a touch is recognised a bit away from the target

![image](https://cloud.githubusercontent.com/assets/3648190/14172671/74317b62-f739-11e5-8a7c-ecd6984fefe5.png)
