### ISSUE TITLE
IE11: There are no sliders (but functionality itself is working) for "speed" and "opacity"

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1571]
**Platform:** Win 7, Win 10.

**Browser:** IE 11.

![snap95](https://cloud.githubusercontent.com/assets/16382915/14077464/84d68bb6-f4f4-11e5-93a8-d454c7190c7e.png)

![snap96](https://cloud.githubusercontent.com/assets/16382915/14077466/885241c2-f4f4-11e5-9007-2bb1c6e03531.png)

![snap97](https://cloud.githubusercontent.com/assets/16382915/14077478/8b144de2-f4f4-11e5-8239-2962bba2b2f8.png)

**Comment by TValeriy** [comment]
Fixed. Retested.

**Comment by angieskazka** [comment]
retest needed on IE11/Edge

**Comment by TValeriy** [comment]
Retested. Fixed.
