### ISSUE TITLE
The bubble disappeared from the chart as the user change the indicator from the size option

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1573]
**SEVERITY:** Major

**MODULE:** Bubble Chart

**Platform:** Windows 7 / Firefox 44.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://gapminder.org/tools/bubbles
2) Bubble Chart will be loaded.
3) Select China and USA bubble 
4) Click play and make trails of bubbles
5) Click size dropdown 
6) Select infrastructure --> Traffic--> Cars, trucks, buses

**ACTUAL RESULTS:**
The bubble got disappeared from the chart as the user change the indicator from size options 

**EXPECTED RESULTS:**
The bubble should not get disappeared from the chart 

SCREENSHOT:

![bubb disapear](https://cloud.githubusercontent.com/assets/9950837/14078137/a41b4d28-f50c-11e5-96a6-a9c5c34534ab.png)

**Comment by sergey-filipenko** [comment]
Should be fixed now, please retest
