### ISSUE TITLE
The bubbles overlaps the y-axis when user change the y axis indicator 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1574]
**SEVERITY:**  Major

**MODULE:** Bubble Chart

**Platform:** Windows 7 / Firefox 44.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://gapminder.org/tools/bubbles
2) Bubble Chart will be loaded.
3) Click options 
4) Click X and Y 
5) Select infrastructure --> Traffic--> Cars, trucks, buses for x axis indicator 
6) Select infrastructure --> Traffic--> Cars, trucks, buses for Y axis indicator 

**ACTUAL RESULTS:**
The bubbles overlaps the y axis line when user change the indicator

**EXPECTED RESULTS:**
The bubble should not overlaps the y axis line when user change the indicator

**NOTE:** When user click the follow bubbles the bubbles place ajusted and no overlaping remain 

**SCREENSHOT:**

![chrt](https://cloud.githubusercontent.com/assets/9950837/14078333/5ffcbb2a-f50e-11e5-9688-e2f6adf7d16c.png)

**Comment by angieskazka** [comment]
same problem as #1640
