### ISSUE TITLE
New data: What's the measurement for "Math achievement, 4th(8th) grade"?

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1576]
![snap99](https://cloud.githubusercontent.com/assets/16382915/14099483/853cd048-f58e-11e5-9dc2-b118eaf2bb18.png)

**Comment by TValeriy** [comment]
Sorry, my mistake.

![snap100](https://cloud.githubusercontent.com/assets/16382915/14105290/5a8751fa-f5b3-11e5-8132-80ef2a629732.png)

**Comment by angieskazka** [comment]
Your confusion is totally understandable. Please keep reporting such cases

i added a unit "TIMSS test score" for math achievements in the original data. (Will take a while to show up in the UI though)

![image](https://cloud.githubusercontent.com/assets/3648190/14184176/3adfe99e-f774-11e5-8f9a-a2343451d442.png)
