### ISSUE TITLE
When user hover the color on color picker the random color get selected for trail head

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1580]
**SEVERITY:**  Major

**MODULE:**  Bubble chart

**Platform:**
* Windows 7 / Internet Explorer 11
* Windows 7 / Chrome 49.0
* Windows 7 / Firefox 44.0

**RELEASE:** v0.13.5

**STEPS TO REPRODUCE:**
1) Navigate to the URL : http://tools-stage.gapminderdev.org/tools/bubbles
2) Bubble Map Chart will be loaded
3) Click the options icon
4) Click on color
5) Click on color dropdown
6) Select any indicator
7) Click on color , the color wheel appear
8) Hover the wheel
9) Observe the random color got selected

**ACTUAL RESULTS:**
The random color got selected when user hover the color wheel 

**EXPECTED RESULTS:**
The color should only be selected from color wheel when user click the specific color and select it 

**SCREENSHOT:**

![29-3-3](https://cloud.githubusercontent.com/assets/9950837/14100390/79d98896-f5a6-11e5-8a1e-af5e522b5214.png)

![cxixvseqcs](https://cloud.githubusercontent.com/assets/3648190/15164135/20e93b86-170d-11e6-8664-7d655f10e974.gif)

**Comment by sergey-filipenko** [comment]
Can not reproduce now, please retest

**Comment by angieskazka** [comment]
i got it now. 
> The color should only be selected from color wheel when user click the specific color 

no, the expected behavior is to update color on hover. this allows trying out different colors without the need to close and reopen the dialog

**Comment by angieskazka** [comment]
i can not reproduce. looks like it was fixed together with some other issue

**Comment by angieskazka** [comment]
@k6Labz so what was really happening: when moving the cursor away from the color you pass the white field on color picker, which would set "old color". sometimes you move cursor too fast, event is not triggered, and the color from the color wheel is stuck

now it should reset to old color in any case, as you hover away from the color wheel
