### ISSUE TITLE
There are empty popups with data descriptions

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1582]
**Platform:** MacBook Air \ OS X 10.10.5
**Browser:** Safari 9.0.3

![screen shot 2016-03-29 at 2 22 56 pm](https://cloud.githubusercontent.com/assets/16382915/14106634/4a326616-f5bb-11e5-8b94-fc9c956da009.png)

**Comment by angieskazka** [comment]
the translated string arrives as expected but the scrollable element "vzb-data-notes-body" has zero height

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1606

**Comment by angieskazka** [comment]
Merged but requested @dab2000 to do some follow up improvements:
> Fix is good exept line92 and it's for Safari only. For IE11 it requires further improvments

**Comment by TValeriy** [comment]
Retested. Fixed.
