### ISSUE TITLE
When user open the chart in new tab the seek bar hides behind the find and color panel

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1585]
**SEVERITY:**  Major

**MODULE:**  Bubble chart

**Platform:**
* MAC (10.11.1) / Safari 9.0 
* MAC (10.11.1) / Chrome 49.0 
* Windows 7 / Internet Explorer 11
* Windows 7 / Chrome 49.0
* Windows 7 / Firefox 44.0

**RELEASE:** v0.13.5

**STEPS TO REPRODUCE:**
1) Navigate to the URL : http://tools-stage.gapminderdev.org/tools/bubbles
2) Bubble Chart will be loaded
3) Scroll down the page and right click and open the other chart in new tab 
4) Don't switch the tabs until the chart gets loaded 
5) Observe the seek bar hides behind the panel

**ACTUAL RESULTS:**
When user loads the chart in new tab the seek bar hides behind the panel 

**EXPECTED RESULTS:**
The seek bar should not hide 

**SCREENSHOT:**

![29-3-5](https://cloud.githubusercontent.com/assets/9950837/14108246/e0f62820-f5d5-11e5-8c11-4db7531a5059.png)

**Comment by sergey-filipenko** [comment]
Can not reproduce on Windows7 Chrome 49.0/Firefox 45.0

**Comment by k6Labz** [comment]
@sergey-filipenko 
It is reproducible on my side
Please follow these steps:
1) Navigate to the URL : http://tools-stage.gapminderdev.org/tools/bubbles
2) Bubble Chart will be loaded
3) Scroll down the page and right click and open the mountain chart in new tab 
4) Don't switch the tabs until the chart gets loaded 
**Note:** When you open the mountain chart in new tab, wait for 5 seconds and remain on the same tab from which you open the chart in new tab, After that go to that tab and observe the seek bar 
5) Observe the seek bar hides behind the panel
