### ISSUE TITLE
URL persistency: some parameters are being added to URL while refreshing the page

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1586]
**Platform:** any.
**Browser:** any.

**Steps to reproduce:**
1. Go to Bubble chart.
2. Select for X-axis "Life expectancy" indicator so there are the same indicators for both axis.
3. Refresh the page.

**Actual result:**
Link http://tools-dev.gapminderdev.org/tools/bubbles#_state_marker_axis%2F_x_which=life%2F_expectancy%2F_years becomes as http://tools-dev.gapminderdev.org/tools/bubbles#_state_marker_axis%2F_x_which=life%2F_expectancy%2F_years&domainMin:1&domainMax:84.1&zoomedMin:1&zoomedMax:84.1 .

![snap102](https://cloud.githubusercontent.com/assets/16382915/14108448/24ce6e0a-f5c6-11e5-9f46-7c16a187ecf6.png)

**Expected result:**
![snap103](https://cloud.githubusercontent.com/assets/16382915/14108460/34467e7c-f5c6-11e5-967c-38ed42550bf4.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1600

**Comment by angieskazka** [comment]
The fix made it more consistent: now you get extra parameters in URL in both cases and it's consistent. But useless. Getting rid of useless parametees will be the next story...

**Comment by TValeriy** [comment]
Retested. Fixed.
