### ISSUE TITLE
Incorrect color scale for "Child mortality rate" before refreshing the page

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1587]
**Platform:** any.
**Browser:** any.

**Steps to reproduce:**
1. Go to http://tools-dev.gapminderdev.org/tools/bubbles .
2. Select for Color "Child mortality rate" indicator.

**Actual result:**
The middle value is 37.9 instead of 379.

![snap105](https://cloud.githubusercontent.com/assets/16382915/14108619/ecb7b110-f5c6-11e5-8815-e1f0df7a7ffd.png)

.3. Refresh the page.

**Actual & Expected result:**

![snap106](https://cloud.githubusercontent.com/assets/16382915/14108666/1dff99e0-f5c7-11e5-8a71-958fab3a4eab.png)

**Comment by angieskazka** [comment]
both scales are correct: one is logarithmic, another one is linear
37.9 = 379/10 is a coincidence
on reload it should keep the scale though, so the issue is correct

later we will have a better legend for log scale, like: 1 10 100 1000 instead of evenly distributed random numbers

**Comment by sergey-filipenko** [comment]
related to #1586

**Comment by TValeriy** [comment]
Retested. Fixed.
