### ISSUE TITLE
The user did not redirect to new page when  click on “?” adjacent to axis description  

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1588]
**SEVERITY:**  Major

**MODULE:**  
*Bubble chart
*Bubble Map

**PLATFORM:** 
* Windows 7 / Internet Explorer 11
* Windows 7 / Chrome 49.0
* Windows 7 / Firefox 44.0
*MAC (10.11.1) / Safari 9.0 
*MAC (10.11.1) / Chrome 49.0

**RELEASE:** v0.13.5

**STEPS TO REPRODUCE:**
1) Navigate to the URL : http://tools-stage.gapminderdev.org/tools/bubbles
2) Bubble Chart will be loaded.
3) Click on “?” adjacent to X/Y axis 

**ACTUAL RESULTS:**
The user does not redirect to the new page 

**EXPECTED RESULTS:**
The user should redirect to the new page when clicks on “?” icon

**SCREENSHOT:**

![ques 30 3](https://cloud.githubusercontent.com/assets/9950837/14142621/568321cc-f6a0-11e5-881f-46996d89425c.png)

**Comment by angieskazka** [comment]
@k6Labz the expected behavior is now like this: 
![zvt924b4wk](https://cloud.githubusercontent.com/assets/3648190/14149146/0f817f64-f6a3-11e5-8843-508833e8db94.gif)

is it different for you? what can you see?

**Comment by k6Labz** [comment]
@angieskazka 
The popup did not appear in mountain chart as when we click on "?" with axis description and redirects to new page but in bubble chart the pop up appears. In my opinion all charts should have same behaviour
