### ISSUE TITLE
IE11: After expand the page when user restore the page, the page did not return to its original form 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1591]
**SEVERITY:**  Major

**MODULE:**  
* Bubble Chart
* Mountain Chart 
* Bubble Map

**PLATFORM:** Windows 7 / Internet Explorer 11 

**RELEASE**: V0.13.5

**STEPS TO REPRODUCE:**
1) Navigate to the URL : 
http://tools-stage.gapminderdev.org/tools/bubbles 
OR
http://static.gapminderdev.org/vizabi/v0.13.5/preview/
2) Bubble Chart will be loaded
3) Click on expand button 
4) Click on restore button
5) Observe the page from bottom   

**ACTUAL RESULTS:**
The page did not return to original after the user clicks the restore button

**EXPECTED RESULTS:**
After clicking restore button the page should return to its original form

**SCREENSHOT:**

![30-2](https://cloud.githubusercontent.com/assets/9950837/14168890/3156e430-f73e-11e5-89b7-99c1a4b96f8a.png)

**Comment by angieskazka** [comment]
@dab2000 testers complain that the issue still persists. did it get fixed for you?

**Comment by dab2000** [comment]
Can't reproduce this issue on
http://tools-stage.gapminderdev.org/tools/bubbles 
and
http://static.gapminderdev.org/vizabi/develop/preview/bubblemap.html
Win7 IE 11.0.9600.18230 and
Win10 IE 11.162.10586.0

Can reproduce only on
http://static.gapminderdev.org/vizabi/v0.13.5/preview/

So it fixed for me

**Comment by angieskazka** [comment]
@k6Labz can you?
