### ISSUE TITLE
"Stack"->"Region" functionality isn't working

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1593]
**Platform where was tested:** MacBook Air, OS X 10.11.3.
**Browsers where was tested:** Chrome 49, Safari 9.0.3.
**Tools page release:** v.0.13.5.

**Steps to reproduce:**
1. Go to Mountain chart.
2. Try to switch between "Stack"->"World" and "Stack"->"Region".

**Actual result:**
Nothing happens on switching.

**Expected result:**
Borders between countries inside region should disappear.

**Comment by sergey-filipenko** [comment]
related to #1605

**Comment by TValeriy** [comment]
Retested. Fixed.
