### ISSUE TITLE
The play button gets disabled when user change the indicators of X and Y axis  during the making of trails 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1597]
**SEVERITY:**  Critical  

**MODULE:** Bubble Chart

**PLATFORM:**
* Windows 7 / Firefox 44.0
* Windows 7 / Chrome 49.0
* Windows 7 / Internet Explorer 11

**STEPS TO REPRODUCE:**
1) Navigate to the URL : http://tools-stage.gapminderdev.org/tools/bubbles 
OR
http://static.gapminderdev.org/vizabi/v0.13.5/preview
2) Bubble Chart will be loaded.
3) Select china and click play 
4) Observe the trails generated and slider is still playing 
5) Click on options 
6) Click on X and Y axis change the x axis indicator 
7) Select child mortality indicator for x axis 
8) Select any other indicator for x axis again 

**ACTUAL RESULTS:**
After trails being generated and play slider is still playing when user change the X and Y axis indicator the play button got disabled 

**EXPECTED RESULTS:**
The play button should not get disabled 

**SCREENSHOT:**

![1-april](https://cloud.githubusercontent.com/assets/9950837/14200780/bd85ef3c-f806-11e5-8a9d-1bffbae1f81e.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1607
