### ISSUE TITLE
The content of page is not properly aligned when user loads the “old bubble chart”

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1598]
**SEVERITY:**  Major

**MODULE:**  
* Bubble Chart
* Mountain Chart 
* Bubble Map

**PLATFORM:** Samsung S6 / Chrome 

**STEPS TO REPRODUCE:**
1) Navigate to the URL : http://tools-stage.gapminderdev.org/tools/bubbles 
2) Bubble Chart will be loaded.
3) Click on “old bubble chart” link below the bubble chart
4) Observe the chart is truncated from the top  

**ACTUAL RESULTS:**
The content of chart is not properly aligned when user loads the page on mobile device 

**EXPECTED RESULTS:**
The old chart page content should be properly aligned and responsive according to screen 

**SCREENSHOT:**

![screenshot_2016-04-01-16-57-38](https://cloud.githubusercontent.com/assets/9950837/14206888/c781af70-f82f-11e5-804c-636c26ba3234.png)

**Comment by angieskazka** [comment]
Ha-ha, this will never work on mobile. @jheeffer @natali-abyss how should we do? can we hide the link to the "old bubble chart" when on mobile?

**Comment by jheeffer** [comment]
mobile will have automatic redirect to tools

**Comment by jheeffer** [comment]
Hmm, but that could be confusing if they click 'old bubble chart' and just go to tools page again.

**Comment by angieskazka** [comment]
@jheeffer i suggest mobiles would have no way back from the tools page

**Comment by angieskazka** [comment]
@vvpanchenko so i tested it and it didn't work on any of my no-flash browsers or devices (Safari, FF, Android chrome) 

=)
