### ISSUE TITLE
The chart name is not present when user load the site on tabs and mobiles

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1599]
**SEVERITY:**  Minor 

**MODULE:**  
* Bubble Chart
* Mountain Chart 
* Bubble Map

**PLATFORM:** Samsung S6 / Chrome 

**STEPS TO REPRODUCE:**
1) Navigate to the URL : http://tools-stage.gapminderdev.org/tools/bubbles 
2) Bubble Chart will be loaded.
3) Scroll down and observe no chart name is present  
4) Observe the chart is truncated from the top  

**ACTUAL RESULTS:**
There is no chart name present on the chart  

**EXPECTED RESULTS:**
The chart name should be present 

**SCREENSHOT:**

![screenshot_2016-04-01-16-58-17](https://cloud.githubusercontent.com/assets/9950837/14207246/5c9ecece-f832-11e5-9119-f7c97155a84c.png)

**Comment by angieskazka** [comment]
This was coded according to the design
@olarosling, do we miss the chart names? 

![image](https://cloud.githubusercontent.com/assets/3648190/14443273/80a9966e-003e-11e6-8f25-6023840d8748.png)

**Comment by angieskazka** [comment]
@k6Labz 
ok, i take a decision. we skip the titles on mobile until the first user complaint, or if @olarosling or @AnnaGapminder will say otherwise
