### ISSUE TITLE
The world button gets disabled when user selects the region radio buttons from the stack 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1605]
**SEVERITY:**  Major

**MODULE:**  Mountain Chart 

**PLATFORM:** 
* Windows 7 / Chrome 49.0
* Windows 7 / Firefox 44.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL : http://www.gapminder.org/tools/mountain
2) Mountain Chart will be loaded
3) Click on options
4) Click on stack
5) Click on region radio button placed above the merge mountains
6) Click on region radio button placed below the merge mountains
7) Now click on world radio button again placed above the merge mountains

**ACTUAL RESULTS:**
When user selects both region radio buttons the world radio button gets disabled 

**EXPECTED RESULTS:**
The world radio button should not get disabled 

**SCREENSHOT:**

![5apr](https://cloud.githubusercontent.com/assets/9950837/14271328/5e7f4462-fb11-11e5-8d13-5d4e6fc3b3cc.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1611
Will have effect when merge #1607
