### ISSUE TITLE
After selecting region from stack when user select countries from show the list of countries from find did not disappear 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1619]
**SEVERITY:**  Major

**MODULE:**  Mountain Chart 

**PLATFORM:** 
* Windows 7 / Chrome 49.0
* Windows 7 / Firefox 44.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://www.gapminder.org/tools/mountain 
2) Mountain Chart will be loaded.
3) Click on stack 
4) Click on region radio button placed above the merge mountain 
5) Click on world radio button placed below the merge mountain 
6) Click show icon and select countries 
7) Observe the list of countries in find 

**ACTUAL RESULTS:**
After selecting region from stack when user select countries from show, all countries are still displayed in find unless user clicks on play 

**EXPECTED RESULTS:**
Only those countries which are selected in show should be displayed in find 

**SCREENSHOT:**

![expected](https://cloud.githubusercontent.com/assets/9950837/14316354/fbb33e36-fc1b-11e5-87e5-11f8fad0de0c.png)

![chnge](https://cloud.githubusercontent.com/assets/9950837/14316363/04a6fb22-fc1c-11e5-95ba-76a87eb16e21.png)

**Comment by sergey-filipenko** [comment]
Can not reproduce, retest please

**Comment by angieskazka** [comment]
@k6Labz you could not possibly do this 
> 4) Click on region radio button placed above the merge mountain 
> 5) Click on world radio button placed below the merge mountain 

because if you stack mountains by region, merging by world will be disabled

![image](https://cloud.githubusercontent.com/assets/3648190/15098027/817edf3e-1530-11e6-878d-4188f0ddd5cc.png)
