### ISSUE TITLE
When user resize the browser window the background year shifted behind the axis line

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1620]
**SEVERITY:**  Major

**MODULE:**  Mountain Chart 

**PLATFORM:** 
* Windows 7 / Chrome 49.0
* Windows 7 / Firefox 44.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://www.gapminder.org/tools/mountain 
2) Mountain Chart will be loaded.
3) Resize the browser window 
4) Observe the background year 

**ACTUAL RESULTS:**
The background year shifted behind the axis line when user resize the window 

**EXPECTED RESULTS:**
The background year should not be shifted behind the axis line but adapts nicely according to browser screen size 

**SCREENSHOT:**

![resize](https://cloud.githubusercontent.com/assets/9950837/14317096/0092c198-fc20-11e5-9b30-d50bf8dc2143.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1630

**Comment by sergey-filipenko** [comment]
upd
