### ISSUE TITLE
IE 11: Unnecessary data is overlapping on the ‘?’ in X and Y options

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1625]
**SEVERITY:**  Minor

**MODULE:**   Bubble chart

**Platform:** Windows 7 / IE 11 

**RELEASE:** v0.13.6

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools/
2)	Bubble Map Chart will be loaded.
3)	Click Options
4)	Click X and Y
5)	Observe the ‘?’ with x axis and y axis description on the chart

**ACTUAL RESULTS:**
Unnecessary data is overlapping on the ‘?’ in X and Y options

**EXPECTED RESULTS:**
Overlapping should be avoided 

**SCREENSHOT:**

![v0 13 6_01](https://cloud.githubusercontent.com/assets/9950837/14344026/60d4e826-fcbe-11e5-8b2a-77e806e4537d.png)

**Comment by dab2000** [comment]
Can't reproduce this issue on
W7 IE 11.0.9600.18230 and
W10 IE 11.162.10586.0
