### ISSUE TITLE
"Color" -> "CO2 emissions": incorrect colors for logarithmic scale

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1626]
**Steps to reproduce:**
1. Go to Bubble chart.
2. Select "Color" -> "CO2 emissions".
3. Switch to logarithmic scale.
4. Select 1988 year for example.

**Actual result:**
There are some blue bubbles. Blue isn't in color range.

![screen shot 2016-04-07 at 11 56 16](https://cloud.githubusercontent.com/assets/16382915/14345855/024841d2-fcb8-11e5-86e4-f0d205ad7d73.png)

**Expected result:**
Colors should be from color range.

**Comment by sergey-filipenko** [comment]
@k6Labz what is not correct? Do you have some picture?

**Comment by k6Labz** [comment]
@sergey-filipenko Follow the steps as issue still persist. Drag the slider to year 1988 and you will face same problem as mentioned above 

![2 may persist](https://cloud.githubusercontent.com/assets/9950837/14947495/e02b55c2-104d-11e6-85dc-8b19f270a507.png)

**Comment by TValeriy** [comment]
Retested. Fixed.
