### ISSUE TITLE
Spinner not visible on Firefox

### ISSUE THREAD

**Issue by arthurcamara1** [Gapminder/vizabi#163]
On Firefox, the spinner doesn't show when loading

![screen shot 2015-06-22 at 2 15 29 pm](https://cloud.githubusercontent.com/assets/3584238/8281560/6b2bde2e-18e9-11e5-8dae-25e8ef629668.png)

**Comment by IncoCode** [comment]
22fce6f5d39c92a541c51095c715795f16151b63 broke url parsing features. The problem is that firefox can't parse the url, that's why spinner doesn't show.

**Comment by IncoCode** [comment]
Fixed in #335.

**Comment by angieskazka** [comment]
i tested on Firefox windows and mac. the spinner is visible
