### ISSUE TITLE
The labels overlaps the X-axis line when user increase the size from label options

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1639]
**SEVERITY:**  Major

**MODULE:** Bubble Chart 

**PLATFORM:** 
* Windows 7 / Chrome 49.0
* Windows 7 / Firefox 44.0
* Windows 7 / Internet Explorer 11.0
* Mac 10 / Safari 9

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http:gapminder.org/tools
2) Click on bubble 
3) Click on options 
3) Click on labels 
4) Drag the slider to the full right position 
5) Drag the label on the x-axis 

**ACTUAL RESULTS:**
The label overlaps the x-axis 

**EXPECTED RESULTS:**
The label should not overlaps the x-axis  

**SCREENSHOT:**

![11 april life expentency label](https://cloud.githubusercontent.com/assets/9950837/14427165/af6d425c-000c-11e6-86db-5085c37996e0.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1642
