### ISSUE TITLE
Unwanted zoom-in on switching the indicator. The bubbles get truncated

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1640]
**SEVERITY:**  Major

**MODULE:** Bubble Chart 

**PLATFORM:** 
* Windows 7 / Chrome 49.0
* Windows 7 / Firefox 44.0
* Windows 7 / Internet Explorer 11.0
* Mac 10 / Safari 9

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http:gapminder.org/tools
2) Click on x-axis 
3) Choose HealthCauses of new born deaths Congenital deaths in new born, total
4) Click on y-axis 
5) Choose HealthCauses of new born deaths Congenital deaths in new born, total  

**ACTUAL RESULTS:**
The bubbles are truncated when user changed both axis  

**EXPECTED RESULTS:**
The bubbles should not truncated but adjusted fully on the chart  

**SCREENSHOT:**

![11 april truncate](https://cloud.githubusercontent.com/assets/9950837/14427207/08848d28-000d-11e6-9389-6ff9ce64be99.png)

**Comment by angieskazka** [comment]
the zoom event can not distinguish if you are trying to zoom in to a rectangle, when bubbles should actually be truncated, or you switched the indicator which changed zoomed min-max, which was interpreted as you need to zoom. This is more of a design problem rather than an unexpected behavior

**Comment by angieskazka** [comment]
maybe @plward11 has some idea on this

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1679
