### ISSUE TITLE
Change the indicator when time value is early: the bubbles get disappeared

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1641]
**SEVERITY:**  Major

**MODULE:** Bubble Map 

**PLATFORM:** 
* Windows 7 / Chrome 49.0
* Windows 7 / Firefox 44.0
* Windows 7 / Internet Explorer 11.0
* Mac 10 / Safari 9

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://www.gapminder.org/tools/map
2) Click on play
3) Click on size drop down 
4) Choose Health-->Causes of new born deaths-->Congenital deaths in new born, total  indicator from size
5) Observe the bubbles from map gets disappeared

**ACTUAL RESULTS:**
The bubbles get disappeared when change the indicator from size when bubbles are playing 

**EXPECTED RESULTS:**
The bubbles should not get disappeared 

**SCREENSHOT:**

![11 apr dis](https://cloud.githubusercontent.com/assets/9950837/14427540/c2722e7e-000e-11e6-8c72-638d9be7d7b7.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1643

**Comment by angieskazka** [comment]
now it doesn't throw an error anymore but bubbles don't show up either

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1647
