### ISSUE TITLE
All the countries disappeared except Barbados when user change the y axis and play the slider

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1645]
**SEVERITY:**  Major

**MODULE:**
* Bubble Chart 
* Bubble Map 

**PLATFORM:** 
* Windows 7 / Chrome 49.0
* Windows 7 / Firefox 44.0
* Windows 7 / Internet Explorer 11.0
* Mac 10 / Safari 9

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http:gapminder.org/tools
2) Click on x-axis 
3) Choose Environment Water Water Withdrawal
4) Click on play
5) Observe the list of countries 

**ACTUAL RESULTS:**
After choosing y axis indicator into Water withdrawal cu meters per person when user play the play button all the countries disappeared except Barbados 

**EXPECTED RESULTS:**
The countries list should remain visible in the find option 

**SCREENSHOT:**

![12 apil 1](https://cloud.githubusercontent.com/assets/9950837/14457904/555b7034-00c7-11e6-98d6-58345471f414.png)

**Comment by angieskazka** [comment]
great timing! this issue is fixed in the coming version 0.13.7 by a smarter select list

![ilyxvvhch7](https://cloud.githubusercontent.com/assets/3648190/14476072/f3db7d24-0105-11e6-878e-5d7e1e06aa24.gif)
