### ISSUE TITLE
The regular opacity of mountain chart does not have full opacity by default 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1646]
**SEVERITY:**  Minor

**MODULE:** Mountain Chart

**PLATFORM:** 
* Windows 7 / Chrome 49.0
* Windows 7 / Firefox 44.0
* Windows 7 / Internet Explorer 11.0
* Mac 10 / Safari 9

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http:gapminder.org/tools/mountain
2) Click on options
3) Click on opacity 
4) Observe the regular opacity slider 

**ACTUAL RESULTS:**
The regular opacity of mountain chart does not have full opacity by default, when user load the mountain chart page 

**EXPECTED RESULTS:**
The regular opacity of mountain chart must be full like bubble map and bubble chart 

**SCREENSHOT:**

![12 opac](https://cloud.githubusercontent.com/assets/9950837/14459839/c8c6aa78-00d3-11e6-9e17-74abef4830e5.png)

![12 april opa mountain](https://cloud.githubusercontent.com/assets/9950837/14459848/d24f3524-00d3-11e6-811c-15019097b9be.png)

**Comment by angieskazka** [comment]
it's intentional. otherwise the mountains are just way too loud

![image](https://cloud.githubusercontent.com/assets/3648190/14476136/4b61f032-0106-11e6-8a5e-b421e9bcd2fc.png)
