### ISSUE TITLE
The y axis value is not properly visible   

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1654]
**SEVERITY:**  Major

**MODULE:** Bubble Chart 

**PLATFORM:** Windows 7 / Firefox 44.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools/bubbles
2) Observe the y axis values 

**ACTUAL RESULTS:**
The y-axis value is not properly visible

**EXPECTED RESULTS:**
The y-axis values should be properly visible 

**SCREENSHOT:**

![14 april y axis](https://cloud.githubusercontent.com/assets/9950837/14523180/b81a29b0-024b-11e6-955c-e8f5218e5fc5.png)

**Comment by angieskazka** [comment]
looks good on my Win7 / FF 44... strange
@k6Labz  what if your browser is not in 100% scale? try to hit [Ctrl] + [0] (zero)

**Comment by k6Labz** [comment]
@angie its also working fine on my browser with out hitting ctrl + 0
