### ISSUE TITLE
The trails gets truncated 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1660]
**SEVERITY:**  Major

**MODULE:** Bubble Chart 

**PLATFORM:**
* Windows 7 / Chrome 49.0
* Windows 7 / Firefox 44.0
* Windows 7 / Internet Explorer 11.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools/bubbles 
2) Click on India bubble 
3) Click play and generate the trails 

**ACTUAL RESULTS:**
The trails gets truncated 

**EXPECTED RESULTS:**
The trails should not be truncated 

**NOTE:** The trails are truncated now because now the minimum y –axis value is started from 30 but earlier it was started from 10 

**SCREENSHOT:**

![15 april trunc](https://cloud.githubusercontent.com/assets/9950837/14554956/54a7984a-0309-11e6-8889-30b043a18416.png)

**Comment by angieskazka** [comment]
i adjusted the Y axis for the better general picture. yes, some of the trails will get truncated, but it's not a severe problem. if users will complain, i will adjust it back

![image](https://cloud.githubusercontent.com/assets/3648190/14556781/20364b2e-02fa-11e6-8c46-a482b1941791.png)
