### ISSUE TITLE
Support time on x/y axis

### ISSUE THREAD

**Issue by jheeffer** [Gapminder/vizabi#1662]
Gapminder World supported it:
http://www.gapminder.org/world/#$majorMode=chart$is;shi=t;ly=2003;lb=f;il=t;fs=11;al=0;stl=t;st=t;nsl=t;se=t$wst;tts=C$ts;sp=6;ti=1800$zpv;v=0$inc_x;mmid=XCOORDS;iid=ti;by=ind$inc_y;mmid=YCOORDS;iid=rX3Jfop_ebuY-chuMpCgmRg;by=ind$inc_s;uniValue=8.21;iid=tL0jLxFBF9TbXIN_39b1qcQ;by=ind$inc_c;uniValue=255;gid=CATID0;by=grp$map_x;scale=lin;dataMin=1723;dataMax=2069$map_y;scale=log;dataMin=240;dataMax=64098$map_s;sma=49;smi=2.65$cd;bd=0$inds=i110_h001800arae;i238_l001800asau;i239_p001800afai;i44_h001800awav;i101_h001800ayat

To make all GW urls compatible with GT, Gapminder Tools needs to support this too.
Also, it's just a nice functionality ; )

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1682

**Comment by angieskazka** [comment]
@sergey-filipenko didn't pass my test: select time on x-axis, set time slider to the middle, refresh the page

**Comment by jheeffer** [comment]
selecting time brings functions in url

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1749
