### ISSUE TITLE
TrailStartTime moves up 1 year from actual data start

### ISSUE THREAD

**Issue by jheeffer** [Gapminder/vizabi#1664]
`age at 1st marriage` has data for 1970 for `tto` (Trinidad & Tobago) and 1973 for `lby`(Libya).
When setting these years as `trailStartTime` in the url Vizabi will turn these in 1971 and 1974 in both url and graph. 

They should stay on 1970 and 1973 and show that data in Vizabi.

data:

https://github.com/open-numbers/ddf--gapminder--gapminder_world/blob/master/output/ddf/ddf--datapoints--age_at_1st_marriage_women--by--geo--time.csv

url with 1970 and 1973 trailStartTime:

http://www.gapminder.org/tools/bubbles#_state_time_value=2005;&entities_select@_geo=tto&trailStartTime=1970;&_geo=lby&trailStartTime=1973&labelOffset@:-0.146&:-0.017;;;;&marker_axis%2F_x_which=children%2F_per%2F_woman%2F_total%2F_fertility&domainMin:0.84&domainMax:9.22&zoomedMin:0.86&zoomedMax:8.7&scaleType=linear;&axis%2F_y_which=age%2F_at%2F_1st%2F_marriage%2F_women&domainMin:12.5&domainMax:33.66&zoomedMin:13&zoomedMax:33.66;&size_extent@:0.02&:0.41;;&color_palette_america=%23ebcc21&sub%2F_saharan%2F_africa=%234e7af0&east%2F_asia%2F_pacific=%23f03838&south%2F_asia=%2335d1d1&middle%2F_east%2F_north%2F_africa=%235be56b&europe%2F_central%2F_asia=%23f49d37;&which=geo.geographic%2F_regions

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1681

**Comment by jheeffer** [comment]
Opened the link in issue description first time: correct behaviour
Opened the link second and every time after: incorrect behaviour (trail starts at 1971 and 1974 instead of 1970 and 1973)

**Comment by angieskazka** [comment]
@jheeffer  did you test it on stage or on prod? updates are not in prod yet
the link in the issue leads to prod

**Comment by jheeffer** [comment]
good one haha, my fault, stage works yes.
