### ISSUE TITLE
IE11: Zoom-in and Zoom-out cursors are not supported

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1666]
**SEVERITY:**  Major

**MODULE:** Bubble Chart

**PLATFORM:** Windows 7 / Internet Explorer 11.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools/bubbles
2) Click on options and click on zoom 
3) Click on zoom in or zoom out icon 
4) Hover mouse on chart 

**ACTUAL RESULTS:**
When user selects the zoom in or zoom out and hover the chart the zoom in or zoom out pointer (magnifier) did not appear instead the simple pointer is visible over the chart

**EXPECTED RESULTS:**
The magnifier icon of zoom in and zoom out should be visible 

**SCREENSHOT:**

http://g.recordit.co/dOGWmSShEs.gif 

http://g.recordit.co/SP4mfE5Co9.gif

**Comment by jheeffer** [comment]
Tested, works, cursor is a bit... win95'ish?

![image](https://cloud.githubusercontent.com/assets/1596071/15108814/5555ee7c-15d8-11e6-9025-072c9ef4d21e.png)
