### ISSUE TITLE
The mountain disappear from chart when user change minimum X-axis value 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1667]
**SEVERITY:**  Major

**MODULE:** Mountain Chart

**PLATFORM:** 
* Windows 7 / Chrome 49.0
* Windows 7 / Firefox 44.0
* Windows 7 / Internet Explorer 11.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://www.gapminder.org/tools/mountain
2) Mountain chart will be loaded
3) Click on options
4) Click on X & Y
5) Click on X axis limit and input min value as “0”

**ACTUAL RESULTS:**
The mountain disappeared when user input min value of X as “0”

**EXPECTED RESULTS:**
The chart should adjust according to X axis limit 

**SCREENSHOT:**

![19 april disapear mountain](https://cloud.githubusercontent.com/assets/9950837/14628452/9df7cc84-0617-11e6-84ea-c2a293a6abd9.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1680

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1698
