### ISSUE TITLE
The user is able to expand and collapse the chart on preview page 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1684]
**SEVERITY:**  Major

**MODULE:**
* Bubble Chart
* Bubble Map 
* Mountain Chart 

**PLATFORM:** 
* Windows 7 / Chrome 49.0
* Windows 7 / Firefox 44.0
* Windows 7 / Internet Explorer 11.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://static.gapminderdev.org/vizabi/develop/preview/
2) Hover the mouse near to play button of chart 
3) Click and hold the mouse left button and move the mouse upward and downward 

**ACTUAL RESULTS:**
The chart expand and collapse when user move the mouse after click and holding the left button 

**EXPECTED RESULTS:**
The chart should not expand or collapse 

**FOR MORE DETAILS:**  http://g.recordit.co/CIavMmNdnr.gif

**Comment by angieskazka** [comment]
It is a feature of the preview page to quickly change the container size. If you click on the bottom right corner you can resize both X and Y.

Please reopen if it gives you trouble!
