### ISSUE TITLE
Values of axis with "Life expectancy, years" indicator should start from 0.

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1686]
![screen shot 2016-04-28 at 13 20 24](https://cloud.githubusercontent.com/assets/16382915/14883028/8afd983c-0d44-11e6-9a8f-98962760944d.png)

**Comment by angieskazka** [comment]
a9451f0e4e5c857bc69bce834d94164e4281fd09

**Comment by angieskazka** [comment]
it still starts from 20 or so, but now you will be able to zoom out or drag the canvas to see the bottom of the trails

**Comment by TValeriy** [comment]
Retested. Fixed in the way described by Angie, but I can't agree that this is user friendly.
