### ISSUE TITLE
When user clicks on the description of indicator or even in the blank space of description column the indicator gets selected

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1689]
**SEVERITY:**  Major

**MODULE:** 
* Bubble Chart 
* Mountain Chart
* Bubble Map 

**PLATFORM:** 
* Windows 7 / Chrome 49.0
* Windows 7 / Internet Explorer 11.0
* Windows 7 / Firefox 44.0
* Mac 10.10 / Safari 9.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://www.gapminder.org/tools/
2) Click on colors 
3) Click on drop down 
4) Hover the indicator and navigate to the description column 
5) Click anywhere in the column and indicator will get selected 

**ACTUAL RESULTS:**
The indictors get selected when user click on anywhere in the description column 

**EXPECTED RESULTS:**
The indicator should only selected when user clicks on ok button 

**SCREENSHOT**

![28 april indicator](https://cloud.githubusercontent.com/assets/9950837/14885933/93c852e0-0d67-11e6-95d1-727fcd57ea74.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1699

**Comment by angieskazka** [comment]
this was intentional, to not require precise click on OK button, which is small and hard to aim at
