### ISSUE TITLE
Small bubbles goes under the big ones after indicator was changed

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1692]
**Severity**: Major.
**Platform where was tested**: MacBook Air
**Browsers**: Safari, Chrome

**Steps to reproduce**:
1. Open Bubble chart - http://tools-dev.gapminderdev.org/tools .
2. Select "For advanced users" -> "Injury deaths by gender, age, road user" -> "Murdered children, 0-14" indicator for X-axis.
3. Select "For advanced users" -> "Injury deaths by gender, age, road user" -> "Murdered men" indicator for X-axis.

**Actual result**:
Small bubbles got hovered by China.

![screen shot 2016-04-28 at 17 22 50](https://cloud.githubusercontent.com/assets/16382915/14889383/39ea1344-0d67-11e6-89e1-84a4534cab81.png)

**Sometimes some of bubbles got not full opacity.**

![screen shot 2016-04-28 at 17 19 57](https://cloud.githubusercontent.com/assets/16382915/14889395/4ec2536c-0d67-11e6-970e-4deae5078539.png)

**Expected result**:
Small bubbles shouldn't be hovered by China.

![screen shot 2016-04-28 at 17 34 55](https://cloud.githubusercontent.com/assets/16382915/14889455/8e2a6332-0d67-11e6-915c-f97e27d74635.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1698

**Comment by TValeriy** [comment]
Retested. Fixed.
