### ISSUE TITLE
After changing the indicator when user click on bubble the trails got disappeared 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1703]
**SEVERITY:**  Major

**MODULE:** Bubble Chart 

**PLATFORM:** 
* Windows 7 / Chrome 49.0
* Windows 7 / Firefox 44.0
* Windows 7 / Internet Explorer 11.0
* Mac 10 / Safari 9

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools/bubbles 
2) Click on India and Sudan bubble 
3) Drag the slider and generate trails 
4) Click on color drop down 
5) Write education aid given in the search field and select that indicator
6) Click play and wait till the slider reaches to the end point 
7) Click on any bubble 

**ACTUAL RESULTS:**
The india and sudan bubble disappeared , as the user click on any other bubble 

**EXPECTED RESULTS:**
The unwanted bubbles and labels should not displayed on the chart 

**SCREENSHOT:**

![2 may buble](https://cloud.githubusercontent.com/assets/9950837/14954977/ec0d1da2-108f-11e6-8c8c-4ef529b553b8.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1752
