### ISSUE TITLE
When dragging time slider, the trail appears with gaps

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#1715]
Select Equatorial Guinea, drag the time slider back and forward with different speed:

![image](https://cloud.githubusercontent.com/assets/3648190/15088193/da85a1d0-13f0-11e6-9031-63b126e5fbd8.png)

OSX + chrome 50

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1737
