### ISSUE TITLE
preview_src refactor and readability improvements

### ISSUE THREAD

**Issue by ambodi** [Gapminder/vizabi#172]
Inside the Vizabi repo, the only place where a developer can see how a tool is embedded inside an HTML is inside `preview_src` folder. The handlebars file need improvement and more documentation to help developers see that bit of the code they need.

**Comment by arthurcamara1** [comment]
Follow-up:
Added warning here: https://github.com/Gapminder/vizabi/tree/develop/preview_src

Added standalone previews:
http://static.gapminderdev.org/vizabi/develop/preview/fullscreen/bubblechart.html
http://static.gapminderdev.org/vizabi/develop/preview/fullscreen/linechart.html
http://static.gapminderdev.org/vizabi/develop/preview/fullscreen/barchart.html

Apart from codepen examples, bl.ocks.org examples, people can also use the source code of these pages to understand how Vizabi is initialized.
