### ISSUE TITLE
The bubbles did not get full opacity when user unselect the bubble after selecting the bubble 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1729]
**SEVERITY:**  Major

**MODULE:** Bubble Chart 

**PLATFORM:** 
* Windows 7 / Chrome 49.0
* Windows 7 / Firefox 44.0
* Windows 7 / Internet Explorer 11.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools/bubbles 
2) Click on USA and China bubble 
3) Drag the slider from the start to end 
4) Drag the slider from start to end to make trails 
5) Now unselect both bubbles by clicking them
6) Now click any other bubble e.g USA 
7) Now click the cross appear on the label 

**ACTUAL RESULTS:**
The bubbles did not get full opacity even when the user unselects all the selected bubbles 

**EXPECTED RESULTS:**
The bubbles should get full opacity after the user unselect all the bubbles 

**SCREENSHOT:**

![9 may opacity](https://cloud.githubusercontent.com/assets/9950837/15112606/b6d6eb76-1608-11e6-8a81-360a2a3ac10a.png)

Follow the steps till step (6)
1) Click on the USA bubble 

**Actual Result:**
The hover effect did not disappear 

**EXPECTED RESULTS:**
The hover effect should disappear

**SCREENSHOT:**

![9 may hover](https://cloud.githubusercontent.com/assets/9950837/15113280/b56635a4-160c-11e6-8518-81f5c631e40e.png)

**Comment by dab2000** [comment]
#1732
