### ISSUE TITLE
line chart not showing lines 

### ISSUE THREAD

**Issue by ambodi** [Gapminder/vizabi#173]
Browser Name: Chrome
Browser Version:  43.0.2357.124 (64-bit)
Platform OS: Mac OSX 10.10.3

![screen shot 2015-06-30 at 11 17 37](https://cloud.githubusercontent.com/assets/6009583/8427694/a751917e-1f19-11e5-924b-0e06c8496914.png)

**Comment by arthurcamara1** [comment]
This might have happened after one of my recent changes to interpolation.
We should also add a test to spec line chart for this. :)
