### ISSUE TITLE
After generating trails when user drag the position of canvas the  bubbles left their respective trails

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1738]
**SEVERITY:**  Major

**MODULE:** Bubble Chart 

**PLATFORM:** 
* Windows 7 / Firefox 44.0
* Windows 7 / Chrome 49.0
* Windows 7 / Internet Explorer

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools/bubbles 
2) Select main region 2008 from color drop down  
3) Click on USA, Pakistan, and India bubble 
4) Drag the slider from the start to end 
5) Drag the slider from start to end to make trails
6) Drag the canvas up and down 
7) Drag the label of the bubbles and drop anywhere in the chart 

**ACTUAL RESULTS:**
After generating trails when user drag the position of canvas the bubbles detached from their trails

**EXPECTED RESULTS:**
The bubbles should not detached from their respective trails 

**SCREENSHOT**

![10 may](https://cloud.githubusercontent.com/assets/9950837/15147302/6d402960-16d9-11e6-960a-2b19274025e5.png)

**Comment by dab2000** [comment]
#1732
