### ISSUE TITLE
The trails did not generate when user deselect the trail option and select the bubbles again and try to generate trails

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1741]
**SEVERITY:**  Major

**MODULE:** Bubble Chart 

**PLATFORM:** Windows 7 / Chrome 49.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools/bubbles 
2) Click on China bubble
3) Drag the slider from start to end to make trails
6) Click trails icon to disappear trails 
7) Click the selected bubble to unselect it 
8) Click any other bubble 
9) Observe this time the trails icon is not selected when the user selected the bubble 

**ACTUAL RESULTS:**
The trails did not generate when user deselect the trail option and select the bubbles again and try to generate trails

**EXPECTED RESULTS:**
The trails should generated 

**SCREENSHOT / Gif :**
http://g.recordit.co/qDyJLdbkmQ.gif

**Comment by angieskazka** [comment]
this is expected. you disabled trails, so they didn't show up
