### ISSUE TITLE
The chart got stuck when user change the size indicator  

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1747]
**SEVERITY:**  Major

**MODULE:** Bubble Chart 

**PLATFORM:** Windows 7 / Chrome 49.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools/bubbles 
2) Click on China bubble
3) Click on Lock icon 
4) Click play icon 
5) Click the size drop down
6) Click Education -> Schooling Cost -> Expenditure per student, tertiary
7) Observe this time the trails icon is not selected when the user selected the bubble 

**ACTUAL RESULTS:**
After lock the bubbles the chart get stuck when user change the size indicator if the slider is moving 

**EXPECTED RESULTS:**
The chart should not stuck though user change the indicators 

**SCREENSHOT / GIF:**

http://g.recordit.co/uwutsMbUUG.gif

**Comment by angieskazka** [comment]
Also, bubbles are still sized by population

**Comment by k6Labz** [comment]
@angie
Yes Exactly
