### ISSUE TITLE
Wrong line values after zooming while hovering

### ISSUE THREAD

**Issue by arthurcamara1** [Gapminder/vizabi#175]
After I selected a bubble and while hovering, I zoomed in.
The lines that mark the X & Y values are in wrong position.

![screen shot 2015-07-01 at 1 22 48 pm](https://cloud.githubusercontent.com/assets/3584238/8454703/d884ff6a-1fff-11e5-89fc-b42068360754.png)

**Comment by angieskazka** [comment]
done

**Comment by arthurcamara1** [comment]
Had to remove this solution due to #109.
Can we solve it in some other way? Maybe skipping the state/events for this scenario?

**Comment by angieskazka** [comment]
I just reset the hover when zooming or panning happens. Please reopen or create a new issue if you find the interaction unnatural

@arthurcamara1 @olarosling
