### ISSUE TITLE
The page become unresponsive when user inputs the 0 value as max x-axis value 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1750]
**SEVERITY:**  Blocker

**MODULE:** Bubble Chart 

**PLATFORM:** 
* Windows 7 / Chrome 49.0
* Windows 7 / Firefox 45.0
* Windows 7 / Internet Explorer 11.0
* Mac 10 / Safari 9

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools/bubbles 
2) Click on Options 
3) Click on X and Y axis 
4) Input 0 as max value of X-axis 
5) Press Enter 

**ACTUAL RESULTS:**
The page become unresponsive when user inputs 0 as the x axis max value 

**EXPECTED RESULTS:**
The page should not become unresponsive

**SCREENSHOT / GIF:**

http://g.recordit.co/jonXnvHpzI.gif

**Comment by angieskazka** [comment]
this is another instance of the problem #1339
