### ISSUE TITLE
The lines appear on the chart with the bubbles when the user change the indicators 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1753]
**SEVERITY:** Major

**MODULE:** Bubble Chart 

**PLATFORM:** 
* Windows 7 / Chrome 49.0
* Windows 7 / Firefox 45.0
* Windows 7 / Internet Explorer 11.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://178.62.135.203:8081/tools/bubbles 
2) Click USA and China bubble 
3) Make trails of the bubbles till the end 
4) Click on color drop down
5) Write Maternal deaths, life time risk in the search field
6) Select the respective indicator 
7) Observe the lines along with the trails 
8) Click and hold the left click and drag the mouse
9) Extra bubbles also appear on the chart 

**ACTUAL RESULTS:**
Extra lines appeared on the chart along with the trails 

**EXPECTED RESULTS:**
No extra lines should appeared on the chart 

**SCREENSHOT / GIF:**

http://g.recordit.co/LsWcHLxyJu.gif

**Comment by sergey-filipenko** [comment]
related to #1703

**Comment by angieskazka** [comment]
@sergey-filipenko you fixed #1703, but this bug still persists on develop

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1760
