### ISSUE TITLE
The liner and log options should be available for all indicators 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1756]
**SEVERITY:** Major

**MODULE:** Bubble Chart 

**PLATFORM:** 
* Windows 7 / Chrome 49.0
* Windows 7 / Firefox 45.0
* Windows 7 / Internet Explorer 11.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://178.62.135.203:8081/tools/bubbles 
2) Click color drop down 
3) Click on indicators 
4) Observe the linear and log option is available 
5) Now click on time indicator 
6) No linear and log option is available 

**ACTUAL RESULTS:**
Linear and log options should be available for all indicators 

**EXPECTED RESULTS:**
Linear and log options should be available for all indicator options 

**SCRENSHOT / GIF:**

http://g.recordit.co/06iXkEr1Hi.gif

**Comment by angieskazka** [comment]
@k6Labz  no, because we don't want people to have logarithmic time
for the same reason all indicators on "size" don't have lin/log selector
