### ISSUE TITLE
The year appear on the label is not exact the same as the year, the trails started from 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1765]
**SEVERITY:**  Major

**MODULE:** Bubble Chart 

**PLATFORM:** 
* Windows 7 / Firefox 44.0
* Windows 7 / Chrome 49.0
* Windows 7 / Internet Explorer 11

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://static.gapminderdev.org/vizabi/develop/preview
2) Click on Aruba check box from country 
3) Drag the slider to year 1900
4) Now drag the slider to the year 2015
5) Observe the changing year on the label 

**ACTUAL RESULTS:**
The year appear on the label is not exact the same as the year, the trails started from

**EXPECTED RESULTS:**
The year on the label should be same as the year from where user started the trails

**SCREENSHOT/GIF**

http://g.recordit.co/uI001tWYQH.gif

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1768

**Comment by angieskazka** [comment]
looks same as #1664
