### ISSUE TITLE
The trails and year disappear when user clicks on the slider ball again and again 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1766]
**SEVERITY:**  Major

**MODULE:** Bubble Chart 

**PLATFORM:** 
* Windows 7 / Firefox 44.0
* Windows 7 / Chrome 49.0
* Windows 7 / Internet Explorer 11

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://static.gapminderdev.org/vizabi/develop/preview
2) Click on Aruba check box from country 
3) Drag the slider to year 1900
4) Now drag the slider to the year 2015
5) Observe the changing year on the label 
6) Click on the slider ball again and again 

**NOTE:** The trails disappear also when user drag the label on the chart at different positions 

**ACTUAL RESULTS:**
The trails and year disappear when user clicks on the slider ball again and again

**EXPECTED RESULTS:**
The trails should not disappear when user clicks on the slider ball again and again 

**SCREENSHOT**

http://g.recordit.co/Uio3Rw0k4z.gif

**Comment by sergey-filipenko** [comment]
resolved in #1765
