### ISSUE TITLE
Search bar is truncated from right side

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1773]
**SUMMARY:** 
1) Search bar is truncated from right side
2) Search bar title is not appropriate 

**SEVERITY:**  Minor

**MODULE:**   Bubble chart

**Platform:**
*   Windows 7 / Chrome 52.0
*    MAC 10 / Chrome 49.0

**RELEASE:** v0.13.11

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools/
2)	Bubble Chart will be loaded.
3)	Note that Search bar is truncated from right side and Search bar title is not appropriate

**ACTUAL RESULTS:**
Search bar is truncated from right side and Search bar title is not appropriate 

**EXPECTED RESULTS:**
Search bar should not be truncated and search bar title should be “Find”

**SCREENSHOT:** 

![v0 13 11_ 01](https://cloud.githubusercontent.com/assets/9950837/15599614/ccdb27a4-23fd-11e6-823b-ed8fcc334d83.png)

**Comment by angieskazka** [comment]
it should be "Select" instead of "dialogs/find"
language strings are updated now
