### ISSUE TITLE
Tooltip is overlapping the axis description

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1774]
**SEVERITY:**  Minor

**MODULE:**   
* Bubble chart
* Bubble Map chart

**Platform:**
*   Windows 7 / Chrome 52.0
*    MAC 10 / Chrome 49.0

**RELEASE:** v0.13.11

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools/
2)	Bubble Chart will be loaded.
3)	Select any bubble
4)	Drag the tooltip of selected bubble over axis description
5)	Note that tooltip is overlapping the axis description 

**ACTUAL RESULTS:**
Tooltip of selected bubble overlapping the axis description 

**EXPECTED RESULTS:**
Overlapping of tooltip and axis should not be there

**SCREENSHOT:** 

![v0 13 11_ 02](https://cloud.githubusercontent.com/assets/9950837/15599740/b85a6960-23fe-11e6-9bfe-cc5f8392d919.png)

**Comment by angieskazka** [comment]
overlapping is fine, but let the label be on top
