### ISSUE TITLE
Bubbles are truncated from upper side by changing the axis description

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1781]
**SEVERITY:**  Major

**MODULE:**   Bubble chart

**Platform:**
*   Windows 7 / Chrome 52.0
*    Windows 7 / Firefox 42.0

**RELEASE:** v0.13.11

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools/
2)	Bubble Chart will be loaded.
3)	Click on Y-axis description
4)	Select Time
5)	Note that bubbles are truncated after selecting the Time as parameter 

**ACTUAL RESULTS:**
Bubbles are truncated after selecting the Time as parameter from Y-axis description

**EXPECTED RESULTS:**
Bubbles should not be truncated

**SCREENSHOT:** 

![v0 13 11_ 04](https://cloud.githubusercontent.com/assets/9950837/15643030/74fd9148-2664-11e6-8c26-f47e04692ae7.png)

**Comment by angieskazka** [comment]
@k6Labz i know, Ola requested this in #1759
