### ISSUE TITLE
List of countries does not appear when user switch the chart to full screen mode 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1795]
**SEVERITY:** Major

**MODULE:** 
* Mountain Chart
* Bubble Map 

**PLATFORM:** 
* Windows 7 / Chrome 49.0
* Windows 7 / Internet Explorer 11
* Windows 7 / Firefox 44.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://static.gapminderdev.org/vizabi/develop/preview
2) Click mountain chart 
3) Click on full button 

**ACTUAL RESULTS:**
The list of countries on side menu does not appear 

**EXPECTED RESULTS:**
The list of countries should appear on side menu 

**SCREENSHOT:**
![1 jun](https://cloud.githubusercontent.com/assets/9950837/15699467/832908f0-27e6-11e6-9cf2-910e2b7f81fe.png)

**Comment by angieskazka** [comment]
the config for color legend was missing. fixed now
