### ISSUE TITLE
The dropdown options list did not clearly open / appear 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1799]
**SEVERITY:**  Major

**MODULE:**
* Bubble Chart 
* Bubble Map
* Mountain Chart

**PLATFORM:** 
* Windows 7 / Internet Explorer 11

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org
2) Click on the size drop down 
3) Select Economy -> Debt & Trade -> High Technology Exports
4) Click on color drop down 
5) Hover mouse on some indicator which has some sub indicators 

**ACTUAL RESULTS:**
The indicators list flashes until user hover the mouse to somewhere on the chart 

**EXPECTED RESULTS:**
The sub indictors list should not flash instead the list just has to appear when user hover the indicator
 
**SCREENSHOT / GIF :**

http://g.recordit.co/9TK6Ol3bnv.gif

**Comment by dab2000** [comment]
#1804
