### ISSUE TITLE
When user hover the bubble the black bubble appear instead of the bubble of same color 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1811]
**SEVERITY:**  Major

**MODULE:**
* Bubble Chart 
* Bubble Map 

**PLATFORM:** 
* Windows 7 / Chrome 49.0
* Windows 7 / Firefox 44.0  

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://www.gapminder.org/tools
2) Click on color dropdown 
3) Select Economy -> Aid received -> Aid received per person
4) Select china and drag the slider to make trails
5) Click on color so color wheel should appear
6) Hover mouse on color bubbles and they turned to black 

**ACTUAL RESULTS:**
The bubbles turned in to black color when user hover the bubbles 

**EXPECTED RESULTS:**
The bubbles color should remain the same when user hover the bubbles 

**SCREENSHOT:**
![6 jun black bubble](https://cloud.githubusercontent.com/assets/9950837/15813815/6f09e224-2bdb-11e6-845f-261dc8ff3f41.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1813
