### ISSUE TITLE
The bubbles get truncated and some portion of bubbles hide behind the countries list 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1812]
**SEVERITY:**  Major

**MODULE:** Bubble Map 

**PLATFORM:** 
* Windows 7 / Chrome 49.0
*Windows 7 / Firefox 44.0  

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org
2) Click on color dropdown 
3) Select Properties -> World regions, 6 colors   
4) Click size dropdown
5) Select Economy -> Aid received -> Aid received per person

**ACTUAL RESULTS:**
The bubbles are truncated and hide behind the countries list 

**EXPECTED RESULTS:**
The bubbles part should not hide behind the countries list 

**SCREENSHOT:**
![6 jun buble truncated](https://cloud.githubusercontent.com/assets/9950837/15817679/a322c6fe-2bf2-11e6-80ab-ddbfb20c04ce.png)

**Comment by angieskazka** [comment]
@k6Labz it's better to have exceptional cases look not as good, than to have extra large margins for all the cases
the picture above is not useful anyway =)
