### ISSUE TITLE
New tool: cartogram

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#1816]
**Current progress: http://static.gapminderdev.org/vizabi/feature/cartogram/preview/cartogram.html**

Let's make a cartogram for vizabi
![image](https://cloud.githubusercontent.com/assets/3648190/15853849/1e49f9d8-2ca7-11e6-83f3-e153fc8143f4.png)

By default, the "size" should be constant, so only color is changing (and cartogram boils down to choropleth map). Use vizabi style color and size pickers, color being also the title of the chart.

Use this ready-made solution and adapt this to vizabi
http://prag.ma/code/d3-cartogram/#popest/2010 
https://github.com/shawnbot/topogram

Preferably we should be able to use svg shapes per entity (and request them as svg shapes).

Use the map of south africa with provinces
http://www.limn.co.za/2013/05/json-topology-maps/

you can convert it to svg using http://www.mapshaper.org/

For the data, use some arbitrary numbers for now (9 provinces x 3 years of data x 2 indicators = 54 numbers. easy to do it manually)

**Comment by angieskazka** [comment]
improvements needed:

http://static.gapminderdev.org/vizabi/feature/cartogram/preview/cartogram.html
![image](https://cloud.githubusercontent.com/assets/3648190/15990007/a49f49ae-3088-11e6-9f57-556fcf46c137.png)

1. change lock-mode: right now the entire map is growing in lock mode. instead let's make shapes grow relative to the total population (and relative to the locked area)
try this (before-after formulas for the area of one shape in locked mode)
![image](https://cloud.githubusercontent.com/assets/3648190/15990137/01010a50-308b-11e6-8dca-969ff3bf8f13.png)

2. try [municipalities data](https://drive.google.com/drive/u/0/folders/0B0WvZkfrMAewSnRGcnJLTDY5UEU) and the full [municipalities map](https://drive.google.com/drive/u/0/folders/0B0-WQm9kCrn9QjRNdEc1Wk81Q3M)

3. Update the province map from the link above too. Shape IDs should be resolved better now

4. styling: black stroke around shapes

**Comment by angieskazka** [comment]
Merged the cartogram branch, generated geo-properties file, found some bugs:

municipality map: lock on 1996 doesn’t work: load cartogram, set size to population: map gets distorted as expected. Move slider to 1996
1) as we are not in lock mode the map should be distorted. But i see a physical map

2) Try to lock on 1996. get errors in console
`d3.min.js:5 Error: <path> attribute d: Expected number, "MNaN,NaNLNaN,NaNL…".`

3) refresh page. same error (i know it's the same, just reminding that refresh should work in any state)

**Comment by angieskazka** [comment]
'8. add update on color scale lin/log change
'9. hide “lock” button when size is constant

**Comment by angieskazka** [comment]
'13. Avoid first screen being grey and then jump

**Comment by jheeffer** [comment]
'15. When playing and hovering over geo, the written values of indicators (top left) should update.

**Comment by angieskazka** [comment]
'16. Make all other tools not require "lockActive" of the model chart =)
