### ISSUE TITLE
New tool: stacked age pyramid

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#1818]
Fork popbyage to produce this

![image](https://cloud.githubusercontent.com/assets/3648190/15855634/dc2bbee2-2cb0-11e6-860f-f68cbd6b2bcf.png)

Say, the data is 4-dimensional:
time, 
age,
left-right groups
stacked groups

on top of these 4 dimensions we can have 2 indicators:
magnitude (above the number of people by age, gender, education level and time)
color (above the color is just by education level)

**Comment by jheeffer** [comment]
Also keep possibility of one sided age pyramid in case of absence of dimension for left-right groups

**Comment by jheeffer** [comment]
Add a button/command to hide/show the stacked groups dimension.

**Comment by jheeffer** [comment]
you can also use this one to see an example.
http://www.oeaw.ac.at/vid/dataexplorer//
click graphic explorer in the top and select south africa if you wan to see south africa

**Comment by jheeffer** [comment]
Data files:
year-age (half pyramid, solid bars)
https://drive.google.com/open?id=0B_dT7XMWVfqaS08wSmtFQkFVQUk

year-age-education (half pyramid, bars split by education)
https://drive.google.com/open?id=0B_dT7XMWVfqaRGI1Q0VEdjJtT1U

year-age-education-gender (full pyramid, half per gender, bars split by education)
https://drive.google.com/open?id=0B_dT7XMWVfqaZHlpUWR3UXJZY2s

**Comment by angieskazka** [comment]
Summary: looks good so far! Now let's make it working in a useful way

Improvements needed: 

![image](https://cloud.githubusercontent.com/assets/3648190/15990739/82beb4cc-309d-11e6-9932-dce9e78fd194.png)

1. time slider should play and bars should move smoothly
three possible options:
* workaround: we produce interpolated data. the data file become larger
* workaround: we turn dimensions into measures. columns in data file would be: `time, age, noschooling_male, someprimary_male, completeprimary_male, somesecondary_male, grade12_male, higher_male, unspecified_male, na_male, total_male, noschooling_female, someprimary_female, completeprimary_female, somesecondary_female, grade12_female, higher_female, unspecified_female, na_female, total_female`
* we actually change the core so that it interpolates the values across all dimensions

2. Color legend should show the color legend: No schooling, Some primary, Complete primary, Some secondary, Grade 12/Std 10, Higher, Unspecified, Not applicable
![image](https://cloud.githubusercontent.com/assets/3648190/15990981/826428b6-30a4-11e6-8563-1ee4e8629a82.png)

3. Make a custom color palette in metadata so it makes more sense

4. Maybe remove "stack" altogether and just have "color", because it doesn't make sense to split the two

5. the hooks should be called color, ~~stack~~, side, similar to what you have
the "which" part of hook (and the indicator name) should go like: Education, ~~Education~~, Sex respectively. "Side" hook should also be available to chose.

if ~~stack~~ color is use=constant, which=none, then we'd have a single bar per age
if ~~stack~~ color is use=property, which=education, then we would have the picture we have
we can also have color use=property, which=race, then instead of education levels we would have black, white, indian, colored

if side=constant, which=none, then we would have one side
if side=property, which=sex, then we would have two sides

6. One x axis takes the values in and the other pushes them out?
![image](https://cloud.githubusercontent.com/assets/3648190/15991027/40eed50a-30a6-11e6-8ef9-5104b52d788f.png)

and here none of them takes 0 in
![image](https://cloud.githubusercontent.com/assets/3648190/15991032/8059d1d6-30a6-11e6-9da1-334d810492ce.png)

7. Bars should resize thickness on resizing the screen

**Comment by jheeffer** [comment]
8. Switch (button/command) between showing proportionate (% of total population) or absolute numbers.

So the x-axis would change from absolute numbers to %. Where % is relative to the total of whole pyramid population.

**Comment by angieskazka** [comment]
'9. Hovering behavior: 
* hover by segments, not by rows
* don't write year, but add segment name
* example for below 25-to-29-year-olds Some secondary: 13.2k
* for left side: text-anchor=end to the middle of the pyramid

![image](https://cloud.githubusercontent.com/assets/3648190/16026977/ac4eb6a8-31d2-11e6-82a5-64dc2aa1b95c.png)

**Comment by angieskazka** [comment]
'10. in this example percent mode didn’t rescale to fit the bars
(it’s in presentation, slide27, file vizabi-agepyramid-race.html)
![image](http://g.recordit.co/GYCyOLAqLw.gif)

**Comment by jheeffer** [comment]
'11 scale on absolute has too much whitespace
'12 changing to single color: stacks stay but with one color
'13 changing to single color: sides switch

![image](https://cloud.githubusercontent.com/assets/1596071/16177515/56d33e80-3630-11e6-9a23-ed11a6ba0361.png)

![image](https://cloud.githubusercontent.com/assets/1596071/16177521/862fab1e-3630-11e6-88c5-ae95a3fce803.png)
