### ISSUE TITLE
The label of the bubble did not appear when user select the bubble 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1827]
**SEVERITY:**  Major

**MODULE:** Bubble Chart 

**PLATFORM:** 
* Windows 7 / Chrome 49.0
* Windows 7 / Firefox 44.0  

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org
2) Click on size 
3) Select Health -> TB -> TB with HIV +, est. new cases total
4) Click Afghanistan check box 
5) The label of selected country did not visible 

**ACTUAL RESULTS:**
The label of the country did not appear when user select the bubble 

**EXPECTED RESULTS:**
The label of the country should be visible when user select the bubble 

**SCREENSHOT:**

![no label 13 june](https://cloud.githubusercontent.com/assets/9950837/16004456/2cbdaf18-317b-11e6-804b-3936d8047dc2.png)

**Comment by angieskazka** [comment]
looks like size data is not available but the bubble still shows up somehow

**Comment by k6Labz** [comment]
Yes and if it so .. than the bubble name also should not appear in the find country list as well

**Comment by k6Labz** [comment]
Fixed
