### ISSUE TITLE
When user loads the chart the slider position should is on 2000 instead of 2015 or  maximum allowed year  

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1872]
**SEVERITY:**  Minor

**MODULE:** Bar Rank Chart 

**PLATFORM:** Windows 7 / Chrome 49.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html
2) Click on Bar rank chart
3) Observe when the chart gets loaded  

**ACTUAL RESULTS:**
The chart slider position is on 2000 when user loads the chart

**EXPECTED RESULTS:**
When user loads the chart the slider position should be on 2015 or on the maximum allowed year

**SCREENSHOT:**
![29 jun slider pos](https://cloud.githubusercontent.com/assets/9950837/16448170/7706a558-3e09-11e6-8cab-8ebc751f2f12.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1875

**Comment by k6Labz** [comment]
Fixed
