### ISSUE TITLE
URL Persistency issue

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1873]
**SEVERITY:**  Major

**MODULE:** Bubble Map 

**PLATFORM:** Windows 7 / Chrome 49.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html
2) Click on Bubble Map
3) Click on China bubble 
4) Drag the slider to backward position like choose 1896 etc
5) Copy the URL and paste it in new tab and proceed 

**ACTUAL RESULTS:**
The label disappeared when the user refreshes or load the URL in new tab  

**EXPECTED RESULTS:**
Same page open when user loads the URL in new tab or refreshes the page 

**SCREENSHOT:**
![29 jun url pe1](https://cloud.githubusercontent.com/assets/9950837/16450353/daa24f7a-3e15-11e6-848c-9195bb547ac7.png)

![url 29](https://cloud.githubusercontent.com/assets/9950837/16450480/9b5be0aa-3e16-11e6-9001-210a5b1261a6.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1875

**Comment by k6Labz** [comment]
issue still persist

**Comment by angieskazka** [comment]
steps to reproduce:
* open bubble map
* select china bubble
* refresh page

alternatively, open this state: 
http://tools-stage.gapminderdev.org/tools/#_state_time_end=2015;&entities_select@_geo=chn;;;;&chart-type=map

**Comment by k6Labz** [comment]
The label appears when user selects other bubble

**Comment by angieskazka** [comment]
ok as a temporary solution, but we will probably need to refactor labels into a helper, not a component #1899

**Comment by k6Labz** [comment]
Fixed
