### ISSUE TITLE
Color anchors in more-options // The color wheel does not appear when user click on the color bar   

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1878]
**SEVERITY:**  Medium

**MODULE:** Bar Rank Chart 

**PLATFORM:** Windows 7 / Chrome 49.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html
2) Click on color drop down
3) Click on Child Mortality Rate indicator 
4) Click on color bar

**ACTUAL RESULTS:**
The color wheel does not appear when user clicks on color bar 

**EXPECTED RESULTS:**
The color wheel should appear when user clicks on the color bar 

**SCREENSHOT:**
![2 july](https://cloud.githubusercontent.com/assets/9950837/16539100/fac0f908-4051-11e6-80df-e47118813682.png)

**Comment by angieskazka** [comment]
@k6Labz no need for changing colors on click in the side panel color gradient

@sergey-filipenko instead: please add markers (let's call them color anchors) according to palette config and configure css to only show them in more options, not in sidebar. Sidebar should stay clean, with less controls

<img width="327" alt="screen shot 2016-08-03 at 13 15 22" src="https://cloud.githubusercontent.com/assets/3648190/17363811/fb49855e-597c-11e6-80fd-9989543a360a.png">

invert() will be needed anyway for adding a new anchor, but let’s leave it for later-later

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1906

**Comment by angieskazka** [comment]
enhancement: only show color anchors when color is in more options, not as a dialog on it's own

bug: switched to properties: anchors appeared
![image](https://cloud.githubusercontent.com/assets/3648190/17547317/d0f5a1d8-5ee6-11e6-8f1d-fbe0ed73eed6.png)
