### ISSUE TITLE
When user tries to open the chart in new tab user always redirect to bubble chart page 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1886]
**SEVERITY:**  Major

**MODULE:**

* Bubble Chart 
* Bubble Map 
* Mountain Chart

**PLATFORM:** 

* Windows 7 / Chrome 49.0
*Windows 7 / Firefox 44.0  

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org
2) Scroll down the page
3) Right click on chart icon
4) Open the chart in new tab
5) Observe the URL 

**ACTUAL RESULTS:**
The user redirects to bubble chart page

**EXPECTED RESULTS:**
The user should redirect to the page of the related chart

**Comment by angieskazka** [comment]
fixed on tools page by @vvpanchenko
