### ISSUE TITLE
White trails got generated when user made changes in the size and indicators 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1891]
**SEVERITY:**  Major

**MODULE:** Bubble Chart 

**PLATFORM:** 
* Windows 7 / Chrome 49.0
* Windows 7 / Firefox 44.0  

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org
2) Drag back the slider
3) Click on color and choose Child mortality rate 
4) Click on option -> size 
5) Increase the size 
6) Observe white bubbles appear 
7) Click the bubbles and click play to generate trails 

**ACTUAL RESULTS:**
White trails got generated when user made changes in the size

**EXPECTED RESULTS:**
All bubbles should have proper  color 

**SCREENSHOT:**

![8-5-2016 12-41-06 pm](https://cloud.githubusercontent.com/assets/9950837/17435849/e09990b2-5b2c-11e6-9f07-8f031eb2e7a2.png)

**Comment by angieskazka** [comment]
this is expected: data is missing, so the color is white. we will add explanation for it later into the color legend
