### ISSUE TITLE
There are broken thumbnails on the webpage

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1896]
**SEVERITY:**  Major

**MODULE:** Bubble Chart 

**PLATFORM:** Windows 7 / Chrome 52.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org
2) Scroll down the page 

**ACTUAL RESULTS:**
The thumbnails are broken on the page 

**EXPECTED RESULTS:**
Thumbnails should not be broken and properly visible

**Comment by angieskazka** [comment]
the fix

Quick instructions in case the digital ocean instance crashes and reboots, like it did 
2015-04-29 11:00
2016-03-24 12:44
2016-08-08 12:00

After the instance (or a restored backup) is up again, login via ssh as root on the dokku instance on digital ocean (ssh root@dokku.gapminder.org) and then run the following to have the production cms respond on cms.gapminder.org again:
dokku deploy master-cms
dokku mariadb:create master-cms

To login you need to be registered with your SSH public key. Currently registered are: Fredrik, Dima, Jasper, Georgii, Angie
