### ISSUE TITLE
The links are not working and redirect to page not found 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1897]
**SEVERITY:**  Major

**MODULE:** Bubble Chart 

**PLATFORM:** 
* Windows 7 / Chrome 52.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org
2) Scroll down the page 
3) Click on videos link 

**ACTUAL RESULTS:**
The user redirect to page not found web page 

**EXPECTED RESULTS:**
The user should redirect to the appropriate page 

**SCREENSHOT:**

![8-8-2016 3-07-53 pm](https://cloud.githubusercontent.com/assets/9950837/17476531/f95076bc-5d79-11e6-91e4-43915208bfd3.png)

**Comment by angieskazka** [comment]
see the fix here https://github.com/Gapminder/vizabi/issues/1896#issuecomment-238229791
