### ISSUE TITLE
BLC_05: drop down option should not show REGION

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#210]
SEVERITY: Major

MODULE: Bubble Chart

OS / BROWSER: Windows 7 / Chrome 45.0

STEPS TO REPRODUCE:
1) Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.5.1/preview/bubblechart.html 
2) Bubble chart page will be loaded
3) Click on Options menu 
4) Select x-axis dropdown as Region
5) Select y-axis of any value (GDP, Lex etc.) 
6) Note that coordinates is not appeared for x-axis where Region is selected

ACTUAL RESULTS:
No coordinates is appeared for “Region”, if it’s selected on X-axis (same for y-axis)

EXPECTED RESULTS: 
Region, Geo Code & Value should not be appeared in dropdown

SCREENSHOT:
![vizabi_bubblechart_08](https://cloud.githubusercontent.com/assets/1772649/8617026/4649670a-2719-11e5-92bb-7105e6596681.png)

**Comment by arthurcamara1** [comment]
They *should* be available, but the axis needs to support those values as well instead of rendering with this error

**Comment by k6Labz** [comment]
**Retest Result:** Failed

**BUILD:** v0.7.0

**DESCRIPTION:** This issue is appeared in another way, can be seen in below screenshot

**SCREENSHOT:**
![blc_05](https://cloud.githubusercontent.com/assets/9950837/9437845/d74317b6-4a72-11e5-8ab2-a9091722a895.png)

**Comment by IncoCode** [comment]
I think, this is a problem with the data, not functional issue.

**Comment by angieskazka** [comment]
solved with b491d2968a28b0dec88c5773be4cfd4ee2389b03
