### ISSUE TITLE
BLC_07: Go SMALL text is slightly cut off from right side in Full screen

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#212]
SEVERITY: Minor

MODULES: Bubble Chart, Bar Chart

OS / BROWSER: Windows 7 / Chrome 45.0

STEPS TO REPRODUCE:
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.5.1/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Click on GO BIG
4)	Big screen will shown
5)	Note that text is slightly cut off from right of GO SMALL

ACTUAL RESULTS:
Go small text is slightly cut off from right side in Full screen

EXPECTED RESULTS: 
Go small text should be shown completely 

SCREENSHOTS:
![vizabi_bubblechart_13](https://cloud.githubusercontent.com/assets/1772649/8617943/7543ce70-2722-11e5-97d9-5fc21a76e071.png)

![vizabi_barchart_13](https://cloud.githubusercontent.com/assets/1772649/8673271/7f6e85d2-2a4e-11e5-8276-bf5ff23ef1af.png)

**Comment by k6Labz** [comment]
**Retest Result:** Failed

**RELEASE:** v0.7.0

**DESCRIPTION:** This issue is appeared again, can be seen in below screenshot

**SCREENSHOT:**
![regression_02](https://cloud.githubusercontent.com/assets/9950837/9438609/a95a8ff4-4a78-11e5-9196-146c2259be88.png)

**Comment by angieskazka** [comment]
@k6Labz please retest on [develop branch](static.gapminderdev.org/vizabi/develop/preview/bubblechart.html)
