### ISSUE TITLE
BLC_08: Text “Size Population, Colors: Region” is overlapping with label of X-axis in small screen resolution

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#213]
SEVERITY: Major

MODULE: Bubble Chart

OS / BROWSER: Windows 7 / Chrome 45.0
STEPS TO REPRODUCE:
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.5.1/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Click on Random button of responsiveness to have different size
4)	Note text is overlap with label of X-axis 

ACTUAL RESULTS:
Text “Size Population, Colors: Region” is overlapping with label of X-axis for screen size of “795x342”, “431x331”, 1011x322, “582x315” etc.

EXPECTED RESULTS: 
Text should not be overlap with X-axis value, irrespective of different screen size 

SCREENSHOT:
![vizabi_bubblechart_15a](https://cloud.githubusercontent.com/assets/1772649/8618021/4d776bb2-2723-11e5-9523-b129f864e025.png)

**Comment by arthurcamara1** [comment]
This was fixed, but the text is still overlapping with the axis.
