### ISSUE TITLE
BLC_09: Coordinates values of X-axis is slightly cut off from below, when clicked on full button of responsiveness

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#214]
SEVERITY: Major

MODULE: Bubble Chart, Bar Chart

OS / BROWSER: Windows 7 / Chrome 45.0

STEPS TO REPRODUCE:
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.5.1/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Click on Full button of responsiveness 
4)	Full screen will be open
5)	Note X-axis coordinates being cut off from below side

ACTUAL RESULTS:
X-axis coordinates cut off from below side, when clicked on Full button of responsiveness 

EXPECTED RESULTS: 
Coordinates should not be cut off from below upon going into full screen 

SCREENSHOTS:
![vizabi_bubblechart_16](https://cloud.githubusercontent.com/assets/1772649/8618059/c00b4680-2723-11e5-8d6b-ee3b442773b2.png)

![vizabi_barchart_16](https://cloud.githubusercontent.com/assets/1772649/8697560/491a56fc-2b0f-11e5-95ab-8a9c6041e839.png)

**Comment by arthurcamara1** [comment]
@k6Labz Please double check and close issue if solved.
