### ISSUE TITLE
BLC_10: All menus text is being cut off from right under language PT

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#215]
SEVERITY: Minor

MODULES: Bubble Chart, Bar Chart

OS / BROWSER: Windows 7/Chrome 45.0

STEPS TO REPRODUCE:
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.5.1/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Click on Set Lang: adjacent to Play 
4)	If already selected language is English, it will be change into PT
5)	Note all menus like options, find, axes etc. text is being cut off from right

ACTUAL RESULTS:
Text of all menus is slightly cut off from right under language set as PT & overlap menus are showing in bottom for portrait view 

EXPECTED RESULTS: 
Menus text should be shown completely in both positions of menus under language as PT  

SCREENSHOTS:
![vizabi_bubblechart_17](https://cloud.githubusercontent.com/assets/1772649/8618085/15279b50-2724-11e5-8b4f-fc258e72e924.png)

![vizabi_barchart_17](https://cloud.githubusercontent.com/assets/1772649/8673300/b83702e0-2a4e-11e5-9c0c-049345aa2cdb.png)

**Comment by angieskazka** [comment]
fixed now
