### ISSUE TITLE
BLC_11: Bubble chart does not fit properly inside in Go Big (Full screen)

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#216]
SEVERITY: Major

MODULE: Bubble Chart

OS / BROWSER: Windows 7/Chrome 45.0
STEPS TO REPRODUCE:
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.5.1/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Click on Go Big 
4)	Bubble chart will be in Full screen
5)	Note bubble chart does not fit properly in full screen mode

ACTUAL RESULTS:
Bubble chart does not properly inside the full screen mode

EXPECTED RESULTS: 
Bubble chart should resize itself according to screen size  

SCREENSHOT:
![vizabi_bubblechart_18](https://cloud.githubusercontent.com/assets/1772649/8618126/8a7a85a2-2724-11e5-8aa7-8f4b44e9244f.png)

**Comment by angieskazka** [comment]
Could not reproduce on Mac, nor on Windows. I think it's been fixed
