### ISSUE TITLE
BLC_12: Chart is faded in the with one color, even a single bubble is not shown on chart

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#217]
SEVERITY: Major

MODULE: Bubble Chart

OS/BROWSER: Windows 7/Chrome 45.0
STEPS TO REPRODUCE:
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.5.1/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Click on Options menu
4)	Scroll down till Size
5)	Select Life expectancy, GDP or Population in dropdown
6)	Select Time in drop down
7)	Slide the slider to forward or backward
8)	Note that bubble chart will covered all inside by a single color  

ACTUAL RESULTS:
Bubble chart is covered by a single color & not even a single bubble is shown inside the chart

EXPECTED RESULTS: 
Bubbles should be shown with the size in the available range

SCREENSHOT:
![vizabi_bubblechart_20](https://cloud.githubusercontent.com/assets/1772649/8618173/0752d20a-2725-11e5-8233-6c2eedf7c6fa.png)

**Comment by angieskazka** [comment]
this one i wouldn't find myself with my monkey-testing. good job @k6Labz !

**Comment by arthurcamara1** [comment]
Fixed.
