### ISSUE TITLE
BLC_14: Bubbles of selected countries not shown in find

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#219]
SEVERITY: Major

MODULE: Bubble Chart

OS/BROWSER: Windows 7/Chrome 45.0
STEPS TO REPRODUCE:
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.5.1/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Click on Find
4)	Click the checkbox for countries like Abkhazia, Akrotiri etc.
5)	Note that bubbles will not be selected for above stated countries 

ACTUAL RESULTS:
Bubbles of selected countries like Abkhazia, Akrotiri etc. in Find, are not shown in chart 

EXPECTED RESULTS: 
Data for countries is not available like Abkhazia, Akrotiri etc. Bubbles & labels should be shown in chart for selected countries as Angola is selected, cab be seen in below screenshot  

SCREENSHOT:
![vizabi_bubblechart_22a](https://cloud.githubusercontent.com/assets/1772649/8618268/d7512bd2-2725-11e5-8889-775b08e16df4.png)
![vizabi_bubblechart_22b](https://cloud.githubusercontent.com/assets/1772649/8618269/d79a316a-2725-11e5-8353-25a227ced106.png)

**Comment by arthurcamara1** [comment]
I believe this was fixed after 13420e0e26b656fc6829567e732a3a5919cc2a23 and will be available for testing after the next release.

The solution was: countries without sufiicient data to be displayed on the chart cannot be selected and do now show up on the "Find" list

**Comment by arthurcamara1** [comment]
You may also quickly check the develop version to make sure it's working: http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html

**Comment by SadiaKualitatem** [comment]
This issue is fixed now from developer end, as provided URL:
http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html

We will test it again when next release will be made available as per above comment of @arthurcamara1
