### ISSUE TITLE
Remove jquery dependency

### ISSUE THREAD

**Issue by arthurcamara1** [Gapminder/vizabi#22]
We're barely even using jQuery, apart from $.Deferred(). Removing jQuery should make it lighter

**Comment by angieskazka** [comment]
@arthurcamara1, you're done with it, aren't you?

**Comment by arthurcamara1** [comment]
Yes. :)

On Monday, March 23, 2015, Angie the Fairytale <notifications@github.com>
wrote:

> @arthurcamara1 <https://github.com/arthurcamara1>, you're done with it,
> aren't you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Gapminder/vizabi/issues/22#issuecomment-84934808>.
>


-- 

*Arthur Camara*
*Software Engineer*
Gapminder Foundation
www.gapminder.org
