### ISSUE TITLE
color.getFilteredItems returns {}, but the hook is otherwise working fine

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#226]
To be able to highlight entities in the main component, my color legend needs to fetch all geos along with their color properties. Now when you hover Asia in color legend map you will get an error

this is because colorLegend.js L155: var filtered = _this.model.color.getFilteredItems();
returns {}

![image](https://cloud.githubusercontent.com/assets/3648190/8636844/bd9a449c-2876-11e5-8c47-9396d1901ade.png)

and inside getFiltered 

var filtered = _DATAMANAGER.get(this._dataId, 'filtered');
returns {} 

maybe because this._dataId = "-186847006"

UPD: the bug was found on bubble chart. Mountain chart is surprisingly OK
this might me a major issue, if getFilteredItems is not doing the thing

**Comment by arthurcamara1** [comment]
@angieskazka 

Fixed. Not major.

The reason is that using `getFilteredItems` to get nested items was a hack we had before. Now we have `getNestedItems(nesting-keys)` to do exactly that.

So I replaced:
```
var filtered = _this.model.color.getFilteredItems();
```
with
```
var filtered = _this.model.color.getNestedItems([KEY]); //getNestedItems(["geo"])
```

And that's it :+1:
