### ISSUE TITLE
BC_17: Checkbox of “check/adaptMinMaxZoom” has not been localized under language PT

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#230]
SEVERITY: Major

MODULE: Bar Chart

OS / BROWSER: Windows 7 / Chrome 45.0
STEPS TO REPRODUCE:
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.5.1/preview/barchart.html
2)	Bar chart page will be loaded
3)	Click on Set Lang: as PT under interaction buttons
4)	Click on Axes menu 
5)	Note that “check/adaptMinMaxZoom” not been localized

ACTUAL RESULTS:
Checkbox of “check/adaptMinMaxZoom” is not localized  

EXPECTED RESULTS: 
Everything should be localized in all menus according to selected language 

SCREENSHOT:
![vizabi_barchart_04](https://cloud.githubusercontent.com/assets/1772649/8673075/176c67c0-2a4d-11e5-9a86-831eb676bb97.png)

**Comment by IncoCode** [comment]
Can't reproduce this issue on `develop` branch.
![_2015-08-07_13-57-50](https://cloud.githubusercontent.com/assets/6574672/9134394/518e94d8-3d0c-11e5-8dc3-ae31e412b101.png)

**Comment by k6Labz** [comment]
@IncoCode 
Please scroll down till axes or check it on Bar chart under axes menu after switching language

**Comment by angieskazka** [comment]
@IncoCode 's pull request above didn't fix, i can still reproduce the issue on develop
"Please check it on Bar chart under axes menu after switching language"

possible reson: barchart doesn't care about this checkbox and doesn't bind it to anything
in fact, this checkbox shouldn't be present in bar chart, but we don't have a pattern yet of how to have different axis dialogs for different tools. Something for @arthurcamara1 to define
