### ISSUE TITLE
BC_19: Only one bar is appeared while all region name are displayed on Y-Axis

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#232]
SEVERITY: Major

MODULE: Bar Chart

OS/BROWSER: Windows 7 / Chrome 45.0
STEPS TO REPRODUCE:
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/develop/preview/fullscreen/Barchart.html 
2)	Bar chart page will be loaded
3)	Click on axes menu 
4)	Select x-axis dropdown as “indicator/_default” 
5)	Select y-axis dropdown as Region or Geo Code
6)	Note that only one bar is appeared while all others region name are appeared on y-axis 

ACTUAL RESULTS:
Only one bar is appeared on x-axis while all other name are displayed on y-axis

EXPECTED RESULTS: 
All bars of region should be appeared as long as their name displayed on axes

SCREENSHOT:
![vizabi_barchart_06](https://cloud.githubusercontent.com/assets/1772649/8697189/7ddb4b06-2b0c-11e5-812a-f91d422464fb.png)

**Comment by IncoCode** [comment]
> All bars of region should be appeared

x-axis contains bars, `indicator/default` it is only one bar. When you change x-axis to `Region` and y-axis to `indicator/default` then there will be 4 bars.

**Comment by k6Labz** [comment]
@IncoCode 
As you instructed in above comment, but issue still remain the same as "Only one bar is appeared" on Y-axis. Retested in "develop" branch, see below screenshot.

![bc_19](https://cloud.githubusercontent.com/assets/9950837/9244034/c78bee08-41b0-11e5-9f47-462f11320839.png)

**Comment by IncoCode** [comment]
Seems like axis dialog doesn't wait for loading data from waffle-server or something. [`this._dataId`](https://github.com/Gapminder/vizabi/blob/eb58d032c6386a4aeb111cb3d46d568dbb5c2a01/src/base/model.js#L945) still contains old request id when user selected new value in indicator picker, after a few moments [`this._dataId`](https://github.com/Gapminder/vizabi/blob/eb58d032c6386a4aeb111cb3d46d568dbb5c2a01/src/base/model.js#L375) got updated, but it's too late. Have no idea how to fix that.

**Comment by angieskazka** [comment]
Guys, @IncoCode 's fix seems be correct but it treats a different problem 
Meanwhile "steps to reproduce" make absolutely no sense and show that we need to just hide impossible options from the list. See #372 for more

**Comment by k6Labz** [comment]
**Retest Result:** Failed

**RELEASE:** v0.7.0

**DESCRIPTION:** This issue is reproduced in another way, can be seen in below screenshot

**SCREENSHOT:**
![regression_06 1](https://cloud.githubusercontent.com/assets/9950837/9439343/7da204c6-4a7f-11e5-98da-d3e5141562e9.png)

![regression_06 2](https://cloud.githubusercontent.com/assets/9950837/9439344/7daac98a-4a7f-11e5-97a8-b08235172c0a.png)

![regression_06 3](https://cloud.githubusercontent.com/assets/9950837/9439345/7dac33c4-4a7f-11e5-9b86-0b57a8568c3e.png)

![regression_06 4](https://cloud.githubusercontent.com/assets/9950837/9439346/7db55e86-4a7f-11e5-9fd9-beb763cf053f.png)

**Comment by IncoCode** [comment]
@k6Labz as you can see from your screenshots `Constant` has only one value in ita domain (`_default`). The same with `Region`, `Region` equals `world` for `America`, `Asia`, `Africa` and `Europe`.

**Comment by angieskazka** [comment]
@k6Labz see the discussion above. "steps to reproduce" make absolutely no sense and show that we need to just hide impossible options from the list. See #372 for more
