### ISSUE TITLE
BC_21: Slider ball is not rolling out on clicking play button

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#234]
SEVERITY: Major

MODULE: Bar Chart

OS/BROWSER: Windows 7 / Chrome 45.0
STEPS TO REPRODUCE:
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.5.1/preview/barchart.html 
2)	Bar chart page will be loaded
3)	Click on axes menu 
4)	Select x-axis drop down as Time
5)	Click on Play 
6)	Note that slider ball will not move farther & Play button below label “interaction button” also converted into Pause 

ACTUAL RESULTS:
Slider ball is not moving farther on clicking the play but at the same time Play converted into Pause in right menu of interaction button   

EXPECTED RESULTS: 
Slider ball should keep moving on clicking the Play 

SCREENSHOT:
![vizabi_barchart_09](https://cloud.githubusercontent.com/assets/1772649/8697289/3c5d5c04-2b0d-11e5-8713-80f3578fd3a8.png)

**Comment by arthurcamara1** [comment]
Actually the opposite is happening now. It never goes to Pause mode on Preview page. I'll take a look

**Comment by arthurcamara1** [comment]
Time shouldn't even be allowed there

**Comment by angieskazka** [comment]
resolved long ago
