### ISSUE TITLE
BC_22: GDP, life expect.., population etc. selected in drop down of X-Axis but it still retain previously selected value

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#235]
SEVERITY: Major

MODULE: Bar Chart

OS/BROWSER: Windows 7 / Chrome 45.0
STEPS TO REPRODUCE:
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.5.1/preview/barchart.html 
2)	Bar chart page will be loaded
3)	Click on Axes menu 
4)	Select either Region or Geo code on x-axis dropdown
5)	These two selected values will get updated under the dropdown 
6)	Now select the values other than two mentioned above i.e. GDP, life expect.., Population  
7)	Note that selected values i.e. GDP, life expect.., Population will not get updated under the drop down

ACTUAL RESULTS:
Selected GDP, Life expect…, Population, etc. in x-axis but these selected values not updated below the drop down

EXPECTED RESULTS: 
Any new value is selected in drop down of x-axis, it should be get updated below the dropdown

SCREENSHOT:
![vizabi_barchart_10](https://cloud.githubusercontent.com/assets/1772649/8697341/a3d3b00e-2b0d-11e5-81c7-e11f9d4172e4.png)

**Comment by maximhristenko** [comment]
@SadiaKualitatem. Now in develop branch there is no values under dropdown list. Is it correct?

**Comment by k6Labz** [comment]
@maximhristenko 

*Retest Result:*
Retested in develop branch & found that values are no more appearing under dropdown list.

**Comment by angieskazka** [comment]
yes
