### ISSUE TITLE
BC_23: In small screen text menu still shown as GO SMALL instead of GO BIG

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#236]
SEVERITY: Major

MODULE: Bubble Chart, Bar Chart

OS/BROWSER: Windows 7 / Chrome 45.0
STEPS TO REPRODUCE:
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.5.1/preview/barchart.html 
2)	Bar chart page will be loaded
3)	Click on GO BIG
4)	Big screen will shown
5)	Click on Exit full screen (Esc) or GO SMALL to return to small screen
6)	Small screen will open
7)	Note that menu still appeared as GO SMALL instead of GO BIG

ACTUAL RESULTS:
Text menu still shown as GO SMALL while already in Small screen

EXPECTED RESULTS: 
There should be text menu of GO BIG instead of GO SMALL as it’s already in Small screen

SCREENSHOT:
![vizabi_barchart_14](https://cloud.githubusercontent.com/assets/1772649/8697382/053bc336-2b0e-11e5-985e-9ad4712b0417.png)

**Comment by angieskazka** [comment]
couldn't reproduce. i believe this was fixed
