### ISSUE TITLE
BC_24: Bars are overlapping with label of X-axis in small screen resolution

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#237]
SEVERITY: Major

MODULE: Bubble Chart

OS/BROWSER: Win7 / Chrome 45.0
STEPS TO REPRODUCE:
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.5.1/preview/barchart.html 
2)	Bar chart page will be loaded
3)	Click on axes menu
4)	Select x-axis dropdown as “Time”
5)	Click on “Random button” of responsiveness to have different size of stated below in actual results
6)	Note Bars are overlap with X-axis selected value 

ACTUAL RESULTS:
Text “Size Population, Colors: Region” is overlapping with coordinates of X-axis for screen size of “346x335”, “469x469”, “1046x646” etc.

EXPECTED RESULTS: 
Bars should not be overlap with X-axis value, irrespective of different screen size 

SCREENSHOT:
![vizabi_barchart_15](https://cloud.githubusercontent.com/assets/1772649/8697455/83a82a98-2b0e-11e5-8b4d-94ce31a802d9.png)

![vizabi_barchart_15b](https://cloud.githubusercontent.com/assets/1772649/8697456/83af6ea2-2b0e-11e5-8a71-04f0094d7dd4.png)

![vizabi_barchart_15c](https://cloud.githubusercontent.com/assets/1772649/8697457/83b6b27a-2b0e-11e5-8c7e-73c37511f0ea.png)

**Comment by gaivoronsky** [comment]
Also this steps reproduces for the next dropdown population, GDP per capita, Life expectancy.

**Comment by k6Labz** [comment]
@gaivoronsky  Yes, also reproducible for population, GDP per capita, Life expectancy etc.But in first comment we made it generic only with "time". :+1:

**Comment by angieskazka** [comment]
this is in fact the same problem as #232 and is now better defined in #372
some things just don't have to be possible to do, like setting "time" x-axis in bar chart

**Comment by k6Labz** [comment]
**Retest Result:** Failed

**RELEASE:** v0.7.0

**DESCRIPTION:** This issue is appeared again, can be seen in below screenshot

**SCREENSHOT:**
![regression_05](https://cloud.githubusercontent.com/assets/9950837/9439138/ae1cd7c2-4a7d-11e5-9d17-a8549a455d5e.png)

**Comment by angieskazka** [comment]
4) Select x-axis dropdown as “Time” -- not allowed any longer
