### ISSUE TITLE
LC_27: Coordinate values of Y-axis are overlapping with each other

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#240]
SEVERITY: Major

MODULE: Line Chart

OS/BROWSER: Windows 7 / Chrome 45.0
STEPS TO REPRODUCE:
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.5.1/preview/linechart.html   
2)	Line Chart page will be loaded
3)	Note that Coordinates values of Y-axis are overlap with each other

ACTUAL RESULTS:
Standard values & actual values of coordinates at Y-axis are overlap with each other for Europe & America 

EXPECTED RESULTS: 
Standard values should be get hidden when hovering for actual value 

SCREENSHOT:
![vizabi_linechart_04](https://cloud.githubusercontent.com/assets/1772649/8697905/a7ad02de-2b12-11e5-9811-cb848a8877aa.png)

![vizabi_linechart_04b](https://cloud.githubusercontent.com/assets/1772649/8697906/a7e79944-2b12-11e5-9fc7-3ae005050ab2.png)

**Comment by IncoCode** [comment]
Can't reproduce this issue on `develop` branch. I think it's already fixed.

**Comment by arthurcamara1** [comment]
@IncoCode In certain resolutions this problem still happens.

Take a look:

<img width="878" alt="screen shot 2015-08-23 at 10 38 29 pm" src="https://cloud.githubusercontent.com/assets/3584238/9430090/bf95d9b8-49e7-11e5-8c08-c7200e6b0898.png">

**Comment by angieskazka** [comment]
there is now more space on the left margin, and all the values fit horizontally
