### ISSUE TITLE
LC_28: Label of X-Axis is missing

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#241]
SEVERITY: Major

MODULE: Line Chart

OS/BROWSER: Windows 7 / Chrome 45.0
STEPS TO REPRODUCE:
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.5.1/preview/linechart.html   
2)	Line Chart page will be loaded
3)	Note that Coordinates values of Y-axis are overlap with each other

ACTUAL RESULTS:
Label of X-Axis is missing as Y-Axis is label as “GDP per capita”

EXPECTED RESULTS: 
Label of X-Axis should be shown as of Y-Axis

SCREENSHOT:
![vizabi_linechart_05](https://cloud.githubusercontent.com/assets/1772649/8697932/dbbff61c-2b12-11e5-9bb7-3f85edaafd8b.png)

**Comment by arthurcamara1** [comment]
Not major and not sure if this chart is supposed to have a "Time" label because the timeslider is synced with axis. @olarosling

**Comment by arthurcamara1** [comment]
Merged, but let's verify
