### ISSUE TITLE
LC_30: Hovering value comes in front of / before the it’s coordinated value of Y-Axis

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#243]
SEVERITY: Minor

MODULE: Line Chart

OS/BROWSER: Windows 7 / Chrome 45.0
STEPS TO REPRODUCE:
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.5.1/preview/linechart.html   
2)	Line Chart page will be loaded
3)	Click the Play 
4)	Hovering the lines much closer to Y-Axis 
5)	Note that hovering values go beyond the graph 

ACTUAL RESULTS:
Hovering value comes before / in front of its exact value at Y-Axis

EXPECTED RESULTS: 
Hovering value should be appeared on a proper location to avoid conflict with its coordinate value

SCREENSHOT:
![vizabi_linechart_07](https://cloud.githubusercontent.com/assets/1772649/8698001/555cee30-2b13-11e5-885b-5c289d1156f4.png)

**Comment by gaivoronsky** [comment]
I think the problem related to #242
