### ISSUE TITLE
LC_31: Slider ball does not synchronized its position with lines of graph

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#244]
SEVERITY: Major

MODULE: Line Chart

OS/BROWSER: Windows 7 / Chrome 45.0
STEPS TO REPRODUCE:
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.5.1/preview/linechart.html   
2)	Line Chart page will be loaded
3)	Click the Play 
4)	Before it stop, click on slide bar starting point i.e. 1990 
5)	Click again on Play 
6)	Note that Slider ball will not move forward but lines keep moving farther 

ACTUAL RESULTS:
Slider ball does not synchronized its position with lines, after dragged slider back to initial point manually

EXPECTED RESULTS: 
Slider ball should move along with lines during play 

SCREENSHOT:
![vizabi_linechart_08](https://cloud.githubusercontent.com/assets/1772649/8698028/8bf76614-2b13-11e5-8263-0dd9c636cca3.png)

**Comment by IncoCode** [comment]
Can't reproduce this issue on `develop` branch.

**Comment by k6Labz** [comment]
@IncoCode 
At this moment line chart can't be loaded in release 0.6. We can retest it, once release 0.7 will be available

**Comment by k6Labz** [comment]
Checked on develop branch, now appeared in another way but "steps to produce" as mentioned in first comment are same. Please see in below screenshot. 

![lc_31](https://cloud.githubusercontent.com/assets/9950837/9247379/0a4376ba-41cc-11e5-9648-a2d2c48e0519.png)

**Comment by angieskazka** [comment]
i guess timeslider animation interrupt() fixed that
