### ISSUE TITLE
GetValues should group first by key then by hook, don't?

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#247]
GetValues should group first by key, then by hook. That would greatly simplify the usage of the result in tools.

Unlike it does now
![image](https://cloud.githubusercontent.com/assets/3648190/8751667/cf64263e-2cae-11e5-8eeb-710945cb0505.png)

**Comment by arthurcamara1** [comment]
I just benchmarked performance.
Simply by inverting, the performance goes down quite a bit for bubble chart:

```javascript
values.axis_x[d[KEY]];
```
Time per frame = 65 - 70 ms

```javascript
values[d[KEY]].axis_x; //better syntax
```
Time per frame = 75 - 82 ms

I'm not sure why yet, but I will investigate this further soon. So let's keep it as it is right now.

**Comment by angieskazka** [comment]
decided not to
