### ISSUE TITLE
MC_32: Slider ball is lagging behind the corresponding year 

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#249]
RELEASE: v0.6.0

SEVERITY: Minor

MODULE: Mountain Chart

OS/BROWSER: Windows 7 / Chrome 45.0
STEPS TO REPRODUCE:
1) Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.6.0/preview/mountainchart.html  
2) Mountain Chart page will be loaded
3) Click on the Play 
6) Note that Slider ball lagging behind the year

ACTUAL RESULTS:
Slider ball is not synch it’s position with corresponding year i.e. 1961

EXPECTED RESULTS: 
Slider ball should keep moving along with year

SCREENSHOT:
![vizabi_mntain_01](https://cloud.githubusercontent.com/assets/1772649/8825432/789886d6-3098-11e5-9dce-52176a9db53d.png)

**Comment by IncoCode** [comment]
Fixed in #271.
