### ISSUE TITLE
MC_33: Year is lagging behind its corresponding position with Slider ball

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#250]
RELEASE: v0.6.0

SEVERITY: Minor

MODULE: Mountain Chart

OS/BROWSER: Windows 7 / Chrome 45.0
STEPS TO REPRODUCE:
1) Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.6.0/preview/mountainchart.html  
2) Mountain Chart page will be loaded
3) Click on the Play 
6) Note that Before it stop, year is lag its position with slider ball

ACTUAL RESULTS:
Year is lagging behind its position with slider ball at the of slide bar

EXPECTED RESULTS: 
Year should keep track its exact position with slider ball

SCREENSHOT:
![vizabi_mntain_02](https://cloud.githubusercontent.com/assets/1772649/8825465/c7c21c72-3098-11e5-95a1-114081955b99.png)

**Comment by IncoCode** [comment]
Fixed in #271.
