### ISSUE TITLE
MC_35: Coordinate values of x-axis are truncated from below 

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#252]
RELEASE: v0.6.0

SEVERITY: Minor

MODULE: Mountain Chart

OS/BROWSER: Windows 7 / Chrome 45.0
STEPS TO REPRODUCE:
1) Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.6.0/preview/mountainchart.html  
2) Mountain Chart page will be loaded
3) Click on Full under label Responsiveness 
6) Note that x-axis values are truncated from below side

ACTUAL RESULTS: 
X-axis coordinate’s values are truncated from below, when click on “full” below to Responsiveness label

EXPECTED RESULTS:
Coordinates values of x-axis should not be truncated under different screen resolutions 

SCREENSHOT:
![vizabi_mntain_05](https://cloud.githubusercontent.com/assets/1772649/8825542/67007d6a-3099-11e5-8fd5-089d1924faed.png)

**Comment by arthurcamara1** [comment]
@k6Labz Please double check and close issue if solved.

**Comment by IncoCode** [comment]
Can't reproduce this issue on `develop` branch.

**Comment by k6Labz** [comment]
@IncoCode 
At this moment, not able to load Mountain chart in release 0.6 as tried many times. we can retest it, once release 0.7 will be available.

**Comment by k6Labz** [comment]
Might be fixed, can't be reproducible also on my side as checked on develop branch

**Comment by angieskazka** [comment]
yes, it was fixed
