### ISSUE TITLE
MC_36: Slider ball is slightly cut off from right side

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#253]
RELEASE: v0.6.0

SEVERITY: Minor

MODULE: Mountain Chart

OS/BROWSER: Windows 7 / Chrome 45.0
STEPS TO REPRODUCE:
1) Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.6.0/preview/mountainchart.html  
2) Mountain Chart page will be loaded
3) Click on Full under label Responsiveness 
6) Note that slider ball is truncated from right side

ACTUAL RESULTS: 
slider ball is truncated from right side

EXPECTED RESULTS:
Slider ball should be appear in in complete spherical shape

SCREENSHOT:
![vizabi_mntain_06](https://cloud.githubusercontent.com/assets/1772649/8825656/29db6426-309a-11e5-8d79-a4c8e80cc8ad.png)

**Comment by IncoCode** [comment]
Can't reproduce this issue on `develop` branch.

**Comment by k6Labz** [comment]
@IncoCode 
At this moment, not able to load Mountain chart in release 0.6 as tried many times. we can retest it, once release 0.7 will be available.

**Comment by k6Labz** [comment]
Might be fixed, can't be reproducible also on my side as checked on develop branch
