### ISSUE TITLE
MC_37: Last digit in stated value of x-axis is truncated from right side

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#254]
RELEASE: v0.6.0

SEVERITY: Minor

MODULE: Mountain Chart

OS/BROWSER: Windows 7 / Chrome 45.0
STEPS TO REPRODUCE:
1) Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.6.0/preview/mountainchart.html  
2) Mountain Chart page will be loaded
3) Click on Full under label Responsiveness Or click on Landscape view 
5) Note that last digit is slightly cut off from right side

ACTUAL RESULTS: 
Last digit of x-axis marked is slightly cut off from right side 

EXPECTED RESULTS: 
Maximum value marked on x-axis scale should be visible completely   

SCREENSHOT:
![vizabi_mntain_07](https://cloud.githubusercontent.com/assets/1772649/8825687/61223c34-309a-11e5-881e-31ac6ed334dd.png)

![vizabi_mntain_07b](https://cloud.githubusercontent.com/assets/1772649/8825688/61234a0c-309a-11e5-86de-b7b6c3c5a639.png)

**Comment by gaivoronsky** [comment]
Can't reproduce on development branch Mac OS X 10.10 / Chromium 46.0

**Comment by k6Labz** [comment]
@gaivoronsky 
At this moment I'm not able to load Mountain chart in release 0.6 as tried many times. we can retest it, once release 0.7 will be available.

**Comment by k6Labz** [comment]
Might be fixed, can't be reproducible also on my side as checked on develop branch

**Comment by angieskazka** [comment]
yes, it was fixed
