### ISSUE TITLE
MC_39: Mountains of chart are truncate from top of the page

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#258]
RELEASE: v0.6.0

SEVERITY: Major

MODULE: Mountain Chart

OS/BROWSER: Windows 7 / Chrome 45.0

STEPS TO REPRODUCE:
1) Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.6.0/preview/mountainchart.html  
2) Mountain Chart page will be loaded
3) Click on Switch Language under Interaction button
4) Click on Full, Landscape, Portrait view or different random screen resolution under label Responsiveness
5) Note that Mountains of chart are truncate from top 

ACTUAL RESULTS: 
Mountains of chart are truncate from top, while in Landscape, portrait, full & different random screen resolutions under RESPONSIVENESS

EXPECTED RESULTS: 
Mountains of chart should be fit inside the chart defined area, irrespective selected language

![image](https://cloud.githubusercontent.com/assets/9950837/8857483/86374f54-318b-11e5-855e-738a6e2229eb.png)

**Comment by gaivoronsky** [comment]
Can't reproduce this on development branch

**Comment by k6Labz** [comment]
@gaivoronsky 
At this moment I'm not able to load Mountain chart in release 0.6 as tried many times. we can retest it, once release 0.7 will be available.

**Comment by k6Labz** [comment]
Might be fixed, can't be reproducible also on my side as checked on develop branch
