### ISSUE TITLE
MC_41: No distinction between sub labels & their values 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#260]
RELEASE: v0.6.0

SEVERITY: Minor

MODULE: Mountain Chart

OS/BROWSER: Windows 7 / Chrome 45.0

STEPS TO REPRODUCE:
1) Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.6.0/preview/mountainchart.html  
2) Mountain Chart page will be loaded
3) Click on Axes	                                                                                    					   
4) Note that sub labels & their values are not differentiated form each other’s

ACTUAL RESULTS: 
There’s no difference between sub labels & their respective values in axes  

EXPECTED RESULTS: 
Sub labels should also be formatted in another color like main label of Axes

SCREENSHOT:
![image](https://cloud.githubusercontent.com/assets/9950837/8857057/64e19bd2-3188-11e5-8c93-dbeb27988b9a.png)

**Comment by arthurcamara1** [comment]
@k6Labz  I don't quite get what the problem here is

**Comment by k6Labz** [comment]
@arthurcamara1 

Category: User Interface
labels of sub heading like "Maximum Y value", "X-axis logarithmic stops" & "X-axis limits" should be prominent like main heading of "Axes".
