### ISSUE TITLE
MC_42: Mountain chart disappears in full screen page

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#261]
RELEASE: v0.6.0

SEVERITY: Blocker

MODULE: Mountain Chart

OS/BROWSER: Windows 7 / Chrome 45.0

STEPS TO REPRODUCE:
1) Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.6.0/preview/mountainchart.html  
2) Mountain Chart page will be loaded
3) Click on Full screen page from right side menu                                                                                                   4) Full screen will be open in new Tab 		   
5) Note that Mountain are not appearing in full screen page

ACTUAL RESULTS: 
Mountains of chart are not appeared in full screen page

EXPECTED RESULTS: 
Mountain of chart should be made visible on full screen page

SCREENSHOT:
 
![image](https://cloud.githubusercontent.com/assets/9950837/8857141/ff5322c6-3188-11e5-804b-d9451683bb64.png)

**Comment by maximhristenko** [comment]
this done https://github.com/Gapminder/vizabi/pull/286

**Comment by angieskazka** [comment]
should be fixed now

**Comment by k6Labz** [comment]
**Retest Result:** Failed

**RELEASE:** v0.7.0

**DESCRIPTION:** This issue is appeared again, can be seen in below screenshot

**SCREENSHOT:**
![regression_03](https://cloud.githubusercontent.com/assets/9950837/9438740/173f64da-4a7a-11e5-97b4-a96c100b6fd8.png)

**Comment by angieskazka** [comment]
fixed now
