### ISSUE TITLE
MC_43: Menu’s label appeared as GO BIG instead of GO SMALL 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#262]
RELEASE: v0.6.0

SEVERITY: Major

MODULE: Mountain Chart

OS/BROWSER: Windows 7 / Chrome 45.0

STEPS TO REPRODUCE:
1) Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.6.0/preview/mountainchart.html  
2) Mountain Chart page will be loaded
3) Click on Full screen page from right side menu                                                                                                   4) Full screen will be open in new Tab 	                                                 				                
5) Note that label of menu is appeared as GO BIG  

ACTUAL RESULTS: 
Menu’s label appeared as GO BIG instead of GO SMALL in Full screen page

EXPECTED RESULTS: 
Label of Menu should be appeared as GO SMALL to go back to small screen as it’s already in full screen page
SCREENSHOT:
![image](https://cloud.githubusercontent.com/assets/9950837/8857251/d91d888e-3189-11e5-9e0e-1a9755507a63.png)

**Comment by maximhristenko** [comment]
@k6Labz , For now when user click on "Fullscreen page" button it's open new tab in "Full page" mode. After user click on "GO BIG" it's open this page in Fullscreen mode. And after click "GO SMALL" page return to "Full page" mode. "Full page" and "Fullscreen page" it's different modes. Maybe you whant that when user click on "Fullscreen page" button it's open new tab at "Fullscreen page" mode with button "GO SMALL" that will open this page at "Full page" mode ?

**Comment by k6Labz** [comment]
Thanks @maximhristenko , you gave very good explanation of different modes. Here is what I got, there are two pages 
1) .../preview/mountainchart.html
2) .../preview/fullscreen/mountainchart.html

first one is normal mode with various options in left and right columns. GO BIG take you to full-screen (without left & right columns and without browser's frames)
second is full-page, no left & right options, only chart with browser frames. GO BIG takes you to full-screen (without browser frames)
GO BIG mode of both pages give same view. 

Now let us assume you are on full-page mode, you will see GO BIG as shown in screenshot. What I do there is press F11, that takes you to GO BIG. Since you have not clicked on GO BIG, the label remain GO BIG. 

![gobig-f11](https://cloud.githubusercontent.com/assets/9950837/8879684/6761e96a-324c-11e5-8895-72f4a007cff1.png)

**Comment by IncoCode** [comment]
This is different modes. When you press `F11` you browser goes into fullscreen (hiding all elements other than the main browser window itself). When you press `Go big` button it's expand chart element into fullscreen (like player on youtube).
`F11` don't fire `fullscreenchange` event, so the only way to determine if the user pressed `F11` button it's add event listener on `keydown`. But I think it's a not good idea, because shortcuts can be changed by user.

**Comment by angieskazka** [comment]
yes, they are different modes. the user will never be exposed to "Fullscreen page" button, this is just something for us to test the layouts. "Go big" button will be the only way to fullscreen

i'm closing this because it's such a minor issue
