### ISSUE TITLE
MC_44: Mountains go beyond the chart area if kept max limit of x-axis at minimum number 

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#263]
RELEASE: v0.6.0

SEVERITY: Major

MODULE: Mountain Chart

OS/BROWSER: Windows 7 / Chrome 45.0
STEPS TO REPRODUCE:
1) Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.6.0/preview/mountainchart.html  
2) Mountain Chart page will be loaded
3) Click on axes						                                                                                                 4) Fill any minimum value i.e. 10, 15 etc. in “Max” text filed of X-axis limits                                                    
5) Note that label of menu is appeared as GO BIG  

ACTUAL RESULTS: 
Mountains of chart is not giving their values for countries that have values greater than kept in max limit of x-axis

EXPECTED RESULTS: 
There’s should be some validation check i.e. max value should be at least at 50-100 as all countries value fall in this range 

SCREENSHOT:
![vizabi_mntain_16](https://cloud.githubusercontent.com/assets/1772649/8875516/30f3f63e-3233-11e5-9058-06e439dfae88.png)

![vizabi_mntain_16b](https://cloud.githubusercontent.com/assets/1772649/8875522/3c18a3c0-3233-11e5-8211-c94f9611f44b.png)

**Comment by IncoCode** [comment]
> i.e. max value should be at least at 50-100 as all countries value fall in this range

But if user wants to see only those countries, where salary is in range 1-10 and etc?

**Comment by arthurcamara1** [comment]
Agreed with @IncoCode. It should allow min and max to be anything, even if not all countries are included.
