### ISSUE TITLE
MC_45: Slide ball moving on with more distance instead of passing through consecutive years

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#264]
RELEASE: v0.6.0

SEVERITY: Major

MODULE: Mountain Chart

OS/BROWSER: Windows 7 / Chrome 45.0
STEPS TO REPRODUCE:
1) Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.6.0/preview/mountainchart.html  
2) Mountain Chart page will be loaded
3) Click on axes						                                                                                                 4) Check the checkbox of 5 under label’s x-axis logarithmic stop 					                   
5) Click on Play  
6) Note that slider ball is moving at more distance on slide bar

ACTUAL RESULTS: 
Slider ball is moving at more distance than moving through each year one by one

EXPECTED RESULTS: 
slider ball should be moves farther by touching each year 

SCREENSHOT:
![vizabi_mntain_17](https://cloud.githubusercontent.com/assets/1772649/8875575/ae76f69c-3233-11e5-817a-3f49270fd823.png)

**Comment by IncoCode** [comment]
Can't reproduce this issue on `develop` branch.

**Comment by arthurcamara1** [comment]
It's moving more than one year for any log value here, so it might be a performance issue related to #385

**Comment by angieskazka** [comment]
could not reproduce, it looks like it's related to performance which was apparent when i had 200 points and 200 mountains. please reopen if you encounter it again
