### ISSUE TITLE
PA_47: Multi selection of the lines bar is not allowed

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#266]
RELEASE: v0.6.0

SEVERITY: Medium

MODULE: Pop By Age Chart

OS/BROWSER: Win7 / Chrome 45.0
STEPS TO REPRODUCE:
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.6.0/preview/popbyage.html 
2)	Pop By Age chart page will be loaded
3)	Select an age bar from the chart.
4)	Select another age bar from the chart.
5)	Notice that second line will not be selected

ACTUAL RESULTS:
More than one age line bar cannot be selected. User can select only one age bar. 

EXPECTED RESULTS: 
More than one age bar should be selected so that user can easily compare among many age changes according to years.

SCREENSHOT: 
![vizabi_pop_by_age_chart_02](https://cloud.githubusercontent.com/assets/1772649/8875891/98280be0-3235-11e5-8748-0d103f0909b5.png)

**Comment by arthurcamara1** [comment]
Not sure if this is expected behavior.
@olarosling: should we be able to select multiple or one? Leaving it as multiple for now and consider it fixed.
