### ISSUE TITLE
PA_48: Label of “GO SMALL” button is truncated from right side.

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#267]
RELEASE: v0.6.0

SEVERITY: Minor

MODULE: Pop By Age Chart

OS/BROWSER: Win7 / Chrome 45.0
STEPS TO REPRODUCE:
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.6.0/preview/popbyage.html 
2)	Pop By Age chart page will be loaded
3)	Click on the “GO BIG” button available on the chart with the “COLORS” button.

ACTUAL RESULTS:
GO SMALL’s label is truncated from right side in full screen

EXPECTED RESULTS: 
Labels should not be truncated from any side. They should properly show to the user.

SCREENSHOT: 
![vizabi_pop_by_age_chart_03](https://cloud.githubusercontent.com/assets/1772649/8875935/d06c720c-3235-11e5-980b-f2cc4eb7a496.png)

**Comment by IncoCode** [comment]
Fixed in #288 + #294.

**Comment by k6Labz** [comment]
**Retest Result:** Failed

**RELEASE:** v0.7.0

**DESCRIPTION:** This issue is appeared again, can be seen in below screenshot

**SCREENSHOT:**
![regression_07](https://cloud.githubusercontent.com/assets/9950837/9439410/183f3c7e-4a80-11e5-8d80-dd9b3558f64b.png)

**Comment by angieskazka** [comment]
i tested on mac and windows and found that it's good now
both on develop and on tools page live

![image](https://cloud.githubusercontent.com/assets/3648190/10128747/c884367e-65b6-11e5-9059-2bdbf0b8bbee.png)

![image](https://cloud.githubusercontent.com/assets/3648190/10128754/e30f0938-65b6-11e5-9595-6432c89f242d.png)
