### ISSUE TITLE
PA_49: Some bar lines are of irregular sizes than others 

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#268]
RELEASE: v0.6.0

SEVERITY: Minor

MODULE: Pop By Age Chart

OS/BROWSER: Win7 / Chrome 45.0
STEPS TO REPRODUCE:
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.6.0/preview/popbyage.html
2)	Pop By Age chart page will be loaded
3)	Select bar line of any age given on the chart.
4)	Selected line is highlighted.
5)	Notice the line distribution.

ACTUAL RESULTS:
Some bar lines are not of same size as others 

EXPECTED RESULTS: 
All bar lines should be of same size

SCREENSHOT:
![vizabi_pop_by_age_chart_04](https://cloud.githubusercontent.com/assets/1772649/8875983/1b622928-3236-11e5-9be1-05e221d0082f.png)

**Comment by arthurcamara1** [comment]
Aha, they are all the same size, but I think there's some problem with the border. Will check it out

**Comment by angieskazka** [comment]
you have to check it on OS/BROWSER: Win7 / Chrome 45.0 and the same screen resolution and size. Our retina displays tend to show vector things better than they really are (and opposite with raster by the way)

**Comment by jheeffer** [comment]
Probably closed in 20cf40681140911328bd152344035d46292156fc as drawing of bars was completely redone
