### ISSUE TITLE
PA_51: Spelling mistake on the description of the age bar

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#270]
RELEASE: v0.6.0

SEVERITY: Minor

MODULE: Pop By Age Chart

OS/BROWSER: Win7 / Chrome 45.0
STEPS TO REPRODUCE:
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.6.0/preview/popbyage.html
2)	Pop By Age chart page will be loaded
3)	Move the cursor on any line bar on the chart.
4)	Due to hover effect, the description is shown to the user.
5)	Notice that spelling appear as Olds instead of Old

ACTUAL RESULTS:
On hovering the line bar spelling mistakes are there. “year olds” is written in the description 

EXPECTED RESULTS:  
The description of the age bar on the chart should be correct. There should be written “years-old” instead of “year-olds”.

SCREENSHOT:
![vizabi_pop_by_age_chart_06](https://cloud.githubusercontent.com/assets/1772649/8876034/7da8701a-3236-11e5-902f-93c9492e735e.png)

**Comment by arthurcamara1** [comment]
It's correct. People who are 50 years old can be called 50-year-olds. Something like this: https://www.google.se/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#safe=off&q=%2220-year-olds%22
