### ISSUE TITLE
PA_52: By clicking on the slide bar, slider ball is moving one year ahead from the selected year

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#272]
SEVERITY: Medium

MODULE: Pop By Age Chart

OS/BROWSER: Win7 / Chrome 45.0
STEPS TO REPRODUCE:
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.6.0/preview/popbyage.html
2)	Pop By Age chart page will be loaded
3)	Click & hold on the slider ball to select a specific year
4)	Release the slider ball
5)	Notice that slider ball moved one year ahead from the selected year.

ACTUAL RESULTS:
By clicking on the slide bar, slider ball is moving one year ahead from the selected year.

EXPECTED RESULTS:  
Same year should be selected on the chart, which is selected by the user

SCREENSHOT:
![vizabi_pop_by_age_chart_07 1](https://cloud.githubusercontent.com/assets/1772649/8905854/3c34a5fa-3483-11e5-9138-cef6f06b58c5.png)

![vizabi_pop_by_age_chart_07 2](https://cloud.githubusercontent.com/assets/1772649/8905855/3c3f780e-3483-11e5-85b1-07e6d0b93cce.png)

**Comment by IncoCode** [comment]
Fixed in #300.
