### ISSUE TITLE
PA_53: Y-axis scale is starting from 1 instead of zero

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#273]
**SEVERITY:** Medium

**MODULE:** Pop By Age Chart

**OS/BROWSER:** Win7 / Chrome 45.0
**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.6.0/preview/popbyage.html 
2)	Pop By Age chart page will be loaded
3)	Click on full screen button for more visibility.
4)	Click on line bar at 100 years old in 1950.
5)	Note that the marking of the age line bar for 100 years is one step ahead of 100 years.

**ACTUAL RESULTS:**
Marking of age line bars on Y-axis is starting from 1 at the origin, which causes an age line bar moving ahead from the marked numbers on Y-axis.

**EXPECTED RESULTS:**  
Marking of age line bar on Y-axis should be started from 0. It will show the population from 0 to 1 year old

**SCREENSHOT:**
![vizabi_pop_by_age_chart_09](https://cloud.githubusercontent.com/assets/1772649/8905954/d3ddcaa8-3483-11e5-8278-0037f2bc3daf.png)

**Comment by arthurcamara1** [comment]
So basically a margin was added. Works for now :+1:
