### ISSUE TITLE
PA_55:  Population for 100 years old in USA is 0 since 2011. The data is wrong

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#275]
**SEVERITY:** Minor

**MODULE:** Pop By Age Chart

**OS/BROWSER:** Win7 / Chrome 45.0
**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.6.0/preview/popbyage.html 
2)	Pop By Age chart page will be loaded
3)	Select the age line bar for 100 years old
4)	Click on play button.
5)	Notice the total population for 100 years old in 2010
6)	Notice the total population for 100 years old in 2011-14
7)	There is apparent change in population from 2010 to 2011-14 for 100 years old.

**ACTUAL RESULTS:**
Population is apparently changing from 13790 to 0 for 100 years old in 2010 to 2011-14.

**EXPECTED RESULTS:**  
There should not be any sudden or apparent change in the chart that creates ambiguity or confusion.

**SCREENSHOT:**
![vizabi_pop_by_age_chart_11 1](https://cloud.githubusercontent.com/assets/9950837/8906291/d7868840-3486-11e5-805c-40603ae5eac7.png)

![vizabi_pop_by_age_chart_11 2](https://cloud.githubusercontent.com/assets/9950837/8906292/d78fcfcc-3486-11e5-8792-715da0e70491.png)

**Comment by maximhristenko** [comment]
@k6Labz  This is not functional issue.  The data which is needed to build graph, is taken from the csv file. In our csv file the data about quantity of 100-years old people from 2011 to 2014 equals "0". To fix this issue, we need to change this data at csv file.

**Comment by angieskazka** [comment]
i checked the data CSV and i can confirm that it's wrong. Population at 99 year old grows while population at 100 is 0 since 2011 and onwards. Let's keep the issue as fixing the data
