### ISSUE TITLE
PA_57: Irrelevant entries are appeared in colors first dropdown 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#277]
**SEVERITY:** Medium

**MODULE:** Pop By Age Chart

**OS/BROWSER:** Win7 / Chrome 45.0
**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.6.0/preview/popbyage.html 
2)	Pop By Age chart page will be loaded
3)	Click on the COLORS button
4)	Click on the first drop down 
5)	Notice the given entries

**ACTUAL RESULTS:**
Non relevant entries are there in the first dropdown option, which is available after clicking the COLORS option.

**EXPECTED RESULTS:** 
Only relevant entries should be there. Irrelevant entries should be eliminated. Like time is not related with this chart.

**SCREENSHOT:** 
![vizabi_pop_by_age_chart_13](https://cloud.githubusercontent.com/assets/9950837/8906356/724f885e-3487-11e5-8f67-52e667cfd7e6.png)

**Comment by angieskazka** [comment]
It's a special case of a bigger issue #372. Requires not a quick fix, but a substantial changes of how we deal with metadata

**Comment by angieskazka** [comment]
closing because of the above
