### ISSUE TITLE
PA_61: Wrong marking of year 1950 on slide bar.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#281]
**SEVERITY:** Minor

**MODULE:** Pop By Age Chart

**OS/BROWSER:** Win7 / Chrome 45.0
**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.6.0/preview/popbyage.html 
2)	Pop By Age chart page will be loaded
3)	Click on play button.
4)	Slider ball will be moving till the end
5)	Click play button again 
6)	Notice that the year 1950 is showing at the last of the slide bar while the slider ball is at the start position.

**ACTUAL RESULTS:**
The year 1950 is showing at the end of the slide bar while the slide ball is at the start position.

**EXPECTED RESULTS:**
The marking of the years should be proper according to their place. 

**SCREENSHOT:** 
![vizabi_pop_by_age_chart_19](https://cloud.githubusercontent.com/assets/9950837/8931264/500bcb32-354e-11e5-9144-57dd910858b5.png)

**Comment by gaivoronsky** [comment]
Can't reproduce this issue on develop branch.

**Comment by k6Labz** [comment]
@gaivoronsky 
We have tested it in release 0.6.0 & still it can be reproduce as mentioned in above steps to reproduce.
We will retest it, when it will be fixed in release *0.7* & available for testing.

**Comment by k6Labz** [comment]
Might be fixed, can't be reproducible also on my side as checked on develop branch

**Comment by arthurcamara1** [comment]
Apparently fixed
