### ISSUE TITLE
PA_62: By clicking switch language, some labels are not localized.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#282]
**SEVERITY:** Critical

**MODULE:** All Charts

**OS/BROWSER:** Win7 / Chrome 45.0
**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.6.0/preview/popbyage.html 
2)	Pop By Age chart page will be loaded
3)	Click the switch language button.
4)	Notice that the right and left panels are not localized.

**ACTUAL RESULTS:**
After clicking the switch language button, some of the labels on left, right panels are not localized 

**EXPECTED RESULTS:**
The language of the whole page should be switched after clicking the switch button.

**SCREENSHOT:** 
![vizabi_pop_by_age_chart_20](https://cloud.githubusercontent.com/assets/9950837/8931301/ac38e246-354e-11e5-8394-38d567fd65ff.png)

**Comment by angieskazka** [comment]
not agree they shoud, as this preview page is only for us to develop and is not part of the product

**Comment by arthurcamara1** [comment]
true, those *don't* have to be localized. I just merged a pull request for this, but I'll undo it.
