### ISSUE TITLE
pop by age is down

### ISSUE THREAD

**Issue by ambodi** [Gapminder/vizabi#308]
Browsers/Platform/Versions: all

Here's the log error:

```Failed to load resource: the server responded with a status of 403 (Forbidden)
vizabi.js:602 No permissions or empty file: /local_data/csv/usa.csv```

**Comment by angieskazka** [comment]
Fixed by moving usa.csv to a different folder. I have no idea why just /local_data/csv/ would return "403 Forbidden" when accessed. something for later thoughts

thanks @ambodi
