### ISSUE TITLE
Control over calling update() method

### ISSUE THREAD

**Issue by amytych** [Gapminder/vizabi#31]
I noticed that `update()` function is called by component.js, upon initialization, here:
https://github.com/Gapminder/vizabi/blob/9c516c2767f49a1cc887be785489a71903bd7efd/src/base/component.js#L301

It's not desired in my case, as I have to load additional data (topoJSON file with districts or the whole world if google maps is not defined), before I can update my tool.

Now I handled it by checking in the `update()` function, if my additional data has loaded. But I feel it's a hack and it would be better if I'd just call the method myself when I know it's ready to be called.

Or maybe there is another, different approach to such scenario?

**Comment by arthurcamara1** [comment]
External data can be loaded independently in the validation method after 13d644236c654a241533ffe7b27dd7ecaaeb34ac

See example here: https://github.com/Gapminder/vizabi/blob/develop/src/tools/_examples-data-loading/data-loading-1-file/data-loading-1-file.js#L43

It's similar to what Ola described in the previous comment, you register a process and remove it when it's done and the `modelReady` method or `ready` event will not be called until there's no pending processes to be loaded.
