### ISSUE TITLE
Allow more zoom out

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#315]
I'd like to zoom out so far that the whole China bubble(largest bubble) fits within the axis's.
![image](https://cloud.githubusercontent.com/assets/496398/9087958/fc272278-3b8d-11e5-91ce-3a585e33a34d.png)

Zoom in and out, should correspond to the same absolute min & max changes: zoom speed. (I think )
So to zoom out further, estimate zoomSpeed-pixels (say 40 pixels) and revers the scale to calculate what it means in terms of the current scale,.... what max-value is 40 pixels out from the current axis-max? 

Another solution that works is : 
Surround the whole chart with a "gutter" a white border of the half width of bubble-max: It appears to be part of the chart but it isn't. (light yellow surface in this image. )
You also extend the axises close to origo, and outside the end of the actual scale: pink axis extension in image. 
![image](https://cloud.githubusercontent.com/assets/496398/9826337/a6213da0-58d9-11e5-8b27-2cddf15b4d21.png)

**Comment by angieskazka** [comment]
the SCALE BUMP (the gutter) was introduced in 0.8.2 =)
