### ISSUE TITLE
Change X-axis in barchart

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#319]
At the moment the Axis setting allow changing the x-axis with a drop down but the change have no influence on the chart. Remove the x-axis-dropdowns from the axis-picker in barchart,... (we can keep the option in the settingspanel, but not enable it until it has some effect on the chart)
![image](https://cloud.githubusercontent.com/assets/496398/9096069/37538396-3bbb-11e5-8262-57600942dc4c.png)

**Comment by maximhristenko** [comment]
@olarosling , please write steps to introduce this problem

**Comment by IncoCode** [comment]
As I understand from the code, x-axis of BarChart should supports only ordinal axes.
Updated my pr #336 (in this pr was added ability to configure dialogs), now x-axis dropdown of BarChart should display right (ordinal) values.

**Comment by angieskazka** [comment]
not sure if i understand the problem. but we now only allow 'properties' on bar chart x axis
