### ISSUE TITLE
parameteric update()

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#32]
In every component we need to `update()` different things depending on which model is updated. 

For instanse, in simple bubble chart: if only timeslider is shifted, then i just need to update the positions of the bubbles only. But if the data is changed, i need to recompute limits, update scales, redraw axes and positions of bubbles. Right now i have to do all of this in any case and it is redundant. 

Suggestion: send the parameter `update(what)`
what can be an array of updated models for example

**Comment by arthurcamara1** [comment]
Closed by 13d644236c654a241533ffe7b27dd7ecaaeb34ac

`modelReady` is executed whenever `ready` or `change` events occur and it receives one argument, which is "what changed".

You may also want to use `this.model_binds` in the `init` function. See here: https://github.com/Gapminder/vizabi/blob/develop/src/components/_examples/bubble-chart/bubble-chart.js#L36
