### ISSUE TITLE
Pinnable dialogs made the checkboxes and radiobuttons go bananas

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#328]
Test stacking controls in mountain chart or follow zoom checkbox in bubble chart. They've stopped working or actually they work in a very strange way: one control is setting the value of another. 

This happened in the latest merging with pull requests, and i don't know how to un-merge now (source tree returns error when i try to reverse commits)

need help

**Comment by IncoCode** [comment]
`git bisect` says that the problem in this commit: https://github.com/Gapminder/vizabi/commit/24654d92ec9b4185c66f5fcf23348fcaf2a4b9f5 (#307)

**Comment by angieskazka** [comment]
thanks @IncoCode, it's exactly that commit broke the check boxes and radio buttons, i tested that one and the one before

@maximhristenko can you please fix it?

**Comment by maximhristenko** [comment]
Ok, i will try to fix this problem

**Comment by angieskazka** [comment]
thank you. looks fixed for now
