### ISSUE TITLE
State restoration from the URL not working

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#338]
open any chart, change state, refresh. state is being reset to default

**Comment by IncoCode** [comment]
Fix here: #335

**Comment by arthurcamara1** [comment]
I don't think that alone solves the issue @IncoCode, but I merged it. I'll fix it

**Comment by IncoCode** [comment]
@arthurcamara1 it solves this issue, you can test it.
The url parsing feature was broken by this commit https://github.com/Gapminder/vizabi/commit/22fce6f5d39c92a541c51095c715795f16151b63 .

**Comment by angieskazka** [comment]
i think it's solved now, right?
