### ISSUE TITLE
Bubble Min-size setting

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#341]
![image](https://cloud.githubusercontent.com/assets/496398/9274088/d4cc643e-4292-11e5-95de-6d491e092bf4.png)
Enable setting Min Size with a similar slider (Require it to be smaller than max size),
minimum one pixel
When sliding min-size up:  reaching the max-size, the max-size-slider should adjust
When sliding max-size down: it eventually hits the min-size-slider should adjust down too.

**Comment by arthurcamara1** [comment]
Still needs improvements, a single slider similar to GW would probably make more sense here. But it's possible to control now.
