### ISSUE TITLE
Y-axis max total, is too low

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#346]
When choosing y-axis max total, we don't use the full screen height in the year when the stacked shapes are the highets. But we should..
![image](https://cloud.githubusercontent.com/assets/496398/9283327/36665476-42d3-11e5-8c11-028dd26a8a7a.png)

**Comment by IncoCode** [comment]
Maybe this is feature? In this case the max value of y-axis = population of all world and the data are displayed relatively to the world's population.

**Comment by angieskazka** [comment]
this was an experimental feature which assumed that yMax should be the sum of all mountain heights when mountains are centred. i needed it earlier to play around with data and shape manipulations. We don't actually need "total" in the product, so it's removed now
