### ISSUE TITLE
Not-stacked Depth order by height

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#347]
When not stacked, the highest shapes should go in the back. In this example: The yellow shape should be the front most http://bit.ly/1MsFVL9
![image](https://cloud.githubusercontent.com/assets/496398/9295971/4d0d2818-4480-11e5-915c-a690fe566958.png)

**Comment by maximhristenko** [comment]
@olarosling on develop branch this issue can not be reproduced
 http://static.gapminderdev.org/vizabi/develop/preview/mountainchart.html#_width:1600&height:549&fullscreen:false&bodyC:null&resp-sect:true&info-sect:true&butt-sect:true&other-sect:false&state_time_dim=time&value=1998&start=1960&end=2000&playable:true&playing:false&loop:false&round=floor&speed:100&unit=year&step:1&adaptMinMaxZoom:false&formatInput=%25Y&xLogStops@:1&:2&:5;&yMaxMethod=total&record:false&formatOutput=%25Y;&entities_show_geo@=*;&geo.cat@=country;;&select@;&brush@;&opacitySelectDim:0.3&opacityRegular:0.6&needUpdate_;&dim=geo;&marker_space@=entities&=time;&label_use=property&which=geo.name;&axis/_y_use=indicator&unit=&which=pop&min:null&max:null&scaleType=linear;&axis/_x_use=indicator&unit=gdp/_per/_cap/_daily&which=gdp/_per/_cap&min:0.05&max:10000&scaleType=log;&size_use=indicator&unit=&which=gini&scaleType=linear;&color_use=property&unit=&palette_asi=#FF5872&eur=#FFE700&ame=#7FEB00&afr=#00D5E9&/_default=#ffb600;&which=geo.region&scaleType=ordinal;&stack_use=value&which=none&merge:false;&group_use=property&which=geo.region&merge:true

**Comment by IncoCode** [comment]
As I understand, the problem in `feature/svgexport` branch.
This problem appears when using [`mountains-pop-gdp-gini-1800-2030.csv`](https://github.com/Gapminder/vizabi/blob/6d2ddcc3228732560f4793a3f625e57f1bf5b20c/local_data/waffles/en/mountains-pop-gdp-gini-1800-2030.csv) as data source (this file was added in 6d2ddcc3228732560f4793a3f625e57f1bf5b20c). Maybe problem in data?
