### ISSUE TITLE
Allow any hardcoded min & max in the state

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#354]
I can actually fiddle with y-axis min & max, to "flip" the y-axis and have the lower range as min, and the higher range as max.
http://bit.ly/1frAv62

I successfully edited the state and set min = 333 and max = 5
![image](https://cloud.githubusercontent.com/assets/496398/9383896/bb2cc3fc-474c-11e5-8d73-fa7bc7e53f1d.png)

But I wanted to use a different range, but then some automatic feature kicks in: I want ot be able to set min=550 & max= 0.1
But when setting the edited state with those min & max, they get overwritten by other values! Please don't.

**Comment by arthurcamara1** [comment]
Fixed. [Example here](http://static.gapminderdev.org/vizabi/feature/svgexport/preview/bubblechart.html#_width:807&height:801&fullscreen:false&bodyC=vzbp-nav-state-editor&resp-sect:true&info-sect:true&butt-sect:true&other-sect:false&state_time_dim=time&value=2016&start=1800&end=2030&playable:true&playing:false&loop:false&round=floor&speed:300&unit=year&step:1&adaptMinMaxZoom:false&formatInput=%25Y&xLogStops@;&yMaxMethod=latest&record:false&povertyline:0&povertyCutoff:0&povertyFade:1&gdpFactor:1&gdpShift:0&xPoints:50&trails:true&lockNonSelected:0&formatOutput=%25Y;&entities_show_geo@=*;&geo.cat@=country;;&select@;&brush@;&opacitySelectDim:0.3&opacityRegular:0.8&needUpdate_;&dim=geo;&marker_space@=entities&=time;&type=geometry&shape=circle&label_use=property&which=geo.name;&axis/_y_use=indicator&unit=u5mr&which=u5mr&min:600&max:0.9&scaleType=log;&axis/_x_use=indicator&unit=gdp/_per/_cap&which=gdp/_per/_cap&min:null&max:null&scaleType=log;&color_use=property&unit=&palette_asi=#FF5872&eur=#FFE700&ame=#7FEB00&afr=#00D5E9&/_default=#ffb600;&which=geo.region&scaleType=ordinal;&size_use=indicator&unit=&which=pop&scaleType=linear&max:0.41)
