### ISSUE TITLE
Change trail icon 

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#359]
This icon means share
![image](https://cloud.githubusercontent.com/assets/496398/9387431/c5f074aa-4760-11e5-8464-8573d9d2268e.png)

**Comment by angieskazka** [comment]
![image](https://cloud.githubusercontent.com/assets/3648190/10003882/0290bf8e-60af-11e5-8aa9-796c584b8003.png)

quick and dirty fix just to close the issue. @olarosling make a new icon if you like
