### ISSUE TITLE
Changing entities dynamically through `setOptions` or state editor is not working

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#362]
I tried using a state that should display only Malawi. But doesn't work.   
"entities": {
    "show": {
      "geo": [
        "mwi"
      ],
    }
}

Reason: "Ready" event is called prematurely, before the dataset is actually ready

**Comment by angieskazka** [comment]
Reason: "Ready" event is called prematurely, before the dataset is actually ready
@arthurcamara1 i can't trace why. also don't see why would the same thing work on bubble chart and not on mountain chart. please give me a hand
