### ISSUE TITLE
Last Updated info on Preview page 

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#367]
When we make changes to the repo, I end up waiting for it to be reflected on the preview page,... but I have no clue if it has already fetched the new version.
To the right under the INFO: Please add a "updated: 3 minutes ago." or "2015 08 22 at 12:52:21" 
with the time, when the gitHub repo was last fetched (Angie comment: shown in user's timezone)
![image](https://cloud.githubusercontent.com/assets/496398/9423621/afdb33ea-48cc-11e5-8816-d7d425801b66.png)

**Comment by angieskazka** [comment]
done in 836a143ecb504670d393bd03f7ddd21c1aaf95bd
