### ISSUE TITLE
Entitiy Picker: Vertical scroll if I press TAB while searching

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#369]
I click the Find button and Type Cambodia, and then press TAB
(Mac OS, Chrome) 
![image](https://cloud.githubusercontent.com/assets/496398/9423872/0434cf04-48d8-11e5-8964-bfa615dc3274.png)

**Comment by angieskazka** [comment]
Might be the same thing as #442

**Comment by angieskazka** [comment]
the commit 987b18b should have fixed it
