### ISSUE TITLE
Search click should move  keyboard-focus to search-textfield

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#370]
After clicking find butotn
I want to start typing
I shouldn't have to click the text box
![image](https://cloud.githubusercontent.com/assets/496398/9423895/88f7a81a-48d8-11e5-90ce-efb54688f70b.png)

**Comment by angieskazka** [comment]
WHERE: 
L67: `open: function () {` in src/components/_gapminder/buttonlist/dialogs/find/find.js

@IncoCode

**Comment by angieskazka** [comment]
#440 fixed this
