### ISSUE TITLE
Enable changing stack order of groups

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#371]
![image](https://cloud.githubusercontent.com/assets/496398/9424399/9cba707c-48eb-11e5-99be-61cafba5168b.png)

**Comment by angieskazka** [comment]
WHERE:
dialogs/stack/stack.js
mountainchart-component.js

see the controls within dialogs/stack/stack.js and how they modify the model (L69)
see how the state listeners are implemented in mount chart component

add a control to stack.js and stack.html, that would modify the state field marker/group/manualSorting
let your control to be user friendly, like a draggable list, it may be a new control or it can be copied and referenced... you might need an existing method of getting unique values from the model. call event on change

add a state listener in mointainchart-component.js for listening to the changes
