### ISSUE TITLE
We can't get away without metadata about dataset anymore

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#372]
By metadata i mean info about indicators: which are available, what are their units, etc.
 
Two approaches are needed:
1) reading metadata from the file, having path to file in gapminder.js
2) reading metadata from waffle server

Let's start from a simple case, where metadata does not depend on entities currently displayed

As pointed out in #232, #336, indicators should also depend on marker AND tool. 
IndicatorPicker.js should have a filter when populating the list. That filter can be configured in tool-specific marker config in gapminder.js. (see sub-issue #443)

For instance, no properties should be available to set on y-axis in bar chart, so in bar chart y-axis marker confog we would write something like: allowed = {"use": ["indicator"]} and in x-axis marker we would have allowed = {"use": ["property"]}

important: we avoid explicitly listing the available indicators like "lex" and "pop" for every tool

the metadata for all indicators should be generic and in one place (like a little database), be it a local file or a server-provided one. @arthurcamara1 can you please outline the solution for serving and receiving this little DB?

Example of metadata (can be extended of course):
{
        'geo.region': {use: 'property',unit: '',scales: ['ordinal'] },
        'geo': {use: 'property',unit: '',scales: ['ordinal'] },
        'time': {use: 'indicator',unit: 'time',scales: ['time'] },
        'childSurv': {use: 'indicator',unit: 'childSurv',scales: ['linear', 'log'] },
        'gdp_per_cap': {use: 'indicator',unit: 'gdp_per_cap',scales: ['log', 'linear'] },
        'pop': {use: 'indicator',unit: '',scales: ['linear', 'log'] },
        'geo.name': {use: 'property',unit: '',scales: ['ordinal'] },
        'u5mr': {use: 'indicator',unit: 'u5mr',scales: ['linear', 'log'] },
        'size': {use: 'property',unit: '',scales: ['ordinal'] },
        'gini': {use: 'indicator',unit: 'gini',scales: ['linear'] },
        'gdppc_pday':{use: 'indicator',unit: 'gdppc_pday',scales: ['log', 'linear'] },
        'inc_pday':{use: 'indicator',unit: 'inc_pday',scales:['log', 'linear'] },
        '_default': {use: 'value',unit: '',scales: ['linear', 'log'] }
}

then, language strings should come in another little DB also

**Comment by angieskazka** [comment]
As pointed out in #232, indicators should also depend on marker AND tool. This can be done in marker config in gapminder.js. For instance, no properties should be available to set on y-axis in bar chart

**Comment by arthurcamara1** [comment]
We'll solve it using files for now.

**Comment by angieskazka** [comment]
@arthurcamara1, partially solved in b491d2968a28b0dec88c5773be4cfd4ee2389b03. i added a filter into indicatorpicker.js and config for the filter in gapminder.js

now if you put `var availOpts = { ... } ` into a csv file and load it from there the issue will be solved completely
