### ISSUE TITLE
Timeslider became discrete. It shouldn't be.

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#373]
some of the latest merges or pull requests changed the time slider so that it became discrete when i drag it. Timeslider should be continuous, with values interpolated between time frames

**Comment by IncoCode** [comment]
This https://github.com/Gapminder/vizabi/pull/304/files#diff-c1ec15870af3e9404c82bed0c17a8149 ?

**Comment by arthurcamara1** [comment]
I remember reversing this. Fixed on develop
