### ISSUE TITLE
Path to data not working under /fullscreen folder on server

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#374]
see gapminder.js, path to data file

locally this path works both from
http://localhost:9000/preview/bubblechart.html
and
http://localhost:9000/preview/fullscreen/bubblechart.html

`/local_data/waffles/{{LANGUAGE}}/basic-indicators.csv`

on server, this path doesn't work and the error looks super confusing because all is correct
![image](https://cloud.githubusercontent.com/assets/3648190/9428612/870c1ab8-49b4-11e5-9a27-be06e5625d45.png)

if we remove slash like this

`local_data/waffles/{{LANGUAGE}}/basic-indicators.csv`

the path works on server (and locally), but only on preview/bubblechart.html, not on preview/fullscreen/bubblechart.html

it's missing the file and need to step 1 level up the file tree to find it

**Comment by arthurcamara1** [comment]
True, it won't work with `fullscreen/`... We need to set up a grunt replace task then to fix it for `fullscreen/` or add a copy to `preview/fullscreen`. The correct one is without the slash

**Comment by angieskazka** [comment]
not relevant any longer, we removed full screen button
