### ISSUE TITLE
Integrate indicator picker menu

### ISSUE THREAD

**Issue by arthurcamara1** [Gapminder/vizabi#375]
We have a nice indicator menu UI that needs to be integrated to Vizabi. It probably depends on #372 to be developed fully, but we can get started without it.

@angieskazka please instruct me on how to get the current code we have so that we can design a good solution to this issue.

**Comment by angieskazka** [comment]
done in 8d652f13555765d68a362128a182006d4bc80bc9

**Comment by angieskazka** [comment]
improved all the way until be9a001d0aca83f2a608217d35ad092b8e6d427a
