### ISSUE TITLE
Size slider should have min and max in the same slider with two handles

### ISSUE THREAD

**Issue by arthurcamara1** [Gapminder/vizabi#376]
Under the size configuration, we have two sliders: one controlling the min size and one controlling the max size.

We would like to have a single slider with two handles, similar to gapminder.org/world .

**Comment by arthurcamara1** [comment]
Refer to the bubble size component: https://github.com/Gapminder/vizabi/tree/develop/src/components/_gapminder/bubblesize

And the experience should be similar to the one we have on Gapminder World http://www.gapminder.org/world/

![image](https://cloud.githubusercontent.com/assets/3584238/10108916/05255616-63c4-11e5-9dc4-215ab4cfa704.png)

**Comment by arthurcamara1** [comment]
The current `bubblesize` component only allows us to control either min or max. Then, we need to add the component twice, the first time to control min size, the second time to control max size

![image](https://cloud.githubusercontent.com/assets/3584238/10109017/a7c2d59c-63c4-11e5-8ea5-db4f2e3e755f.png)

Then, when we add the two components, we determine that it controls `min` or `max` by passing the configuration `field` to the component:

This is from [the size dialog](https://github.com/Gapminder/vizabi/blob/develop/src/components/_gapminder/buttonlist/dialogs/size/size.js)
```js
      this.components = [{
        component: 'gapminder-bubblesize',
        placeholder: '.vzb-dialog-bubblesize-min',
        model: ["state.marker.size"],
        ui: {
          show_button: false
        },
        field: 'min'
      },{
        component: 'gapminder-bubblesize',
        placeholder: '.vzb-dialog-bubblesize-max',
        model: ["state.marker.size"],
        ui: {
          show_button: false
        },
        field: 'max'
      }
      ...
      ];
```

And the `bubblesize` component [expects to receive the `field` configuration](https://github.com/Gapminder/vizabi/blob/develop/src/components/_gapminder/bubblesize/bubblesize.js), otherwhise it controls `max`:

```js
 init: function (config, context) {
      this.template = this.template || "src/components/_gapminder/bubblesize/bubblesize.html";

      this.model_expects = [{
        name: "size",
        type: "size"
      }];

      this.field = config.field || 'max';
      ...
}
```

That needs to be removed. the  `bubblesize` component should just expect the model `size` and change both `min` and `max` with the correct handles :smile:

**Comment by angieskazka** [comment]
Adding mockups to this thread

here are the two prototypes, with circles and arcs. both are fine (circles are easier)
the important bit is that the scale of these circles should be exactly equal to the bubbles — the biggest and the smallest

![image](https://cloud.githubusercontent.com/assets/3648190/10282076/0c3ec8a8-6b79-11e5-9aed-1109ae6d0c43.png)

![image](https://cloud.githubusercontent.com/assets/3648190/10282079/1579e4b6-6b79-11e5-8520-87aacd887af4.png)


i really suggest you use <svg>, <g>, <text>, <line>, <circle> elements
taking timeslider as an example, this is how your element tree would look like:

![image](https://cloud.githubusercontent.com/assets/3648190/10282104/3cda98d4-6b79-11e5-90fa-7d9fc07cc426.png)

**Comment by angieskazka** [comment]
the basics are done in the above
