### ISSUE TITLE
Clickable Axis Labels

### ISSUE THREAD

**Issue by arthurcamara1** [Gapminder/vizabi#377]
Clicking the labels should bring up the multi-level menu similar to the experience on Gapminder World. We should be able to change scales as well.

@angieskazka @olarosling Let's discuss how to design this solution so that the UI is consistent

**Comment by angieskazka** [comment]
@arthurcamara1 why label `gapminder-world`? don't we want to have it for `bubble-chart` in general?

**Comment by angieskazka** [comment]
@arthurcamara1 UI discussion pending. meanwhile i move the issue to 0.7.2, and connect it together with integration of the new indicator picker #375

**Comment by angieskazka** [comment]
done in 8d652f13555765d68a362128a182006d4bc80bc9

**Comment by angieskazka** [comment]
improved all the way until be9a001d0aca83f2a608217d35ad092b8e6d427a
