### ISSUE TITLE
Play speed control

### ISSUE THREAD

**Issue by arthurcamara1** [Gapminder/vizabi#378]
Charts should include Play speed control, similar to gapminder.org/world. It's a simple slider that controls how slow or fast the timeslider plays

**Comment by angieskazka** [comment]
**where to hack:**
in timeslider component

**how to hack:**
see and understand timeslider.js  .html and .scss

see how the time is set in the model by timeselider.js L 400: `_this.model.time.value = time;`
similarly you will need to set `_this.model.time.speed` with a speed slider

add a sped slider below the main slider (roughly 1/6 of its width with 1/6 width left margin)

```
==================O=================
     [S]===O==[F]
```

in place of [S] and [F] use these svg icons for indicating slow and fast:
http://www.flaticon.com/free-icon/snail-facing-right_83949
http://www.flaticon.com/free-icon/cheetah-feline-silhouette_47403

limits
upper limit (fast): _this.model.time.speed = 100 ms
lower limit (slow): _this.model.time.speed = 1000 ms

hide speed slider by default. just have two icons next to each other in grey color, barely visible
(see color conventions in scss. like 'vzb-grey-light' and similar)

on hover, the icons get more strong color and shift apart and speed slider appears between them

**Comment by olarosling** [comment]
Put a speed slider under options. All state properties should be there. And then we re-visit the design of the speed-slider with a less creative solution. You can start by ripping the one in Gapminder World.

**Comment by angieskazka** [comment]
done
