### ISSUE TITLE
Typography issues. Need to serve Bariol when on Gapminder domains

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#395]
In response to repeatedly reported issues about labels being not displayed or partially displayed or cut off or otherwise being weird on Windows (#252 #254 #267 #215 ... some else, don't remember), i am setting the typeface so that we see on our Macbooks the same what Windows users will see, and we'll hopefully skip having to process issues caused by things looking different. 

The choice is very limited, as the default fonts on different platforms are different 
(see http://www.apaddedcell.com/sites/www.apaddedcell.com/files/fonts-article/final/index.html and http://www.granneman.com/webdev/coding/css/fonts-and-formatting/default-fonts/#android).

My choice for now is Lucida, which looks a little bit rounded, comparing to the other *safe* sans-serifs.

As this issue suggests in title, we should integrate and ship Bariol font with Vizabi when serving from Gapminder domains, otherwise we don't have the right to use it.

**Comment by arthurcamara1** [comment]
Bariol here: http://178.62.135.203:8080/bubbles
Anywhere *else* we need to include Bariol, we need to do it through the page, adding CSS like this:

```javascript
.vzb-tool {
    font-family: "Bariol Regular", "Lucida Sans Unicode","Lucida Grande",sans-serif !important;
}
```

Just a quick reminder that we can't include it in the Vizabi repo.
