### ISSUE TITLE
after min max change I can't zoom out again

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#398]
After having manually set the min max of axis. I still want to zoom to let me zoom out to the original data-range (and even a bit further out)
http://bit.ly/1U18Agq

**Comment by angieskazka** [comment]
@olarosling yeah... kind of bad design. by entering values you change the input domain manually (in units of the scale) and zoom is only operating with output range (in units of pixels) =/ thinking how to shape it up differently
