### ISSUE TITLE
"Ready" event is called many times

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#402]
here we go again!

Open bubblechart-component.js

add a print:
```    
ready: function() {
        console.log("ready event called!")
```

load the bubble chart
![image](https://cloud.githubusercontent.com/assets/3648190/9438622/a3c102f8-4a5f-11e5-8b69-e15951819c3e.png)

(should not happen. readyOnce should be enough)

open state panel. change `"geo":["*"]` to `"geo":["mwi"]`

see how the things are getting sad:

![image](https://cloud.githubusercontent.com/assets/3648190/9438639/e30c9fa8-4a5f-11e5-8526-e2318aa26984.png)

(should happen only once)

i know somebody removed the `if (_this.markersUpdatedRecently)...`

but why 10 times?

**Comment by arthurcamara1** [comment]
Will take a look! That's why I like the automated testing approach @k6Labz (making sure that details and failures that are hard to detect or spot are still working as expected)

**Comment by arthurcamara1** [comment]
By the way, both `readyOnce` and `ready` are supposed to be triggered the first time. Unless we want to change that behavior, but it's been like this since `readyOnce` was introduced.

**Comment by angieskazka** [comment]
last comment: it's fine! we can treat the remaining redundancy on tool level
