### ISSUE TITLE
v0.7.0_01: Go Big button is truncated

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#404]
**SEVERITY:** Major

**MODULE:** Bubble Chart

**Platform:**
* Windows 7 / Chrome 45.0
* MAC / Safari 8.0
* iPad Air 2 iOS(8.3) / Safari 8.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Note that “Go Big” button is truncated

**ACTUAL RESULTS:**
Go Big button is truncated on the bubble chart

**EXPECTED RESULTS:** 
Go Big button should be available properly on the chart

**SCREENSHOT:** 
![vizabi_bubble_chart_01](https://cloud.githubusercontent.com/assets/9950837/9492680/2a98b712-4c13-11e5-9a4b-83e43ceda93d.png)

**Comment by k6Labz** [comment]
**Retest Result:** Failed ( Above mentioned bug is not fixed on devlop branch ) 
**Environment:** Develop branch - http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html 
**Platform:** 
* iPad Air 2 iOS(8.3) / Safari 8.0
* Windows 7 / Chrome 45.0
* MAC / Safari 8.0

**Comment by angieskazka** [comment]
ok, now i see what you mean. this is expected behavior because these buttons are on a scrollable panel, and we want to give a hint that there is something to the right as well

agree that we need a more elegant solution, but we'll deal with it much later

severity: minor
