### ISSUE TITLE
v0.7.0_02: Chart is disturbed on some values

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#405]
**SEVERITY:** Major

**MODULE:** Bubble Chart

**PLATFORM:** Windows 7 / Chrome 45.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Give 844 as input in first input box in the right side
4)	Give 300 as input in second input box in the right side
5)	Note that chart is disturbed on these given values

**ACTUAL RESULTS:**
Chart is disturbed on different given values like 844 and 300

**EXPECTED RESULTS:** 
Chart should not be disturbed on any given valid value

**SCREENSHOT:** 
![vizabi_bubble_chart_02](https://cloud.githubusercontent.com/assets/9950837/9492753/e06262b4-4c13-11e5-9e7a-7e9de7112eed.png)

**Comment by angieskazka** [comment]
this was fixed in 0.8.3

![image](https://cloud.githubusercontent.com/assets/3648190/10607401/93007e4c-7739-11e5-9d36-3f5b076db224.png)
