### ISSUE TITLE
v0.7.0_03: X-axis description is not localized

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#406]
**SEVERITY:** Minor

**MODULE:** Bubble Chart

**PLATFORM:** Windows 7 / Chrome 45.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Click switch language button to switch the language to SE
4)	Note that the all description on the x-axis is not localized

**ACTUAL RESULTS:**
All the description on the x-axis is not localized after switching the language

**EXPECTED RESULTS:** 
All the description on the x-axis should be localized after switching the language

**SCREENSHOT:** 
![vizabi_bubble_chart_03](https://cloud.githubusercontent.com/assets/9950837/9492772/23aeb7b6-4c14-11e5-8f3d-359fe4d5f708.png)

**Comment by arthurcamara1** [comment]
It is, this is Swedish :smile:
