### ISSUE TITLE
v0.7.0_05: Slider ball is disappeared 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#408]
**SEVERITY:** Minor

**MODULE:** Bubble Chart

**PLATFORM:** Windows 7 / Chrome 45.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Click on the full screen button under RESPONSIVENESS
4)	Click play button
5)	Click Portrait view before stopping the movement of the slider ball
6)	Chart view is changed to Portrait view
7)	Note that slider ball is missing on portrait view

**ACTUAL RESULTS:**
Slider ball is disappeared orientation from full screen to portrait view

**EXPECTED RESULTS:** 
Slider ball should be there by changing the orientation 

**SCREENSHOT:** 

![vizabi_bubble_chart_05 1](https://cloud.githubusercontent.com/assets/9950837/9492842/989543ba-4c14-11e5-8e31-9f59c8914de3.png)

![vizabi_bubble_chart_05 2](https://cloud.githubusercontent.com/assets/9950837/9492843/989c5074-4c14-11e5-89d9-303cf051688c.png)

**Comment by arthurcamara1** [comment]
Solving #407 will fix this too

**Comment by angieskazka** [comment]
@arthurcamara1 i doubt it will, because the #407 problem is contained within bubble chart component.
but the solution seems to be similar for the two

**Comment by angieskazka** [comment]
the above fixed the issue

**Comment by angieskazka** [comment]
@k6Labz please check the develop if the issue still persists
http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html

**Comment by k6Labz** [comment]
Retest Result: Passed 
Environment: Develop branch - http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html
