### ISSUE TITLE
v0.7.0_06: Slider ball is not placed at the start of the slide bar manually 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#409]
**SEVERITY:** Minor

**MODULE:** Bubble Chart

**PLATFORM:**
* Windows 7 / Chrome 45.0
* MAC / Safari 8.0
* iPad Air 2 iOS(8.3) / Safari 8.0
* Android Nexus-5 (5.1.1) / Chrome 44.0
* Nexus 9 (5.0.1) / Chrome 45.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Click on the full screen button under RESPONSIVENESS
4)	Click at the start of the slide bar
5)	Note that slider ball is not placed at the start of the slide bar manually. 

**ACTUAL RESULTS:**
 Slider ball is not placed at the start of the slide bar manually. If we drag the slider ball to the start and drop it there then  slider ball is moved ahead, it does not placed at the start.

**EXPECTED RESULTS:** 
Slider ball should be placed at the start of the slide bar manually  

**SCREENSHOT:** 
![vizabi_bubble_chart_06](https://cloud.githubusercontent.com/assets/9950837/9492873/e94fccd0-4c14-11e5-86d5-80097b9d46f5.png)

**Comment by angieskazka** [comment]
Where to look: timeslider.js, timeslider component, drag function

Solution: check if the dragging cursor moves out of the expected range, then set the time slider to boundary value.

**Comment by angieskazka** [comment]
i think @IncoCode fixed it. 
@k6Labz please retest on [develop](http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html)

**Comment by IncoCode** [comment]
@angieskazka no, i didn't. I have told you in the chat, that the problem in round function (`ceil`).

**Comment by arthurcamara1** [comment]
We can't reproduce anymore. It seems to have been fixed, @k6Labz

**Comment by k6Labz** [comment]
Result Retest: Passed
Environment: Develop branch
