### ISSUE TITLE
Make data-gapfill optional

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#41]
Make the usage of gap-filling optional in the class src/models/data.js. Make it an option that can be toggled on / off at runtime, so that tools which don't want gaps fills, can avoid getting it.
(for examples a table view, would rather show the missing data as empty cells, and then let user say, fill gaps, and see how empty cells got filled on the screen.)

**Comment by angieskazka** [comment]
The issue got irrelevant since we don't have no gap-fill any longer, we interpolate every indicator independently. 
So far we are satisfied with the performance.
