### ISSUE TITLE
v0.7.0_07: X-axis description is overlapping

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#411]
**SEVERITY:** Minor

**MODULE:** Bubble Chart

**PLATFORM:**
* Windows 7 / Chrome 45.0
* MAC / Safari 8.0
* iPad Air 2 iOS(8.3) / Safari 8.0
* Android Nexus-5 (5.1.1) / Chrome 44.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Click the Random button under RESPONSIVENESS
4)	Note that on some different sizes, x-axis description on the chart is overlapping
 
**ACTUAL RESULTS:**
On some different sizes, x-axis description on the chart is overlapping.

**EXPECTED RESULTS:** 
X-axis is description should not be overlapped 

**SCREENSHOT:** 
![vizabi_bubble_chart_07](https://cloud.githubusercontent.com/assets/9950837/9492912/20902fbe-4c15-11e5-94f9-140e5a44f225.png)

**Comment by angieskazka** [comment]
@IncoCode fixed this recently (if i remember correctly)

**Comment by IncoCode** [comment]
@angieskazka no. It's occurs when pressing `Random` button under `Responsiveness`.

**Comment by angieskazka** [comment]
weird
