### ISSUE TITLE
v0.7.0_08: Options button  label is truncated 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#412]
**SEVERITY:** Minor

**MODULE:** Bubble Chart

**PLATFORM:** Windows 7 / Chrome 45.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Click the Random button under RESPONSIVENESS
4)	Note that on some different sizes , options button label is truncated

**ACTUAL RESULTS:**
On some different sizes, options button label is truncated 

**EXPECTED RESULTS:** 
Options button label should not be truncated

**SCREENSHOT:** 
![vizabi_bubble_chart_08](https://cloud.githubusercontent.com/assets/9950837/9492942/6b76f120-4c15-11e5-883a-3ff35c18400c.png)

**Comment by angieskazka** [comment]
@k6Labz please retest on [develop branch](static.gapminderdev.org/vizabi/develop/preview/bubblechart.html)

**Comment by k6Labz** [comment]
Retest Result: Passed 
Environment: Develop branch - http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html 
Platform: Windows 7 / Chrome 45.0
