### ISSUE TITLE
v0.7.0_13: Options are not selectable

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#417]
**SEVERITY:** Major

**MODULE:** Bubble Chart

**PLATFORM:**
* Windows 7 / Chrome 45.0
* MAC / Safari 8.0
* iPad Air 2 iOS(8.3) / Safari 8.0
* Android Nexus-5 (5.1.1) / Chrome 44.0
* Nexus 9 (5.0.1) / Chrome 45.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Click on the full screen button under RESPONSIVENESS
4)	Click the Options button
5)	Select “Constant” option from first dropdown box under X-axis 
6)	Select “Linear” option from second dropdown box under X-axis 
7)	Note that options is not selected

**ACTUAL RESULTS:**
Options are not selectable under option from second dropdown box under X-axis 

**EXPECTED RESULTS:** 
Options should be selectable 

**SCREENSHOT:** 
![vizabi_bubble_chart_13](https://cloud.githubusercontent.com/assets/9950837/9493107/c84071dc-4c16-11e5-8a77-624bca451e63.png)

**Comment by arthurcamara1** [comment]
Can't choose constant for axes anymore
