### ISSUE TITLE
v0.7.0_14: No values are shown for chart resolution

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#418]
**SEVERITY:** Major

**MODULE:** Bubble Chart

**PLATFORM:**
* Windows 7 / Chrome 45.0
* MAC / Safari 8.0
* iPad Air 2 iOS(8.3) / Safari 8.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Click on the full screen button under RESPONSIVENESS
4)	Click the Options button
5)	Select “Region” , “Geo code”, “Geo name” or “Constant” option from first dropdown box under X-axis 
6)	Note that min and max values are not shoeing. They are showing as “NaN”

**ACTUAL RESULTS:**
No values are shown for chart resolution 

**EXPECTED RESULTS:** 
Values should be available for chart resolution

**SCREENSHOT:** 
![vizabi_bubble_chart_14](https://cloud.githubusercontent.com/assets/9950837/9493138/0dfff198-4c17-11e5-8414-cc7317de5141.png)

**Comment by angieskazka** [comment]
Fixed by disallowing selection of properties on bubble chart axes
