### ISSUE TITLE
v0.7.0_15: Chart is not loading

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#419]
**SEVERITY:** Critical

**MODULE:** Bubble Chart

**PLATFORM:** Windows 7 / Firefox 41.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/bubblechart.html 
2)	Note that Bubble chart page is not loading

**ACTUAL RESULTS:**
Bubble chart page is not loading 

**EXPECTED RESULTS:** 
Bubble chart page should be loaded 

**SCREENSHOT:**
![vizabi_bubble_chart_15](https://cloud.githubusercontent.com/assets/9950837/9493162/380ee46c-4c17-11e5-9aa9-b3c0a2cb6ef7.png)

**Comment by arthurcamara1** [comment]
**Super critical!** Not breaking on MacOS Chrome, but breaking on Firefox :open_mouth:

**Comment by arthurcamara1** [comment]
This is what I get as an error:
```
TypeError: this.sTitleHelpEl is undefined
```
