### ISSUE TITLE
v0.7.0_16:  X-axis description is truncated

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#420]
**SEVERITY:** Major

**MODULE:** Bar Chart

**PLATFORM:**
* Windows 7 / Chrome 45.0
* Windows 7 / Firefox 41.0
* MAC / Safari 8.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/barchart.html 
2)	Bar chart page will be loaded
3)	Note that X-axis description is truncated

**ACTUAL RESULTS:**
X-axis description is truncated 

**EXPECTED RESULTS:** 
X-axis description should not be truncated 

**SCREENSHOT:** 
![vizabi_bar_chart_01](https://cloud.githubusercontent.com/assets/9950837/9493247/b88d2176-4c17-11e5-8f3a-c8b3c6953c0e.png)

**Comment by arthurcamara1** [comment]
Seems fixed
