### ISSUE TITLE
v0.7.0_20: Page is not loading

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#424]
**SEVERITY:** Critical

**MODULE:** Bar Chart

**PLATFORM:**
* Windows 7 / Chrome 45.0
* Windows 7 / Firefox 41.0
* MAC / Safari 8.0
* Nexus 9 (5.0.1) / Chrome 45.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/barchart.html 
2)	Bar chart page will be loaded
3)	Click the “Axes” option
4)	Select  “Time” from first drop down under X-axis
5)	Click “ok”
6)	Refresh the current page
7)	Note that page is not loaded

**ACTUAL RESULTS:**
Page is not loaded on refreshing

**EXPECTED RESULTS:** 
Page should be loaded after refreshing

**SCREENSHOT:** 
![vizabi_bar_chart_05](https://cloud.githubusercontent.com/assets/9950837/9493598/17e2e51e-4c1a-11e5-8fa9-2b005f3b9165.png)

**Comment by arthurcamara1** [comment]
We don't have time in axes anymore
