### ISSUE TITLE
Multiple data readers

### ISSUE THREAD

**Issue by amytych** [Gapminder/vizabi#43]
It seems that framework isn't quite ready for multiple data inputs. In a couple of places in `data.js` I can find code like [this](https://github.com/Gapminder/vizabi/blob/b679756b267cbf0656de97e0e690b943003e86f7/src/models/data.js#L51):

    if (this._items.length === 1) return this._items[0];

It seems that it's always assumed, that `getItems()` method returns one element array. But in my case, this array is a nested array with 4 arrays inside (additionally I have latlng & topojson for districts, topojson for the world).

It may be that my approach is wrong, it's not clearly documented anywhere, what should be correct solution?

**Comment by angieskazka** [comment]
@arthurcamara1 is this still relevant?

**Comment by arthurcamara1** [comment]
No, because of #45
