### ISSUE TITLE
Bubble sizes are wrong after changing entities

### ISSUE THREAD

**Issue by arthurcamara1** [Gapminder/vizabi#431]
![screen shot 2015-08-27 at 10 26 15 am](https://cloud.githubusercontent.com/assets/3584238/9516069/77865b5e-4ca6-11e5-96b0-336bc07e6b62.png)

How to reproduce:

- Go to Bubble Chart: http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html
- Change the state to show only Guyana (`guy`) and refresh the page (or [click here](http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html#_lang=en&width:949&height:906&fullscreen:false&bodyC=vzbp-nav-state-editor&resp-sect:true&info-sect:true&butt-sect:true&other-sect:false&state_time_dim=time&value=2000&start=1990&end=2012&playable:true&playing:false&loop:false&round=ceil&speed:300&unit=year&step:1&adaptMinMaxZoom:false&formatInput=%25Y&xLogStops@:1&:2;&yMaxMethod=latest&record:false&trails:true&lockNonSelected:0&formatOutput=%25Y;&entities_show_geo@=guy;&geo.cat@=country;;&select@;&brush@;&opacitySelectDim:0.3&opacityRegular:0.8&needUpdate=2015-08-27T08/:22/:53.343Z&dim=geo;&marker_space@=entities&=time;&type=geometry&shape=circle&label_use=property&which=geo.name;&axis/_y_use=indicator&unit=lex&which=lex&min:25.5025&max:86.16749999999999&scaleType=linear;&axis/_x_use=indicator&unit=gdp/_per/_cap&which=gdp/_per/_cap&min:211.42499999999998&max:119847.05&scaleType=log;&color_use=property&unit=&palette_asi=#FF5872&eur=#FFE700&ame=#7FEB00&afr=#00D5E9&/_default=#ffb600;&which=geo.region&scaleType=ordinal;&size_use=indicator&unit=&min:0&max:0.75&which=pop&scaleType=linear))
- Change the state on the state editor back to star:
```
"show": {
    "geo": [
    "*"
 ],
 "geo.cat": [
     "country"
 ]
 },
```
- Press tab or unfocus

**Comment by angieskazka** [comment]
i think i figured out why. the scale just never change it's limits in "size" hook

solution: send a signal to the hook to kill the scale on entities change. it will be rebuilt automatically, upon the first request.

@arthurcamara1 what is the good way to send a signal: 
from tool? from show UI control? from entities model?

maybe entities model should tell marker: kill all scales of your children?

**Comment by angieskazka** [comment]
looks like it was fixed
