### ISSUE TITLE
Tools page on gapminder.org

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#432]
Create a "tools" page that would host two fullscreen vizabi containers with a menu to switch between the tools. 

Menu can be graphic, similar to this one 

![image](https://cloud.githubusercontent.com/assets/3648190/9518816/42d4affa-4cba-11e5-8f15-07fea6cb1f9b.png)

Names are stories, not our tool names: wealth and health of the nations, world income distribution

minimalistic info what we are looking at on the left side (gapminder world)

![image](https://cloud.githubusercontent.com/assets/3648190/9518782/fe2b8cca-4cb9-11e5-833c-cd7a61cfed5a.png)

buttons to share the URL with the state, reset the state, embed viz. (maybe github too somewhere in the corner?)

TOP PRIO: Redisign tools page, so it's like mocks 
Very basic angular page
Jade (HTML syntax)
Sass
Grunt
arthur ROUTING
angie LAYOUTS

**Comment by arthurcamara1** [comment]
Closing this because the page is set up. We just need to solve bugs on separate repo https://github.com/Gapminder/gapminder-tools-vizabi
