### ISSUE TITLE
v0.7.0_21:  By changing color, the color is not changed instantly

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#445]
**SEVERITY:** Minor

**MODULE:**
* Mountain Chart
* Bar Chart

**PLATFORM:**
* Windows 7 / Chrome 45.0
* Windows 7 / Firefox 41.0
* MAC / Safari 8.0
* iPad Air 2 iOS(8.3) / Safari 8.0
* Nexus 9 (5.0.1) / Chrome 45.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/mountainchart.html 
2)	Mountain chart page will be loaded
3)	Click “Color” option
4)	Click first dropdown and select “Constant”
5)	Click the colored bold dot
6)	Change the color
7)	Note that color is not changed

**ACTUAL RESULTS:**
Color is not changed by selecting another color until we click the play button

**EXPECTED RESULTS:** 
Color should be changed immediately after selecting another color

**SCREENSHOT:**
![vizabi_mountain_chart_04](https://cloud.githubusercontent.com/assets/9950837/9572266/64c2ada6-4fc6-11e5-8a36-071632b21cf9.png)

**Comment by angieskazka** [comment]
fixed by 2433e6e

**Comment by k6Labz** [comment]
**Summary:** Colored bold dot is not select-able 

**SEVERITY:** Major

**MODULE:**
* Mountain Chart
* Bar Chart

**PLATFORM:**
* Windows 7 / Chrome 45.0
* Windows 7 / Firefox 41.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/develop/preview/mountainchart.html 
2)	Mountain chart page will be loaded
3)	Click “Color” option
4)	Click first dropdown and select “Constant”
5)	Click the colored bold dot
6)     Note that colored bold dot is not select-able.

**ACTUAL RESULTS:**
Colored bold dot can not be selected that's why we can not change the color of the graph under constant option 

**EXPECTED RESULTS:** 
Colored bold dot should be select-able. 

**SCREENSHOT:**
![1](https://cloud.githubusercontent.com/assets/9950837/9710741/f922b4f6-5556-11e5-8873-d345b064d3c6.png)
