### ISSUE TITLE
v0.7.0_22:  Different years are shown on same place

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#446]
**SEVERITY:** Minor

**MODULE:** Mountain Chart

**PLATFORM:**
* Windows 7 / Chrome 45.0
* MAC / Safari 8.0
* iPad Air 2 iOS(8.3) / Safari 8.0
* Android Nexus-5 (5.1.1) / Chrome 44.0
* Nexus 9 (5.0.1) / Chrome 45.0 

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/mountainchart.html 
2)	Mountain chart page will be loaded
3)	Click full screen button under “RESPONSIVENESS”
4)	Click play
5)	Note that year “1960” and “1962” are appearing on same place

**ACTUAL RESULTS:**
Year “1960” and “1962” are appearing on same place when we click full screen button under “RESPONSIVENESS” 

**EXPECTED RESULTS:** 
Years should be shown according to their places

**SCREENSHOT:**

![vizabi_mountain_chart_05 1](https://cloud.githubusercontent.com/assets/9950837/9572285/d6082f18-4fc6-11e5-94b3-a356736c054e.png)

![vizabi_mountain_chart_05 2](https://cloud.githubusercontent.com/assets/9950837/9572286/d60e744a-4fc6-11e5-97c5-9b1c56224fcd.png)

**Comment by arthurcamara1** [comment]
Seems to be fixed
