### ISSUE TITLE
v0.7.0_23: Years are not increasing linearly

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#447]
**SEVERITY:** Major

**MODULE:** Mountain Chart

**Platform:** Windows 7 / Chrome 45.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/mountainchart.html 
2)	Mountain chart page will be loaded
3)	Click full screen button under “RESPONSIVENESS”
4)	Click play
5)	Note that years are not increasing linearly.

**ACTUAL RESULTS:**
Years are not increasing linearly. They are jumping by skipping one year. 
 
**EXPECTED RESULTS:** 
Years should be shown linearly

**SCREENSHOT:**
![vizabi_mountain_chart_06 1](https://cloud.githubusercontent.com/assets/9950837/9572304/252a4f18-4fc7-11e5-9980-869bb5b4ecc6.png)

![vizabi_mountain_chart_06 2](https://cloud.githubusercontent.com/assets/9950837/9572303/252a3726-4fc7-11e5-8699-689e90c02f6b.png)

**Comment by angieskazka** [comment]
@k6Labz i guess it's fixed by now. see develop branch here http://static.gapminderdev.org/vizabi/develop/preview/mountainchart.html

**Comment by k6Labz** [comment]
Retest Result: Passed 
Environment: Develop branch - http://static.gapminderdev.org/vizabi/develop/preview/mountainchart.html 
Platform: Windows 7 / Chrome 45.0
