### ISSUE TITLE
v0.7.0_24: Alignment is disturbed on Firefox

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#448]
**SEVERITY:** Major

**MODULE:** 
* Mountain Chart
* Line Chart
* Bar Chart
* Pop By age Chart

**PLATFORM:**
* Windows 7 / Firefox 41.0
* MAC / Safari 8.0
* iPad Air 2 iOS(8.3) / Safari 8.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/mountainchart.html 
2)	Mountain chart page will be loaded
3)	Note that on the right panel, alignment of the buttons is disturbed

**ACTUAL RESULTS:**
On the right panel, alignment of the buttons is disturbed. 
 
**EXPECTED RESULTS:** 
Alignment should not be disturbed

**SCREENSHOT:**
![vizabi_mountain_chart_08](https://cloud.githubusercontent.com/assets/9950837/9572326/81838478-4fc7-11e5-90e0-989588313659.png)

**Comment by angieskazka** [comment]
Should be resolved in f050a39. @k6Labz please retest on [develop](static.gapminderdev.org/vizabi/develop/preview/bubblechart.html)

**Comment by k6Labz** [comment]
Retest Result: Passed 
Environment: Develop branch - http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html 
Platform: Windows 7 / Firefox 41.0

**Comment by k6Labz** [comment]
Retest Result: Failed
Environment: http://static.gapminderdev.org/vizabi/release/v0.7.1/preview/mountainchart.html
Platform: MAC / Safari 8.0

**Comment by angieskazka** [comment]
i looked now, and it's fixed
