### ISSUE TITLE
v0.7.0_26: Chart is disturbed on Firefox

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#450]
**SEVERITY:** Critical

**MODULE:** 
* Mountain Chart
* Bar Chart
* Pop By age Chart

**Platform:** Windows 7 / Firefox 41.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/mountainchart.html 
2)	Mountain chart page will be loaded
3)	Click “Go Big” button
4)	Click “Go Small” button
5)	Note that after clicking “”Go small” button the resolution of the chart (input box for chart height and width) is same as before clicking “Go big” button but chart is moved to right side 

**ACTUAL RESULTS:**
Chart is moved to right side by changing screen size through “Go Small” to ”Go Big”

**EXPECTED RESULTS:** 
Chart should not be disturbed

**SCREENSHOT:**
![vizabi_mountain_chart_10](https://cloud.githubusercontent.com/assets/9950837/9572373/97b0afae-4fc8-11e5-9ab4-da735291b476.png)

**Comment by IncoCode** [comment]
Cannot reproduce this issue on `develop` branch. Perhaps, because of #479 :)

**Comment by angieskazka** [comment]
@k6Labz can you please retest it on 0.7.1? http://static.gapminderdev.org/vizabi/release/v0.7.1/preview/mountainchart.html

**Comment by k6Labz** [comment]
Retest Result: Passed 
Environment: http://static.gapminderdev.org/vizabi/release/v0.7.1/preview/mountainchart.html 
Platform: Windows 7 / Firefox 41.0
