### ISSUE TITLE
v0.7.0_28:  Marking line of number is moving ahead from its original place

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#452]
**SEVERITY:** Minor

**MODULE:** Pop By Age Chart

**PLATFORM:**
* Windows 7 / Chrome 45.0
* Windows 7 / Firefox 41.0
* MAC / Safari 8.0
* iPad Air 2 iOS(8.3) / Safari 8.0
* Android Nexus-5 (5.1.1) / Chrome 44.0
* Nexus 9 (5.0.1) / Chrome 45.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/popbyage.html 
2)	Pop By Age chart page will be loaded
3)	Note that marking line of number is moving ahead from its original place on y-axis

**ACTUAL RESULTS:**
Marking line of number is moving ahead from its original place on y-axis

**EXPECTED RESULTS:** 
Marking line should be according to the numbers on axis

**SCREENSHOT:** 
![vizabi_pba_chart_01](https://cloud.githubusercontent.com/assets/9950837/9572441/5c0d72f6-4fc9-11e5-9553-75f8432f2842.png)

**Comment by IncoCode** [comment]
This is feature (#273) :smiley:
