### ISSUE TITLE
v0.7.0_29:  Million is truncated on the population description

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#453]
**SEVERITY:** Minor

**MODULE:** Pop By Age Chart

**Platform:**
* Windows 7 / Chrome 45.0
* Windows 7 / Firefox 41.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/popbyage.html 
2)	Pop By Age chart page will be loaded
3)	Select a bar line for 20 year-olds from the chart
4)	Note that “M” is truncated from the description of bar line

**ACTUAL RESULTS:**
“M” is truncated from the description of bar line

**EXPECTED RESULTS:** 
Nothing should be truncated from the description of line bar

**SCREENSHOT:** 
![vizabi_pba_chart_02](https://cloud.githubusercontent.com/assets/9950837/9572486/d33cf1bc-4fc9-11e5-84c2-620ee6c6aad1.png)

**Comment by IncoCode** [comment]
Fixed in `develop` branch.

**Comment by jheeffer** [comment]
Already fixed in earlier release
