### ISSUE TITLE
v0.7.0_31: Slider ball moved ahead by changing the orientation

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#455]
**SEVERITY:** Major

**MODULE:**
* Pop By Age Chart
* Line Chart
* Mountain Chart
* Bar Chart

**PLATFORM:**
* Windows 7 / Chrome 45.0
* Windows 7 / Firefox 41.0
* MAC / Safari 8.0
* iPad Air 2 iOS(8.3) / Safari 8.0
* Nexus 9 (5.0.1) / Chrome 45.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/popbyage.html 
2)	Pop By Age chart page will be loaded
3)	Click the full screen button under RESPONSIVENESS
4)	Click play from the start
5)	Note the position of the slider ball
6)	Click Portrait view without stopping 
7)	Chart is switched to Portrait view
8)	 Note that the slider ball is moved about ten years ahead after changing its view

**ACTUAL RESULTS:**
Slider ball moved ahead by changing the orientation from full screen to Portrait view 

**EXPECTED RESULTS:** 
Slider ball should have same place after changing its view

**SCREENSHOT:**
![vizabi_pba_chart_05 1](https://cloud.githubusercontent.com/assets/9950837/9572566/9cbce916-4fca-11e5-89fd-7d55e07a41fe.png)

![vizabi_pba_chart_05 2](https://cloud.githubusercontent.com/assets/9950837/9572567/9cc34626-4fca-11e5-9712-9a2487fcd385.png)

**Comment by k6Labz** [comment]
**Retest Result:** Fail 

**Release:** v0.8.4

**Testing Environment:** http://static.gapminderdev.org/vizabi/release/v0.8.4/preview/bubblechart.html

**Comment by arthurcamara1** [comment]
Same as #456
