### ISSUE TITLE
v0.7.0_32: Slider ball remained behind from its original place by changing the orientation

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#456]
**SEVERITY:** Major

**MODULE:**
* Pop By Age Chart
* Line Chart
* Mountain Chart
* Bar Chart

**PLATFORM:**
* Windows 7 / Chrome 45.0
* Windows 7 / Firefox 41.0
* MAC / Safari 8.0
* iPad Air 2 iOS(8.3) / Safari 8.0
* Nexus 9 (5.0.1) / Chrome 45.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/popbyage.html 
2)	Pop By Age chart page will be loaded
3)	Click play from the start
4)	Note the position of the slider ball
5)	Click the full screen button under RESPONSIVENESS
6)	Chart is switched to full screen
7)	 Note that the slider ball remained behind from its original place by changing the orientation

**ACTUAL RESULTS:**
Slider ball remained behind from its original place by changing the orientation from Portrait to full screen. When we click play after switching to full screen, the slider ball move quickly to attain its original place, after reaching it the slider ball moves normally

**EXPECTED RESULTS:** 
Slider ball should have same place after changing its view

**SCREENSHOT:**
![vizabi_pba_chart_06 1](https://cloud.githubusercontent.com/assets/9950837/9572589/dc7c27ce-4fca-11e5-9a9c-0d094f065826.png)

![vizabi_pba_chart_06 2](https://cloud.githubusercontent.com/assets/9950837/9572590/dc84b204-4fca-11e5-8cb3-35a832743f11.png)

**Comment by k6Labz** [comment]
**Retest Result:** Fail 

**Release:** v0.8.4

**Testing Environment:** http://static.gapminderdev.org/vizabi/release/v0.8.4/preview/bubblechart.html

**Comment by angieskazka** [comment]
@dab2000 closed this in dd2b82a a minute ago

**Comment by k6Labz** [comment]
@angieskazka 
This issue is reproducing on v0.9.1 (Bubble Map Chart)
But it is not reproducing consistently. 

**Module:** Bubble Map Chart

**Platform:** MAC / Safari 9.0

**Testing Environment:** http://static.gapminderdev.org/vizabi/release/v0.9.1/preview/bubblemap.html

**Comment by angieskazka** [comment]
@k6Labz please retest on develop, i've attempted a fix

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Module:**
* Bubble Map Chart
* Bar Chart 

**Platform:** MAC / Safari 9.0


**Testing Environment:** http://static.gapminderdev.org/vizabi/develop/preview/bubblemap.html
