### ISSUE TITLE
v0.7.0_33: Chart is taking too much time to be loaded

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#465]
**SEVERITY:** Major

**MODULE:** Mountain Chart

**Platform:** iPad Air 2 iOS(8.3) / Safari 8.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/mountainchart.html 
2)	Mountain chart page is taking too much time to be loaded

**ACTUAL RESULTS:**
Mountain chart page is taking too much time to be loaded 

**EXPECTED RESULTS:** 
Mountain chart should be loaded immediately after navigating its URL

**SCREENSHOT:**
![vizabi_ipad_01](https://cloud.githubusercontent.com/assets/9950837/9629803/e48d11ec-518e-11e5-8ccc-4f3168fe3cd2.PNG)

**Comment by angieskazka** [comment]
this is because #382 and partially because #385

**Comment by angieskazka** [comment]
I did what i could for now. Waiting when @arthurcamara1 will finish 1-year loading, this supposed to improve a lot more =)
