### ISSUE TITLE
v0.7.0_34: Multi selection is not allowed

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#466]
**SEVERITY:** Major

**MODULE:** 
* Pop By Age Chart
* Mountain Chart
* Bubble Chart

**Platform:** iPad Air 2 iOS(8.3) / Safari 8.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Select a bubble from the chart, bubble is selected
4)	Select another bubble
5)	Note that only one bubble is allowed to select

**ACTUAL RESULTS:**
Multi selection for bubbles, bar lines is not allowed

**EXPECTED RESULTS:** 
Multi selection should be allowed

**SCREENSHOT:**
![vizabi_ipad_02](https://cloud.githubusercontent.com/assets/9950837/9629895/9e49f9ce-518f-11e5-924a-0ca297dc61ff.PNG)

**Comment by angieskazka** [comment]
same as #468, same as #467

**Comment by arthurcamara1** [comment]
It is now
