### ISSUE TITLE
v0.7.0_35: Selected age bar line is unselected by changing the view of the chart

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#467]
**SEVERITY:** Major

**MODULE:**  Pop By Age Chart

**Platform:** iPad Air 2 iOS(8.3) / Safari 8.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/popbyage.html 
2)	Pop By Age chart page will be loaded
3)	Tap full screen button under RESPONSIVENESS
4)	Select an age bar line from the chart, it is selected
5)	Now tap the Portrait view button under RESPONSIVENESS
6)	Note that selected line is unselected automatically

**ACTUAL RESULTS:**
Selected age bar line is unselected by changing the view of the chart from full screen to portrait view 

**EXPECTED RESULTS:** 
Age line bar should not be unselected by changing the view of the chart

**SCREENSHOT:**
![vizabi_ipad_03 1](https://cloud.githubusercontent.com/assets/9950837/9629921/e74b393a-518f-11e5-83d4-1289c8906e1e.PNG)

![vizabi_ipad_03 2](https://cloud.githubusercontent.com/assets/9950837/9629922/e7757be6-518f-11e5-90a2-82e4ac8ee85a.PNG)

**Comment by angieskazka** [comment]
same as #468

**Comment by k6Labz** [comment]
**SEVERITY:** Major

**MODULE:**  Pop By Age Chart

**Platform:** Windows 7 / Chrome 45.0

**RELEASE:** v0.7.1

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.7.1/preview/popbyage.html 
2)	Pop By Age chart page will be loaded
3)     Select an age bar line
4)	Click "Full screen page" link
5)     Note that selected bar line is unselected

**ACTUAL RESULTS:**
Selected age bar line is unselected by clicking the "Full screen page" link
 
**EXPECTED RESULTS:** 
Selected age bar line should not be unselected by clicking the "Full screen page" link

**Comment by arthurcamara1** [comment]
It doesn't seem to happen anymore
