### ISSUE TITLE
v0.7.0_36: Selected bubble is unselected 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#468]
**SEVERITY:** Major

**MODULE:** Bubble chart

**Platform:** 
* iPad Air 2 iOS(8.3) / Safari 8.0
* Nexus 9 (5.0.1) / Chrome 45.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Select a bubble from the chart, bubble is selected
4)	Now tap the selected bubble again but it is not unselected
5)	Tap on the chart other than the selected bubble
6)	Note that selected bubble is unselected by tapping any other place on the chart

**ACTUAL RESULTS:**
Selected bubble is unselected by tapping any other place on the chart
 
**EXPECTED RESULTS:** 
Selected bubble should be unselected by tapping on the selected bubble, not by tapping any other place on the chart

**SCREENSHOT:**
![vizabi_ipad_04 1](https://cloud.githubusercontent.com/assets/9950837/9629958/33894e9a-5190-11e5-93f8-9dd89abb8739.PNG)

![vizabi_ipad_04 2](https://cloud.githubusercontent.com/assets/9950837/9629959/338bbc84-5190-11e5-8b4d-40d6a08b9213.PNG)

**Comment by angieskazka** [comment]
PROBLEM: after you tap the bubble on mobile device, the bubble is not selected, but "hovered".

SOLUTION:  We need to intercept touch event and treat it differently. Possible ways to deal with it: 
• forget about hovering on mobile, let tap do the selection
• or let tap bring up a "select" button next to the bubble, where you can actually select it
• select on tap. hover the nearest bubble on drag, when zoomed in, show the button to switch the drag gesture to actual dragging (like google maps)
• same but drag with two fingers
• hover on tap, select on longtap. show a hint box when some bubble is hovered "Press bubble and hold to select it"

i think the last is the most elegant and consistent with desktop version / other apps

need a comment of @olarosling which way to choose, then @IncoCode can take it on =)

**Comment by angieskazka** [comment]
@IncoCode, let's not wait for @olarosling, take the last approach from the list and move on =) 
this is a bigger task. 

please avoid dependencies on external libraries like hammer.js, but feel free to make your own class that is like hammer.js but contains only what we need
