### ISSUE TITLE
v0.7.0_37: Some options are truncated

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#469]
**SEVERITY:** Major

**MODULE:** 
* Pop By Age Chart
* Mountain Chart
* Bubble chart

**Platform:**
* iPad Air 2 iOS(8.3) / Safari 8.0
* Android Nexus-5 (5.1.1) / Chrome 44.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Tap Landscape view under RESPONSIVENESS
4)	Tap find 
5)	A list of countries with check box is displayed
6)	Scroll down to the last country
7)	Note that some last countries are not shown and “OK” button is also truncated

**ACTUAL RESULTS:**
Some last countries from find option are not shown and “OK” button is also truncated

**EXPECTED RESULTS:** 
All the countries should be shown properly and “OK” button should also be visible properly

**SCREENSHOT:**
![vizabi_ipad_05](https://cloud.githubusercontent.com/assets/9950837/9630002/9ba0baea-5190-11e5-9e50-1f2e01367252.PNG)

**Comment by angieskazka** [comment]
this is so far by the intended design of the tools. Vizabi tools are contained and live within their boxes, so dialogs stay there... (exception is systems list to pick indicators, but that will change as well)

**Comment by arthurcamara1** [comment]
It seems to work now on develop
