### ISSUE TITLE
v0.7.0_39: Options list is overlapping with slide bar

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#476]
**SEVERITY:** Major

**MODULE:** Bubble chart

**Platform:** Android Nexus-5 (5.1.1) / Chrome 44.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Tap “Go Big“ button
4)	Options list is opened automatically
5)	Note that slide bar is overlapping with options list

**ACTUAL RESULTS:**
Slide bar is overlapping with options list after tapping “Go Big” button

**EXPECTED RESULTS:** 
Overlapping should be avoided

**SCREENSHOT:**
![vizabi_android_01](https://cloud.githubusercontent.com/assets/9950837/9657785/7eeb46b8-525d-11e5-9e50-57c2233857d5.png)

**Comment by angieskazka** [comment]
fixed in 57fdf5d
