### ISSUE TITLE
v0.7.0_40: Country is unselected but still prominent 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#477]
**SEVERITY:** Major

**MODULE:** Mountain chart

**Platform:** Android Nexus-5 (5.1.1) / Chrome 44.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/mountainchart.html 
2)	Mountain chart page will be loaded
3)	Select the highest top country China
4)	Select second highest top country India
5)	Unselect the highest top which represents China
6)	Note that country is unselected but top is still prominent which represents China

**ACTUAL RESULTS:**
Country is unselected but top is still prominent which represents unselected country China 

**EXPECTED RESULTS:** 
After unselecting a country, the country graph should not remain prominent

**SCREENSHOT:**
![vizabi_android_03 1](https://cloud.githubusercontent.com/assets/9950837/9657823/e29860c4-525d-11e5-9913-6073739579f6.png)

![vizabi_android_03 2](https://cloud.githubusercontent.com/assets/9950837/9657824/e29b2cfa-525d-11e5-91b0-b4dd9e43db49.png)

**Comment by angieskazka** [comment]
i guess it's because #468. Same issue with touch events being confused between selecting and hovering. you basically have china hovered on the second screen

**Comment by angieskazka** [comment]
@IncoCode good job on writing up a touch event handler! 
can you please include it into mountain chart as well?
mountainchart-component.js
