### ISSUE TITLE
Improve time slider so that 1 event happens on click, not 2

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#487]
Right now if we click timeslider it will produce two events: first on drag action with interpolation between years, then on `dragend` action, with snapping to the next year.
Can we avoid the first event in case if `dragend` fired within 50ms after the `drag` event?

By resetting throttle on `dragend`, maybe...
Discussion @arthurcamara1 @IncoCode

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/633
