### ISSUE TITLE
Opacity and size sliders are ugly on Firefox

### ISSUE THREAD

**Issue by brylie** [Gapminder/vizabi#496]
- **Severity**: Minor
- **Module**: Bubble Chart
- **Platform**: xUbuntu 15.04 / Firefox 40.0.3
- **Release**: v0.6.0

# Steps to reproduce
1. Navigate to URL: http://vizabi.org/examples/bubble-chart.html
1. Bubble chart page will be loaded
1. Click the **Find** icon
1. Select any country
1. Note that grey background behind the opacity slider is mis-aligned

# Actual results
Opacity slider background appears, but is not fully aligned below the slider widget.

# Expected results
Grey background should be fully aligned beneath the slider widget.

# Screenshots
## Full view of Find dialogue
![bubblechart-opacityslider-backgroundspillover](https://cloud.githubusercontent.com/assets/17307/9758041/b3e3a0c0-56ec-11e5-84b1-b2f637b30ab5.jpeg)

## Detail view of slider widget
![bubblechart-opacityslider-backgroundspillover-detail](https://cloud.githubusercontent.com/assets/17307/9758080/f6e41404-56ec-11e5-82b5-6df5daf3f875.jpeg)

**Comment by IncoCode** [comment]
Already fixed.

**Comment by angieskazka** [comment]
thanks for contribution, @brylie! 
this indeed was fixed in our latest version, the thing is that we haven't updated the version link in vizabi.org for a couple of weeks. please retest, it should be good now

**Comment by angieskazka** [comment]
@brylie by the way we welcome any contribution. if you have some time and feel like you want to help, please check out our [latest release](http://static.gapminderdev.org/vizabi/release/v0.7.1/preview/bubblechart.html) and find more bugs =)

**Comment by angieskazka** [comment]
@IncoCode can you please fiddle with CSS and make opacity and size sliders *hide focus frame* when they are in focus?
i mean this dashed rectangle after you drag it

(platform: Firefox on Mac OS X)


![image](https://cloud.githubusercontent.com/assets/3648190/9836548/435980d8-5a1e-11e5-9098-e19e9b114f36.png)

![image](https://cloud.githubusercontent.com/assets/3648190/9836551/4a4f10e2-5a1e-11e5-8299-486813a6afa8.png)

**Comment by IncoCode** [comment]
Fixed.
> because the main time slider has none!

Main slider implemented not as range input, that's why the main slider doesn't has such bugs.
