### ISSUE TITLE
Bubble chart not rendering on static.gapminderdev.org

### ISSUE THREAD

**Issue by brylie** [Gapminder/vizabi#497]
When attempting to reproduce an issue with the latest version of Visbi, I noticed the Bubble Chart demonstration on static.gapminderdev.org is not rendering.

- **Severity**: Major
- **Module**: Bubble Chart
- **Platform**: xUbuntu 15.04 / Firefox 40.0.3
- **Release**: v0.7.0

# Steps to reproduce
1. Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/bubblechart.html
1. Bubble chart page will be loaded
1. Notice the bubble chart fails to render, and the spinner remains active
1. Notice the following error in the Firefox developer console:

```JavaScript
TypeError: this.sTitleHelpEl is undefined  visbi.js:9280:8
```

# Actual results
The Bubble Chart fails to render, leaving the spinner in perpetual motion with misaligned text along the top of the box.

# Expected results
The Bubble Chart should render properly.

# Screenshot
## View of Bubble Chart container
![bubblechart-0 7 0-failtorender-box](https://cloud.githubusercontent.com/assets/17307/9758232/f4cb2d0a-56ed-11e5-83ae-2ed1e51f69f3.jpeg)

**Comment by IncoCode** [comment]
Already fixed.

**Comment by brylie** [comment]
Where has it been fixed? This issue was observed today at http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/bubblechart.html

**Comment by IncoCode** [comment]
http://static.gapminderdev.org/vizabi/release/v0.7.1/preview/bubblechart.html
#419
