### ISSUE TITLE
modelReady called multiple times

### ISSUE THREAD

**Issue by amytych** [Gapminder/vizabi#50]
It seems we're back to square one with calling this method multiple times, like we were with previous `update` implementation. It happens in my map tool and in bubble-chart example. Is it a known issue or a desired behaviour? If the latter, then is there something else to hook to, to guarantee that my code will have the updated data and will be executed only once?

**Comment by arthurcamara1** [comment]
Closed by 13d644236c654a241533ffe7b27dd7ecaaeb34ac
