### ISSUE TITLE
Picking continues colours broken

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#500]
Picking colours for continues scale is great, but needs to be fixed. 
1. Make it work (currently the picked color doesn't change what I see in the chart.
2. Show live-preview at the time of picking the color.
3. More steps: let me pick multiple colours for the scale: At least three steps, so I can put one [min color, one for max color and one for data-scale-center.
 ![image](https://cloud.githubusercontent.com/assets/496398/9808117/5ce0cc64-585c-11e5-801a-e2fe6cfe882e.png)

**Comment by angieskazka** [comment]
@olarosling can you please write steps to reproduce? 
i just tested, and all 3 points work exactly as you say on mountain and bubble charts (that's what i've also been aiming for).

**Comment by angieskazka** [comment]
couldn't reproduce  ¯\_(ツ)_/¯
