### ISSUE TITLE
v0.7.1_04: Labels are truncated from right side

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#505]
**SEVERITY:** Minor

**MODULE:**
* Bubble Chart
* Bar Chart
* Mountain Chart

**Platform:**Windows 7 / Chrome 45.0

**RELEASE:** v0.7.1

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.7.1/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Click the “Expand” option
4)	The chart is expanded
5)	Note that some labels are truncated from right side

**ACTUAL RESULTS:**
Some labels are truncated from right side

**EXPECTED RESULTS:** 
Labels should not be truncated 

**SCREENSHOT:** 

![vizabi_bubble_chart_04](https://cloud.githubusercontent.com/assets/9950837/9815245/05c5556a-58ae-11e5-9be3-7f4f8b74608c.png)

**Comment by angieskazka** [comment]
...edit: not really 4ca2299 but the next two commits
