### ISSUE TITLE
v0.7.1_06: Bars fail to color by regions because waffle server responds geo.region = "world" for all entities

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#507]
**SEVERITY:** Major

**MODULE:** Bar Chart

**Platform:** 
* Windows 7 / Chrome 45.0
* Windows 7 / Firefox 41.0

**RELEASE:** v0.7.1

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.7.1/preview/barchart.html 
2)	Bar chart page will be loaded
3)	Click colors
4)	Click first dropdown
5)	List is shown
6)	Click first option “Region”
7)	Note that the bar have same color, they are not differentiated according to region colors

**ACTUAL RESULTS:**
Bars have same color; they are not differentiated according to region colors 

**EXPECTED RESULTS:** 
Bars should have colors according to the selected option

**SCREENSHOT:** 

![vizabi_bar_chart_01](https://cloud.githubusercontent.com/assets/9950837/9815310/7c1aad46-58ae-11e5-9acc-33e08e227580.png)

**Comment by angieskazka** [comment]
thanks! once in a while i have this WAT feeling when i just can't explain things. will take a look

![image](https://cloud.githubusercontent.com/assets/3648190/9836201/8ccf765e-5a10-11e5-83d1-a8292487d9d8.png)
