### ISSUE TITLE
"change:language" in indicatorpicker.js is not called on the first language change // v0.7.1_07: Options are not localized. 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#508]
**SEVERITY:** Critical

**MODULE:** Bar  Chart

**Platform:**
* Windows 7 / Chrome 45.0
* Windows 7 / Firefox 41.0
* MAC / Safari 8.0
* Nexus 9 (5.0.1) / Chrome 45.0
* iPad Air 2 iOS(8.3) / Safari 8.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.7.1/preview/barchart.html 
2)	Bar chart page will be loaded
3)	Click the switch language button
4)	Click the colors option
5)	Click first dropdown
6)	Note that all the options are not localized

**ACTUAL RESULTS:**
All the options are not localized under first dropdown of colors options

**EXPECTED RESULTS:** 
Options should be localized

**SCREENSHOT:**

![vizabi_bar_chart_02](https://cloud.githubusercontent.com/assets/9950837/9815345/b87ba1b4-58ae-11e5-95c7-a64e091c8ad4.png)

**Comment by angieskazka** [comment]
see indicatorpicker.js Line 64

```
"change:language": function(evt) {
    console.log(evt)
    _this.updateView();
}
```

the event is not called on the first language change but is called on all the following changes

@arthurcamara1 need help

**Comment by angieskazka** [comment]
@arthurcamara1  printing ctx.getObject() in model.js:1185

first change of language
![image](https://cloud.githubusercontent.com/assets/3648190/9832837/bd139322-5984-11e5-8105-34ddd2f84133.png)

second change of language
![image](https://cloud.githubusercontent.com/assets/3648190/9832840/d556a262-5984-11e5-8074-c7c8248c2227.png)

**Comment by angieskazka** [comment]
fixed some time ago

**Comment by angieskazka** [comment]
fine on Chrome now, but still buggy on Safari 9

![image](https://cloud.githubusercontent.com/assets/3648190/10935314/9b1b6332-82e5-11e5-97c0-229be6bf2035.png)

**Comment by arthurcamara1** [comment]
Seems to be fixed
