### ISSUE TITLE
v0.7.1_08: Graph is not drawn according to the population

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#513]
**SEVERITY:** Major

**MODULE:** Mountain Chart

**Platform:**
* Windows 7 / Chrome 45.0
* Windows 7 / Firefox 41.0

**RELEASE:** v0.7.1

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.7.1/preview/mountainchart.html 
2)	Mountain chart page will be loaded
3)	Select top two countries
4)	Note that according to the population 1.4B should be on the top (screenshot is given below)

**ACTUAL RESULTS:**
Graph is not drawn according to the population

**EXPECTED RESULTS:** 
The country having the highest population within a region should be on the top on the mountain graph. Graphs arrangement is set according to the year 2030 population. For example if India will have the highest population in year 2030 then it will remain on top within its region from 1800 to 2030.But graph should be changed according to the population. If China has the highest population then it should be on the top.

**SCREENSHOT:** 

![vizabi_mountain_chart_01](https://cloud.githubusercontent.com/assets/9950837/9849136/63fd56c8-5b01-11e5-8c79-4fc4ffb1e031.png)

**Comment by angieskazka** [comment]
the observed behavior is expected. if countries would switch in their stacked order during play, they will be hard or impossible to follow. we'll end up in a mess.
the list to the left is sorted by the stacking order of the countries, not by population

closing as not-an-issue
@olarosling might have opinions
