### ISSUE TITLE
v0.7.1_10: X axis scale marking is not available by expanding screen size

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#515]
**SEVERITY:** Major

**MODULE:** Pop By Age Chart

**Platform:** Windows 7 / Chrome 45.0

**RELEASE:** v0.7.1

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.7.1/preview/popbyage.html 
2)	Pop By Age chart page will be loaded
3)	Click “Expand”
4)	Pop by age will be loaded as full screen
5)	Note that X axis scale has no marking

**ACTUAL RESULTS:**
X axis scale marking is not available by expanding screen size

**EXPECTED RESULTS:** 
Marking on X axis should be available by expanding screen size

**SCREENSHOT:** 

![vizabi_pba_chart_01](https://cloud.githubusercontent.com/assets/9950837/9849236/4982eac8-5b02-11e5-99d5-99972991d6e7.png)

**Comment by angieskazka** [comment]
Solution: 
increase margin.bottom constant for the "large" profile in the popbyage-component .js, see method "resize"

**Comment by jheeffer** [comment]
Already fixed in a previous release
