### ISSUE TITLE
v0.7.1_12: Options are disappeared after expanding the screen size

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#517]
**SEVERITY:** Major

**MODULE:** Bar chart

**Platform:** Android Nexus-5 (5.1.1) / Chrome 44.0

**RELEASE:** v0.7.1

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.7.1/preview/barchart.html 
2)	Bar chart page will be loaded
3)	Tap “Expand“ 
4)	Screen will be expanded
5)	Note that the options for “restore” is disappeared

**ACTUAL RESULTS:**
Options for restoring default screen size is disappeared after tapping “Expand” button

**EXPECTED RESULTS:** 
”Restore” button should not be disappeared 

**SCREENSHOT:**

![vizabi_android_01](https://cloud.githubusercontent.com/assets/9950837/9849314/2c4f051c-5b03-11e5-8ee3-7aef09151115.png)

**Comment by angieskazka** [comment]
could not reproduce on a similar platform Android Nexus-5 (5.1.1) / Chrome 44.0
but i have Chrome 45.0.2454.84

**Comment by sergey-filipenko** [comment]
@k6Labz could not reproduce. Please retest

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Testing Environment:** http://static.gapminderdev.org/vizabi/develop/preview/barchart.html 

**Platform:** Nexus-5 (6.0) / Chrome 47.0
