### ISSUE TITLE
Include version banner on top of the files, also when calling "Vizabi" in console

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#518]

**Comment by arthurcamara1** [comment]
Versioning banners can be seen [on top of files](http://static.gapminderdev.org/vizabi/develop/dist/vizabi.min.js):

```javascript
/**
 * vizabi - Vizabi Framework, Interactive charts and visualization tools animated through time
 * @version v0.8.1
 * @link http://vizabi.org
 * @license BSD
 */
```

And on console by typing:

```javascript
Vizabi._version
//currently outputs: "0.8.1" , extracted from package.json
```

**To update the version across the project:**

```bash
gulp bump --version 0.8.1
#sets the version precisely to 0.8.1
```
or
```bash
gulp bump --type patch
# 0.8.1 ---> 0.8.2
gulp bump --type minor
# 0.8.1 ---> 0.9.0
```

More details here: https://github.com/stevelacy/gulp-bump#versioning

**Comment by angieskazka** [comment]
@arthurcamara1 why can't it be visible here like in d3?

![image](https://cloud.githubusercontent.com/assets/3648190/10201760/e52d353e-67ad-11e5-88bf-f0c0216a3940.png)
