### ISSUE TITLE
v0.7.1_14:  Description for selected bubble is truncated

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#521]
**SEVERITY:** Minor

**MODULE:** Bubble chart

**Platform:** 
* Nexus 9 (5.0.1) / Chrome 45.0
* iPad Air 2 iOS(8.3) / Safari 8.0
* Nexus-5 (5.1.1) / Chrome 44.0

**RELEASE:** v0.7.1

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.7.1/preview/bubblechart.html 
2)	Bubble chart will be loaded
3)	Select a bubble representing a country with “Life Expectancy” almost above than 70
4)	Note that the description is truncated which is shown after selecting a bubble

**ACTUAL RESULTS:**
Description is truncated which is shown after selecting a bubble with “Life Expectancy” almost above than 70

**EXPECTED RESULTS:** 
 Description for selected country should not be truncated 

**SCREENSHOT:**

**Complete Description**
![vizabi_android_02 1](https://cloud.githubusercontent.com/assets/9950837/9904034/4865dd42-5c94-11e5-8010-2ab99a3427ca.png)

**Truncated Description**
![vizabi_android_02 2](https://cloud.githubusercontent.com/assets/9950837/9904035/486d7548-5c94-11e5-9433-f8e984dea4e3.png)

**Comment by arthurcamara1** [comment]
@angieskazka  @olarosling 
Maybe we should remove hover functionality from mobile and just select when tapping.
All the few users we've shown this to had problems selecting the buttons with hold.
