### ISSUE TITLE
v0.7.1_16: Small screen for options is truncated

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#523]
**SEVERITY:** Major

**MODULE:**
* Bubble chart
* Mountain chart
* Pop by age chart

**Platform:** Nexus 9 (5.0.1) / Chrome 45.0

**RELEASE:** v0.7.1

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.7.1/preview/bubblechart.html 
2)	Bubble chart will be loaded
3)	Click “Expand”
4)	Click “Colors”
5)	Note that the small screen is displayed with different options but it is truncated and play icon is also truncated

**ACTUAL RESULTS:**
Small screen for options is truncated on expanded screen 

**EXPECTED RESULTS:** 
 Small screen for options should not be truncated

**SCREENSHOT:**

![vizabi_android_04](https://cloud.githubusercontent.com/assets/9950837/9904271/da83f4ce-5c95-11e5-89e9-f1e2f554206f.png)

**Comment by k6Labz** [comment]
**Retest Result:** Fail 

**Testing Environment - DEVELOP:** http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html 

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html  
2)	Bubble chart will be loaded
3)     Click "Color"
4)	Click “Expand”
5)	Click “Colors” again
6)     Note that small pop up screen is disturbed

**Screeenshot:**

![1111](https://cloud.githubusercontent.com/assets/9950837/10757389/93b72c9e-7ccc-11e5-9dae-449f7adb6fea.png)

**Comment by arthurcamara1** [comment]
Couldn't reproduce. Retest?

**Comment by k6Labz** [comment]
@arthurcamara1 
When this bug was reported, the expanded screen had a different view(having just icons and labels) and now the view is improved with explained right panel on expanded screen in v0.8.4 and onward. Now I think this issue is like #899
