### ISSUE TITLE
v0.7.1_17: Pin icon is missing

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#524]
**SEVERITY:** Major

**MODULE:** Mountain chart

**Platform:**
* Nexus 9 (5.0.1) / Chrome 45.0
* Windows 7 / Chrome 45.0
* Windows 7 / Firefox 41.0
* MAC / Safari 8.0
* iPad Air 2 iOS(8.3) / Safari 8.0
* Android Nexus-5 (5.1.1) / Chrome 44.0

**RELEASE:** v0.7.1

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.7.1/preview/mountainchart.html  
2)	Mountain chart will be loaded
3)	Click “X and Y”
4)	Note that the pin icon is missing on the small screen

**ACTUAL RESULTS:**
Pin icon is missing on the small screen which is shown by clicking “X and Y”

**EXPECTED RESULTS:** 
 Pin should be available on the small screen which is shown by clicking “X and Y”

**SCREENSHOT:**

![vizabi_android_05](https://cloud.githubusercontent.com/assets/9950837/9904377/bb3ff2c4-5c96-11e5-8e76-c30a625558c1.png)

**Comment by angieskazka** [comment]
@IncoCode can you please look at this? 
also please tell us where you store the pin and hand icons? 

we are supposed to have them inside the code like this:
https://github.com/Gapminder/vizabi/blob/develop/src/components/_gapminder/buttonlist/buttonlist.js#L522

**Comment by IncoCode** [comment]
@angieskazka ok.
The pin icon was already here (font-awesome). Hand icon is stored in [dialog.js](https://github.com/Gapminder/vizabi/blob/develop/src/components/_gapminder/buttonlist/dialogs/_dialog.js#L140).

**Comment by angieskazka** [comment]
@IncoCode we don't ship font awesome with vizabi. all what we use within the framework should be included.

**Comment by angieskazka** [comment]
Supposingly done in 1cb5ef3aac95eeb064c5f83774108091d0bec167
