### ISSUE TITLE
v0.7.1_18:Color change is implemented but color of the scale remains unchanged

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#525]
**SEVERITY:** Minor

**MODULE:** Bubble chart

**Platform:** Nexus 9 (5.0.1) / Chrome 45.0

**RELEASE:** v0.7.1

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.7.1/preview/mountainchart.html  
2)	Bubble chart will be loaded
3)	Click “Colors”
4)	Click first dropdown
5)	Select “Time”
6)	Change the color of the scale
7)	Note that the color change is implemented but color of the scale remains unchanged

**ACTUAL RESULTS:**
Color change is implemented but color of the scale remains unchanged 

**EXPECTED RESULTS:** 
 Color of the scale should be changed according to the implemented changed color. It should not remain constant

**SCREENSHOT:**

![vizabi_android_06](https://cloud.githubusercontent.com/assets/9950837/9904443/2e87eade-5c97-11e5-9aef-ee5ac81f1335.png)

**Comment by jheeffer** [comment]
Already fixed since it was reported
