### ISSUE TITLE
v0.7.1_19: Charts are not loading

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#526]
**SEVERITY:** Critical

**MODULE:**
* Pop by age chart
* Line chart

**Platform:** Nexus-5 (5.1.1) / Chrome 44.0

**RELEASE:** v0.7.1

**STEPS TO REPRODUCE:**
**For pop by age chart**
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.7.1/preview/popbyage.html
2)	Note that chart is not loading

**For line chart** 
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.7.1/preview/linechart.html
2)	Note that chart is not loading

**ACTUAL RESULTS:**
Pop by age and line charts are not loading on Nexus-5

**EXPECTED RESULTS:** 
 All charts should be loaded

**SCREENSHOT:**

![vizabi_android_07 1](https://cloud.githubusercontent.com/assets/9950837/9932399/02fe1976-5d5d-11e5-9e10-e36df2cd1ecd.png)

![vizabi_android_07 2](https://cloud.githubusercontent.com/assets/9950837/9932400/0308af26-5d5d-11e5-9058-bf1e462d36f8.png)

**Comment by angieskazka** [comment]
could not reproduce on Nexus-5 (5.1.1) / Chrome 45.0
could it be that you had some troubles with network? or maybe we fixed it somehow...
