### ISSUE TITLE
Select panel must show deselect buttons

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#527]
![image](https://cloud.githubusercontent.com/assets/496398/9932696/2cab93b4-5d46-11e5-9f72-6df2b675da65.png)

**Comment by arthurcamara1** [comment]
It's there if at least one country is selected.

![screen shot 2015-09-17 at 3 22 47 pm](https://cloud.githubusercontent.com/assets/3584238/9934265/710cb6b4-5d50-11e5-9f4d-f425672f80e4.png)

Seems to be a problem in that resolution.
