### ISSUE TITLE
Color palette is broken after changing in indicator

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#528]
Te colors change (after dropdown selection) but they don't update correctly until I click OK. This is disturbing
![image](https://cloud.githubusercontent.com/assets/496398/9932789/f198345c-5d46-11e5-877f-6aa6456036b7.png)
![image](https://cloud.githubusercontent.com/assets/496398/9932808/118f4142-5d47-11e5-8d46-6bf8df4c7517.png)

**Comment by angieskazka** [comment]
@olarosling  could not reproduce it 
On the screenshots above you clearly have done multiple actions to achieve that state. Can you remember how you got there?

**Comment by angieskazka** [comment]
Steps to reproduce:
change color to geo.name
refresh
change color to population

here you go

![image](https://cloud.githubusercontent.com/assets/3648190/10123682/8016a01e-6540-11e5-9f8e-eecac97cde10.png)

**Comment by angieskazka** [comment]
Where to look:
the shit most likely happens in buildScale method of color.js
debug the updateView method in colorlegend.js

please understand how the color legend and scales are working before hacking it!
