### ISSUE TITLE
Removed array from entities

### ISSUE THREAD

**Issue by amytych** [Gapminder/vizabi#53]
I tried to merge the latest commit on develop (2f86eac681b2098b1ecc4e6cec7d05873bd50dbd) removing the array from the entities but it causes an error in my tool.

`"Error: m30 can't find the entities"`

Upon some investigation I can see, that `this.getHook()` is being called multiple times, like dozens or even more, and sometimes `this._hooks` is an empty object when it's called.

I'm not sure why this happens and how to resolve it. Maybe it has something to do with the fact that I have multiple entities in my tool, defined like so:

            entities: {
                show: {
                    dim: 'adm1.name',
                    filter: {
                        'adm1': ['*']
                    }
                }
            },

            entities_world: {
                show: {
                    dim: 'geo',
                    filter: {
                        'geo': ['*']
                    }
                }
            },

            entities_shapes: {
                show: {
                    dim: 'name',
                    filter: {
                        'name': ['*']
                    }
                }
            },

Is this the proper way to define multiple entities?

**Comment by arthurcamara1** [comment]
Just noticed this has been fixed by fe034abde4185ed7d60dc6c3b8401cee100a73b6 Hooks were trying to load things before being fully initialized.
