### ISSUE TITLE
Hovering the first year's bubble brings label and numbers in wrong positions

### ISSUE THREAD

**Issue by arthurcamara1** [Gapminder/vizabi#532]
**URGENT BUG**

After 9abd354c0d9c94f5b79cfe3344e0f1434fe28ec3 (loading one year first), when hovering the bubble of the first loaded year, lines and tooltip appear in the wrong position (they appear in the position of the first bubble in the whole dataset).

For example, in the picture below, the Indian bubble is being hovered.

![screen shot 2015-09-18 at 3 11 21 pm](https://cloud.githubusercontent.com/assets/3584238/9959920/aec5ac3c-5e17-11e5-9ce1-7e74eff07dd0.png)

**Steps to reproduce**:
- Load bubble chart: 
- Wait for loading to be done
- hover a bubble

In other years (other than the one initially loaded), all seems fine. The screenshot below shots 1997:

![screen shot 2015-09-18 at 3 13 37 pm](https://cloud.githubusercontent.com/assets/3584238/9959954/e8ad91ee-5e17-11e5-8eb5-4690e11c83cb.png)

**This also affects the trails**

For some reason, the bubble trail for the first year loaded is replaced for the bubble trail of the first item in the dataset:

![screen shot 2015-09-18 at 3 15 09 pm](https://cloud.githubusercontent.com/assets/3584238/9959990/2c2b1932-5e18-11e5-8438-44de6ebb64af.png)

The trail for 2015 (first year loaded) is placed as the trail of 1800

![screen shot 2015-09-18 at 3 15 30 pm](https://cloud.githubusercontent.com/assets/3584238/9960005/3fc03c34-5e18-11e5-9a9b-e0ba5c4a856c.png)

**Comment by angieskazka** [comment]
the true reason: on first load the the interpolation index gets cached in `interpIndexes`
on second load the index is not being reset, so interpolator takes cached index 0 instead of the actual one
