### ISSUE TITLE
Black stroke around selected in mountain

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#536]
I can't see where Sweden is
![image](https://cloud.githubusercontent.com/assets/496398/10012283/e6ad1558-6106-11e5-8f50-173464aeda62.png)

**Comment by olarosling** [comment]
Is there anyway, we can put the stroke on the inside, and avoid the feeling that "sweden reaches all the way down under the extreme poverty line" ? 
![image](https://cloud.githubusercontent.com/assets/496398/10055161/fb932e06-6234-11e5-83fa-923b915e99a8.png)

**Comment by angieskazka** [comment]
Done in release v0.8
