### ISSUE TITLE
Deselecting on mountain label should use small close-cross

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#537]
Hovering the  label or the mountain, the small cross Circle should show up to the right of the Label in the mountain chart. By clicking a selected country´s shape, you can deselect it. And by clicking the label you also deselect it. I just want the cross sign to show up so that it's clear that you can get rid of the selection.
On touch screen, there must be a DESELECT button popping up. So the first click is like HOVER and then you select or deselect by explicitly clicking buttons with those words.

![image](https://cloud.githubusercontent.com/assets/496398/10012378/c63d11dc-6107-11e5-9c5c-bdde4d6151fe.png)

![image](https://cloud.githubusercontent.com/assets/496398/10012338/64fd4400-6107-11e5-8643-364f6fc3976a.png)

**Comment by angieskazka** [comment]
Make the same style of the cross as we have in bubblechart-component.js labels

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/595

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/614

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/626

**Comment by angieskazka** [comment]
done
