### ISSUE TITLE
Bubble-Label improvements 

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#538]
1) Center the text in the label, vertically and horizontally
2) When hitting chart-border, the whole label-border should be visible, and not get stuck under the chart-axis 
![image](https://cloud.githubusercontent.com/assets/496398/10012753/151b6d64-610b-11e5-84c6-d991a78696cb.png)

**Comment by angieskazka** [comment]
let @sergey-filipenko do this as well

**Comment by sergey-filipenko** [comment]
fixed in https://github.com/Gapminder/vizabi/pull/557

**Comment by arthurcamara1** [comment]
Fixed by @sergey-filipenko
