### ISSUE TITLE
Unstable modelReady invoke

### ISSUE THREAD

**Issue by kobylin** [Gapminder/vizabi#54]
Found bug.

How it is appears:

Init state: PopulationByAgeChart->modelReady should be invoked and print in console message __"model ready! ready "__

__Then__ 

Left only one submodel in __markers__ (comment __bar__):
https://github.com/kobylin/vizabi/blob/feature/population-by-age-chart-bug/preview_pages/_gapminder/population-by-age.html#L142

__No output in console.__

If I change state somehow. I.e. dragging slider modelReady() invoked then.

Looks that there is some problem in async calls.
To reproduce this bug simply clone and run locally branch for this bug https://github.com/kobylin/vizabi/blob/feature/population-by-age-chart-bug

I tried to fix it by myself but it was hard to find root of this bug.
But I can continue working.

**Comment by arthurcamara1** [comment]
Closed by 13d644236c654a241533ffe7b27dd7ecaaeb34ac
