### ISSUE TITLE
v0.7.1_20: Data is started to display after some time. // MIN-MAX problem with splash loading

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#540]
**SEVERITY:** Major

**MODULE:** Tool page

**Platform:**
* Windows 7 / Chrome 45.0
* Windows 7 / Firefox 41.0

**RELEASE:** v0.7.1

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://static.gapminderdev.org/tools/ 
2)	Tool page is loaded.
3)	Drag the slider ball to the start
4)	Click play
5)	Note that data is started to display after year 1849.

**ACTUAL RESULTS:**
Data is started to display after year 1849

**EXPECTED RESULTS:** 
Data should be shown from the start to the end

**SCREENSHOT:** 

![vizabi_tool_02](https://cloud.githubusercontent.com/assets/9950837/10017154/89a3197c-6145-11e5-8e98-7ac209c1f6e5.png)

**Comment by olarosling** [comment]
use this url: gapminderdev.org/tools/

**Comment by angieskazka** [comment]
Solution: 
1) get vizabi scale builders to read the min and max from metadata
2) have min max in metadata or calculated by server

**Comment by angieskazka** [comment]
introduced domain field in metadata. the init sequence for the domain is as follows:
default domain is based on limits
domain from metadata can override it if defined
min and max can override the domain if defined
