### ISSUE TITLE
Decrease the size of labels-color-circles 

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#542]
The colored circles could just be small dots.
![image](https://cloud.githubusercontent.com/assets/496398/10018668/e2b56af4-6138-11e5-9fbf-39d0065bf2ae.png)

**Comment by angieskazka** [comment]
![image](https://cloud.githubusercontent.com/assets/3648190/10032465/8c8760a6-6183-11e5-9f18-cd2b4639db38.png)
