### ISSUE TITLE
Data doubts 

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#544]
Remove the  ![image](https://cloud.githubusercontent.com/assets/496398/10019768/80cfb89c-613f-11e5-8d7a-2be77b36c88d.png)

A clickable icon and text saying ""DATA DOUBTS" below 
![image](https://cloud.githubusercontent.com/assets/496398/10019659/dd415bb8-613e-11e5-824b-927acd99647b.png)

( the bubble chart has doubt in the lower right corner. 
![image](https://cloud.githubusercontent.com/assets/496398/10019808/bfa77e42-613f-11e5-9b19-529531526e85.png)

Color: 
![image](https://cloud.githubusercontent.com/assets/496398/10019910/4ddf7516-6140-11e5-9c92-bfa9fa819300.png)

When clicked it opens a modal panel in front of the chart with a custom text (one text for income mountain and one for bubble chart ) 
Some thing like this (Allowing links in the text) 

![image](https://cloud.githubusercontent.com/assets/496398/10019703/11824b08-613f-11e5-9a80-8012a87ac531.png)

FYI: In the future this feature will be more advanced and allow users to quickly see a quantified measure of our doupts. If we believe te data might be 20% wrong, that will display in the chart, when clicking the button. We need a second column in the data next to every indicator, that displays the doupt as a numeric value between 0 and 100 ) The text will thne be a more info about the doubts levels .

**Comment by arthurcamara1** [comment]
Icon in svg : http://www.flaticon.com/free-icon/warning-sign-on-a-triangular-background_25411
