### ISSUE TITLE
Higher poverty line with text

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#545]
Extend dashed line vertically 
Add the text "EXTREME POVERTY" vertically rotated on the LEFT side of the line, WITH THE PERCENT HORIZONTALLY ABOVE THE LABEL
![image](https://cloud.githubusercontent.com/assets/496398/10020300/6f431404-6142-11e5-86ae-90fe12a766ed.png)

**Comment by angieskazka** [comment]
@olarosling the low positioning is for reason.

otherwise the clash with the select list will happen much sooner:

![image](https://cloud.githubusercontent.com/assets/3648190/10020163/a9fc42b0-6141-11e5-89f3-52248e458af2.png)

**Comment by olarosling** [comment]
Decrease fontsize of select labels to half and remove the notion of number of people

**Comment by olarosling** [comment]
I added this as well:
![image](https://cloud.githubusercontent.com/assets/496398/10020328/93ca9a54-6142-11e5-854b-9455f65e55de.png)

**Comment by arthurcamara1** [comment]
Plus, the fonts have a white border, it should be no problem for the dashed vertical line :+1:
