### ISSUE TITLE
Jumpy Year label in background

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#546]
See the tools page here: http://www.gapminder.org/tools/bubbles
Some fonts have different width of 1s and 0s, and these fonts are not equally centered for 2000 and 2001 etc because the center anchor moves.

When slide over time, the years jump horizontally. I'd like them to be centered in a way, so the two left digits expand to the left, and the two right digits to the right.
Imagine 1844 was rendered in two different text boxes. 18 in the left, which is right aligned
and 44 in the right text box which is left aligned
![image](https://cloud.githubusercontent.com/assets/496398/10020047/1800025c-6141-11e5-8f23-2cd8e0b4f912.png)

**Comment by angieskazka** [comment]
where to hack: 
mountainchart.html -- to make 2 pieces of <text> instead of one

mountainchart-component.js
methods: 
domReady() to reference the two elements
updateSize() to position them on the page (test all screen resolutions!)
updateTime() to update the values

**Comment by angieskazka** [comment]
@olarosling not agree. this violates your own word about not having jumping things not driven by the data (remember jumping labels that i did the other day) because they distract from the story and trying to tell you something via animation

suggesting let's do like this instead:

![image](https://cloud.githubusercontent.com/assets/3648190/10206371/da2fede8-67c6-11e5-9ad2-ccff3ce56f74.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/641

**Comment by arthurcamara1** [comment]
@sergey-filipenko submitted a solution with #641.

**Comment by angieskazka** [comment]
@sergey-filipenko it might be not that easy as it seems...

here i changed `font-family` to `fantasy` on mac (and it might be changed for anything)
1) the entire text is misaligned now. 
2) the label jumps really a lot when going from 1999 to 2000


![image](https://cloud.githubusercontent.com/assets/3648190/10371343/31b88c06-6de3-11e5-9fe4-db575312f13d.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/674
integrated to booblechart for now, It can be integrated to other charts when approved

**Comment by angieskazka** [comment]
approved! can you please also integrate it to mountain chart? (and avoid jumping label from one side to another as the app loads)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/676

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/679

**Comment by angieskazka** [comment]
thanks! @sergey-filipenko
