### ISSUE TITLE
hover labels must stay within chart

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#550]
![image](https://cloud.githubusercontent.com/assets/496398/10027506/a89f529c-6167-11e5-8204-9b7abf870108.png)

**Comment by sergey-filipenko** [comment]
related to #552

**Comment by arthurcamara1** [comment]
Actually assigned to @sergey-filipenko, he's working on it :+1:

**Comment by sergey-filipenko** [comment]
fixed in https://github.com/Gapminder/vizabi/pull/557
