### ISSUE TITLE
selected label shouldn't overlap with bubble

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#552]
Find a default position that is not overlapping with bubbl.
![image](https://cloud.githubusercontent.com/assets/496398/10027639/6f3e6abe-6168-11e5-92cc-0c451c476502.png)

**Comment by arthurcamara1** [comment]
Actually assigned to @sergey-filipenko, he's working on it :+1:

**Comment by sergey-filipenko** [comment]
done
https://github.com/Gapminder/vizabi/pull/557

**Comment by arthurcamara1** [comment]
Fixed by @sergey-filipenko
