### ISSUE TITLE
Get more then one dimension in the hooks

### ISSUE THREAD

**Issue by kobylin** [Gapminder/vizabi#56]
My question is is it possible to get more then one dimension in model(hook)?

Cause I'm filtering using two specific properties - geo and age_group
https://github.com/kobylin/vizabi/blob/feature/population-by-age-chart/src/components/_gapminder/population-by-age-chart/population-by-age-chart.js#L136
But age_group item not exists in items, only pop.

I want to do something like this,
but it is not working https://github.com/kobylin/vizabi/blob/feature/population-by-age-chart/preview_pages/_gapminder/population-by-age.html#L134

**Comment by ambodi** [comment]
I need this to test the multicsv reader. any updates on this issue?

**Comment by ambodi** [comment]
Any updates on this. Need it for complete example of Multicsvreader.

**Comment by arthurcamara1** [comment]
There are no updates on this yet, meaning that the query with multiple dimensions is not automatically constructed yet. However, I think what you could do not to get blocked is simulating, or hardcoding the query yourself.

If you extend a model you can overwrite the default `getQuery` function of the model and include a query that has more than one dimension:

Example:

```javascript
var popAgeModel = Model.extend({
        //...
        getQuery: function() {
                return [{
                        "from": "data",
                        "select": ["geo", "age", "time", "pop"],
                        "where": {
                                "geo": ["swe", "fin", "nor"],
                                "age": ["1", "100"],
                                "geo.category": ["country"],
                                "time": ["1990", "2010"]
                        }
                }];
        }
});
```

Then it's possible to work on understanding that type of query and reading from multiple CSV files.

**Comment by ambodi** [comment]
@arthurcamara1 that is true, however, this will bypass hooks. right? Because if so, we need to change requirement as we agreed to use hooks for CSV example.

**Comment by arthurcamara1** [comment]
Yes, this will bypass the hooks' automatic  query construction. But its a
simple solution that will unblock the multiCSVReader task to do the other
things related to the reader itself when there are more dimensions (The
reader itself is unrelated to query construction because it should not
matter to a reader how the query was built, it just receives a query and
behaves accordingly). Later, when multi dimensions get
supported, we could remove these few lines. Just a suggestion not to
be blocked :)

On Wednesday, January 21, 2015, Amir Rahnama <notifications@github.com>
wrote:

> @arthurcamara1 <https://github.com/arthurcamara1> that is true, however,
> this will bypass hooks. right? Because if so, we need to change requirement
> as we agreed to use hooks for CSV example.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Gapminder/vizabi/issues/56#issuecomment-70839729>.
>


-- 

*Arthur Camara*
*Software Engineer*
Gapminder Foundation
www.gapminder.org

**Comment by ambodi** [comment]
Well I am fine with it, if @olarosling agrees :smile: I got it from him that he wanted me to do it with hooks.

**Comment by ambodi** [comment]
I edited the title of the issue, because apparently it works with models but not hooks :smile:

**Comment by arthurcamara1** [comment]
This is already supported now after cae456e251a21b0bd9278bbf173eb3ab54b1c049
