### ISSUE TITLE
Hide Ordinal from color settings pane

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#561]
Don't show Ordial Dropdown in settings pane for color
In Settings Panel we can have it: but ot if it's passive like in this case.
![image](https://cloud.githubusercontent.com/assets/496398/10129970/0fa56548-65c4-11e5-81f7-3e8c9462a421.png)

**Comment by angieskazka** [comment]
where to hack:
indicatorpicker.js

how to hack:
take a look ar redraw() method. 
hide the second selector if 'use' of the attached model is == "property" 

(not if "scaletype" is "ordinal". it's a consequence of "use" being a "property")

**Comment by angieskazka** [comment]
@sergey-filipenko 
if i understood @olarosling correctly, we should only hide the control when it shows "ordinal", not when it shows one option. It's good to see if the scale is linear ot log

in this sense, please see what the proper fix should have looked like
