### ISSUE TITLE
getting issue in bubble chart after get update

### ISSUE THREAD

**Issue by chauhanmohit** [Gapminder/vizabi#570]
![vizabi bubble chart](https://cloud.githubusercontent.com/assets/13454062/10191004/1db80c00-678e-11e5-9658-4f34d375f32e.png)

**Comment by angieskazka** [comment]
The build broke most likely because of this:
https://github.com/Gapminder/vizabi/wiki/Updates-on-dev-environment-Sept-28

then, try pulling again, we fixed a bunch of things recently

**Comment by angieskazka** [comment]
resolved by updating the environment
