### ISSUE TITLE
Tools_v0.8.1 _01: Drag symbol is not center aligned on Windows (but OK on Mac)

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#576]
**Release:** v0.8.1

**Testing Link:** http://128.199.60.177:8080/tools/ 

**Module:** Tools page (Bubble Chart)

**Description:**
Already reported on  /gapminder-tools-vizabi/issues  as :
 https://github.com/Gapminder/gapminder-tools-vizabi/issues/42  
But it needs to be logged here.

**Comment by angieskazka** [comment]
where to hack:
_dialog.scss
.html of every dialog (search the respective classes across the project)

solution:
changing constants in scss
OR! a more proper fix might be possible. why not applying `vzb-button` class to drag and pin icons?
and make these buttons similar to the buttons in the button list
this will also make it cleaner

test on mac and windows.

**Comment by arthurcamara1** [comment]
Couldn't reproduce. Can you retest?

**Comment by angieskazka** [comment]
looks good on all combinations: Win7, Mac, Chrome, Firefox, Safari
