### ISSUE TITLE
Tools_v0.8.1 _02: Alignment of “?” is disturbed by reducing screen size.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#577]
**Release:** v0.8.1

**Testing Link:** http://128.199.60.177:8080/tools/ 

**Module:** Tools page (Bubble Chart)

**Description:**
Already reported on  /gapminder-tools-vizabi/issues  as :
 https://github.com/Gapminder/gapminder-tools-vizabi/issues/44   
But it needs to be logged here.

**Comment by angieskazka** [comment]
Where to hack
bubblechart-component.js
mountainchart-component.js

Solution: 
replace the <circle> + <text> element with this svg icon from base/iconset.js
`iconset.question`
(see how the iconset is used)

adjust the styling so that it looks similar to how we have it now
