### ISSUE TITLE
Tools_v0.8.1 _04: Slider ball of “Minimum bubble size” is crossing slider ball of “Maximum bubble size”

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#579]
**Release:** v0.8.1

**Testing Link:** http://128.199.60.177:8080/tools/ 

**Module:** Tools page (Bubble Chart)

**Description:**
Already reported on  /gapminder-tools-vizabi/issues  as :
 https://github.com/Gapminder/gapminder-tools-vizabi/issues/49 

But it needs to be logged here.

**Comment by angieskazka** [comment]
this will be naturally resolved when we introduce a new `bubblesize` slider with two handles. 
see #376 

of course, the slider with two handles should make it impossible for one handle to cross or jump over the other

**Comment by angieskazka** [comment]
solved with a new slider with two handles

![image](https://cloud.githubusercontent.com/assets/3648190/10427012/1af0c1d6-70e6-11e5-861e-3eabc03920a9.png)
