### ISSUE TITLE
Tools_v0.8.1 _07: Some bubbles are going out of defined boundary while making trails

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#582]
**Release:** v0.8.1

**Testing Link:** http://128.199.60.177:8080/tools/ 

**Module:** Tools page (Bubble Chart)

**Description:**
Already reported on  /gapminder-tools-vizabi/issues  as :
 https://github.com/Gapminder/gapminder-tools-vizabi/issues/54     

But it needs to be logged here.

**Comment by angieskazka** [comment]
as Hans says, these are terrible events in human history
i suggest leave it up to the user to define the domain in metadata and not to extend it automatically
