### ISSUE TITLE
Tools_v0.8.1 _08: Trails are not visible due to messed bubbles

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#583]
**Release:** v0.8.1

**Testing Link:** http://128.199.60.177:8080/tools/ 

**Module:** Tools page (Bubble Chart)

**Description:**
Already reported on  /gapminder-tools-vizabi/issues  as :
 https://github.com/Gapminder/gapminder-tools-vizabi/issues/56 
     
But it needs to be logged here.

**Comment by angieskazka** [comment]
They are actually working but hidden below many other bubbles =) Roll the time slider a bit further and you can see it

![image](https://cloud.githubusercontent.com/assets/3648190/10244341/cc419720-68fe-11e5-9949-12821be4cbd7.png)
![image](https://cloud.githubusercontent.com/assets/3648190/10244371/fbd2a9ac-68fe-11e5-87bf-75a4bd8d8aa0.png)


Solution: the user created a mess by setting bubble sizes to a variable similar in many countries
let the user decrease the opacity of the non-selected:

![image](https://cloud.githubusercontent.com/assets/3648190/10244404/4ae88ba6-68ff-11e5-8638-438f1b0df68e.png)

or the max size of bubbles. 

![image](https://cloud.githubusercontent.com/assets/3648190/10244414/6194d116-68ff-11e5-989c-61dead66d1bb.png)

then the thing gets visible! 
@k6Labz please not reopen :-)
