### ISSUE TITLE
Fit the little world map horizontally. 

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#585]
after merging #584, the bubble got resized so that Australia and South America cuts off
please adjust the styling of the <svg> so that the map fits horizontally (and it might scroll vertically if it's just a little fraction, as before)

![image](https://cloud.githubusercontent.com/assets/3648190/10242748/5190e5ae-68f3-11e5-93b9-224a443a4a81.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/586
