### ISSUE TITLE
Tools_v0.8.1 _10: Treemenu: Pop up screen size is reduced by hovering  effect

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#588]
**SEVERITY:** Minor

**MODULE:** Tools page (Bubble Chart)

**Platform:**
* Windows 7 / Chrome 45.0
* Windows 7 / Firefox 42.0
* MAC / Safari 8.0

**RELEASE:** v0.8.1

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://128.199.60.177:8080/tools/
2)	Tools page is loaded.
3)	Click Y axis or X axis label
4)	Take mouse over small pop up screen
5)	Note that the small screen size is reduced automatically by hovering effect

**ACTUAL RESULTS:**
After clicking X axis or Y axis a small pop up screen is displayed, that pop up screen size is reduced by hovering effect.

**EXPECTED RESULTS:** 
Pop up screen size should not change by hovering effect 

**SCREENSHOT:** 

![tools_page_v0 8 1 _02 1](https://cloud.githubusercontent.com/assets/9950837/10247209/02dd2c2c-6931-11e5-989e-bef0333ff817.png)

![tools_page_v0 8 1 _02 2](https://cloud.githubusercontent.com/assets/9950837/10247217/0932e972-6931-11e5-8fe2-dc3c86b1cf86.png)

**Comment by angieskazka** [comment]
Where to hack:
treemenu.js 
_treemenu.scss

**Comment by dab2000** [comment]
Which menu size(width) is right? before hovering or after hovering?

**Comment by angieskazka** [comment]
fixed now
