### ISSUE TITLE
Tools_v0.8.1 _11: Treemenu: Marque animation sucks //Arrow indicator is overlapping with the text

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#589]
**SEVERITY:** Minor

**MODULE:** Tools page (Bubble Chart)

**Platform:** 
* Windows 7 / Chrome 45.0
* MAC / Safari 8.0

**RELEASE:** v0.8.1

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://128.199.60.177:8080/tools/
2)	Tools page is loaded.
3)	Click Y axis or X axis label
4)	Take mouse to “Wealth” , two more options are shown
5)	Now mouse to first option
6)	Note that arrow indicator is overlapping with the text

**ACTUAL RESULTS:**
Arrow indicator is overlapping with the text by hovering the text.

**EXPECTED RESULTS:** 
Arrow indicator should not overlap with the text by hovering the text

**SCREENSHOT:**

![tools_page_v0 8 1 _03](https://cloud.githubusercontent.com/assets/9950837/10247279/697f9fc8-6931-11e5-9fc6-4de5cca4b847.png)

**Comment by angieskazka** [comment]
Solution: 
1. make arrow stick to the right, like the issue suggests
2. edit keyframes so that marque animation always runs one direction: right to left
3. also it should not leave 100% blank space, but run infinintely, with the beginning of text visible while the end of text is still there

```
wrong:
[This is the end of text...  ]
[ of text...                 ]
[f text...                   ]
[xt...                       ]
[                   Beginning]

correct:
[This is the end of text...  ]
[ of text...        Beginning]
[f text...        Beginning o]
[xt...        Beginning of te]
```

**Comment by angieskazka** [comment]
nice solution by @dab2000

**Comment by k6Labz** [comment]
**Retest Result:** Fail

**Testing Environment - DEVELOP:** http://dev-tools.gapminderdev.org:3001/ 

**Screenshot:** 
![1](https://cloud.githubusercontent.com/assets/9950837/10722073/2641eff4-7bce-11e5-9cff-e9fdc469d1ca.png)

**Comment by arthurcamara1** [comment]
The arrow div should have a background that covers the words behind it.

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Platform:** Windows 7 / Chrome 48.0

**Testing Environment - DEVELOP:** http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Platform:** Windows 7 / Chrome 48.0

**Testing Environment - DEVELOP:** http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html
