### ISSUE TITLE
Tools_v0.8.1 _14: Treemenu: No options are displayed by clicking or hovering the arrow indicator of  axes options

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#592]
**SEVERITY:** Major

**MODULE:** Tools page (Bubble Chart)

**Platform:** 
* Windows 7 / Firefox 42.0
* MAC / Safari 8.0
* iPad Air 2 iOS(8.3) / Safari 8.0
* Nexus 9 (5.0.1) / Chrome 45.0 

**RELEASE:** v0.8.1

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://128.199.60.177:8080/tools/
2)	Tools page is loaded.
3)	Click the given option with an arrow indicator
4)	Note that no options are displayed by clicking or hovering the arrow indicator of  axes options

**ACTUAL RESULTS:**
No options are displayed by clicking or hovering the arrow indicator of axes options 

**EXPECTED RESULTS:** 
 Options should be available by clicking or hovering the arrow indicator of axes options

**SCREENSHOT:**

![tools_page_v0 8 1 _06](https://cloud.githubusercontent.com/assets/9950837/10247360/01b30b0e-6932-11e5-965b-57ca36ace87f.png)

**Comment by k6Labz** [comment]
**Retest Result:** Fail

**Testing Environment:** http://static.gapminderdev.org/vizabi/develop/preview/

**Comment by arthurcamara1** [comment]
Apparently N/A anymore
