### ISSUE TITLE
Sizing of the panels

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#604]
Propose and develop the solution so that the sizing of the panel is nice

Like, we want `size` and `color` to be of a certain min-size and max-size
While we want `find` to be a different, a larger max-size, because of the long list. let it expand height while the others would stay small. 

If the dialogs don't fit in their min-size, then let the lowest dialog behave like a any other button that is not in `buttons_expand`, so let it collapse. The rest would resize to fill the space as long as their max-size would allow

**Comment by angieskazka** [comment]
I couldn't see it working (Mac + Chrome)

in this case it would be reasonable to let the list in "Find" dialog fill the space, rather than to have it blank
you need a generic solution to distribute free space between dialogs height based on their "needs". `Size` and `Axes` need fixed height, `Color` and `Stack` need minimum, some stretching if it has a scrollable list in it, and maximum, `find` needs minimum and then as much as possible. Sometimes color, find and stack come together and they need to share it smart!

![image](https://cloud.githubusercontent.com/assets/3648190/10418478/590a0322-705c-11e5-86a3-9d090b52e9af.png)

**Comment by arthurcamara1** [comment]
**SOLUTION**

This can be easily done with flexbox.

![image](https://cloud.githubusercontent.com/assets/3584238/10423213/5b9d0356-70c4-11e5-90f3-6171a37e02c8.png)

**Checkout the prototypical code I wrote here:**
http://codepen.io/arthurcamara1/pen/yYogZz

*How does it work?*
The expanded sidebar is styled as:
```css
display: flex
```

All sidebar dialogs and buttons container have the following:
```css
flex-grow: 0
```

The **Find** dialog (or others that expand) are styled as:
```css
flex-grow: 1;
overflow: auto; //to allow scrolling
```

We should add a property to control which dialogs grow or not here: https://github.com/Gapminder/vizabi/blob/develop/src/components/buttonlist/buttonlist.js#L46 . That will add a class to the dialog to be styled like the Find example above

**Comment by arthurcamara1** [comment]
@Rathunter

**Comment by arthurcamara1** [comment]
HI @Rathunter :) Any progress on this? Need help?

**Comment by Rathunter** [comment]
I have tried what you have suggested. Applying dispay:flex to the parent and flex-grow to children has worked on the top level as you could see from the code that was merged in by Angie. This does position the little buttons on the bottom and grows the panel that holds the expanded dialogs to 100% of what height is left. 
The issue I am having now is how to position the dialogs inside the panel as the HTML structure is this way:
<div //button-list// > (style = {display:flex, flex-direction: column;})
  <div // dialogs//>  (style = {flex-grow: 1;})
    <div //dialog1//></div> 
    <div //dialog2//></div>
    <div //dialog3//></div>
  </div>
  <div // buttons//>  (style = {flex-grow: 0;})
  </div>
</div>

How do I make the dialog1, dialog2, dialog3 flex-grow or not grow within the dialogs container? 
Do I need to make the dialogs and buttons on the same level (in html)?

**Comment by arthurcamara1** [comment]
@Rathunter aha, I see. You can solve that by applying another layer of flex-box, in the dialog itself. We could apply `flex-grow` to the containe, along with another `display:flex; flex-direction:column` in each dialog wrapper, and apply `flex-grow` to the divs inside the dialog.

Let me try to draw it to make it clear:

![flexbox](https://cloud.githubusercontent.com/assets/3584238/10616557/f3809348-7765-11e5-935d-8d57a600dc3c.png)

Notice the `flex-grow: 1` **both** in the outter div (dialog) and in the inner panel of "Find" (the one that will actually fill up the space).

Of course, this is generic with any dialog (not necessarily "Find", but the ones we define was "growable")

**IN PRACTICE, THE SOLUTION IS**

Container `.vzb-dialog-side`: `flex-grow: 1` or `flex-grow: 0` depending on whether it grows or not.

Dialog wrapper `.vzb-dialog-modal`: `display: flex; flex-direction: column`

Dialog title `.vzb-dialog-title`: `flex-grow: 0`

Dialog contents `.vzb-dialog-content`: `flex-grow: 1` or `flex-grow: 0` depending on whether it grows or not.

Let me know if you run into trouble :+1:

**Comment by arthurcamara1** [comment]
Also, make sure the compiled final version contains the correct prefixes. It's supposed to be included _automatically_ by autoprefixer. But if it's not, you might have to add them yourself. I would assume it's added automatically.

Useful reference: https://css-tricks.com/using-flexbox/

**Comment by Rathunter** [comment]
I tried what you have suggested. Not getting the desired results.

**Comment by angieskazka** [comment]
looks like done, but i can't test on my small screens yet
