### ISSUE TITLE
Confusing namings (domain, property, indicator, value)

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#61]
1. "Domain" `this.model.marker.axis_y.getDomain();` This actually returns a D3 scale object, while "domain" is one property of the scale. We should stick to this D3 convention. Should be `hook.getScale()`. `hook.scale = 'log'` should be `hook.scaleType = 'log'`or something like it.

2. "Property" is a generic term used for object properties and we can't reuse it differently for our needs. When referring to property-property .geo as opposed to property-indicator .lex we should use "dimension" .geo, following the "dimension-measure" convention. See below

3. "Indicator" is ok and valid. It is a synonym of "measure". Correct me if i'm wrong, but there is already a convention in visualization community about dimensions and measures. A quick search gives examples [here](http://www.newmediamarketer.com/dimensions-vs-measures/), and [here](http://onlinehelp.tableausoftware.com/v6.1/public/online/en-us/Id112A8A00YEX.html). 

4. "Value" has 3 different uses. Already pointed this to @arthurcamara1. In `model.js` we had `this.value` which would store "lex" or "gdp" for the hook. Should be something like `this.name` instead. Function `getValue()` returns a requested interpolated value from the dataset. I guess it is logical, but we also had `getItems()` and `this._items` which have the meaning of values. Lastly, we call it one of hook types, for example `use: "value", value: 42`. Should be `use: "constant", value: 42`.

**Comment by gapminderdeploy** [comment]
@angie: 1: Yes probably, 2; No ;our model is richer, 3; Don't understand what you mean?

**Comment by angieskazka** [comment]
and 4: should be yes
