### ISSUE TITLE
v0.8.1_22: Cross symbol is not center aligned

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#611]
**SEVERITY:** Minor

**MODULE:**  Bubble Chart

**Platform:**
* Windows 7 / Chrome 45.0

**RELEASE:** v0.8.1

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.1/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Click axes description, a small pop up screen is displayed
4)	Take the mouse over cross button on that small pop up screen
5)	Note that cross symbol is not center aligned

**ACTUAL RESULTS:**
Cross symbol is not center aligned 

**EXPECTED RESULTS:** 
Cross symbol should be center aligned 

**SCREENSHOT:**

![v0 8 1_22](https://cloud.githubusercontent.com/assets/9950837/10280467/f601d658-6b86-11e5-85b2-88988e6ecb53.png)

**Comment by k6Labz** [comment]
**Retest Result:** Fail

**Testing Environment:** http://static.gapminderdev.org/vizabi/develop/preview/

**Comment by angieskazka** [comment]
treemenu.js
datawarning.js

replace HTML cross with a similar SVG icon

**Comment by angieskazka** [comment]
The above solved the issue. thanks!
