### ISSUE TITLE
v0.8.1_23: Text is overlapping by changing the language

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#612]
**SEVERITY:** Minor

**MODULE:** Bubble Chart

**Platform:** 
* Windows 7 / Chrome 45.0
* MAC / Safari 8.0
* iPad Air 2 iOS(8.3) / Safari 8.0
* Nexus 9 (5.0.1) / Chrome 45.0

**RELEASE:** v0.8.1

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.1/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Click switch language
4)	Note that text is overlapping 

**ACTUAL RESULTS:**
Text is overlapping by changing the language 

**EXPECTED RESULTS:** 
Text should not overlap 

**SCREENSHOT:**

![v0 8 1_23](https://cloud.githubusercontent.com/assets/9950837/10280494/1d9dc5f0-6b87-11e5-94d3-9b8eee4e3590.png)

**Comment by k6Labz** [comment]
**Retest Result:** Fail

**Release:** v0.8.3

**Testing Environment:** http://static.gapminderdev.org/vizabi/release/v0.8.3/preview/bubblechart.html

**Comment by angieskazka** [comment]
i see this. can you post a screenshot? @k6Labz 

![image](https://cloud.githubusercontent.com/assets/3648190/10573882/e043f220-7652-11e5-9f61-ca53587d80a6.png)

**Comment by k6Labz** [comment]
![222](https://cloud.githubusercontent.com/assets/9950837/10574153/9efeab5a-766d-11e5-8ee1-7e6ccce7b47f.png)

**Comment by angieskazka** [comment]
@k6Labz yes, and how about develop? i just have done it recently, so it should be included in 0.8.4, not 0.8.3

can you check the develop too?

**Comment by angieskazka** [comment]
ok, it's probably done. @k6Labz please open if persists on 0.8.4 and above, thanks

**Comment by k6Labz** [comment]
**Retest Result:** Fail

**Platform:** Nexus 9 (5.0.1)/Google Chrome 45.0

**RELEASE:** v0.8.4

**STEPS TO REPRODUCE:** 
1)	Navigate to URL : http://static.gapminderdev.org/vizabi/release/v0.8.4/preview/bubblechart.html
2)	Tap the switch language button under “Interaction buttons” sections.
3)	Tap on “X and Y” button.
4)	A pop-up will appear and choose (BNP per invanare) for X-axis and indicator for Y-axis.
5)	Text on the x-axis is overlapped by the “Data Doubts” in portrait view of “Responsiveness”.

**ACTUAL RESULTS:** Text on the X-axis is overlapped by the “Data Doubts”

**EXPECTED RESULTS:** Text on the X-axis should not be overlapped by the Data Doubts.

**Screenshot:**

![v0 8 4_02](https://cloud.githubusercontent.com/assets/9950837/10729143/1597201c-7c09-11e5-92c5-efb8a86f76db.png)

**Comment by arthurcamara1** [comment]
@angieskazka is this still happening? reassign if appropriate and check if effort1: easy is fair :)

**Comment by angieskazka** [comment]
@k6Labz please retest on develop. and the same device

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Platform:** Nexus 9 (5.0.1)/Google Chrome 45.0

**Testing Environment - DEVELOP:** http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html

**Comment by angieskazka** [comment]
:metal: :dizzy_face: :metal:
