### ISSUE TITLE
Lines when hovering bubbles are broken

### ISSUE THREAD

**Issue by arthurcamara1** [Gapminder/vizabi#615]
STEPS TO REPRODUCE:
1) Navigate URL: http://static.gapminderdev.org/vizabi/develop/preview/
2) Bubble chart page will be loaded
3) Hover a bubble

![image](https://cloud.githubusercontent.com/assets/3584238/10281088/6ec89c44-6b72-11e5-8618-27104c875340.png)

**Comment by angieskazka** [comment]
strange, i fixed this before but my fix got overwritten by some other pull
