### ISSUE TITLE
v0.8.1_25 : Text is overlapped and Y axis marking is disturbed by changing the orientation on Firefox

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#618]
**SEVERITY:** Minor

**MODULE:**  Bubble Chart

**Platform:** Windows 7 / Firefox 42.0

**RELEASE:** v0.8.1

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.1/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Change the orientation of the chart  to landscape
4)	Note that text is overlapping
5)	Also note that Y axis marking is disturbed, -6.0 has been shifted upward. 

**ACTUAL RESULTS:**
Text is overlapped and Y axis marking is disturbed by changing the orientation on Firefox  

**EXPECTED RESULTS:** 
Text should not overlap and marking should be proper. The axis values should be written according to their marking on the axis, like -6.0 should be written against its own mark on the axis not against 0 mark on the axis.

**SCREENSHOT:**

![v0 8 1_25](https://cloud.githubusercontent.com/assets/9950837/10308551/d7639e7e-6c4f-11e5-8533-b16235389368.png)

**Comment by angieskazka** [comment]
Please retest on develop. http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Testing Environment:** DEVELOP Branch - http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html
