### ISSUE TITLE
v0.8.1_27: Pop up screen is disturbed 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#621]
**SEVERITY:** Major

**MODULE:**  Bubble Chart

**Platform:**
* Windows 7 / Chrome 45.0
* Windows 7 / Firefox 42.0
* MAC / Safari 8.0
* iPad Air 2 iOS(8.3) / Safari 8.0
* Nexus 9 (5.0.1) / Chrome 45.0

**RELEASE:** v0.8.1

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.1/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Click “Find”. Small pop up screen is displayed
4)	Now again click “Find”. Small pop up screen is disappeared
5)	Click "Full" or “Landscape” button under RESPONSIVENESS
6)	Again click “Find”
7)	Note that small pop up screen is disturbed  

**ACTUAL RESULTS:**
Small pop up screen is disturbed after clicking “Find” options which is available on the chart.  This happens in another way also. After loading chart on Firefox, click random button under responsiveness until all options are displayed. Then click any options and see that same issue is there.

**EXPECTED RESULTS:** 
Small pop up screen should not be disturbed

**SCREENSHOT:** 

![v0 8 1_27](https://cloud.githubusercontent.com/assets/9950837/10308714/1bab7f1a-6c51-11e5-9e4e-eb8d384df28d.png)

**Comment by k6Labz** [comment]
**Retest Result:** Failed

**Release:** v0.8.3

**Testing Environment:** http://static.gapminderdev.org/vizabi/release/v0.8.3/preview/bubblechart.html

**Comment by angieskazka** [comment]
fixed
