### ISSUE TITLE
v0.8.1_28: There is space between heading and the description 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#622]
**SEVERITY:** Minor

**MODULE:**  Mountain Chart

**Platform:**
* Windows 7 / Chrome 45.0
* Windows 7 / Firefox 42.0
* MAC / Safari 8.0
* iPad Air 2 iOS(8.3) / Safari 8.0
* Nexus 9 (5.0.1) / Chrome 45.0
* Nexus 5 (5.1.1) / Chrome 44.0

**RELEASE:** v0.8.1

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.1/preview/mountainchart.html 
2)	Mountain chart page will be loaded
3)	Click “X and Y”
4)	Note that there is space between heading and the description

**ACTUAL RESULTS:**
There is space between heading and the description.

**EXPECTED RESULTS:** 
Spacing should be reduced between heading and the description

**SCREENSHOT:**

![v0 8 1_28](https://cloud.githubusercontent.com/assets/9950837/10308741/4246bc16-6c51-11e5-934b-320bf70b288d.png)

**Comment by angieskazka** [comment]
i might have partially fixed it. please pull from develop and check
