### ISSUE TITLE
v0.8.1_30: Color is not changed according to the selected option

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#624]
**SEVERITY:** Major

**MODULE:**  Line Chart

**Platform:**
* Windows 7 / Chrome 45.0
* Windows 7 / Firefox 42.0
* MAC / Safari 8.0
* iPad Air 2 iOS(8.3) / Safari 8.0
* Nexus 9 (5.0.1) / Chrome 45.0
* Nexus 5 (5.1.1) / Chrome 44.0

**RELEASE:** v0.8.1

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.1/preview/linechart.html 
2)	Line chart page will be loaded
3)	Click “Color”
4)	Select any option
5)	Note that there is no color change after selecting any other color options

**ACTUAL RESULTS:**
Color is not changed according to the selected option.

**EXPECTED RESULTS:** 
Color should be changed according to the selected options

**SCREENSHOT:**

![v0 8 1_30](https://cloud.githubusercontent.com/assets/9950837/10308775/91925564-6c51-11e5-9499-077a49ede6b2.png)

**Comment by k6Labz** [comment]
**Retest Result:** Fail

**Platform:** Windows 7 / Chrome 48.0

**Testing Environment:** http://static.gapminderdev.org/vizabi/release/v0.8.5/preview/linechart.html

**Comment by angieskazka** [comment]
fixed now
