### ISSUE TITLE
Timeslider not dragging until the end

### ISSUE THREAD

**Issue by arthurcamara1** [Gapminder/vizabi#627]
Page to reproduce: http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html and mountain chart

After a certain year, I can't drag the timeslider any further. I'm able to change the year, but the handle doesn't move further:

![image](https://cloud.githubusercontent.com/assets/3584238/10310830/36d521cc-6c44-11e5-91f9-00b338b1d22c.png)

**Comment by angieskazka** [comment]
solved by @sergey-filipenko in ea461b37ca0221e27b8c02bd8c8d5979855bbdd5 or nearby somewhere
