### ISSUE TITLE
presence of time with geo.name and geo in hooks/model default query

### ISSUE THREAD

**Issue by ambodi** [Gapminder/vizabi#63]
Our ```select``` clause of our default query is created in form of ```['time', 'geo']``` whenever a value is not explicitly mentioned. The question is what does this mean, really. Because asking about both ```geo``` and ```geo.name``` make sense and presence of ```time``` next to them does not make any sense anymore. 

This makes ```reader``` confused as in what time values can relate to ```geos``` without an time-based indicator which seems to be missing in the query.

**Comment by gapminderdeploy** [comment]
1) We should have a default query 2) Are quoting the SELECT part or the
WHERE part?

**Comment by gapminderdeploy** [comment]
SORRY MY MISSTAKE: 1 should say: "We should NOT  have a default query."
with a NOT

**Comment by arthurcamara1** [comment]
`geo.name` is *not* included in default query in the select part. `geo` and `time` are because in the current version of develop, it looks for time and entities if `hook_to` is not explicitely stating something different. Still, this is temporary and will change after 9dca5f3ac72ca3dcdeb993009e77eda9047f00f6 is merged to develop.

**Comment by arthurcamara1** [comment]
So, clarifying, the idea is that when `hook_to` is not explicit in the current version, a hook like this:
```javascript
bubble: {
     use: "indicator",
     value: "pop"
}
```
produces a query like
```javascript
select: ['geo', 'time', 'pop']
```
and a hook like:
```javascript
bubble: {
     use: "property",
     value: "geo.name"
}
```
produces a query like
```javascript
select: ['geo', 'time', 'geo.name']
```

so only 'geo' and 'time' are "default" in this version. but will be flexible, like I mentioned.

**Comment by ambodi** [comment]
Updated the question. Two points: 1) the mentioned part is the ```select``` clause. 2) ```geo.name``` was mentioned wrong in the ```select``` clause.
