### ISSUE TITLE
v0.8.1_34: Treemenu: No options are available by clicking axes description

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#631]
**SEVERITY:** Major

**MODULE:**  Bar chart

**Platform:**
* Windows 7 / Chrome 45.0
* Windows 7 / Firefox 42.0

**RELEASE:** v0.8.1

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.1/preview/barchart.html 
2)	Bar chart is loaded
3)     Click "Full" under RESPONSIVENESS
4)	Click on the axes description
5)	Note that no options are available by clicking axes description

**ACTUAL RESULTS:**
No options are available by clicking axes description 

**EXPECTED RESULTS:** 
Options should be available by clicking axes description

**SCREENSHOT:** 

![v0 8 1_34](https://cloud.githubusercontent.com/assets/9950837/10337111/097931fe-6d17-11e5-951e-e2ab99cc676c.png)

**Comment by k6Labz** [comment]
**Retest Result:** Fail

**Testing Environment:** http://static.gapminderdev.org/vizabi/develop/preview/

**Comment by angieskazka** [comment]
yes, now i could reproduce it. thank you

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/680

**Comment by k6Labz** [comment]
**Retest Result:** Failed

**Release:** v0.8.3

**Testing Environment:** http://static.gapminderdev.org/vizabi/release/v0.8.3/preview/bubblechart.html

**Comment by angieskazka** [comment]
fixed on develop
