### ISSUE TITLE
v0.8.1_35: Line is missing under the options

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#632]
**SEVERITY:** Minor

**MODULE:** Bar chart

**Platform:** Windows 7 / Chrome 45.0

**RELEASE:** v0.8.1

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.1/preview/barchart.html 
2)	Bar chart is not loaded
3)	Click on the axes description
4)	Click “Wealth”. “GDP per capita” option is shown
5)	Note that there is no line under the “GDP per capita” option

**ACTUAL RESULTS:**
There is no line under the “GDP per capita” option. 

**EXPECTED RESULTS:** 
Ending line should be there under the “GDP per capita” option.

**SCREENSHOT:** 

![v0 8 1_35 1](https://cloud.githubusercontent.com/assets/9950837/10337179/71e0d468-6d17-11e5-9ddb-f0ee1d0e9e61.png)

![v0 8 1_35 2](https://cloud.githubusercontent.com/assets/9950837/10337180/71e6fcd0-6d17-11e5-8bac-2e2d27dbb084.png)

**Comment by angieskazka** [comment]
no lines now :-P

**Comment by k6Labz** [comment]
**Retest Result:** Failed

**Release:** v0.8.3

**Testing Environment:** http://static.gapminderdev.org/vizabi/release/v0.8.3/preview/bubblechart.html

**Comment by angieskazka** [comment]
ACTUAL RESULTS:
There is no line under the “GDP per capita” option.

EXPECTED RESULTS: 
Ending line should be there under the “GDP per capita” option.


no, there shouldn't be any lines

**Comment by k6Labz** [comment]
**MODULE:** Bar chart

**Platform:** Windows 7 / Chrome 48.0

**RELEASE:** v0.8.5

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.5/preview/barchart.html 
2)	Bar chart is loaded
3)	Click on the Y axis description
4)	Click “Health”. 
5)     Note that there is a line under option

**ACTUAL RESULTS:**
There is a line under the “Health” option. 

**EXPECTED RESULTS:** 
There shouldn't be any lines

**SCREENSHOT:** 

![comment](https://cloud.githubusercontent.com/assets/9950837/10876531/76d0a28a-815f-11e5-8ab7-f72902cd6790.png)

**Comment by arthurcamara1** [comment]
We shouldn't have lines now. Fixed apparently
