### ISSUE TITLE
v0.8.1_36 : Download symbol is not center aligned

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#634]
**SEVERITY:** Minor

**MODULE:**
* Bubble Chart
* Mountain Chart

**Platform:** MAC / Safari 8.0

**RELEASE:** v0.8.1

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.1/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Click the “Record” button available on the right panel
4)	A red ball is shown on the right top of the chart
5)	Take mouse to that red ball 
6)	Note that download symbol is not center aligned

**ACTUAL RESULTS:**
Download symbol is not center aligned

**EXPECTED RESULTS:** 
Download symbol should be center aligned

**SCREENSHOT:** 

![v0 8 1_36](https://cloud.githubusercontent.com/assets/9950837/10365465/e6e7da98-6ddc-11e5-922e-16192ab155a6.png)

**Comment by arthurcamara1** [comment]
We shouldn't worry about this for now
