### ISSUE TITLE
v0.8.1_37: By clicking download button a page with code is opened but file is not downloaded

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#635]
**SEVERITY:** Minor

**MODULE:**
* Bubble Chart
* Mountain Chart

**Platform:** 
* MAC / Safari 8.0
* iPad Air 2 iOS(8.3) / Safari 8.0

**RELEASE:** v0.8.1

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.1/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Click the “Record” button available on the right panel
4)	A red ball is shown on the right top of the chart
5)	Take mouse to that red ball and click that 
6)	Note that a new page is opened with a messed code but file is not downloaded

**ACTUAL RESULTS:**
By clicking download button a page is opened but file is not downloaded 

**EXPECTED RESULTS:** 
File should be downloaded by clicking download button

**SCREENSHOT:** 

![v0 8 1_37](https://cloud.githubusercontent.com/assets/9950837/10365504/5278f6b6-6ddd-11e5-8332-4444f20012b3.png)

**Comment by arthurcamara1** [comment]
Like #634, we shoulnd't worry about this
