### ISSUE TITLE
v0.8.1_38: Check box of a country is disappeared by selecting other checkbox of a country

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#636]
**SEVERITY:** Major

**MODULE:** Bubble Chart

**Platform:** MAC / Safari 8.0

**RELEASE:** v0.8.1

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.1/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Click “Find”. A list for countries is displayed
4)	Click “Austria”
5)	Note that check box of “Argentina” is disappeared

**ACTUAL RESULTS:**
Check box of “Argentina” is disappeared by selecting checkbox of “Austria” 

**EXPECTED RESULTS:** 
No checkbox should disappeared by selecting any other checkbox of a country

**SCREENSHOT:**

![v0 8 1_38](https://cloud.githubusercontent.com/assets/9950837/10365536/99f8d100-6ddd-11e5-9a83-fda199c7ca8c.png)

**Comment by angieskazka** [comment]
Couldn't reproduce on Mac/Safari 9 can anyone?

**Comment by angieskazka** [comment]
¯\_(ツ)_/¯
