### ISSUE TITLE
v0.8.1_39: Play icon is not working on expanded screen.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#637]
**SUMMARY:** 
**1)**	      Play icon is not working on expanded screen.
**2)**	      Poverty line is not moving by moving mouse on X axis on expanded screen

**SEVERITY:** Major

**MODULE:**
* Bubble Char
* Mountain Chart
* Bar Chart
* Line Chart

**Platform:** MAC / Safari 8.0

**RELEASE:** v0.8.1

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.1/preview/mountainchart.html 
2)	Mountain chart page will be loaded
3)	Click “Expand”
4)	Click play
5)	Note that play is not working
6)	Also note that poverty line is not moving by moving mouse on X axis on expanded screen

**ACTUAL RESULTS:**
On expanded screen play icon is not working and poverty line is not moving by moving mouse on X axis

**EXPECTED RESULTS:** 
Play icon should work in any case and poverty line should also move along the X axis by moving cursor along it

**SCREENSHOT:**

![v0 8 1_39](https://cloud.githubusercontent.com/assets/9950837/10365609/144c0b7a-6dde-11e5-8ebd-67382b0b2649.png)

**Comment by angieskazka** [comment]
@k6Labz couldn't reproduce. please retest on develop, it might have been fixed 
http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html

**Comment by angieskazka** [comment]
ok, it's probably done. @k6Labz please open if persists on 0.8.4 and above, thanks
