### ISSUE TITLE
v0.8.1_40:  Download options is not available by clicking “Record” button

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#638]
**SEVERITY:** Major

**MODULE:**
* Bar Chart
* Line Chart

**Platform:**
* MAC / Safari 8.0
* Windows 7 / Chrome 45.0
* Windows 7 / Firefox 42.0
* iPad Air 2 iOS(8.3) / Safari 8.0

**RELEASE:** v0.8.1

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.1/preview/linechart.html 
2)	Line chart page will be loaded
3)	Click the “Record” button available on the right panel
4)	Note that download options is not available on the right upper corner of the chart

**ACTUAL RESULTS:**
Download options is not available on the right upper corner of the chart by clicking “Record” button

**EXPECTED RESULTS:** 
Download options should be available on the right upper corner of the chart by clicking “Record” button

**SCREENSHOT:**

![v0 8 1_40](https://cloud.githubusercontent.com/assets/9950837/10365689/aaf66ec6-6dde-11e5-9f13-4bc1b0ff7e1a.png)

**Comment by arthurcamara1** [comment]
We shouldn't worry about record button for now, right @angieskazka ?
