### ISSUE TITLE
v0.8.1_41: Heading of “Maximum Y value” in "X and Y" axis is missing 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#639]
**SEVERITY:** Major

**MODULE:** Mountain Chart

**Platform:** iPad Air 2 iOS(8.3) / Safari 8.0

**RELEASE:** v0.8.1

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.1/preview/mountainchart.html 
2)	Mountain chart page will be loaded
3)	Click the “X and Y”
4)	Note that “Maximum Y value” heading is missing

**ACTUAL RESULTS:**
“Maximum Y value” heading is missing in “X and Y” options

**EXPECTED RESULTS:** 
No options should be missing

**SCREENSHOT:** 

![v0 8 1_41](https://cloud.githubusercontent.com/assets/9950837/10365815/798a683c-6ddf-11e5-9266-33b22cfd1e7b.PNG)

**Comment by angieskazka** [comment]
Somebody please try to reproduce and fix on the noted platforms. My safari looks fine

http://static.gapminderdev.org/vizabi/release/v0.8.1/preview/mountainchart.html

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Testing Environment:** DEVELOP Branch - http://static.gapminderdev.org/vizabi/develop/preview/
