### ISSUE TITLE
Scrollable dialogs should include a scrollbar

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#640]
**SEVERITY:** Major

**MODULE:** Mountain Chart

**Platform:** iPad Air 2 iOS(8.3) / Safari 8.0

**RELEASE:** v0.8.1

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.1/preview/mountainchart.html 
2)	Mountain chart page will be loaded
3)	Click the “Stack”
4)	Note that scroll bar under “Manual sorting of groups” is missing

**ACTUAL RESULTS:**
Scroll bar under “Manual sorting of groups” is missing in “Slack” options

**EXPECTED RESULTS:** 
No scroll bar should be missing

**SCREENSHOT:** 

![v0 8 1_42](https://cloud.githubusercontent.com/assets/9950837/10365832/a6801486-6ddf-11e5-9059-fb00f76c7722.PNG)

**Comment by arthurcamara1** [comment]
I wrote a solution here. Use these styles: http://codepen.io/arthurcamara1/pen/avELvX

**Comment by angieskazka** [comment]
I assume it's not yet done, right? i have these very intrusive ones

![image](https://cloud.githubusercontent.com/assets/3648190/10634556/eebd3342-77f2-11e5-8120-42f689242a19.png)

**Comment by arthurcamara1** [comment]
@angieskazka Why do we even have a scrollbar just for the manual sorting? It could be just a list (no scrolling). If content grows too large the dialog itself will handle scroll.

**Comment by angieskazka** [comment]
@arthurcamara1 indeed

**Comment by arthurcamara1** [comment]
@hucharal Please check this out :)

**Comment by arthurcamara1** [comment]
It's been fixed
