### ISSUE TITLE
v0.8.1_43: Last letters of all regions names are missing by changing axis options

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#642]
**SEVERITY:** Minor

**MODULE:**  Bar chart

**Platform:**
* Windows 7 / Chrome 45.0
* Windows 7 / Firefox 42.0
* MAC / Safari 8.0
* iPad Air 2 iOS(8.3) / Safari 8.0
* Nexus 9 (5.0.1) / Chrome 45.0
* Nexus 5 (5.1.1) / Chrome 44.0

**RELEASE:** v0.8.1

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.1/preview/barchart.html
2)	Bar chart is loaded
3)	Click on the X axis description
4)	Click “Properties”. 3 options are shown
5)	Select “Geo Code” or “Region”
6)	Note that last letters of all regions names are missing on X axis

**ACTUAL RESULTS:**
Last letters of all regions names are missing by changing axis options

**EXPECTED RESULTS:** 
Full names should be available in any case

**SCREENSHOT:**

![v0 8 1_43](https://cloud.githubusercontent.com/assets/9950837/10393337/8ba018ea-6ea8-11e5-871a-911a691513f9.png)

**Comment by k6Labz** [comment]
**Retest Result:** Failed

**Release:** v0.8.3

**Testing Environment:** http://static.gapminderdev.org/vizabi/release/v0.8.3/preview/bubblechart.html

**Comment by arthurcamara1** [comment]
Before fixing we will have to discuss strings on axes
