### ISSUE TITLE
v0.8.1_44: Treemenu: Arrow indicator is not aligned with the text

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#653]
**SEVERITY:** Minor

**MODULE:**  Bubble chart

**Platform:** Android Nexus-5 (5.1.1) / Chrome 44.0

**RELEASE:** v0.8.1

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.1/preview/bubblechart.html 
2)	Bubble chart is loaded
3)	Click on the Y axis description
4)	Click “Wealth”. An option is displayed. Click that option
5)	Note that arrow indicator is not aligned with the text on that options

**ACTUAL RESULTS:**
Arrow indicator is not aligned with the text 

**EXPECTED RESULTS:** 
Arrow indicator should be aligned with the text 

**SCREENSHOT:**

![v0 8 1_44](https://cloud.githubusercontent.com/assets/9950837/10427555/0e7f46de-7104-11e5-91cc-758babb2b777.png)

**Comment by angieskazka** [comment]
fixed now
