### ISSUE TITLE
v0.8.1_45: Lines of Line chart are moving ahead from the circle

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#654]
**SEVERITY:** Minor

**MODULE:**  Line chart

**Platform:** Android Nexus-5 (5.1.1) / Chrome 44.0

**RELEASE:** v0.8.1

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.1/preview/linechart.html 
2)	Line chart is loaded
3)	Click Play
4)	Note that Lines of Line chart are moving ahead from the circle

**ACTUAL RESULTS:**
Lines of Line chart are moving ahead from the circle 

**EXPECTED RESULTS:** 
Lines of the line chart should not move ahead from the circle.

**SCREENSHOT:**

![v0 8 1_45](https://cloud.githubusercontent.com/assets/9950837/10427697/1fa617a2-7105-11e5-98cf-c1d85e1889d7.png)

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Testing Environment - DEVELOP:** http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html

**Comment by k6Labz** [comment]
**Retest Result:** Fail

**Platform:** iPhone-4G(iOS 7.1.2)/ Safari 

**Testing Environment:** http://static.gapminderdev.org/vizabi/release/v0.9.2/preview/linechart.html

**Comment by sergey-filipenko** [comment]
related to https://github.com/Gapminder/vizabi/issues/981
