### ISSUE TITLE
v0.8.1_46:  After entering the required country name , by clicking OK the writing pad is not gone 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#655]
**SUMMARY:** 
**1)**  After entering the required country name , by clicking OK the writing pad is not gone 
**2)**  Small pop up screen is not appearing on the screen after clicking “Find”

**SEVERITY:** Minor

**MODULE:**  Mountain chart

**Platform:** Android Nexus-5 (5.1.1) / Chrome 44.0

**RELEASE:** v0.8.1

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.1/preview/mountainchart.html 
2)	Mountain chart is loaded
3)	Click “Find”
4)	Enter any country’s name
5)	Click OK button on the pad
6)	Note that OK button is not working
7)	Also note that small pop up screen is not appearing on the screen after clicking “Find”

**ACTUAL RESULTS:**
After entering the required country name, by clicking OK the writing pad is not gone and Small pop up screen is not appearing on the screen after clicking “Find”

**EXPECTED RESULTS:** 
After entering the required country name, by clicking OK the writing pad should be gone and Small pop up screen should appear on the screen after clicking “Find”

**SCREENSHOT:**

![v0 8 1_46](https://cloud.githubusercontent.com/assets/9950837/10427724/658f1872-7105-11e5-9807-c2543c7c5278.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/725

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/759

**Comment by angieskazka** [comment]
done
