### ISSUE TITLE
v0.8.1_47: Population value at "1800" year is not consistent with values at others year

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#656]
**SEVERITY:** Minor

**MODULE:**  Mountain chart

**Platform:**
* Android Nexus-5 (5.1.1) / Chrome 44.0
* Windows 7 / Chrome 45.0
* Windows 7 / Firefox 42.0

**RELEASE:** v0.8.1

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.1/preview/mountainchart.html 
2)	Mountain chart is loaded
3)	Click Play
4)	Note that At year 1800 the population is shown in full form while at other years it is shown in short form like 3.2 M.

**ACTUAL RESULTS:**
At year 1800 the population is shown in full form while at other years it is shown in short form like 3.2 M.

**EXPECTED RESULTS:** 
Population value at "1800" year should be consistent with values at others year.

**SCREENSHOT:**

![v0 8 1_47](https://cloud.githubusercontent.com/assets/9950837/10427757/a93abde2-7105-11e5-99f3-00133ef067d7.png)

**Comment by angieskazka** [comment]
done
