### ISSUE TITLE
tool undefined when trying to setOptions

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#66]
hi @arthurcamara1 
one of the last changes broke my tool. 30a549093fccf2176ceda27f6228628d1cb84bf5

It says `tool` is undefined in vizabi.js line 8 when trying to set options from the example page

**Comment by ambodi** [comment]
@angieskazka be explicity. My tool you mean axis labeler which is on https://github.com/Gapminder/vizabi/tree/feature/axis-labeler

I could not re-produce the problem. Have you pushed your changes? Because whether its @arthurcamara1 investigating or someone else, we need to see the exact code you are seeing on our machines.

**Comment by arthurcamara1** [comment]
Yes @angieskazka, sorry, I noticed that problem too and fixed it already yesterday but forgot to push it on develop. Pushed now.

**Comment by angieskazka** [comment]
@ambodi this was not tool-specific. also i could not push because i needed to have it working yesterday, so i reverted to before merge state and wrote here, hoping that Arthur already knows why it happened or can see it with other tools

thanks, @arthurcamara1, the subject issue was solved but now i discovered another :bug: 
the addition `position: relative !important; ` in _common.scss on Line 54 makes full-screen mode not working for me
![image](https://cloud.githubusercontent.com/assets/3648190/6079982/cb8cfe3a-ae0c-11e4-8264-3d61099eb852.png)

i couldn't reproduce it in other tools, so merged and pushed mine

upd: the version on the web is not refreshing for some reason. To reproduce, try to pull my latest axis-labeler branch and run it locally

**Comment by angieskazka** [comment]
upd: actually, no, forget my branch. just try locally full-screen mode on bubble chart in /develop. 
same thing
