### ISSUE TITLE
Tools_v0.8.1 _48: After loading from WS is complete, vizabi drops year 2015. //After clicking play, the slider ball stops at 2014 instead of 2015

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#661]
**SEVERITY:** Major

**MODULE:** Tools page (Bubble Chart)

**Platform:**
* Windows 7 / Chrome 45.0
* Windows 7 / Firefox 42.0
* MAC / Safari 8.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://128.199.60.177:8080/tools/
2)	Tools page is loaded.
3)	Note the year shown behind the bubbles
4)	Click play
5)	Let the slider ball reach end
6)	Note that the slider ball stops at 2014 instead of 2015

**ACTUAL RESULTS:**
After clicking play, the slider ball stops at 2014 instead of 2015

**EXPECTED RESULTS:** 
After clicking play, the slider ball should stop at 2015 instead of 2014

**SCREENSHOT:**

![tools_v0 8 1 _48 1](https://cloud.githubusercontent.com/assets/9950837/10453647/6bf52ac2-71c7-11e5-945e-839ab0b67d7f.png)

![tools_v0 8 1 _48 2](https://cloud.githubusercontent.com/assets/9950837/10453655/7ff51f5a-71c7-11e5-8a09-05723a278eaf.png)

**Comment by arthurcamara1** [comment]
Reason: waffle server is not returning data for 2015 inclusive when 1800-2015 is requested. Only returning data up to 2014.

That's also why the bubbles jump back one year after all data is loaded.

**Comment by arthurcamara1** [comment]
Fixed by @valorkin by fixing the returned data from waffle
