### ISSUE TITLE
Tools_v0.8.1 _49: United States have 2015: GDP: 52118 $/year/person

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#662]
**SEVERITY:** Major

**MODULE:** Tools page 

**Platform:**
* Windows 7 / Chrome 45.0
* Windows 7 / Firefox 42.0
* MAC / Safari 8.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://128.199.60.177:8080/tools/
2)	Tools page is loaded.
3)	Bubble chart is at year 2015
4)	Click “Find” and select United States
5)	Note that United States have 2015: GDP: 52118 $/year/person

**ACTUAL RESULTS:**
United States have 2015: GDP: 52118 $/year/person 

**EXPECTED RESULTS:** 
United States should have 2015: GDP: 53354 $/year/person

**SCREENSHOT:**

![tools_v0 8 1 _49](https://cloud.githubusercontent.com/assets/9950837/10453677/b4b8dbfa-71c7-11e5-9c48-e5817a4b835f.png)

**Comment by angieskazka** [comment]
@k6Labz thanks for the good catch! @valorkin fixed it now on server side 
all looks good here https://stage-tools.gapminderdev.org/tools/bubbles
