### ISSUE TITLE
Tools_v0.8.1 _50: The chart is refreshed before the slider ball reaches the end

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#663]
**SEVERITY:** Major

**MODULE:** Tools page (Bubble Chart)

**Platform:** MAC / Safari 8.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://128.199.60.177:8080/tools/
2)	Tools page is loaded.
3)	Click Play
4)	Note that the chart is refreshed before the slider ball reaches the end

**ACTUAL RESULTS:**
The chart is refreshed before the slider ball reaches the end 

**EXPECTED RESULTS:** 
The chart should not refresh before the slider ball reaches the end

**Comment by angieskazka** [comment]
Couldn't reproduce on Max/ Safari. can anyone?

**Comment by angieskazka** [comment]
`¯\_(ツ)_/¯`
