### ISSUE TITLE
Tools_v0.8.1 _51: By changing  Y axis description , the description is not changed

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#664]
**SUMMARY:** 
**1)** By changing  Y axis description , the description is not changed
**2)** By changing  Y axis description , the chart is disappeared
**3)** By changing  Y axis description , the warning sign is missing

**SEVERITY:** Critical

**MODULE:** Tools page (Bubble Chart)

**Platform:**
* Windows 7 / Chrome 45.0
* MAC / Safari 8.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://128.199.60.177:8080/tools/
2)	Tools page is loaded.
3)	Click Y axis description
4)	Change the axis description to “Population”
5)	Click play
6)	Note that the description is not changed and the chart is disappeared. By changing  Y axis description, the warning sign is also missing

 **ACTUAL RESULTS:**
Note that the description is not changed and the chart is disappeared. By changing Y axis description, the warning sign is also missing

**EXPECTED RESULTS:** 
By changing Y axis description the description should change, chart should be visible and warning sign should be available

**NOTE:** The issue is not reproduced on every attempt but it can be reproduced most of the times

**SCREENSHOT:**

![tools_v0 8 1 _51](https://cloud.githubusercontent.com/assets/9950837/10453737/1a5cec26-71c8-11e5-8128-24bf682f9f9b.png)

**Comment by arthurcamara1** [comment]
Fixed
