### ISSUE TITLE
Tools_v0.8.1 _53: By changing  color options from “Region” to “Population” , the play icon is not working

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#671]
**SUMMARY:** 
**1)** By changing  color options from “Region” to “Population” , the play icon is not working
**2)** By changing  color options from “Region” to “Population” , the color of bubbles are changing unexpectedly at every year
**3)** By changing  color options from “Region” to “Population” , “Deselect” and slider bar are missing in “Find” options
**4)** By changing  color options from “Region” to “Population” , bubbles are not selected 
**5)** By changing  color options from “Region” to “Population” , trails are missing
**6)** By changing  color options from “Region” to “Population” , text is overlapping
**7)** By changing  color options from “Region” to “Population” , trails are shown in black color on expanded screen
**8)** By changing  color options from “Region” to “Population” , slider ball stops at 2013 but 2014 is shown on the behind of bubbles

**SEVERITY:** Critical

**MODULE:** Tools page (Bubble Chart)

**Platform:** iPad Air 2 iOS(8.3) / Safari 8.0

**STEPS TO REPRODUCE:**

**Starting steps:**
1)	Navigate to URL: http://128.199.60.177:8080/tools/
2)	Tools page is loaded. 
3)	Click “Color” 
4)	Click first drop down
5)	Select “Population” and click OK

a)	Click play icon
b)	Note that play icon is not working

a)	After repeating first five steps click “Find”
b)	Select any country 
c)	Note that Deselect” and slider bar are missing at the bottom end of the small pop up screen

a)	After repeating first five steps click “Find”
b)	Select any country and click OK
c)	Note that no bubble is selected

a)	After repeating first two steps drag the slider ball at the start
b)	Click “Color” 
c)	Click first drop down
d)	Select “Population” and click OK
e)	Click play
f)	Note that , the color of bubbles are changing unexpectedly at every year

a)	After repeating first two steps drag the slider ball at the start
b)	Click “Color” 
c)	Click first drop down
d)	Select “Population” and click OK
e)	Select any country
f)	Click play
g)	Note that there are no trails for that bubble but only a line is there

a)	After repeating first two steps drag the slider ball at the start
b)	Click “Color” 
c)	Click first drop down
d)	Select “Population” and click OK
e)	Select any country
f)	Click play
g)	Click expand then play 
h)	Note that, trails are shown in black color on expanded screen
i)	Also note that the text is overlapping on the left top of the screen (on Y axis description)

a)	After repeating first two steps drag the slider ball at the start
b)	Click “Color” 
c)	Click first drop down
d)	Select “Population” and click OK
e)	Select any country
f)	Click play
g)	Let the slider ball reach the end
h)	Note that slider ball is showing 2013 year but there is 2014 behind the bubbles

**ACTUAL RESULTS:**
By changing color options from “Region” to “Population” , there are many defects. Like click is not working, trails are missing, text is overlapping, bubbles are not selected, deselect option is missing.

**EXPECTED RESULTS:** 
By changing color options from “Region” to “Population” , no defect should come

**NOTE:** The issues are not reproduced on every attempt but it can be reproduced most of the times

**SCREENSHOT:**

All the related screenshots are in the given word file
[screenshots.docx](https://github.com/Gapminder/vizabi/files/13134/screenshots.docx)

**Comment by sergey-filipenko** [comment]
Can not reproduce any of these points. Retest please

**Comment by k6Labz** [comment]
**Retest Result:** All Pass except number 6 which is "By changing  color options from “Region” to “Population” , text is overlapping."

**Testing Environment:** http://128.199.60.177:8080/tools/

**Screenshot:**
![fb2db4a3ed294713820417c0a6e53557abdad2a9782ccb438f pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/9950837/10961110/ed56c7e6-83ac-11e5-902c-65bc0cdf4e60.jpg)

**Comment by arthurcamara1** [comment]
Ok, then it's fixed. The overlapping text is part of toolspage
