### ISSUE TITLE
Bubble Chart Axis Label bug with Geo.regions

### ISSUE THREAD

**Issue by arthurcamara1** [Gapminder/vizabi#68]
This is what happens when I change a hook for axis Y to `geo.region`

![screen shot 2015-02-27 at 6 05 52 pm](https://cloud.githubusercontent.com/assets/3584238/6417092/5e3ee74e-beab-11e4-9f42-9a12e261fbf4.png)

Same with X

![screen shot 2015-02-27 at 6 07 31 pm](https://cloud.githubusercontent.com/assets/3584238/6417115/84862106-beab-11e4-9440-853fae58b90b.png)

**Comment by angieskazka** [comment]
Just for the record here, this is expected for now, as ordinal scales are not supported by axis labeler. I will prio it up now :)

**Comment by angieskazka** [comment]
@olarosling what do we do when the scale is categorical and categories are too many?

![image](https://cloud.githubusercontent.com/assets/3648190/6503896/6ecc685e-c331-11e4-8953-8cd374256e35.png)

**Comment by olarosling** [comment]
We will deal with this later

On 5 March 2015 at 12:17, Angie the Fairytale <notifications@github.com>
wrote:

> @olarosling <https://github.com/olarosling> what do we do when the scale
> is categorical and categories are too many?
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/3648190/6503896/6ecc685e-c331-11e4-8953-8cd374256e35.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Gapminder/vizabi/issues/68#issuecomment-77347208>.
>



-- 
*Ola Rosling *twitter@olarosling <https://twitter.com/OlaRosling> + 46 73
838 7778
Director & Co-founder, Gapminder
www.gapminder.org — twitter@gapminder <https://twitter.com/Gapminder> —
facebook/gapminder.org  <https://www.facebook.com/gapminder.org>

**Comment by angieskazka** [comment]
then i close is for now: ordinals are supported
