### ISSUE TITLE
v0.8.3_04: X axis line is missing 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#691]
**SEVERITY:** Major

**MODULE:**  Bubble Chart

**Platform:**
* Windows 7 / Chrome 45.0
* Windows 7 / Firefox 42.0

**RELEASE:** v0.8.3

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.3/preview/bubblechart.html
2)	Bubble chart page will be loaded
3)	Note that X axis line is missing on Firefox
4)	Click play
5)	Click “Portrait” button under RESPONSIVENESS
6)	Note that X axis line is missing on Chrome and Firefox
7)	Also note that bubbles place is disturbed

**ACTUAL RESULTS:**
X axis line is missing and bubbles place is disturbed by changing orientation

**EXPECTED RESULTS:** 
Axes lines should be available and bubbles place should not be disturbed by changing orientation

**SCREENSHOT:**

![v0 8 3_04](https://cloud.githubusercontent.com/assets/9950837/10540851/504f1d4a-7425-11e5-9f88-7e069d1a8b9e.png)

**Comment by angieskazka** [comment]
i hope i fixed it. please retest static.gapminderdev.org/vizabi/develop/preview

**Comment by k6Labz** [comment]
**Retest Result:** Pass
**Testing Environment:** http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html
