### ISSUE TITLE
v0.8.3_07: Year behind the chart is not center aligned 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#694]
**SEVERITY:** Major

**MODULE:**  Mountain Chart

**Platform:**
* Windows 7 / Chrome 45.0
* Windows 7 / Firefox 42.0

**RELEASE:** v0.8.3

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.3/preview/mountainchart.html
2)	Mountain chart page will be loaded
3)	Click “Full” under RESPONSIVENESS
4)	Note that year behind the chart is not center aligned

**ACTUAL RESULTS:**
Year behind the chart is not center aligned 

**EXPECTED RESULTS:** 
Year behind the chart should be center aligned 

**SCREENSHOT:**

![v0 8 3_07](https://cloud.githubusercontent.com/assets/9950837/10540918/03875e90-7426-11e5-82db-319d66fb5482.png)

**Comment by sergey-filipenko** [comment]
Fixed in https://github.com/Gapminder/vizabi/issues/546

**Comment by angieskazka** [comment]
year will still be top right on the "large" profile. it's ok!
