### ISSUE TITLE
v0.8.3_08: Color scale is slightly disturbed 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#695]
**SEVERITY:** Minor

**MODULE:**
* Bubble Chart
* Mountain Chart

**Platform:** Windows 7 / Firefox 42.0

**RELEASE:** v0.8.3

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.3/preview/bubblechart.html
2)	Bubble chart page will be loaded
3)	Click “Color”
4)	Click the drop down and select “Population”
5)	Note that Color scale is slightly disturbed from bottom side

**ACTUAL RESULTS:**
Color scale is slightly disturbed from bottom side 

**EXPECTED RESULTS:** 
Color scale should not be disturbed 

**SCREENSHOT:**

![v0 8 3_08](https://cloud.githubusercontent.com/assets/9950837/10540935/2c0844ec-7426-11e5-9759-4d62b2c9c258.png)

**Comment by k6Labz** [comment]
@angieskazka:
This issue is reproduced again on version 0.9.1

**Platform:** Windows 7 / Firefox 43.0

**RELEASE:** v0.9.1

**Comment by angieskazka** [comment]
@k6Labz i made an attempt to fix it. please retest on develop

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Platform:** Windows 7 / Firefox 43.0

**Testing Environment:** http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html
