### ISSUE TITLE
Background year disappeared on Firefox

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#698]
this has probably happened when the smart year label centring was introduced

i discovered recently that Firefox is more strict when it comes to the syntax of setting style via JS, like .style("stuff", value + "px")
this would work without +"px" in Chrome, but not in Firefox
this might be a reason...

![image](https://cloud.githubusercontent.com/assets/3648190/10558890/9bd7e17c-74e1-11e5-9473-d9ee87ab8d4b.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/708

**Comment by angieskazka** [comment]
done
