### ISSUE TITLE
Line labels overlapping

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#70]
The labels should re-order after animation stops (or while moving)  and never overlap.
http://bit.ly/1aIDllF
![image](https://cloud.githubusercontent.com/assets/496398/6443155/5261d1ec-c0f5-11e4-892a-82cfb80f83f7.png)

**Comment by angieskazka** [comment]
status: this is a tough one, and i am looking to solve it using approach similar to a "force directed graph", but just 1-dimensional. Labels be attracted by line ends and repelled by their siblings

not done yet

**Comment by angieskazka** [comment]
getting there 
![image](https://cloud.githubusercontent.com/assets/3648190/6618356/7fb2a2fa-c8c2-11e4-80ee-24ea5e7f6b6c.png)

**Comment by angieskazka** [comment]
declaring DONE

![image](https://cloud.githubusercontent.com/assets/3648190/6673396/f18fabc2-cc12-11e4-873d-92b190592cef.png)
