### ISSUE TITLE
v0.8.3_09: Lines of line chart are missing

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#709]
**SEVERITY:** Critical

**MODULE:** Line Chart

**Platform:** 
* Windows 7 / Chrome 45.0
* Windows 7 / Firefox 42.0
* iPad Air 2 iOS(8.3) / Safari 8.0
* MAC / Safari 8.0

**RELEASE:** v0.8.3

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.3/preview/linechart.html
2)	Line chart page will be loaded
3)	Note that lines of line chart are missing

**ACTUAL RESULTS:**
Lines of line chart are missing

**EXPECTED RESULTS:** 
Lines of line chart should not missing

**SCREENSHOT:**

![v0 8 3_09](https://cloud.githubusercontent.com/assets/9950837/10576949/bfa77f72-7680-11e5-8866-c5895f2a4325.png)

**Comment by angieskazka** [comment]
need to add min and max properties in Tool configuration in Gapminder.js
