### ISSUE TITLE
time-slider & x-axis should be aligned and, timeline label overlap xis labels, nice

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#71]
http://bit.ly/1aIDllF
![image](https://cloud.githubusercontent.com/assets/496398/6443181/8b412698-c0f5-11e4-93ce-bf4a38824843.png)

See the mocks in [this doc](https://docs.google.com/a/gapminder.org/document/d/14T5_6PTxju7-acaJwSnwIrUwXgq-Z8J3R0nq5rqbPn4/edit#)
![image](https://cloud.githubusercontent.com/assets/496398/6443224/c48365e2-c0f5-11e4-8a78-44cff6812347.png)

**Comment by angieskazka** [comment]
aligning done, overlapping — not yet

**Comment by angieskazka** [comment]
overlap now done as well 
http://bit.ly/1MmFYXA
