### ISSUE TITLE
v0.8.3_10: Check box is not  selected for a selected country

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#710]
**SEVERITY:** Major

**MODULE:** Mountain Chart

**Platform:** 
* Windows 7 / Chrome 45.0
* Windows 7 / Firefox 42.0
* iPad Air 2 iOS(8.3) / Safari 8.0

**RELEASE:** v0.8.3

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.3/preview/mountainchart.html
2)	Mountain chart page will be loaded
3)	Click “Full” under responsiveness
4)	Click “SHOW”
5)	Click first check box which is for “Afghanistan”
6)	Then click “Show all” and the click “OK”
7)	Again click “SHOW”
8)	Note that check box for Afghanistan is selected while the cure of Afghanistan is not prominent
9)	Uncheck the check box of Afghanistan and then click “OK”
10)	 Note that the check box is unchecked but the country curve is there

**ACTUAL RESULTS:**
Check box is unchecked but the country curve is there 

**EXPECTED RESULTS:** 
If check box is unchecked then the curve should not be prominent

**SCREENSHOT:**

![v0 8 3_10](https://cloud.githubusercontent.com/assets/9950837/10576995/f64dea8e-7680-11e5-982d-71c15818b4c9.png)

**Comment by angieskazka** [comment]
it's not a bug it’s a feature 
we have to communicate it clearly that it’s “the only things to show” in “show”, opposite to “select"

**Comment by angieskazka** [comment]
ok, i get it now. yes, it's a bug.
`change:state:entities:show` event is not fired in show.js when we change show
https://github.com/Gapminder/vizabi/blob/develop/src/components/buttonlist/dialogs/show/show.js#L21

@arthurcamara1 can you help to fix it? why is there no event?

**Comment by arthurcamara1** [comment]
Yes :) I'll look into it

**Comment by arthurcamara1** [comment]
For some reason `change:entities:show` is being fired correctly but not `change:state:entities:show`. Looking into it
