### ISSUE TITLE
Tools_v0.8.3 _15 :  iPhone-5-W (iOS 8.1.3) / Safari: missing icon Warning sign

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#719]
**SUMMARY:**
**1)** Repeated options are there
**2)** Warning sign is missing

**SEVERITY:** Minor

**MODULE:** Tools page 

**Platform:** 
* iPhone-5-W (iOS 8.1.3) / Safari
* iPhone-5 (iOS 7.1)

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://dev-tools.gapminderdev.org:3001/
2)	Tools page is loaded.
3)	Note that on the right bottom “Data Doubts” options is repeating
4)	Also note that warning sign is missing

**ACTUAL RESULTS:**
On the right bottom “Data Doubts” options is repeating and warning sign is missing too.

**EXPECTED RESULTS:** 
Options should not be repeated and warning sign should be there

**SCREENSHOT:**

![tools_v0 8 3 _15](https://cloud.githubusercontent.com/assets/9950837/10606259/1ecdf042-774b-11e5-9f72-91a459bdd5b0.PNG)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/748

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Testing Environment - DEVELOP:** http://dev-tools.gapminderdev.org:3001/
