### ISSUE TITLE
Play animation creates back events in chrome

### ISSUE THREAD

**Issue by Wneh** [Gapminder/vizabi#72]
When you hit the play button to start the animation it creates a new "back" state in Chrome(haven't tested other browsers). Is it suppose to do so?

If you follow this link http://bit.ly/1aIDllF

Before starting the animation the back button has the following "states":
![screen shot 2015-03-02 at 4 36 30 pm](https://cloud.githubusercontent.com/assets/722053/6444007/193d6f10-c0fb-11e4-9e6a-9d107fc5a189.png)

And after the animation:
![screen shot 2015-03-02 at 4 37 14 pm](https://cloud.githubusercontent.com/assets/722053/6444022/3445c0a0-c0fb-11e4-82f4-4a725980eba7.png)

The down side is if the user follows a link on the web to a Vizabi page and want go back where they came from, they would have to press the back button the same amount of times there was steps in the animation.

**Comment by arthurcamara1** [comment]
Thanks for your question @Wneh .  :+1:  You're right, we should probably push to the URL without polluting the history. At the moment, this only affects the Preview Pages, which need to be refactored and improved anyways, so this is part of much needed improvements on that end. See #24

**Comment by angieskazka** [comment]
i see it back events are no more
