### ISSUE TITLE
Tools_v0.8.3 _16: iPhone-5-W (iOS 8.1.3) / Safari: missing X icon on bubble labels

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#720]
**SUMMARY:**
**1)** “x” is missing
**2)** Play icon is disturbed

**SEVERITY:** Major

**MODULE:** Tools page 

**Platform:** 
* iPhone-5-W (iOS 8.1.3) / Safari
* iPhone-5 (iOS 7.1)

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://dev-tools.gapminderdev.org:3001/
2)	Tools page is loaded.
3)	Select a country bubble
4)	Tap the tool tip of selected country
5)	Note that “x” is missing on the tool tip of the country
6)	~~Also note that play icon is disturbed~~ it's a feature

**ACTUAL RESULTS:**
“x” is not available on the tool tip of selected country
**EXPECTED RESULTS:** 
“x” should be available on the tool tip of selected country

**SCREENSHOT:**

![tools_v0 8 3 _16](https://cloud.githubusercontent.com/assets/9950837/10606294/5d45186e-774b-11e5-9f92-9242965e5125.PNG)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/748

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Testing Environment - DEVELOP:** http://dev-tools.gapminderdev.org:3001/
