### ISSUE TITLE
Tools_v0.8.3 _17:  iPhone-5-W (iOS 8.1.3) / Safari: Tick mark on check box is disturbed

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#721]
**SEVERITY:** Minor

**MODULE:** Tools page 

**Platform:** 
* iPhone-5-W (iOS 8.1.3) / Safari
* iPhone-5 (iOS 7.1)

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://dev-tools.gapminderdev.org:3001/
2)	Tools page is loaded.
3)	Tap “Find”
4)	Tap any country
5)	Note that tick mark on check box is disturbed

**ACTUAL RESULTS:**
Tick mark on check box is disturbed 

**EXPECTED RESULTS:** 
Tick mark on check box should not be disturbed 

**SCREENSHOT:**

![tools_v0 8 3 _17](https://cloud.githubusercontent.com/assets/9950837/10606330/928351da-774b-11e5-9c94-f7565262c2a1.PNG)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/748

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Testing Environment - DEVELOP:** http://dev-tools.gapminderdev.org:3001/
