### ISSUE TITLE
Tools_v0.8.3 _18: iPhone-5-W (iOS 8.1.3) / Safari: missing icon “?”

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#722]
**SEVERITY:** Minor

**MODULE:** Tools page 

**Platform:** 
* iPhone-5-W (iOS 8.1.3) / Safari
* iPhone-5 (iOS 7.1)

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://dev-tools.gapminderdev.org:3001/
2)	Tools page is loaded.
3)	Note that “?” link is missing with axes description

**ACTUAL RESULTS:**
“?” link is missing with axes description 

**EXPECTED RESULTS:** 
“?” link should be available with axes description 

**SCREENSHOT:**

![tools_v0 8 3 _18](https://cloud.githubusercontent.com/assets/9950837/10606351/bbb6c19a-774b-11e5-858f-e95a70d03af9.PNG)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/748

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Testing Environment - DEVELOP:** http://dev-tools.gapminderdev.org:3001/
