### ISSUE TITLE
Size slider should not be circles

### ISSUE THREAD

**Issue by arthurcamara1** [Gapminder/vizabi#726]
Instead of this:
![image](https://cloud.githubusercontent.com/assets/3584238/10611585/11987ff8-774d-11e5-8ab5-201d19e844c4.png)

It should look more like this:
![image](https://cloud.githubusercontent.com/assets/3584238/10611614/32390174-774d-11e5-9576-d557fcdb7be3.png)

With **arcs and the triangles**

**Comment by angieskazka** [comment]
done
