### ISSUE TITLE
When dialog is pinned, it should still be draggable

### ISSUE THREAD

**Issue by arthurcamara1** [Gapminder/vizabi#728]
When dialog is pinned, it should still be draggable.

Right now, it looks like this and it's not draggable when pinned:

![image](https://cloud.githubusercontent.com/assets/3584238/10611815/288a051e-774e-11e5-861a-49bc984d60c4.png)

Only the pinned icon should be active (blue background), and the drag icon should still look like this:

![image](https://cloud.githubusercontent.com/assets/3584238/10611840/46851f04-774e-11e5-9d84-8ba1b2830d6b.png)

**Comment by angieskazka** [comment]
done
