### ISSUE TITLE
Pinned dialogs should not be removed from the screen

### ISSUE THREAD

**Issue by arthurcamara1** [Gapminder/vizabi#729]
When a new dialog is opened, all pinned dialogs should stay in place. They should not be closed. That way, we could have multiple dialogs on the screen at the same time.

Right now, pinned dialogs are closed when we open other dialogs. In the example below, size should stay in place if the user clicks "Options", for instance

![image](https://cloud.githubusercontent.com/assets/3584238/10611935/c7670678-774e-11e5-9bdb-8b9c1557e55b.png)

**Comment by hucharal** [comment]
It also was fixed by pull request #752

**Comment by angieskazka** [comment]
yes, thank you!
