### ISSUE TITLE
layers of bubbles: large at the back  

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#73]
The large bubbles must be at the back
![image](https://cloud.githubusercontent.com/assets/496398/6479882/adc31d68-c24c-11e4-930c-5125d1c05272.png)

**Comment by angieskazka** [comment]
Directly applied sorting caused bubble markers to get ebind to different entities on every time step. Working this around at the moment

**Comment by gapminderdeploy** [comment]
Sorting them once by Radius of the last point in time is work around I used
before
