### ISSUE TITLE
Buttonlist should be expandable, not scrollable

### ISSUE THREAD

**Issue by arthurcamara1** [Gapminder/vizabi#730]
Buttonlist should collapse buttons under a "More" button. When clicking this button, the remaining buttons on the list should appear (it should be expanded somehow).

It shouldn't be scrollable like it is
![image](https://cloud.githubusercontent.com/assets/3584238/10612947/563a9dc0-7753-11e5-85ab-e7f748ea205b.png)

**Comment by angieskazka** [comment]
not convinced. why is it better @arthurcamara1? 
it adds a click to get to the right dialog. fewer clicks is better
it adds an extra floating panel (with collapsed buttons). fewer panels is better

**Comment by arthurcamara1** [comment]
@angieskazka Because it's not intuitive or easy to use at all.

**With scrollable version:**
Even if we go with a scrollable option, there should be a better way to show it's scrollable. An example would be with tab dots:

![dots](https://ipadnotebook.files.wordpress.com/2011/07/screen-dots.png)

or arrows...

But I would still vote for the more button. Here's why:

**With "more button":**
pros:
- clear where to find more buttons, just click/tap "More..."
- no "aha" moment after realizing you have to scroll horizontally to get to the extra buttons
- no button being cut out, which in some resolutions may look good, but in others looks like an error
- easier to use, more intuitive, specially on non-touch devices, or with regular mouse scrolling (touch pad and touch screen make the interaction a bit better)

cons:
- an extra click (which is not a big deal if you want to access more advanced options)

**Comment by arthurcamara1** [comment]
I quickly coded a prototype example of how I think it should work:
**[SEE LIVE EXAMPLE HERE](http://codepen.io/arthurcamara1/full/YyLpNd/)**

And [code here](http://codepen.io/arthurcamara1/pen/YyLpNd) .
One of our collaborators could work on putting this solution in Vizabi itself, good exercise :smile: 

**Retracted**
![Button List](http://i.imgur.com/E7MCUoC.png)

**Expanded after clicking more**
![Button List Expanded](http://i.imgur.com/5f7qvM3.png)

It even used to be similar to this a long time ago, if I remember correctly.
@angieskazka @olarosling what do you think? check out my arguments for "more button" above

**Comment by jheeffer** [comment]
(Horizontal) scrollable is definitely not the way to go on desktop.
Draggable on mobile, I can see that happen. 
For consistencies sake I'd keep it to a more button. Little additin: wouldn't replace the more button with another button, it's confusing. And give the user a way to make it less again. More like a toggle which has a different layout than the dialog buttons.

Changed your example a bit:
http://codepen.io/anon/pen/bVMYGg

**Comment by angieskazka** [comment]
@arthurcamara1 @jheeffer ok, we go for a button, @rlage is already on it

**Comment by olarosling** [comment]
Too many buttons: Do it like this instead. 
https://github.com/Gapminder/vizabi/issues/840
All state-properties must be under Options anyway: So "OPTIONS" is always "more"

**Comment by angieskazka** [comment]
@arthurcamara1 @olarosling please reopen this if becomes relevant
