### ISSUE TITLE
Wrong positioning country labels in locked state 

### ISSUE THREAD

**Issue by jheeffer** [Gapminder/vizabi#731]
Lock a couple of countries, then slide the timeslider.

1) When hovering over locked countries, their label appears on the 'would be unlocked'.

![image](https://cloud.githubusercontent.com/assets/3648190/10618542/d4fa4f8a-7770-11e5-9dfa-1bc6e454a4be.png)

2) Turn trails off. Now, if you click on a locked country, the label disappears. It reappears again on next redraw (e.g. with another country click, resize or timechange)

**Comment by angieskazka** [comment]
Steps to reproduce:

go to http://static.gapminderdev.org/vizabi/release/v0.8.4/preview/bubblechart.html
click on China -- it gets selected 
press lock -- the button indicates that it's locked on 2015
![image](https://cloud.githubusercontent.com/assets/3648190/10666929/d3db6408-78d4-11e5-9578-ce846badcfd7.png)
drag timeslider back to some year in the past
hover any of the locked bubbles

expected result: the label would appear near the locked bubbles

actual result: the label would appear as if the bubble would not be locked, far off in the blank space

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/753

**Comment by angieskazka** [comment]
yes
