### ISSUE TITLE
v0.8.4_02: Color picker is overlapping with “Find” options

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#734]
**SEVERITY:** Major

**MODULE:** 
* Bubble Chart
* Mountain Chart

**Platform:** Windows 7 / Chrome 45.0

**RELEASE:** v0.8.4

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.4/preview/bubblechart.html
2)	Bubble chart page will be loaded
3)	Click “Expand”
4)	Click the dropdown with color option on the right top corner
5)	Select constant
6)	Click color ball to change the color. The color picker is displayed
7)	Note that color picker is overlapping with “Find” options

**ACTUAL RESULTS:**
Color picker is overlapping with “Find” options 

**EXPECTED RESULTS:** 
Color picker should not overlap with “Find” options 

**SCREENSHOT:**

![v0 8 4_02](https://cloud.githubusercontent.com/assets/9950837/10636143/010a1906-7817-11e5-8130-2ec368ecb9fe.png)

**Comment by angieskazka** [comment]
Solution: maybe it's time to move colorpi
