### ISSUE TITLE
v0.8.4_03: Tool container doesn't resize when side bar opens. // Slider ball is disappeared after year 1972

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#735]
**SEVERITY:** Major

**MODULE:**  Bubble Chart

**Platform:** Windows 7 / Chrome 45.0

**RELEASE:** v0.8.4

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.4/preview/bubblechart.html
2)	Bubble chart page will be loaded
3)	Click “Expand”
4)	Click play
5)	Note that slider ball is disappeared after year 1972

**ACTUAL RESULTS:**
Slider ball goes under the right panel of options after year 1972

**EXPECTED RESULTS:** 
Slider ball should properly be shown till end

**SCREENSHOT:**

![v0 8 4_03](https://cloud.githubusercontent.com/assets/9950837/10636293/48ccddc2-7818-11e5-93b7-a16236d6f35c.png)

**Comment by angieskazka** [comment]
done
