### ISSUE TITLE
v0.8.4_04: Drag and Pin icons are missing

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#736]
**SEVERITY:** Major

**MODULE:**  Bubble Chart

**Platform:** Windows 7 / Chrome 45.0

**RELEASE:** v0.8.4

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.4/preview/bubblechart.html
2)	Bubble chart page will be loaded
3)	Click “Expand”
4)	Click “X and Y” or “Options”. A small pop up screen is shown
5)	Note that drag and Pin icons are missing on the small pop up screen

**ACTUAL RESULTS:**
Drag and Pin icons are missing on the small pop up screen 

**EXPECTED RESULTS:** 
Drag and Pin icons should not missing on the small pop up screen 

**SCREENSHOT:**

![v0 8 4_04](https://cloud.githubusercontent.com/assets/9950837/10636310/6fb78f54-7818-11e5-90f6-7fb05c0c552e.png)

**Comment by angieskazka** [comment]
fixed
