### ISSUE TITLE
Click and then hover on country makes close-button on label appear, but it disappears when you want to go to the button.

### ISSUE THREAD

**Issue by jheeffer** [Gapminder/vizabi#739]
This is a usability issue.

First click on a country. Then hover remove mouse and hover over it. A close button appears on the static label on the side. However, the link between hover and the close-button appearing isn't obvious. Moreover, moving mouse to the close-button  makes the button disappear (because hover ends before you reach the button).

What would be good ways to improve the usability in this case. Maybe there's a better way to control the selection?

**Comment by angieskazka** [comment]
made a little improvement, let it reappear when you hover an invisible button
@olarosling and @AnnaGapminder will complain if the usability is not right.
