### ISSUE TITLE
Remove one of the ticks at the top of Y-axis:

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#74]
![image](https://cloud.githubusercontent.com/assets/496398/6503062/a9365fc0-c329-11e4-91a4-8ff6bb9a7f78.png)

Here:
https://dl.dropboxusercontent.com/u/4933279/Gapminder/contentful/test.html

**Comment by angieskazka** [comment]
i would interpret this as "remove outer ticks if they are minor ticks" (minor ticks = shorter and have no label)
