### ISSUE TITLE
Dragging icon: dragging dialogs in medium profile not supported

### ISSUE THREAD

**Issue by arthurcamara1** [Gapminder/vizabi#741]
In medium profile, dragging/pining dialogs is not supported. The icons should go away

![image](https://cloud.githubusercontent.com/assets/3584238/10638330/baa2e2a6-780a-11e5-89d0-2aa3a3459c42.png)

These icons should be hidden
![image](https://cloud.githubusercontent.com/assets/3584238/10638345/d17b060c-780a-11e5-86e0-2dd03a73b737.png)

**Comment by angieskazka** [comment]
@arthurcamara1 why not? medium should be ok

**Comment by arthurcamara1** [comment]
@angieskazka  If they are not draggable, we should remove the icons. If they are draggable, they should work. So yes, we should keep them if we can drag :) :+1:

**Comment by hucharal** [comment]
Guys, but which is better for medium profile: to drag or not?

**Comment by angieskazka** [comment]
ok, let's make on medium profile: the dialogs are draggable and the icons visible

this issue becomes redundant, and we need to fix #784 instead
