### ISSUE TITLE
v0.8.4_06: Links are overlapping

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#744]
**SEVERITY:** Major

**MODULE:**  Mountain Chart

**Platform:** iPhone-5 (iOS 7.1)

**RELEASE:** v0.8.4

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.4/preview/mountainchart.html
2)	Mountain chart page will be loaded
3)	Note that y axis description is overlapping with the data warning option

**ACTUAL RESULTS:**
Y axis description is overlapping with the data warning option 

**EXPECTED RESULTS:** 
Links should not overlap

**SCREENSHOT:**

![v0 8 4_06](https://cloud.githubusercontent.com/assets/9950837/10662631/6dd577e8-78cf-11e5-8370-8e83cc259555.PNG)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/765

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Testing Environment - DEVELOP:** http://static.gapminderdev.org/vizabi/develop/preview/mountainchart.html
