### ISSUE TITLE
v0.8.4_07: Bars are truncated from upper side

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#745]
**SEVERITY:** Major

**MODULE:**  Bar Chart

**Platform:** iPhone-5 (iOS 7.1)

**RELEASE:** v0.8.4

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.4/preview/barchart.html
2)	Bar chart page will be loaded
3)	Click “X and Y”
4)	Click dropdown under Y axis and select “GDP Per Capita” and then click OK
5)	Note that bars are truncated from upper side and going beyond the defined Y axis limit

**ACTUAL RESULTS:**
Bars are truncated from upper side by changing y axis description and going beyond the defined Y axis limit

**EXPECTED RESULTS:** 
Y axis scale should be adjustable according to the bars by changing options

**SCREENSHOT:**

![v0 8 4_07](https://cloud.githubusercontent.com/assets/9950837/10662669/a9b3d818-78cf-11e5-9db3-2fd4d9725f81.PNG)

**Comment by angieskazka** [comment]
@arthurcamara1 it is because metadata "domain" field is written for countries
i see no better solution than to wait for the server metadata update. adding more logic to vizabi min and max system would be far from elegant

**Comment by arthurcamara1** [comment]
Agreed @angieskazka. We need that ASAP

**Comment by jheeffer** [comment]
This bug is not present in the current develop branch btw.
