### ISSUE TITLE
v0.8.4_09: Small pop up screen is disturbed

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#747]
**SEVERITY:** Minor

**MODULE:**  Mountain Chart

**Platform:** iPhone-5 (iOS 7.1)

**RELEASE:** v0.8.4

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.4/preview/barchart.html
2)	Bar chart page will be loaded
3)	Click x axis description
4)	Note that small pop up screen is disturbed

**ACTUAL RESULTS:**
Small pop up screen is disturbed by clicking X axis description

 **EXPECTED RESULTS:** 
Small pop up screen should not be disturbed by clicking X axis description

**SCREENSHOT:**

![v0 8 4_09](https://cloud.githubusercontent.com/assets/9950837/10662745/fe152f4c-78cf-11e5-8770-23ef641dc7a0.PNG)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/757

**Comment by angieskazka** [comment]
@k6Labz please retest on develop

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Testing Environment - DEVELOP:**  http://dev-tools.gapminderdev.org:3001/
