### ISSUE TITLE
zoomOnRectangle became imprecise. Manual setting of min/max is disturbed

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#751]

**Comment by plward11** [comment]
Pull request: https://github.com/Gapminder/vizabi/pull/1165

**Comment by angieskazka** [comment]
thanks! this was an issue since 0.8.4 and now it's finally done almost 10 releases after! :bomb:

**Comment by plward11** [comment]
Glad to help! Thanks for the opportunity to work on it :)
