### ISSUE TITLE
Font-sizing is disturbed when going from 18 tot 19 selected markers

### ISSUE THREAD

**Issue by jheeffer** [Gapminder/vizabi#755]
Select 18 markers
Select one more. 
See the font size get extremely disturbed

Expected:
Font-size should not be disturbed

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/777

**Comment by angieskazka** [comment]
not sure if #777 really fixed the problem, but we'll reopen it if the issue comes back
