### ISSUE TITLE
Sorting order of markers gets disturbed when selecting many

### ISSUE THREAD

**Issue by jheeffer** [Gapminder/vizabi#756]
Select a whole lot of markers
See that the sorting per region is not completely right

![image](https://cloud.githubusercontent.com/assets/3648190/10731646/aeb1ed6c-7bf6-11e5-9e2d-8b8a92c09a20.png)

here Japan and Madagascar switched places

Expected:
Sorting to not be disturbed

**Comment by angieskazka** [comment]
i guess this two-level sorting is not done properly
https://github.com/Gapminder/vizabi/blob/develop/src/tools/mountainchart/mountainchart-selectlist.js#L21-L27


this is the example of correct sorting i tried to achieve

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/767

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/768

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/769

**Comment by angieskazka** [comment]
done
