### ISSUE TITLE
v0.8.4_10: Small pop up screen is not shown properly on landscape mode

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#762]
**SEVERITY:** Major

**MODULE:**  
* Bubble Chart
* Mountain Chart

**Platform:** Nexus-5 (5.1.1) / Chrome 44.0

**RELEASE:** v0.8.4

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.4/preview/bubblechart.html
2)	Bubble chart page will be loaded
3)	Change mobile orientation from portrait to landscape
4)	Click any option on the chart, like click “X and Y”
5)	Note that small pop up screen is not shown properly

**ACTUAL RESULTS:**
Small pop up screen is not shown properly on landscape mode 

**EXPECTED RESULTS:** 
Small pop up screen should be shown properly on any mode

**SCREENSHOT:**

![v0 8 4_10](https://cloud.githubusercontent.com/assets/9950837/10728408/55926df8-7c03-11e5-8edb-8bb2577b56bc.png)

**Comment by dab2000** [comment]
isn't reproduced on develop

**Comment by k6Labz** [comment]
Now this issue is reproduced in another way on develop

**Testing Environment - DEVELOP:** http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html 

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Change mobile orientation from portrait to landscape
4)	Click “Color”
5)	Note that OK is missing from small pop up screen.

**Screenshot:**

![screenshot_20151027-092643](https://cloud.githubusercontent.com/assets/9950837/10749704/4a669fa8-7c8f-11e5-9324-6a5f1e0a7547.png)

**Comment by angieskazka** [comment]
looks fine on my nexus 5 now
