### ISSUE TITLE
v0.8.4_12: Axes values for selected bubble are not shown 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#764]
**SEVERITY:** Minor

**MODULE:**  Bubble Chart

**Platform:** Nexus-5 (5.1.1) / Chrome 44.0

**RELEASE:** v0.8.4

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.4/preview/bubblechart.html
2)	Bubble chart page will be loaded
3)	Tap a bubble , the bubble is selected
4)	Note that axes values for selected bubble are not shown

**ACTUAL RESULTS:**
Axes values for selected bubble are not shown 

**EXPECTED RESULTS:** 
Axes values for selected bubble should show properly 

**SCREENSHOT:**

![v0 8 4_12 1](https://cloud.githubusercontent.com/assets/9950837/10728444/9a0a8aba-7c03-11e5-86e7-a5dfe6bab79f.png)

![v0 8 4_12 2](https://cloud.githubusercontent.com/assets/9950837/10728445/9a0f4460-7c03-11e5-844e-8f1a02680832.png)

**Comment by angieskazka** [comment]
it's ok, we don't support this on mobile
