### ISSUE TITLE
v0.8.4_14: Options are disappeared by selecting a bubble

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#773]
**SEVERITY:** Major

**MODULE:**  Bubble Chart

**Platform:**  MAC / Safari 8.0

**RELEASE:** v0.8.4

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.4/preview/bubblechart.html
2)	Bubble chart page will be loaded
3)	Change the orientation from portrait to landscape by clicking “Landscape” button under RESPONSIVENESS
4)	Select a bubble 
5)	Note that options are disappeared by selecting a bubble

**ACTUAL RESULTS:**
Options are disappeared by selecting a bubble on landscape view

**EXPECTED RESULTS:** 
Options should be available on any mode

**SCREENSHOT:**

![v0 8 4_14](https://cloud.githubusercontent.com/assets/9950837/10757193/0321c55a-7ccb-11e5-939a-edc1cba9b004.png)

**Comment by arthurcamara1** [comment]
Good catch

**Comment by arthurcamara1** [comment]
The problem is that it’s VERTICALLY scrollable instead of Horizontally, even when we change to landscape on small screen

**Comment by arthurcamara1** [comment]
@sergey-filipenko

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/776

**Comment by angieskazka** [comment]
thanks
