### ISSUE TITLE
v0.8.4_15: Options are not clickable on expanded screen

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#774]
**SUMMARY:** 
**1)** Options are not clickable on expanded screen
**2)** Chart is disturbed expanded screen
**3)** Right panel of preview page is missing
**4)** X axis line is missing

**SEVERITY:** Major

**MODULE:**  Bubble Chart

**Platform:**  MAC / Safari 8.0

**RELEASE:** v0.8.4

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.4/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Click “Expand”
4)	**Note that chart is disturbed**
5)	Now press “Esc” button for Restore
6)	**Note that right panel of preview page is missing**
7)	Now click “Expand” again
8)	**Note that options are not clickable on expanded screen**
9)	Now press “Esc” button again for Restore
10)	**Note that X axis line is missing**

**ACTUAL RESULTS:**
Options are not clickable and chart is disturbed expanded screen

**EXPECTED RESULTS:** 
Options should be clickable and chart should not be disturbed

**SCREENSHOT:**

**File is attached with Screenshots**

[v0.8.4_15.docx](https://github.com/Gapminder/vizabi/files/21622/v0.8.4_15.docx)

**Comment by angieskazka** [comment]
Could not reproduce any of these on MAC/Safari. Can anyone?

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Testing Environment:**
**1)** http://static.gapminderdev.org/vizabi/release/v0.8.5/preview/bubblechart.html
**2)** http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html

**Platform:** MAC / Safari 9.0
