### ISSUE TITLE
This x-axis should be labeled using doubling labels

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#78]
![image](https://cloud.githubusercontent.com/assets/496398/6552517/ea160e12-c646-11e4-99f8-54c41967ff3c.png)
http://static.gapminderdev.org/vizabi/develop/preview_pages/_examples/bubble-chart.html#{"state":"{\"marker\":{\"dimensions\":[\"entities\",\"time\"],\"type\":\"geometry\",\"shape\":\"circle\",\"label\":{\"use\":\"property\",\"value\":\"geo.name\"},\"axis_y\":{\"use\":\"indicator\",\"value\":\"lex\",\"scale\":\"linear\"},\"axis_x\":{\"use\":\"indicator\",\"value\":\"gdp_per_cap\",\"scale\":\"log\"},\"size\":{\"use\":\"indicator\",\"value\":\"pop\",\"scale\":\"linear\",\"max\":0.75},\"color\":{\"use\":\"property\",\"value\":\"geo.region\",\"domain\":[\"#F77481\",\"#E1CE00\",\"#B4DE79\",\"#62CCE3\"]}},\"time\":{\"value\":\"1970\",\"start\":\"1952\",\"end\":\"2012\",\"playable\":true,\"playing\":false,\"loop\":false,\"roundOnPause\":true,\"speed\":300,\"unit\":\"year\",\"step\":1,\"formatInput\":\"%Y\"},\"entities\":{\"show\":{\"dim\":\"geo\",\"filter\":{\"geo\":[\"afg\",\"alb\",\"dza\",\"ago\",\"atg\",\"arg\",\"arm\",\"abw\",\"aus\",\"aut\",\"aze\",\"bhs\",\"bhr\",\"bgd\",\"brb\",\"blr\",\"bel\",\"blz\",\"ben\",\"btn\",\"bol\",\"bih\",\"bwa\",\"bra\",\"chn\",\"brn\",\"bgr\",\"bfa\",\"bdi\",\"khm\",\"cmr\",\"can\",\"cpv\",\"caf\",\"tcd\",\"_cis\",\"chl\",\"col\",\"com\",\"cod\",\"cog\",\"cri\",\"civ\",\"hrv\",\"cub\",\"cyp\",\"cze\",\"dnk\",\"dji\",\"dom\",\"ecu\",\"egy\",\"slv\",\"gnq\",\"eri\",\"est\",\"eth\",\"fji\",\"fin\",\"fra\",\"guf\",\"pyf\",\"gab\",\"gmb\",\"geo\",\"deu\",\"gha\",\"grc\",\"grd\",\"glp\",\"gum\",\"gtm\",\"gin\",\"gnb\",\"guy\",\"hti\",\"hnd\",\"hkg\",\"hun\",\"isl\",\"ind\",\"idn\",\"irn\",\"irq\",\"irl\",\"isr\",\"ita\",\"jam\",\"jpn\",\"jor\",\"kaz\",\"ken\",\"kir\",\"prk\",\"kor\",\"kwt\",\"kgz\",\"lao\",\"lva\",\"lbn\",\"lso\",\"lbr\",\"lby\",\"ltu\",\"lux\",\"mac\",\"mkd\",\"mdg\",\"mwi\",\"mys\",\"mdv\",\"mli\",\"mlt\",\"mtq\",\"mrt\",\"mus\",\"myt\",\"mex\",\"fsm\",\"mda\",\"mng\",\"mne\",\"mar\",\"moz\",\"mmr\",\"nam\",\"npl\",\"nld\",\"ant\",\"ncl\",\"nzl\",\"nic\",\"ner\",\"nga\",\"nor\",\"omn\",\"pak\",\"pan\",\"png\",\"pry\",\"per\",\"phl\",\"pol\",\"prt\",\"pri\",\"qat\",\"reu\",\"rou\",\"rus\",\"rwa\",\"lca\",\"vct\",\"wsm\",\"stp\",\"sau\",\"sen\",\"srb\",\"syc\",\"sle\",\"sgp\",\"svk\",\"svn\",\"slb\",\"som\",\"zaf\",\"sds\",\"esp\",\"lka\",\"sdn\",\"sur\",\"swz\",\"swe\",\"che\",\"syr\",\"twn\",\"tjk\",\"tza\",\"tha\",\"tls\",\"tgo\",\"ton\",\"tto\",\"tun\",\"tur\",\"tkm\",\"uga\",\"ukr\",\"are\",\"gbr\",\"usa\",\"ury\",\"uzb\",\"vut\",\"ven\",\"pse\",\"esh\",\"vnm\",\"vir\",\"yem\",\"zmb\",\"zwe\"],\"geo.category\":[\"country\"]}},\"select\":[],\"brush\":[]}}","width":320,"height":568,"fullscreen":false}

**Comment by angieskazka** [comment]
It's an interesting almost a boundary case. I use double scale when the domain max/min is between 10 and 1024. This domain has max/min = 180 000 / 141 = 1275, which is beyond the allowed range.

@olarosling I suggest let's solve it by decreasing the margins in the domain. Like, setting min to 180 instead of 141 will solve the problem. No country goes ever below 400 $ anyway
