### ISSUE TITLE
v0.8.4_16: “Expand” button is not available in landscape view.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#782]
**SEVERITY:** Major  

**MODULE:** Bubble Chart

**Platform:** 
* Nexus 9 (5.0.1) / Chrome 45.0
* Ipad-Air-2 (9.1)/ Safari 

**RELEASE:** v0.8.4

**STEPS TO REPRODUCE:** 
1)	Navigate to URL : http://static.gapminderdev.org/vizabi/release/v0.8.4/preview/bubblechart.html
2)	Click on Landscape button.
3)	Note that “Expand” button is not available in landscape view.

**ACTUAL RESULTS:**
Expand button is not available in landscape view.

**EXPECTED RESULTS:**
Expand button should be available in landscape view.

**SCREENSHOT:**

![v0 8 4_16](https://cloud.githubusercontent.com/assets/9950837/10787277/7d6e9b96-7d91-11e5-8c12-f9d68f7cef38.PNG)

**Comment by sergey-filipenko** [comment]
Bottom button bar is crollable (fixed 27.10) check now please

**Comment by k6Labz** [comment]
Agree with you @sergey-filipenko  that bottom button bar is scroll-able but "Expand" button is still missing on landscape view of v0.8.4.
But this is OK on DEVELOP

**Retest Result:** Pass

**Testing Environment - DEVELOP:** http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html
