### ISSUE TITLE
v0.8.4_17: No pin and hand icon is available on pop-up in “Full” screen view.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#783]
**SEVERITY:**  Major

**MODULE:** 
* Bubble Chart
* Mountain Chart

**Platform:** 
* Nexus 9 (5.0.1) / Chrome 45.0
* Ipad-Air-2 (9.1)/ Safari 

**RELEASE:** v0.8.4

**STEPS TO REPRODUCE:** 
1)	Navigate to URL : http://static.gapminderdev.org/vizabi/release/v0.8.4/preview/bubblechart.html
2)	Tap on “Full” view button.
3)	Full screen will appear and click on “Color” button.
4)	A pop-up will appear
5)	Note that there is no pin and hand icon on pop-up in “Full” screen view.

**ACTUAL RESULTS:**
No pin and hand icon is appeared on pop-up in “Full screen” view 

**EXPECTED RESULTS:**
Pin and hand icon should appear on pop-up in “Full screen” view.

**SCREENSHOT:**

![v0 8 4_17](https://cloud.githubusercontent.com/assets/9950837/10787302/b68a74d6-7d91-11e5-9174-eed8e9d944c3.PNG)

**Comment by angieskazka** [comment]
@k6Labz can you please take a bigger screenshot so that we can see width and height of vizabi container on top right?

**Comment by k6Labz** [comment]
**Testing Environment:** 
**1)** http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html 
**2)** http://static.gapminderdev.org/vizabi/release/v0.8.5/preview/bubblechart.html

**Screenshots:**

![edcb58cad0a4ffe4542e77a7822021d2e0dc4507fbd4ec14cb pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/9950837/10931325/4220a6fe-82e8-11e5-9d3d-a1c3430c3cb3.jpg)

![cba33d52adb61b83adc6acaef18da370c658a64a2c13ca8e31 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/9950837/10931327/48201c60-82e8-11e5-956b-7e813b024a7b.jpg)

![058469264dbf004571ace4e07644e17ca9cd7390d6ff6c5159 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/9950837/10931331/4dd761e0-82e8-11e5-96cd-9f838456974b.jpg)

**Comment by angieskazka** [comment]
thank! vizabi is running in "small" profile, as defined in jayout.js, because the width above is 448px
small profile implies no dragging-pinning functionality 

```
  screen_profiles: {
    small: {
      min_width: 0,
      min_height: 0
    },
    medium: {
      min_width: 600,
      min_height: 400
    },
    large: {
      min_width: 1000,
      min_height: 700
    }
  },
```
