### ISSUE TITLE
v0.8.4_19: On selecting the default color, icon of color/x becomes colorless.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#785]
**SEVERITY:**  Major

**MODULE:**  
* Mountain chart.
* Bubble chart.
* Bar chart.

**Platform:** 
* Ipad-Air-2 (9.1)/ Safari 
* Nexus 9 (5.0.1) / Chrome 45.0

**RELEASE:** v0.8.4

**STEPS TO REPRODUCE:** 
1.	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.8.4/preview/mountainchart.html
2.	Tap on “Color” button.
3.	A pop-up will appear with a dropdown.
4.	Select “Geo name” from dropdown.
5.	A list of colors appears.
6.	Click on “color/1”.
7.	Color picker will appear.
8.	Click on the (Black) default button.
9.	Note that Color/1 will become colorless.

**ACTUAL RESULTS:**
On selecting the default color, icon of color/x becomes colorless.

**EXPECTED RESULTS:**
On selecting the default color, icon of color/x should not be colorless.

**SCREENSHOT:**

![v0 8 4_19](https://cloud.githubusercontent.com/assets/9950837/10787366/48f351da-7d92-11e5-808e-1845593fae4a.PNG)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/788
