### ISSUE TITLE
v0.8.4_21: Bubbles are hiding below x-axis.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#787]
**SEVERITY:**  Major

**MODULE:**  Bubble chart.

**Platform:**  Ipad-Air-2 (9.1)/ Safari 

**RELEASE:** v0.8.4

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.8.4/preview/bubblechart.html
2)	User is on bubble chart page.
3)	Set “GDP per capita” on x axis and y axis as well.
4)	Click “Full” view.
5)	Slide the bar to 1800 on the extreme left.
6)	Note that the bubbles are hiding below x-axis.

**ACTUAL RESULTS:**
Bubbles are hiding below x-axis.

**EXPECTED RESULTS:**
Bubbles should not hide below x-axis and should be visible clearly.

**SCREENSHOT:**

![v0 8 4_21](https://cloud.githubusercontent.com/assets/9950837/10787438/beb4acde-7d92-11e5-8738-0704cf289b5d.PNG)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/812

**Comment by k6Labz** [comment]
**Retest Result:** Passed
**Environment:** Develop - http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html
