### ISSUE TITLE
Trails fail after window resize

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#792]
![image](https://cloud.githubusercontent.com/assets/496398/10801284/fdb5c610-7db6-11e5-9310-c216678d09f3.png)
![Uploading image.png…]()

**Comment by jheeffer** [comment]
@angieskazka can you reproduce this? Is our labelling correct?

**Comment by angieskazka** [comment]
Could only reproduce on 0.8.6 with "follow bubbles with zoom" option ON
then could not reproduce on 0.8.7 and 0.8.8. assume it's fixed
