### ISSUE TITLE
Scroll of a dialog spills over to page-scroll

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#794]
When scrolling down the options list, when hitting bottom, the rest of the page starts scrolling down !

The solution must be to not continue scroll, unless scroll was interupted, and then continues down again.

(we should also see an indication of "scroll bar to the right of the options list ", separate issue listed)

[image](https://cloud.githubusercontent.com/assets/496398/10801440/adc9cb5a-7db7-11e5-904e-c34221464e78.png)

http://dev-tools.gapminderdev.org:3001/tools/bubbles#_time_adaptMinMaxZoom:true&lockNonSelected=2015;&entities_select@_geo=USA&labelOffset@:0.09038684838020394&:-0.06280942136031899;&trailStartTime=1800;&_geo=NGA&labelOffset@:0&:0;&trailStartTime=1800;;&needUpdate_;;&marker_axis%2F_y_min:0&max:550&fakeMin=0.0&fakeMax=550;&axis%2F_x_min:500&max:130000&fakeMin=500&fakeMax=130000;&size_min:0.08333333333333333&max:0.7962962962962963

**Comment by angieskazka** [comment]
A bit clearer explanation: 
when you rotate a scroll wheel the views will scroll in the priority of inside out
as the inner view reaches the end of scrolling, all the unused scrolling events are applied to the outer view and so on...

if your mouse has a step by step scrolling, like on windows 7, that's no problem
if your mouse is continuous, like on mac, then you can observe an undesired effect that OIa described

solution: when the view reached the end scrolling position, discard all pending scrolling events in the queue. then proceed as normal: scroll outer view with the new events

if that may help, you can find the next-priority scrollable view using function
`utils.findScrollableAncestor(node)`
where `node` is the current view

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1033

**Comment by angieskazka** [comment]
@sergey-filipenko country list in find and show dialogs

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1057
