### ISSUE TITLE
Tools_v0.8.4 _22: OK button is not functional on small pop up screen

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#799]
**SEVERITY:** Major

**MODULE:** Tools page 

**Platform:** Windows 7 / Chrome 48.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://dev-tools.gapminderdev.org:3001/
2)	Tools page is loaded.
3)	Click the “Options” button, a small pop up screen will be displayed
4)	Click OK button which is available on the small pop up screen
5)	Note that OK is not functional

**ACTUAL RESULTS:**
OK button is not functional on small pop up screen of “Options” button.

**EXPECTED RESULTS:** 
OK button should be functional on small pop up screen of “Options” button.

**SCREENSHOT:**

![tools_v0 8 4 _22](https://cloud.githubusercontent.com/assets/9950837/10816726/f6aa0214-7e56-11e5-9839-7499ca4418c1.png)

**Comment by jheeffer** [comment]
Is fixed on dev-tools
