### ISSUE TITLE
selected bubble bug

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#80]
When clicking a bubble it gets selected, and the other bubbles show with lower alpha. But the effect doesn't happen until I move times-slider . It shows that clicking the bubble is doesn't trigger a re-render bubbles, after setting the state value correctly.  ( the same goes for deselecting)
![image](https://cloud.githubusercontent.com/assets/496398/6563737/acdfc9d6-c6a3-11e4-8fec-a0924fb40c04.png)

**Comment by angieskazka** [comment]
done
