### ISSUE TITLE
Tools_v0.8.4 _23: Text is overlapping

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#800]
**SEVERITY:** Minor

**MODULE:** Tools page 

**Platform:** Windows 7 / Chrome 48.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://dev-tools.gapminderdev.org:3001/
2)	Tools page is loaded.
3)	Note that text is overlapping on right upper corner if the chart

**ACTUAL RESULTS:**
Text is overlapping on right upper corner if the chart.

**EXPECTED RESULTS:** 
Text should not overlap in any case

**SCREENSHOT:**

![tools_v0 8 4 _23](https://cloud.githubusercontent.com/assets/9950837/10816794/5b173802-7e57-11e5-9032-326bbb2f384c.png)

**Comment by jheeffer** [comment]
Please repost this issue in https://github.com/Gapminder/gapminder-tools-vizabi

**Comment by angieskazka** [comment]
i fixed it now
