### ISSUE TITLE
Tools_v0.8.4 _24: Small pop up screen is drag able even after pinning it.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#801]
**SEVERITY:** Major

**MODULE:** Tools page 

**Platform:** Windows 7 / Chrome 48.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://dev-tools.gapminderdev.org:3001/
2)	Tools page is loaded.
3)	Click the “Options” button, a small pop up screen will be displayed
4)	Click “Pin” icon which is available on the small pop up screen
5)	Hold the hand icon and drag the small pop up screen
6)	Note that hand icon is working even after we enable the pin functionality 

**ACTUAL RESULTS:**
Hand icon is working and small pop up screen is drag able even after we enable the pin functionality 

**EXPECTED RESULTS:** 
Small pop up screen should not be drag able after enabling the pin functionality

**SCREENSHOT:**

![tools_v0 8 4 _24](https://cloud.githubusercontent.com/assets/9950837/10816820/92bab5e0-7e57-11e5-89fd-e21b735a9704.png)

**Comment by angieskazka** [comment]
it's not a bug, it's a feature. see #728
