### ISSUE TITLE
Tools_v0.8.4 _25: No country is selected after selecting countries from “Show” pop up.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#802]
**SEVERITY:** Critical

**MODULE:** Tools page 

**Platform:** Windows 7 / Chrome 48.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://dev-tools.gapminderdev.org:3001/
2)	Tools page is loaded.
3)	Click the “Show” button, a small pop up screen will be displayed
4)	Select any country from pop up screen
5)	Note that no country is selected after selecting countries from “Show” pop up.

**ACTUAL RESULTS:**
No country is selected after selecting countries from “Show” pop up.

**EXPECTED RESULTS:** 
Desired countries should be selected after selecting countries from “Show” pop up.

**SCREENSHOT:**

![tools_v0 8 4 _25](https://cloud.githubusercontent.com/assets/9950837/10816846/bc8e9cec-7e57-11e5-9e88-469a684734db.png)

**Comment by valorkin** [comment]
as agreed Gapminder ids will be lowercased

**Comment by angieskazka** [comment]
thanks!

**Comment by k6Labz** [comment]
@angieskazka 
This bug is reproduced again.

**Testing Environment:** http://tools-stage.gapminderdev.org/tools/mountain

**Platform:** Windows 7 / 48.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://tools-stage.gapminderdev.org/tools/mountain 
2)	Tools page is loaded.
3)	Click the “Show” button, a small pop up screen will be displayed
4)	Select first country "Antigua and Barbuda"
5)	Note that no country is selected after selecting country from “Show” pop up.

**Screenshot:** 

![vizabi1](https://cloud.githubusercontent.com/assets/9950837/13346162/1c8222a4-dc86-11e5-912a-5b04ba9c9eb2.png)
