### ISSUE TITLE
Tools_v0.8.4 _27: Pop up screen size is reduced by hovering effect

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#804]
**SEVERITY:** Minor

**MODULE:** Tools page 

**Platform:** Windows 7 / Chrome 48.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://dev-tools.gapminderdev.org:3001/
2)	Tools page is loaded.
3)	Click Y axis description
4)	Take mouse to the first option which is “Wealth”
5)	Sub options will be available on second small pop up screen
6)	Note that the second small pop up screen size is reduced by hovering effect.

**ACTUAL RESULTS:**
By clicking Y axis description and then “Wealth”, second small pop up screen size is reduced by hovering effect 

**EXPECTED RESULTS:** 
Pop up screen size should not reduce by hovering effect

**SCREENSHOT:**

![tools_v0 8 4 _27 1](https://cloud.githubusercontent.com/assets/9950837/10816886/124adf24-7e58-11e5-8f60-44d35f16072e.png)

![tools_v0 8 4 _27 2](https://cloud.githubusercontent.com/assets/9950837/10816887/12525fce-7e58-11e5-816a-a26b0f9293b3.png)

**Comment by angieskazka** [comment]
the idea here is to replicate Mac Finder multicolumn view. many columns can be open and they still fit
when the new column doesn't fit, the previous columns contract a little, to give space to the latest column

the algortithm is supposed to be implemented in treemenu.js (might be function _resizeDropdown)
but it's either not working at all or buggy

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1004

**Comment by k6Labz** [comment]
Retest Result: Pass

Platform: Windows 7 / Chrome 46.0

Testing Environment: http://dev-tools.gapminderdev.org:3001/
