### ISSUE TITLE
Dragged dialogs and recently opened dialogs should always be in front

### ISSUE THREAD

**Issue by arthurcamara1** [Gapminder/vizabi#810]
In the example below, I opened the dialog Stack, dragged it a bit and pinned, and then opened the dialog Find. Notice that Find dialog is **below** stack dialog . It would be much better to have it open to the front. 

![Example](http://i.imgur.com/64oLCHr.png)

Also, if the user starts dragging a dialog, it should immediately placed in the front.

This can be achieved with manipulation of `z-index` through javascript

**Comment by angieskazka** [comment]
thanks!
