### ISSUE TITLE
Individual colors, 4 improvements

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#814]
1. The option to show seaparet colors, should be called "Individual colors"
2. When using individual colors, don't show a color legend at all, just the drop down.
3. Use a more joyful color-schema: which goes across happy colors like ours! 
4. Don't show the geo-id and geo name as options under color drop down.

![image](https://cloud.githubusercontent.com/assets/496398/10854573/d1bf9b08-7f3c-11e5-9f11-88c50336e0b2.png)

**Comment by jheeffer** [comment]
Add 'individual' option in dropdown
Think of how to 'dynamically' hide what is now geo-id and geo-name (maybe according to the definition of space).

**Comment by angieskazka** [comment]
in `vizabi-gapminder.js` a hook has "allow" field, we can add something like allow --> names --> ["!geo.name"] thus not allowing names to appear in the list

![image](https://cloud.githubusercontent.com/assets/3648190/11163379/325a47d8-8acd-11e5-9394-89c20461a402.png)

regarding geo-id we can figure out from entities --> dim that this is a key for individual colors and rename it

**Comment by angieskazka** [comment]
Happy colors update:

![image](https://cloud.githubusercontent.com/assets/3648190/11172641/16b5da44-8c0b-11e5-8ee9-2c83036f6b9c.png)
