### ISSUE TITLE
v0.8.5_01: Map of “Region” is truncated from right side.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#817]
**SEVERITY:**  Minor

**MODULE:**  
* Bubble Chart.
* Mountain Chart.

**Platform:**
* Windows 7 / Chrome 48.0
* Windows 7 / Firefox  42.0
* MAC / Safari 8.1

**RELEASE:** v0.8.5

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.8.5/preview/bubblechart.html
2)	“Bubble Chart” will be loaded.
3)	Click on “Expand” button on the Bubble Chart.
4)	Note that on top right corner right portion of map is truncated.

**ACTUAL RESULTS:**
Map of “Region” is truncated from right side.

**EXPECTED RESULTS:**
Map of “Region” should not truncate from any side.

**SCREENSHOT:**

![v0 8 5_1](https://cloud.githubusercontent.com/assets/9950837/10880750/9832bd4e-817f-11e5-8c7b-ffe395d3beb0.png)

**Comment by dab2000** [comment]
fixed in #604

**Comment by angieskazka** [comment]
still there... Mac/Chrome 46

![image](https://cloud.githubusercontent.com/assets/3648190/10932799/07287e50-82d4-11e5-969c-d8cc4297b487.png)

**Comment by angieskazka** [comment]
done
