### ISSUE TITLE
v0.8.5_02: “YEAR” behind the “Mountain Chart” is truncated.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#818]
**SEVERITY:**  Major

**MODULE:**  Mountain Chart

**Platform:**  Windows 7 / Chrome 48.0

**RELEASE:** v0.8.5

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL :  http://static.gapminderdev.org/vizabi/release/v0.8.5/preview/mountainchart.htm
2)	“Mountain Chart” page will be loaded.
3)	Click “landscape” view button on the preview page.
4)	Note that “YEAR” behind the “Mountain Chart” is truncated.

**ACTUAL RESULTS:**
“YEAR” behind the “Mountain Chart” is truncated.

**EXPECTED RESULTS:**
“YEAR” behind the “Mountain Chart” should not truncate.

**SCREENSHOT:**

![v0 8 5_2](https://cloud.githubusercontent.com/assets/9950837/10880780/d0cce71a-817f-11e5-872d-b4ae3f848761.png)

**Comment by angieskazka** [comment]
fixed in 8d31a216abacf5f6b648d61e00f97208968f2ece
