### ISSUE TITLE
v0.8.5_03: Alphabet “S” is overlap by X-axis Line.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#819]
**SEVERITY:**  Minor.

**MODULE:**  Bubble Chart

**Platform:**
* Windows 7 / Chrome 48.0
* Windows 7 / Firefox  42.0

**RELEASE:** v0.8.5

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.8.5/preview/bubblechart.html
2)	“Bubble Chart” page is open.
3)	Click on “Landscape” view.
4)	Note that, alphabet “S” is overlap by X-axis line.

**ACTUAL RESULTS:**
Alphabet “S” is overlap by X-axis Line.

**EXPECTED RESULTS:**
Alphabet “S” should not overlap by X-axis Line.

**SCREENSHOT:**

![v0 8 5_3](https://cloud.githubusercontent.com/assets/9950837/10880947/e13a5604-8180-11e5-9cc1-40d42102126a.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/838
