### ISSUE TITLE
v0.8.5_04: “Search” word is not localized to “Sök” by switching language.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#820]
**SEVERITY:**  Minor.

**MODULE:**  Bubble Chart

**Platform:**
* Windows 7 / Chrome 48.0
* Windows 7 / Firefox  42.0
* MAC / Safari 8.1

**RELEASE:** v0.8.5

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.8.5/preview/bubblechart.html
2)	Click on the description of Y-Axis or X-axis.
3)	A pop-up will appear having “Search” bar in it.
4)	Click on “Switch Language” button.
5)	Note that content written in pop-up is translated to “Swedish” language except word “Search” in the search bar.

**ACTUAL RESULTS:**
“Search” word is not translated to word “Sök” by changing “Swedish” language.

**EXPECTED RESULTS:**
“Search” word should be translated to word “Sök” by changing “Swedish” language.

**SCREENSHOT:**

![v0 8 5_4](https://cloud.githubusercontent.com/assets/9950837/10880964/083aa48e-8181-11e5-9c7c-d730df4acab2.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/835

**Comment by angieskazka** [comment]
and also 84ac90dc920e8acd1498ee04118c239f17f4fd2f
