### ISSUE TITLE
v0.8.5_05: “Icon” labels are truncated from below side.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#821]
**SEVERITY:**  Major

**MODULE:**    Bubble Chart

**Platform:**    Windows 7 / Firefox  42.0

**RELEASE:** v0.8.5

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.8.5/preview/bubblechart.html
2)	“Bubble Chart” page will be loaded.
3)	Click on “Landscape” view button.
4)	Landscape view will be displayed on the page.
5)	Note that “Icon” labels are truncated.

**ACTUAL RESULTS:** 
“Icon” labels are truncated from below side.

**EXPECTED RESULTS:**
“Icons” labels should not be truncated.

**SCREENSHOT:**

![v0 8 5_5](https://cloud.githubusercontent.com/assets/9950837/10880978/274c4b02-8181-11e5-9908-c9f51888dabc.png)

**Comment by angieskazka** [comment]
how come the scrollbar is back?
see #449

**Comment by jheeffer** [comment]
Will be fixed by #840

**Comment by angieskazka** [comment]
no, not yet =) @rlage can you please look into this too

**Comment by rlage** [comment]
@angieskazka, I'm on it!

**Comment by k6Labz** [comment]
**Retest Result:** Pass 

**Platform:** Windows 7 / Firefox 43.0(b6)

**Testing Environment:** http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html
