### ISSUE TITLE
v0.8.5_06: Bubbles are hiding in “Expand” view of “Bubble Chart”.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#822]
**SEVERITY:**  Major

**MODULE:**   Bubble Chart

**Platform:** 
* Windows 7 / Chrome 48.0
* Windows 7 / Firefox  42.0
* MAC / Safari 8.1

**RELEASE:** v0.8.5

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.8.5/preview/bubblechart.html
2)	Select “Child mortality rate” on Y-axis and GDP per capita on X-axis.
3)	Click on “Expand button” and large screen will appear.
4)	Select “Size Gini coefficient” and “YEAR” 1800.
5)	Note that the bubbles are hiding behind Y-axis line.

**ACTUAL RESULTS:**
Bubbles are hiding in “Expand” view of “Bubble Chart”.

**EXPECTED RESULTS:**
Bubbles should not hide in “Expand” view of “Bubble Chart”.

**SCREENSHOT:**

![v0 8 5_6](https://cloud.githubusercontent.com/assets/9950837/10881000/503ddf1c-8181-11e5-96b0-2ac35e33acf4.png)

**Comment by sergey-filipenko** [comment]
fixed in https://github.com/Gapminder/vizabi/issues/787

**Comment by angieskazka** [comment]
yes ;)
