### ISSUE TITLE
v0.8.5_07: Hand Click icon should not appear on empty spaces between icons.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#823]
**SEVERITY:**  Minor

**MODULE:**  
* Bubble Chart.
* Mountain Chart.

**Platform:**
* Windows 7 / Chrome 48.0
* Windows 7 / Firefox  42.0
* MAC / Safari 8.1

**RELEASE:** v0.8.5

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.8.5/preview/bubblechart.html
2)	“Bubble Chart” page will be loaded.
3)	Drag mouse over empty space exactly between “Color” and “Find” icons.
4)	Note that hand click icon appears on the screen even hover on empty spaces.

**ACTUAL RESULTS:**
Hand click icon should not appear between empty spaces in Chart icons.

**EXPECTED RESULTS:**
Hand click icon should not appear between empty spaces in Chart icons and it should appear when we hover on the icon or its label

**SCREENSHOT:**

![v0 8 5_7](https://cloud.githubusercontent.com/assets/9950837/10881034/767737b4-8181-11e5-9b90-787ae2672b39.png)

**Comment by angieskazka** [comment]
...but areas belonging to buttons should still be clickable to reduce fat finger effect

**Comment by jheeffer** [comment]
Add hover effect to button might be enough? @angieskazka @arthurcamara1

**Comment by angieskazka** [comment]
yes, `cursor-pointer` should be on circle, but not on the entire button. but the entire button should remain clickable
