### ISSUE TITLE
v0.8.5_08: “Follow bubbles with zoom” checkbox is not completely functional.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#824]
**SEVERITY:** Major

**MODULE:** Bubble Chart 

**Platform:**
* Windows 7 / Chrome 48.0
* Windows 7 / Firefox  42.0
* MAC / Safari 8.1
* iPad Air 2 iOS(9.1) / Safari 
* Nexus 9 (5.0.2) / Chrome 
* Nexus-5 (6.0) / Chrome 

**RELEASE:** v0.8.5

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.8.5/preview/bubblechart.html
2)	“Bubble Chart” will be loaded.
3)	Click on “X AND Y” and a pop-up is appeared.
4)	On the pop-up, check “Follow bubbles with zoom” checkbox.
5)	Bubbles will zoom-in behind. Click on Ok.
6)	Again Click on “X AND Y” and a pop-up is appeared.
7)	On the pop-up, uncheck on “Follow bubbles with zoom” checkbox.
8)	Bubbles will zoom-out behind. Click on Ok.
9)	Now repeat step 3 and 4.
10)	Note that bubbles will not zoom-in behind.

**ACTUAL RESULTS:** 
Follow bubbles with zoom” checkbox is not completely functional.

**EXPECTED RESULTS:**
 Follow bubbles with zoom” checkbox should be functional every time it is checked/unchecked.

**SCREENSHOT:**

![v0 8 5_8](https://cloud.githubusercontent.com/assets/9950837/10881067/a0f099a4-8181-11e5-923b-80c20eaad2a7.png)

**Comment by angieskazka** [comment]
related to #751

**Comment by jheeffer** [comment]
@angieskazka is effort2: day correct?

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Platform:** Windows 7 / Chrome 46.0

**Testing Environment:** http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html
