### ISSUE TITLE
v0.8.5_09: Blank pop-up is displayed on clicking “Color” icon twice.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#825]
**SEVERITY:**  Major

**MODULE:**  Bubble Chart

**Platform:**
* Windows 7 / Chrome 48.0
* Windows 7 / Firefox  42.0

**RELEASE:** v0.8.5

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.8.5/preview/bubblechart.html
2)	“Bubble Chart” page will be loaded.
3)	 Click on “Landscape” view button.
4)	Click on “Color” icon and pop-up is appeared.
5)	Click Ok.
6)	Again click on “Color” icon.
7)	Note that blank pop-up is display on the screen.

**ACTUAL RESULTS:**
Blank pop-up is displayed on clicking “Color” icon twice.

**EXPECTED RESULTS:**
Blank pop-up should not display on clicking “Color” icon twice.

**SCREENSHOT:**

![v0 8 5_9](https://cloud.githubusercontent.com/assets/9950837/10881086/c972bb00-8181-11e5-932a-049800dee820.png)

**Comment by angieskazka** [comment]
thanks @dab2000
