### ISSUE TITLE
v0.8.5_13: Color of age bar lines is not changed instantly by changing color

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#829]
**SEVERITY:** Minor

**MODULE:**  Pop by age Chart

**Platform:**
* Windows 7 / Chrome 48.0
* Windows 7 / Firefox  42.0
* MAC / Safari 8.1

**RELEASE:** v0.8.5

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.5/preview/popbyage.html 
2)	Pop by age chart page will be loaded
3)	Click “Color” option
4)	A small pop up screen is displayed with a colored ball
5)	Click on that ball and select any color
6)	Note that color of age bar lines is not changed instantly by changing color

**ACTUAL RESULTS:**
Color of age bar lines is not changed instantly by changing color 

**EXPECTED RESULTS:** 
Color of age bar lines should be changed instantly by changing color 

**SCREENSHOT:**

![v0 8 5_13](https://cloud.githubusercontent.com/assets/9950837/10881160/655e3d3c-8182-11e5-83dc-4110a0d76f8f.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/894

**Comment by jheeffer** [comment]
Closed by https://github.com/Gapminder/vizabi/commit/e9570eb6331ef26225c2ab53f79f33b9dd9d0580
