### ISSUE TITLE
v0.8.5_14: Text is overlapping by changing axis description

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#830]
**SEVERITY:** Minor

**MODULE:**  Bar  Chart

**Platform:**
* Windows 7 / Chrome 48.0
* Windows 7 / Firefox  42.0
* MAC / Safari 8.1

**RELEASE:** v0.8.5

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.5/preview/barchart.html 
2)	Bar chart page will be loaded
3)	Click Y axis description
4)	Select “GDP Per Capita”
5)	Note that text is overlapping

**ACTUAL RESULTS:**
Text is overlapping by changing axis description 

**EXPECTED RESULTS:** 
Text should not overlap by changing axis description 

**SCREENSHOT:**

![v0 8 5_14](https://cloud.githubusercontent.com/assets/9950837/10881185/8ced2ffc-8182-11e5-9e8d-632901d8afc7.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/836
