### ISSUE TITLE
v0.8.5_15: No data on LEX //Chart is disappeared by changing axis description

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#831]
**SEVERITY:** Critical

**MODULE:**  Bar  Chart

**Platform:**
* Windows 7 / Chrome 48.0
* Windows 7 / Firefox  42.0
* MAC / Safari 8.1

**RELEASE:** v0.8.5

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.5/preview/barchart.html 
2)	Bar chart page will be loaded
3)	Click Y axis description
4)	Select “Life Expectancy” 
5)	Note that chart is disappeared by changing axis description

**ACTUAL RESULTS:**
Chart is disappeared by changing axis description 

**EXPECTED RESULTS:** 
Chart should not disappear by changing axis description 

**SCREENSHOT:**

![v0 8 5_15](https://cloud.githubusercontent.com/assets/9950837/10881199/ac78dcae-8182-11e5-9a29-c8e88dc1cc51.png)

**Comment by angieskazka** [comment]
we don't have the new data for lex yet. need to wait Ola, when he will update us on it
