### ISSUE TITLE
v0.8.5_16: Play icon is not clickable for first click 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#832]
**SEVERITY:** Major

**MODULE:**  Bar  Chart

**Platform:**
* Windows 7 / Chrome 48.0
* Windows 7 / Firefox  42.0
* MAC / Safari 8.1

**RELEASE:** v0.8.5

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.5/preview/barchart.html 
2)	Bar chart page will be loaded
3)	Click play icon
4)	Note that play icon is not working
5)	By clicking again on play icon, it will work 

**ACTUAL RESULTS:**
Play icon is not clickable for first click but it will work on second click

**EXPECTED RESULTS:** 
Chart should play after first click

**SCREENSHOT:**

![v0 8 5_16](https://cloud.githubusercontent.com/assets/9950837/10881220/cf643114-8182-11e5-863a-bfb790312673.png)

**Comment by angieskazka** [comment]
a guess: first click sets Windows-focus to Chrome window, but makes no action within it. Second click does

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/895

**Comment by arthurcamara1** [comment]
Fixed, but we should review the forced change in time model.
