### ISSUE TITLE
v0.8.5_18:  Age bar lines for United States are showing all region colors by changing “Color” option to “Region”

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#834]
**SEVERITY:** Major

**MODULE:**  Bar  Chart

**Platform:**
* Windows 7 / Chrome 48.0
* Windows 7 / Firefox  42.0
* MAC / Safari 8.1

**RELEASE:** v0.8.5

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.5/preview/barchart.html 
2)	Bar chart page will be loaded
3)	Click “Color”. A small pop up screen is displayed
4)	Click drop down and select “Region”
5)	Note that age bar lines for United States are showing all region colors by changing “Color” option to “Region”

**ACTUAL RESULTS:**
Age bar lines for United States are showing all region colors by changing “Color” option to “Region”

**EXPECTED RESULTS:** 
Age bar lines for United States should show only green color by changing “Color” option to “Region”

**SCREENSHOT:**

![v0 8 5_18](https://cloud.githubusercontent.com/assets/9950837/10881253/12e2421e-8183-11e5-8821-f61a213dc205.png)

**Comment by jheeffer** [comment]
Possible Duplicate #884

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/904

**Comment by jheeffer** [comment]
@sergey-filipenko Thanks for the update, the dropdown to region is working now (so the other issues are fixed), but the chart still shows a lot of colours while it should be just green.
