### ISSUE TITLE
Skip last feature-button, when all buttons don't fit

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#840]
In this case, the x & y - button should be hidden, because it is the last in the array fo buttons (before the two buttons that should always show : options, and full screen)
![image](https://cloud.githubusercontent.com/assets/496398/10907332/76732284-8229-11e5-9f84-2a774731c9fb.png)

**Comment by arthurcamara1** [comment]
This is also related to https://github.com/Gapminder/vizabi/issues/730

**Comment by angieskazka** [comment]
a few improvements are needed 
(please pull first!)

1. Open bubble chart, don't select any bubble
2. Resize window - trail and lock buttons appear on resize
Trail and lock buttons should only appear when something is selected
![image](https://cloud.githubusercontent.com/assets/3648190/10993872/9abf117a-8472-11e5-98ab-caf9366629ec.png)


1. Open bubble chart
2. Select a bubble
3. Trail and lock buttons appear and make "find" and "color" buttons invisible
instead they "find", "color", "size" should stay visible. then some buttons skipped including "trails" and "lock", then options and fullscreen visible
![image](https://cloud.githubusercontent.com/assets/3648190/10993927/fed4422a-8472-11e5-86a8-7af3a3a0d57a.png)


1. Open bubble chart
2. Switch to Landscape under responsiveness panel
3. Select a bubble.
trails and lock buttons become visible but "expand" becomes invisible (i can still scroll to get to it)

![image](https://cloud.githubusercontent.com/assets/3648190/10993975/6bf437c0-8473-11e5-8184-6691e01e3cf1.png)

instead see portrait mode with the same width: 
the spacing between buttons decreases and all buttons fit

![image](https://cloud.githubusercontent.com/assets/3648190/10993984/8889c422-8473-11e5-98b1-c7aaa6f023bb.png)

if they don't fit (say, we have many more buttons), then the expected pattern should stay: color, find, size, all else ..., options, expand

**Comment by angieskazka** [comment]
done for now, #912 concerns further improvement
