### ISSUE TITLE
v0.8.5_19: “Preview Page” is not disappeared on taping “Expand” icon.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#841]
**SEVERITY:** Major

**MODULE:**  Bubble Chart

**Platform:**  iPad Air-2(9.1) / Safari

**RELEASE:** v0.8.5

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL: http://static.gapminderdev.org/vizabi/release/v0.8.5/preview/bubblechart.html
2)	“Bubble Chart” page will be loaded.
3)	Tap on “Expand” icon.
4)	Note that “Preview Page” of “Bubble Chart” will be there even after tapping "Expand".

**ACTUAL RESULTS:**
“Preview Page” is not disappeared on taping “Expand” icon.

**EXPECTED RESULTS:**
By expanding the screen, the preview page should be disappeared.

**SCREENSHOT:**

![v0 8 5_19](https://cloud.githubusercontent.com/assets/9950837/10907557/f76f421e-824c-11e5-894e-6599928bbe37.PNG)

**Comment by sergey-filipenko** [comment]
retest please, https://github.com/Gapminder/vizabi/pull/888

**Comment by k6Labz** [comment]
**Retest Result:** Pass
**Platform:**  iPad Air-2(9.1) / Safari
**Testing Environment:** http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html
