### ISSUE TITLE
v0.8.5_20: Default drop down option is not mentioned.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#842]
**SEVERITY:** Minor

**MODULE:**  Pop by Age.

**Platform:**
* iPad Air-2(9.1) / Safari
* Nexus 9(5.0.2)/ Chrome

**RELEASE:** v0.8.5

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL: http://static.gapminderdev.org/vizabi/release/v0.8.5/preview/popbyage.html
2)	“Pop-by-Age Chart” page will be loaded.
3)	Tap on “Color” icon and pop-up will appear.
4)	Note that default dropdown option is not mentioned.

**ACTUAL RESULTS:**
Default dropdown option is not mentioned.

**EXPECTED RESULTS:**
Default dropdown option should be mentioned.

**SCREENSHOT:**

![v0 8 5_20](https://cloud.githubusercontent.com/assets/9950837/10907681/1f6a3f98-824e-11e5-9169-204cce98113b.PNG)

**Comment by jheeffer** [comment]
Duplicate #884

(Same underlying issue)
