### ISSUE TITLE
v0.8.5_21: 11.3% hides behind the chart on taping “Present” icon. 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#843]
**SEVERITY:** Minor

**MODULE:**  Mountain Chart

**Platform:**
* iPad Air-2(9.1) / Safari
* Nexus 9(5.0.2)/ Chrome
* Nexus-5 (6.0) / Chrome 

**RELEASE:** v0.8.5

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL: http://static.gapminderdev.org/vizabi/release/v0.8.5/preview/mountainchart.html
2)	“Mountain Chart” page will be loaded.
3)	Change iPad orientation to landscape.
4)	Tap on “Present” icon.
5)	Note that 11.3% hides behind the chart.

**ACTUAL RESULTS:**
11.3% hides behind the chart on taping “Present” icon.

**EXPECTED RESULTS:**
No description/content should hide behind the chart on taping “Present” icon.

**SCREENSHOT:**

![v0 8 5_21](https://cloud.githubusercontent.com/assets/9950837/10907745/b11af4f0-824e-11e5-8e95-b5358fe12bce.PNG)

**Comment by jheeffer** [comment]
We should not allow presentation mode on small profile.
