### ISSUE TITLE
v0.8.5_22: Content is truncated on changing the orientation of iPad.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#844]
**SEVERITY:** Minor

**MODULE:**  Bubble Chart

**Platform:**  
* iPad Air-2(9.1) / Safari
* Nexus 9 (5.0.2) / Chrome 

**RELEASE:** v0.8.5

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL: http://static.gapminderdev.org/vizabi/release/v0.8.5/preview/mountainchart.html
2)	“Mountain Chart” page will be loaded.
3)	Hold the iPad at Portrait orientation.
4)	Tap on “Full” view icon.
5)	Change the orientation of iPad to landscape view.
6)	Note that X-axis and Y-Axis description, “Year” behind the chart and “Year” slide bar is truncated.

**ACTUAL RESULTS:**
Content is truncated on changing the orientation of iPad.

**EXPECTED RESULTS:**
Content should not be truncated on changing the orientation of iPad.

**SCREENSHOT:**

![v0 8 5_22](https://cloud.githubusercontent.com/assets/9950837/10907770/e0ca2856-824e-11e5-877f-f8da7bd4c9b0.PNG)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/887

**Comment by k6Labz** [comment]
**Retest Result:** Fail

**Platform:** Nexus 9 (5.1) / Chrome 46.0

**Testing Environment:** http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL: http://static.gapminderdev.org/vizabi/release/v0.8.5/preview/mountainchart.html
2)	“Mountain Chart” page will be loaded.
3)	Hold the iPad at Portrait orientation.
4)	**Tap on “Landscape” view icon.**
5)	Change the orientation of iPad to landscape view.
6)	Note that X-axis and Y-Axis description, “Year” behind the chart and “Year” slide bar is truncated.

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/915

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Platform:** Nexus 9 (5.1) / Chrome 46.0

**Testing Environment - DEVELOP:** http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html
