### ISSUE TITLE
v0.8.5_23: “STORRE” word is not localized to “EXPAND” by switching language.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#845]
**SEVERITY:** Major

**MODULE:**  
* Bubble Chart
* Mountain Chart
* Line Chart
* Pop by Age
* Bar Chart

**Platform:**
* iPad Air-2(9.1) / Safari
* Nexus 9(5.0.2)/ Chrome

**RELEASE:** v0.8.5

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL: http://static.gapminderdev.org/vizabi/release/v0.8.5/preview/bubblechart.html
2)	“Bubble Chart” page will be loaded.
3)	By default – all content will be in English language.
4)	Tap on “Set Lang: SE” icon.
5)	Content will be localized to Swedish language.
6)	Tap on “STORRE” icon and full screen will appear.
7)	Tap “Mindre” and normal view will appear again.
8)	Tap on “Set Lang: EN “icon again.
9)	All content will be localized to English from Swedish except “STORRE” word.

**ACTUAL RESULTS:**
“STORRE” word is not localized to “EXPAND” by switching language.

**EXPECTED RESULTS:**
All content should be localized by switching the language.

**SCREENSHOT:**

![v0 8 5_23](https://cloud.githubusercontent.com/assets/9950837/10907831/52c1b0aa-824f-11e5-8a41-fb13ed768896.PNG)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/864

**Comment by angieskazka** [comment]
tack!
