### ISSUE TITLE
v0.8.5_24: Input fields are not working in fullscreen Safari

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#846]
**SEVERITY:** Major

**MODULE:** Bar Chart

**Platform:**  MAC / Safari 8.1

**RELEASE:** v0.8.5

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.4/preview/barchart.html 
2)	Bar chart page will be loaded
3)	Click “Expand”
4)	Click Y axis description
5)	Click on search bar and write to search
6)	Note that search bar is not editable

**ACTUAL RESULTS:**
Search bar is not editable on expanded screen of bar chart

**EXPECTED RESULTS:** 
Search bar should be editable in every chart 

**SCREENSHOT:**

![v0 8 5_24](https://cloud.githubusercontent.com/assets/9950837/10907868/81f6810c-824f-11e5-9481-395fd6603ea3.png)

**Comment by angieskazka** [comment]
thanks! i did a little search and found that it's disabled by apple, unfortunately 
http://stackoverflow.com/questions/16150601/substitute-for-allow-keyboard-input-javascript-full-screen

@arthurcamara1 how should we work this around?

**Comment by arthurcamara1** [comment]
If completely disabled we can turn fullscreen off in Safari only and make it fill the browser width and height only. Complete fullscreen would just be available on other browsers. Partial fullscreen on Safari (sounds paradoxal)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/893

**Comment by jheeffer** [comment]
Sergey's solution makes input possible but might be confusing as it covers the whole page with the chart.

**Comment by angieskazka** [comment]
that's cool. works just like Arthur suggested above
