### ISSUE TITLE
v0.8.5_26: Line is overlapping with x axis scale line

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#848]
**SEVERITY:** Minor

**MODULE:** Line Chart

**Platform:**  MAC / Safari 8.1

**RELEASE:** v0.8.5

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.4/preview/linechart.html 
2)	Line chart page will be loaded
3)	Click “Landscape” button under RESPONSIVENESS
4)	Nota that red line which is for china, is overlapping with x axis scale line

**ACTUAL RESULTS:**
Red line which is for china, is overlapping with x axis scale line on landscape view

**EXPECTED RESULTS:** 
No line should overlap with X axis scale line

**SCREENSHOT:**

![v0 8 5_26](https://cloud.githubusercontent.com/assets/9950837/10907923/c80d52d8-824f-11e5-8753-835f0d60ca55.png)

**Comment by sergey-filipenko** [comment]
Can not reproduce. Retest please

**Comment by angieskazka** [comment]
a7359b2dd4c3e6d4607c6bdb0005986cc47fccd9 should have fixed it, along with #787

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Testing Environment:** http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html
