### ISSUE TITLE
v0.8.5_27: No small pop up screen is displayed on full screen (Safari 8)

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#849]
**SEVERITY:** Major

**MODULE:** Mountain Chart

**Platform:**  MAC / Safari 8.1

**RELEASE:** v0.8.5

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.4/preview/Mountainchart.html 
2)	Mountain chart page will be loaded
3)	Click “Full” button under RESPONSIVENESS
4)	Now click “X and Y” or “Color”
5)	Note that  no small pop up screen is displayed by clicking the options

**ACTUAL RESULTS:**
No small pop up screen is displayed by clicking the options full screen view

**EXPECTED RESULTS:** 
Small pop up screen should be displayed by clicking options available on the chart 

**SCREENSHOT:**

![v0 8 5_27](https://cloud.githubusercontent.com/assets/9950837/10907964/e68a592c-824f-11e5-8e1d-ff35bb50e3e8.png)

**Comment by k6Labz** [comment]
**Retest Result:** Fail

**Testing Environment:** http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/873

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Platform:**  MAC / Safari 9.0.1

**Testing Environment:** http://static.gapminderdev.org/vizabi/develop/preview/mountainchart.html

**Comment by k6Labz** [comment]
**Retest Result:** Fail

**Platform:**  MAC / Safari 9.0.1

**Testing Environment:** 
**1)** http://static.gapminderdev.org/vizabi/develop/preview/mountainchart.html 
**2)** http://static.gapminderdev.org/vizabi/release/v0.8.8/preview/bubblechart.html

**Comment by arthurcamara1** [comment]
It works for me if I refresh the page after clicking Fullscreen

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/970

**Comment by arthurcamara1** [comment]
Thought it was fixed, but it didn't actually.
