### ISSUE TITLE
wrong size of div on example page

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#85]
This link, for me, on Mac OSX, Chrome & firefox
, renders the vizabi chart four times to large to fit on my scren, or something like that, I only see the top left corner.
http://static.gapminderdev.org/vizabi/feature/line-chart/preview_pages/_gapminder/line-chart.html#{"state":"{\"marker\":{\"dimensions\":[\"entities\",\"time\"],\"type\":\"geometry\",\"shape\":\"line\",\"label\":{\"use\":\"property\",\"value\":\"geo.name\"},\"axis_y\":{\"use\":\"indicator\",\"value\":\"gdp_per_cap\",\"scale\":\"linear\",\"unit\":1000000000},\"axis_x\":{\"use\":\"indicator\",\"value\":\"time\",\"scale\":\"time\"},\"size\":{\"use\":\"value\",\"value\":0.5},\"color\":{\"use\":\"property\",\"value\":\"geo.region\",\"domain\":[\"#00D8ED\",\"#FC576B\",\"#FBE600\",\"#82EB05\"],\"domain_type\":\"continuous\"}},\"time\":{\"value\":\"1810\",\"start\":\"1800\",\"end\":\"2100\",\"playable\":true,\"playing\":false,\"loop\":false,\"roundOnPause\":true,\"speed\":300,\"unit\":\"year\",\"step\":1,\"formatInput\":\"%Y\"},\"entities\":{\"show\":{\"dim\":\"geo\",\"filter\":{\"geo\":[\"ago\",\"arg\",\"aus\",\"swe\"],\"geo.category\":[\"country\"]}},\"select\":[],\"brush\":[]}}","width":2302,"height":1394,"fullscreen":false}

**Comment by angieskazka** [comment]
This link contains unreasonably large "width":2302,"height":1394
@arthurcamara1 should we validate these on load and limit by the available screen size?

**Comment by arthurcamara1** [comment]
No, it should work in this resolution too! :open_mouth:

**Comment by arthurcamara1** [comment]
Similarly,  Bubble Chart seems to work fine: **"width":2574,"height":1369**

http://static.gapminderdev.org/vizabi/develop/preview_pages/_examples/bubble-chart.html#{"state":"{\"time\":{\"start\":1952,\"end\":2012,\"value\":2012,\"step\":1,\"speed\":300,\"formatInput\":\"%Y\",\"trails\":true},\"entities\":{\"show\":{\"dim\":\"geo\",\"filter\":{\"geo\":[\"afg\",\"alb\",\"dza\",\"ago\",\"atg\",\"arg\",\"arm\",\"abw\",\"aus\",\"aut\",\"aze\",\"bhs\",\"bhr\",\"bgd\",\"brb\",\"blr\",\"bel\",\"blz\",\"ben\",\"btn\",\"bol\",\"bih\",\"bwa\",\"bra\",\"chn\",\"brn\",\"bgr\",\"bfa\",\"bdi\",\"khm\",\"cmr\",\"can\",\"cpv\",\"caf\",\"tcd\",\"_cis\",\"chl\",\"col\",\"com\",\"cod\",\"cog\",\"cri\",\"civ\",\"hrv\",\"cub\",\"cyp\",\"cze\",\"dnk\",\"dji\",\"dom\",\"ecu\",\"egy\",\"slv\",\"gnq\",\"eri\",\"est\",\"eth\",\"fji\",\"fin\",\"fra\",\"guf\",\"pyf\",\"gab\",\"gmb\",\"geo\",\"deu\",\"gha\",\"grc\",\"grd\",\"glp\",\"gum\",\"gtm\",\"gin\",\"gnb\",\"guy\",\"hti\",\"hnd\",\"hkg\",\"hun\",\"isl\",\"ind\",\"idn\",\"irn\",\"irq\",\"irl\",\"isr\",\"ita\",\"jam\",\"jpn\",\"jor\",\"kaz\",\"ken\",\"kir\",\"prk\",\"kor\",\"kwt\",\"kgz\",\"lao\",\"lva\",\"lbn\",\"lso\",\"lbr\",\"lby\",\"ltu\",\"lux\",\"mac\",\"mkd\",\"mdg\",\"mwi\",\"mys\",\"mdv\",\"mli\",\"mlt\",\"mtq\",\"mrt\",\"mus\",\"myt\",\"mex\",\"fsm\",\"mda\",\"mng\",\"mne\",\"mar\",\"moz\",\"mmr\",\"nam\",\"npl\",\"nld\",\"ant\",\"ncl\",\"nzl\",\"nic\",\"ner\",\"nga\",\"nor\",\"omn\",\"pak\",\"pan\",\"png\",\"pry\",\"per\",\"phl\",\"pol\",\"prt\",\"pri\",\"qat\",\"reu\",\"rou\",\"rus\",\"rwa\",\"lca\",\"vct\",\"wsm\",\"stp\",\"sau\",\"sen\",\"srb\",\"syc\",\"sle\",\"sgp\",\"svk\",\"svn\",\"slb\",\"som\",\"zaf\",\"sds\",\"esp\",\"lka\",\"sdn\",\"sur\",\"swz\",\"swe\",\"che\",\"syr\",\"twn\",\"tjk\",\"tza\",\"tha\",\"tls\",\"tgo\",\"ton\",\"tto\",\"tun\",\"tur\",\"tkm\",\"uga\",\"ukr\",\"are\",\"gbr\",\"usa\",\"ury\",\"uzb\",\"vut\",\"ven\",\"pse\",\"esh\",\"vnm\",\"vir\",\"yem\",\"zmb\",\"zwe\"],\"geo.category\":[\"country\"]}}},\"marker\":{\"dimensions\":[\"entities\",\"time\"],\"type\":\"geometry\",\"shape\":\"circle\",\"label\":{\"use\":\"property\",\"value\":\"geo.name\"},\"axis_y\":{\"use\":\"indicator\",\"value\":\"lex\",\"scale\":\"linear\"},\"axis_x\":{\"use\":\"indicator\",\"value\":\"gdp_per_cap\",\"scale\":\"log\"},\"size\":{\"use\":\"indicator\",\"value\":\"pop\",\"scale\":\"linear\",\"max\":0.75},\"color\":{\"use\":\"property\",\"value\":\"geo.region\",\"domain\":{\"_default\":\"#ffb600\",\"world\":\"#ffb600\",\"eur\":\"#FFE700\",\"afr\":\"#00D5E9\",\"asi\":\"#FF5872\",\"ame\":\"#7FEB00\"},\"domain_type\":\"continuous\"}}}","width":2574,"height":1369,"fullscreen":true}

**Comment by angieskazka** [comment]
@arthurcamara1 reproducing the bug: go fullscreen, leave fullscreen, refresh

**Comment by arthurcamara1** [comment]
Got it @angieskazka  :+1:

**Comment by angieskazka** [comment]
with the new preview page the bug was naturally solved
