### ISSUE TITLE
v0.8.5_28: Country names with the population are merged with each other 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#850]
**SEVERITY:** Minor

**MODULE:** Mountain Chart

**Platform:**  MAC / Safari 8.1

**RELEASE:** v0.8.5

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.4/preview/Mountainchart.html 
2)	Mountain chart page will be loaded
3)	Select any 4 to 5 curves for different countries
4)	Note that country names with the population are merged with each other

**ACTUAL RESULTS:**
Country names with the population are merged with each other 

**EXPECTED RESULTS:** 
There should be space between every two consecutive country names with the population for better visibility

**SCREENSHOT:**

![v0 8 5_28](https://cloud.githubusercontent.com/assets/9950837/10907982/1145d056-8250-11e5-992c-30ef931d4cac.png)

**Comment by olarosling** [comment]
So, please CSS style the font size, to be smaller in this situation

**Comment by angieskazka** [comment]
@olarosling it's sligtly more tricky
this happens because of incorrect fix #777 for the issue #755 (spacing was set to 0.7 of label box height)

fixed now
