### ISSUE TITLE
Tools_v0.8.5 _29: Pause icon is not center aligned

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#856]
**SEVERITY:** Minor

**MODULE:** Tools page 

**Platform:** Windows 7 / Chrome 48.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://dev-tools.gapminderdev.org:3001/tools/
2)	Tools page is loaded.
3)	Click the “Options” button, a small pop up screen will be displayed
4)	Check the checkbox under buttons/presentations
5)	Click play icon
6)	Note that pause icon is not center aligned

**ACTUAL RESULTS:**
Pause icon is not center aligned when we check the checkbox under buttons/presentations

**EXPECTED RESULTS:** 
Pause icon should be center aligned

**SCREENSHOT:**

![tools_v0 8 5 _29](https://cloud.githubusercontent.com/assets/9950837/10935248/a9ca1f92-8306-11e5-9059-a543fda8ad2e.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/896

**Comment by arthurcamara1** [comment]
Safest solution: Replace whole icon with SVG icon rather than div + icon

**Comment by arthurcamara1** [comment]
Fixed by @sergey-filipenko 's https://github.com/Gapminder/vizabi/pull/905
