### ISSUE TITLE
Tools_v0.8.5 _30: Axes descriptions are not aligned with question mark ‘?’ 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#857]
**SEVERITY:** Minor

**MODULE:** Tools page 

**Platform:** Windows 7 / Chrome 48.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://dev-tools.gapminderdev.org:3001/tools/
2)	Tools page is loaded.
3)	Click the “Options” button, a small pop up screen will be displayed
4)	Note that axes descriptions are not aligned with question mark ‘?’

**ACTUAL RESULTS:**
After checking the check box under buttons/presentations axes description are not aligned with question mark ‘?’  

**EXPECTED RESULTS:** 
Axes description should be aligned with question mark ‘?’

**SCREENSHOT:**

![tools_v0 8 5 _30](https://cloud.githubusercontent.com/assets/9950837/10935271/d0434f90-8306-11e5-916a-14545c47b34b.png)

**Comment by jheeffer** [comment]
Look at alignment across different platforms

**Comment by angieskazka** [comment]
yes, the key point here is different browsers and platforms. also both preview page and tools page are to be tested because they use different font-family

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/935

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/935

**Comment by angieskazka** [comment]
i checked on all my platforms and it finally looks nice

win7/chrome46
win7/firefox
osx/chrome46
osx/firefox
osx/safari
nexus5/android6/chrome46

**Comment by k6Labz** [comment]
@angieskazka 
This issue is reproducing again on v0.9.1

**SEVERITY:** Minor

**MODULE:** Bubble Map Chart

**Platform:** MAC / Safari 9.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.9.1/preview/barchart.html
2)	 Bubble Map chart is loaded.
3)	Note that Y-axis description is not aligned with question mark ‘?’

**Comment by angieskazka** [comment]
there is a special issue #1093 for "?" on bubble map. i reopened that instead
