### ISSUE TITLE
Tools_v0.8.5 _31: Play icon is not working after selecting a bubble 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#858]
**SUMMARY:** 
**1)** Play icon is not working after selecting a bubble 
**2)** Trails and Lock buttons are not working after selecting a bubble
**3)** Tooltip for country is missing after selecting a bubble
**4)** Bubbles place of selected bubble is disturbed when we select a bubble and expand the screen
**5)** Disturbed trails are shown when we select a bubble and change the size of bubbles

**SEVERITY:** Critical

**MODULE:** Tools page 

**Platform:** Windows 7 / Chrome 48.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://dev-tools.gapminderdev.org:3001/tools/ 
2)	Tools page is loaded.
3)	Select a country. For example China.
4)	**Note that tooltip for country is missing**
5)	Then click play icon
6)	**Note that play icon is not working**
7)	Click Lock or Trails button
8)	**Note that Trails and Lock buttons are not working**
9)	Click “Expand”
10)	**Note that Bubbles place of selected bubble is disturbed**

11)	To reproduce next bug , repeat first 3 steps
12)	Click play icon
13)	Increase the size of minimum size of bubble through size scale which is given on the right panel
14)	**Note that disturbed trails are shown**

**ACTUAL RESULTS:**
After selecting a bubble no tooltip is there, play icon is not working, disturbed trails are there, bubbles placed is disturbed and trails and lock buttons are not working

**EXPECTED RESULTS:** 
After selecting a bubble nothing wrong should be happened. Play icon should work in any condition. All buttons should be functional. Bubbles place should be correct according to the axes description and year. Tooltip should be there after selecting a country

**SCREENSHOT:**

![tools_v0 8 5 _31 1](https://cloud.githubusercontent.com/assets/9950837/10935348/7400c18a-8307-11e5-9639-7ca67841a009.png)

![tools_v0 8 5 _31 2](https://cloud.githubusercontent.com/assets/9950837/10935347/73fe6cb4-8307-11e5-8572-6efbcca655fa.png)

![tools_v0 8 5 _31 3](https://cloud.githubusercontent.com/assets/9950837/10935349/7429f3c0-8307-11e5-959c-59e7ce625f6c.png)

**Comment by angieskazka** [comment]
this one is important. i fixed it but want to be sure i did.
please retest on develop, v0.8.6 and http://dev-tools.gapminderdev.org:3001/tools/

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Testing Environment:** 
**1)** http://dev-tools.gapminderdev.org:3001/tools/
**2)** http://static.gapminderdev.org/vizabi/release/v0.8.6/preview/bubblechart.html 
**3)** http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html
