### ISSUE TITLE
I don't see charts on safari

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#86]
Safari doesn't show me any chart on example page

**Comment by ambodi** [comment]
@olarosling I can add Vizabi example pages in the sauce lab and get screenshot to get a better sense in different platforms and browsers. You prioritise though, this is to say it is doable in a short time.

**Comment by angieskazka** [comment]
i guess it was the issue some time ago but now i tested and all works
@olarosling  @ambodi please reopen if you or your freelancers can reproduce it
