### ISSUE TITLE
Bug in event propagation when there's model mapping of names

### ISSUE THREAD

**Issue by arthurcamara1** [Gapminder/vizabi#863]
**Not-so-brief explanation about how events propagate**

Events in Vizabi work in a theoretically simple way. Each object under `options` becomes a model and the objects inside them are submodels. Models trigger events when their properties are changed and propagate those events up the model tree.

So, let's imagine we have an options object like this:

```javascript
{
  state: {
    marker: {
      color: {
        which: "pop"
      }
    }
  }
}
```

[Tool](https://github.com/Gapminder/vizabi/blob/develop/src/base/tool.js#L46) will receive that configuration and instantiate a [ToolModel](https://github.com/Gapminder/vizabi/blob/develop/src/base/tool.js#L18), which [will initiate submodels](https://github.com/Gapminder/vizabi/blob/develop/src/base/model.js#L131)  and create the following model structure:

```
model (model)
   |---state (model)
          |---marker (model)
                 |---color (model)
                        |---which (property, string)
```

Whenever there's a change in the **property** of a model, the model [schedules a change event](https://github.com/Gapminder/vizabi/blob/develop/src/base/model.js#L126) and [triggers it](https://github.com/Gapminder/vizabi/blob/develop/src/base/model.js#L151). Therefore, a change in the `which` property of the model `color`, would trigger `change:which` and `change`.

If we are listening _directly_ to the `color` model changes, we could do something like:

```javascript
color.on("change:which", function() { alert("color.which changed!"); }); 
// or any change
color.on("change", function(evt) { alert("something changed in model color: "+evt); }); 
```

However, events are also **propagated to the parent models**. Whenever there's a change event in any model, the [parent models also trigger those events](https://github.com/Gapminder/vizabi/blob/develop/src/base/model.js#L1313).

So, instead of listening directly to `color`, one could listen to `state` instead:

```javascript
state.on("change:color:which", function() { alert("color.which changed!"); }); 
// or any change
state.on("change:color", function(evt) { alert("something changed in model color: "+evt); }); 

// the above produces the same result as:
state.color.on("change:which", function() { alert("color.which changed!"); }); 
// and
state.color.on("change", function(evt) { alert("something changed in model color: "+evt); }); 

```

**In summary, events are propagated as follows:**

![event propagation](https://cloud.githubusercontent.com/assets/3584238/10940553/4c576fe4-8307-11e5-92ab-26931a874421.png)

**It gets a bit more complex**.

Components receive models in order to render their UI correctly. We also create the listeners of models in components, usually.

[A component states that it "expects" certain models and model types](https://github.com/Gapminder/vizabi/blob/develop/src/components/timeslider/timeslider.js#L89), and is free to give it any name. In [this example, timeslider expects a model of type time](https://github.com/Gapminder/vizabi/blob/develop/src/components/timeslider/timeslider.js#L89), and calls it "time" internally. The fact that it's called "time" is a coincidence here. The name could be "t", or any string. Let's imagine a color picker component that expects a color model, but calls it "col". The `model_expects` in the `init` would look like this:

```javascript
//define expected models/hooks for this component
this.model_expects = [{
  name: "col",
  type: "color"
}];
```

Now, if another component uses this color picker component, it will have to pass a model color to it:

```javascript
this.components = [{
  component: colorPickerComponent, 
  placeholder: '.vzb-div-placeholder', 
  model: ["state.marker.color"] 
}]
```

What Vizabi will do in this case is to create a "local model" for colorPickerComponent, containing the desired model under the property `col`. [It basically maps the references to the original](https://github.com/Gapminder/vizabi/blob/develop/src/base/component.js#L372). The actual object `state.market.color` in the outside component is the SAME object as `this.model.col` inside the colorPickerComponent. It basically contains a reference.

This picture illustrates the process:

![virtual model](https://cloud.githubusercontent.com/assets/3584238/10940875/0c02aba0-8309-11e5-9b0d-78f81e5e9bbc.png)

If we want to listen to changes inside `colorPickerComponent`, we should be able to:

```javascript
this.model.on("change:col:which", function() { alert("color.which changed!"); }); 
//or
this.model.col.on("change:which", function() { alert("color.which changed!"); }); 
```

It basically follows the same logic with the new name under that "virtual" branch of the model tree:

![virtual model propagation](https://cloud.githubusercontent.com/assets/3584238/10940937/6b20205e-8309-11e5-80b1-1e02a95c8bfb.png)

And outside, the model propagation should face no difference:

```javascript
this.model.on("change:state:marker:color:which", function() { alert("color.which changed!"); }); 
```

Here, the event needs to come with the name "color", **NOT** "col".

**BUG**

The problem is, if we open the color dialog:

![image](https://cloud.githubusercontent.com/assets/3584238/10940989/b4d43ffa-8309-11e5-9bb0-ae8ad237a2f7.png)

Start to record the events in Timeline:

<img width="689" alt="screen shot 2015-11-04 at 3 36 05 pm" src="https://cloud.githubusercontent.com/assets/3584238/10941033/e549b5f2-8309-11e5-892d-91f7f1908325.png">

And change the color which using the dropdown, we'll get this:

![image](https://cloud.githubusercontent.com/assets/3584238/10941117/3d35b5a4-830a-11e5-9c16-dc2ea886132a.png)

The event renaming map is working fine (axis was a local name, color is the original name), but we are not propagating the events further up the tree when such mapping happens. We should see also `change:marker:color`

**Multiple references**
Multiple models are created with references to the same original model. The following situation happens often:

![virtual model 2](https://cloud.githubusercontent.com/assets/3584238/10941571/5b43eb18-830c-11e5-8a28-96f98028ecfc.png)

One component is using `color` under `this.model.col`, the other under `this.model.c` and the original is called `color`.

If you change the model color using **any of the paths leading to the object**, all these events should be triggered:

```js
//at tool level
change:state:marker:color:which, change:state:marker:color, change:state:marker, change:state, change
//at "Another component" level
change:col:which, change:col, change
//at "Yet another component" level
change:c:which, change:c, change
```

But what's happening now is that not all of those events are being triggered. Most likely only the path from which the change originated and the original one (we have to check).

One way to make sure they are all triggered might be using the references to the parents. We have [a back reference of all parents of a model](https://github.com/Gapminder/vizabi/blob/develop/src/base/model.js#L45). Or making sure the "virtual model" parent is listening to each submodel correctly [when mapping is done](https://github.com/Gapminder/vizabi/blob/develop/src/base/component.js#L289)

**Comment by jheeffer** [comment]
closed in 94c16b045f08b3c954a35754a9a7f43bb084d93b
