### ISSUE TITLE
v0.8.6 _01: Text is overlapping by reducing screen size

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#865]
**SEVERITY:** Minor

**MODULE:** Stage 

**Platform:** Windows 7 / Chrome 48.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: https://stage-tools.gapminderdev.org/tools/ 
2)	Tools page is loaded.
3)	Reduce the screen size
4)	Note that text is overlapping

**ACTUAL RESULTS:**
Text is overlapping in the header by reducing screen size

**EXPECTED RESULTS:** 
Text should not overlap by reducing screen size

**SCREENSHOT:**

![v0 8 6 _01](https://cloud.githubusercontent.com/assets/9950837/10962303/0615aa34-83b9-11e5-8a2c-83c60dbbae0f.png)

**Comment by jheeffer** [comment]
Please repost this issue at https://github.com/Gapminder/gapminder-tools-vizabi

**Comment by angieskazka** [comment]
works fine until width = 320, which is equal to iPhone 3G we ain't willing to support smaller screens

![image](https://cloud.githubusercontent.com/assets/3648190/11128802/61645c3c-897c-11e5-96fe-2f1e701efa88.png)
