### ISSUE TITLE
v0.8.6 _02: Size scale bar is missing

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#866]
**SUMMARY:** 
**1)** Size scale bar is missing
**2)** OK button is not functional 

**SEVERITY:** Major

**MODULE:** Stage 

**Platform:** Windows 7 / Chrome 48.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: https://stage-tools.gapminderdev.org/tools/ 
2)	Tools page is loaded.
3)	Note that on the right panel size scale bar is missing
4)	Click “Options”
5)	Note that size scale bar is missing here also 
6)	Click OK to close pop up screen of “Options”
7)	Note that OK button is not functional

**ACTUAL RESULTS:**
Size scale bar is missing on the right panel and in the options and OK button is not functional

**EXPECTED RESULTS:** 
Size scale bar should be available and OK button should be functional

**SCREENSHOT:**

![v0 8 6 _02](https://cloud.githubusercontent.com/assets/9950837/10962326/232b18ac-83b9-11e5-8ed0-dd6a95c261bc.png)

**Comment by jheeffer** [comment]
Ok button is fixed on dev.
Cannot reproduce missing size scale bar

**Comment by k6Labz** [comment]
**Retest Result:** Fail

**Platform:** Windows 7 / Chrome 48.0

**Testing Environment:** https://stage-tools.gapminderdev.org/tools/  

**Screenshot:** 

![2](https://cloud.githubusercontent.com/assets/9950837/11055353/5ece666a-8798-11e5-9e93-d3159967a8d1.png)

**Comment by angieskazka** [comment]
Same as #826. pannels need reconsideration

**Comment by jheeffer** [comment]
@k6Labz Cannot reproduce the missing scale bar on first load. Can you give a more specific reproduction scenario? Is it missing with every possible window size?

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Platform:** Windows 7 / Chrome 48.0

**Testing Environment:** 
**1)** https://stage-tools.gapminderdev.org/tools/ 
**2)** http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Platform:** Windows 7 / Chrome 48.0

**Testing Environment:** 
**1)** https://stage-tools.gapminderdev.org/tools/ 
**2)** http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html
