### ISSUE TITLE
v0.8.6 _03: Mountain chart is not loading on Firefox

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#867]
**SEVERITY:** Critical

**MODULE:** Stage 

**Platform:** Windows 7 / Firefox 42.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: https://stage-tools.gapminderdev.org/tools/ 
2)	Tools page is loaded.
3)	Bubble chart is available
4)	Scroll down and click mountain chart to display it
5)	Note that mountain chart is not displayed

**ACTUAL RESULTS:**
Mountain chart is not displayed by selecting this

**EXPECTED RESULTS:** 
Mountain chart should be displayed by selecting it

**SCREENSHOT:**

![v0 8 6 _03](https://cloud.githubusercontent.com/assets/9950837/10962351/46abde88-83b9-11e5-9253-638087cabbe1.png)

**Comment by angieskazka** [comment]
thanks @natali-abyss
