### ISSUE TITLE
v0.8.6_04 : Mountain Chart is not loading

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#868]
**SEVERITY:** Critical

**MODULE:**  Mountain Chart

**Platform:** iPhone-4 (iOS 7.1) / Chrome

**RELEASE:** v0.8.6

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.6/preview/mountainchart.html 
2)	Mountain chart page will not be loaded

**ACTUAL RESULTS:**
Mountain Chart is not loading 

**EXPECTED RESULTS:** 
Mountain Chart should be loaded

**SCREENSHOT:**

![v0 8 6_04](https://cloud.githubusercontent.com/assets/9950837/10966786/c48330ea-83d7-11e5-9864-fcd0556babca.jpg)

**Comment by jheeffer** [comment]
#869
