### ISSUE TITLE
v0.8.6_05: Bubbles are not visible after loading bubble chart 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#869]
**SEVERITY:** Critical

**MODULE:**  Bubble Chart

**Platform:** iPhone-4 (iOS 7.1) / Chrome

**RELEASE:** v0.8.6

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.6/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Note that bubbles are not visible

**ACTUAL RESULTS:**
Bubbles are not visible after loading bubble chart. If we click play after loading the chart, extremely small size bubbles are displayed but they cannot seen easily

**EXPECTED RESULTS:** 
After loading the bubble chart, the bubbles should be visible properly

**SCREENSHOT:**

![v0 8 6_05](https://cloud.githubusercontent.com/assets/9950837/10966820/fcc7bf02-83d7-11e5-81da-64c15f1ce3d9.jpg)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/913

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Platform:** 
* iPhone-4 (iOS 7.1) / Chrome
* iPhone-4 (iOS 7.1) / Safari 

**Testing Environment:** http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html
