### ISSUE TITLE
Bubble should hide, if missing data

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#87]
A bubble with missing data for X, or Y or Size, can not show.  and should not be on the axis, as it does now See small bubbles on Y-axis
![image](https://cloud.githubusercontent.com/assets/496398/6677420/1a55f8be-cc30-11e4-8e7a-2ee541988cc8.png)
When playing over time the availability of data changes, those appearing should fade in, and does disappearing should fade out from and to the invisible status.

**Comment by angieskazka** [comment]
done
