### ISSUE TITLE
v0.8.6_06: Color scale is not appearing according to the option.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#870]
**SEVERITY:** Major

**MODULE:**  Pop by Age Chart

**Platform:** Nexus 5(6.0) / Chrome

**RELEASE:** v0.8.6

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL: http://static.gapminderdev.org/vizabi/release/v0.8.6/preview/popbyage.html
2)	“Pop-by-Age Chart” page will be loaded.
3)	Tap on “Color” icon and pop-up will appear.
4)	Select “Geo name” or “Region” from dropdown.
5)	Note that respective color scale is not appeared.

**ACTUAL RESULTS:**
Color scale is not appearing according to the option.

**EXPECTED RESULTS:**
Color scale should be appearing according to the option.

**SCREENSHOT:**

![v0 8 6_06](https://cloud.githubusercontent.com/assets/9950837/10968354/691b1352-83e2-11e5-8f3d-ae61b070cf10.png)

**Comment by jheeffer** [comment]
Related to #884

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/904

**Comment by jheeffer** [comment]
closed by https://github.com/Gapminder/vizabi/commit/aed7c868f5c4d9f0287a1b9fa3fc570597662dea
