### ISSUE TITLE
v0.8.6_07: Axis lines are disturbed on changing the orientation.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#871]
**SUMMARY:** 
**1)** Axis lines are disturbed on changing the orientation.
**2)** Axis values are overlapped.

**SEVERITY:** Major

**MODULE:** Line Chart.

**Platform:** Nexus 5(6.0) / Chrome

**RELEASE:** v0.8.6

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL: http://static.gapminderdev.org/vizabi/release/v0.8.6/preview/linechart.html 
2)	“Line Chart” page will be loaded.
3)	Hold the device in portrait orientation.
4)	Make sure slider ball is at the end of slide bar
5)	Tap on United States line from the extreme right.
6)	A square of dotted lines will appear on the chart.
7)	Hold the device in landscape view now.
8)	Note that axis lines are unaligned and values are overlapped.

**ACTUAL RESULTS:**
Axis lines are disturbed and values overlapped on changing the orientation.

**EXPECTED RESULTS:**
Axis lines and values should not be disturbed on changing the orientation.

**SCREENSHOT:**

![v0 8 6_07](https://cloud.githubusercontent.com/assets/9950837/10968485/4cc12d6c-83e3-11e5-87c6-dc4e09bb7930.png)

**Comment by angieskazka** [comment]
still buggy on the actual device Nexus 5(6.0) / Chrome
