### ISSUE TITLE
set a bit darker and thicker trail stroke width

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#875]
The darker color should use the shade verison of the colors, as defined here
![image](https://cloud.githubusercontent.com/assets/496398/10982448/8674b1da-840d-11e5-878e-f375219247b7.png)

The trails lines are too thin, they almost dissapear. 
Use two pixel width, 
Make it easy to set in state (as a hoookable) so the default is actually the default Uni-stroke-width
Later we start enable strokewidth by indicator, not now.

**Comment by angieskazka** [comment]
done setting a thicker stroke, setting it darker would require rethinking of color palletes. now we have one color that a palette can return, not an array of colors
