### ISSUE TITLE
v0.8.6_08: Text cursor is unaligned on Search bar.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#876]
**SEVERITY:** Major

**MODULE:** Bubble Chart

**Platform:** iPad Air-2(9.1) / Safari

**RELEASE:** v0.8.6

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL: http://static.gapminderdev.org/vizabi/release/v0.8.6/preview/bubblechart.html
2)	“Bubble Chart” page will be loaded.
3)	Tap on “Find” icon and pop-up will appear.
4)	Write “China” on search bar field and “China” will appear.
5)	Mark check on “China” and tap ok.
6)	Repeat step 3 and 4 again.
7)	Remove “China” by taping backspace on search bar.
8)	Note that text cursor is not aligned on search bar.

**ACTUAL RESULTS:**
Text cursor is unaligned on Search bar.

**EXPECTED RESULTS:**
Text cursor should be aligned on Search bar.

**SCREENSHOT:**

![v0 8 6_08](https://cloud.githubusercontent.com/assets/9950837/10996855/5d549f5c-84aa-11e5-914a-2b53e8572c9f.PNG)

**Comment by jheeffer** [comment]
Cannot recreate on desktop: check on ipad or maybe other mobile device

**Comment by arthurcamara1** [comment]
One solution: remove placeholder when input is focused, restore it on blur. Example here: http://codepen.io/arthurcamara1/pen/EVRYqp
