### ISSUE TITLE
v0.8.6_09: Axis values are not displayed on changing the orientation.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#877]
**SEVERITY:** Major

**MODULE:** Bubble Chart

**Platform:** iPad Air-2(9.1) / Safari

**RELEASE:** v0.8.6

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL: http://static.gapminderdev.org/vizabi/release/v0.8.6/preview/bubblechart.html
2)	“Bubble Chart” page will be loaded.
3)	Tap on “Expand” icon.
4)	Hold the device in portrait orientation.
5)	Now tap on “United States” green bubble and a tooltip will appear.
6)	Tap on the tooltip and a dotted chart values will appear.
7)	Hold the device in landscape orientation.
8)	Note that dotted chart values are not displayed.

**ACTUAL RESULTS:**
Axis statistics are not displayed on changing the orientation.

**EXPECTED RESULTS:**
Axis statistics should be displayed in any view and orientation.

**SCREENSHOT:**
![v0 8 6_09](https://cloud.githubusercontent.com/assets/9950837/10996890/90f73b9e-84aa-11e5-80ab-4792cb3e65ec.png)

**Comment by jheeffer** [comment]
Before doing this we have to define the mobile interactions

**Comment by angieskazka** [comment]
@jheeffer  we defined mobile interactions a while ago: no hovering functionality, just click
with all it implies: no projection lines, only select

**Comment by angieskazka** [comment]
we will redefine the mobile interactions later in a more powerful way
