### ISSUE TITLE
v0.8.6_10: Axis lines are still there by un selecting the bubble.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#878]
**SEVERITY:** Major

**MODULE:** Bubble Chart

**Platform:** iPad Air-2(9.1) / Safari

**RELEASE:** v0.8.6

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL: http://static.gapminderdev.org/vizabi/release/v0.8.6/preview/bubblechart.html
2)	“Bubble Chart” page will be loaded.
3)	Tap on “China” bubble after then tap “Lock” icon and finally tap “Play” icon.
4)	Let the slider ball reach the end
5)	Now tap on any “China” trail.
6)	Dotted Chart values with year are shown on the screen.
7)	Tap on Last bubble of China Trail i.e 2015.
8)	Note that all trails will disappear but dotted chart lines will still appear.

**ACTUAL RESULTS:**
Axis lines are still displayed by un selecting the bubble.

**EXPECTED RESULTS:**
Axis lines should be displayed by un selecting the bubble.

**SCREENSHOT:**

![v0 8 6_10](https://cloud.githubusercontent.com/assets/9950837/10996923/ba60637a-84aa-11e5-8fd8-89e510e542b5.jpg)

**Comment by jheeffer** [comment]
Check on mobile version as it pertains to hover-behaviour on tap

**Comment by angieskazka** [comment]
we defined mobile interactions a while ago: no hovering functionality, just click
with all it implies: no projection lines, only select

**Comment by angieskazka** [comment]
we will redefine the mobile interactions later in a more powerful way
