### ISSUE TITLE
v0.8.6_11: Poverty Line disappears on entering alphabets in “Probeline” field.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#879]
**SEVERITY:** Major

**MODULE:** Mountain Chart

**Platform:** 
* Windows 7 / Chrome 48.0
* Windows 7 / Firefox 42.0
* iPad Air 2 iOS(9.1) / Safari 
* MAC / Safari 9.0
* Nexus-5 (6.0) / Chrome 
* Nexus 9 (5.0.2) / Chrome 

**RELEASE:** v0.8.6

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL: http://static.gapminderdev.org/vizabi/release/v0.8.6/preview/mountainchart. html
2)	“Mountain Chart” page will be loaded.
3)	Tap on “X AND Y” icon and pop up will appear.
4)	Enter “abcd” on Probeline field.
5)	Tap Ok.
6)	Note that “Extreme Poverty” line disappears on the chart.

**ACTUAL RESULTS:**
Poverty Line disappears on entering alphabets in “Probeline” field.

**EXPECTED RESULTS:**
Alphabets should also override with the original value 1.85 like negative values and “Extreme Poverty” line should not disappear in any case.

**SCREENSHOT:**
![v0 8 6_11](https://cloud.githubusercontent.com/assets/9950837/10996955/ff72d6a0-84aa-11e5-97c9-ecac5032cfd9.PNG)

**Comment by jheeffer** [comment]
Improve validation of time.probex.
Maybe find better position in state than in time.

**Comment by angieskazka** [comment]
the above fixed =)
