### ISSUE TITLE
v0.8.6_12: Tooltip of country is truncated on hovering effect

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#880]
**SEVERITY:**  Minor

**MODULE:**  Mountain Chart.

**Platform:**
* Windows 7 / Chrome 48.0
* Windows 7 / Firefox  42.0
* MAC / Safari 9.0

**RELEASE:** v0.8.6

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.8.6/preview/mountainchart.html
2)	Mountain Chart will be loaded.
3)	Take mouse to the top of the mountain chart
4)	Note that tooltip of country is truncated on hovering effect  

**ACTUAL RESULTS:**
Tooltip of country is truncated on hovering effect 

**EXPECTED RESULTS:**
Tooltip should not be truncated

**SCREENSHOT:**

![v0 8 6_12](https://cloud.githubusercontent.com/assets/9950837/10997036/9aba1736-84ab-11e5-87a9-44460ae7b48b.png)

**Comment by jheeffer** [comment]
Limit tooltip y-position by 0

**Comment by angieskazka** [comment]
looks like done
