### ISSUE TITLE
v0.8.6_14: Large extra space is there on right panel on expanded screen

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#882]
**SEVERITY:**  Minor

**MODULE:**  Line Chart

**Platform:**
* Windows 7 / Chrome 48.0
* Windows 7 / Firefox  42.0

**RELEASE:** v0.8.6

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.8.6/preview/linechart.html
2)	Line Chart will be loaded.
3)	Click “Expand”
4)	Note that there is large space on the right panel

**ACTUAL RESULTS:**
Large extra space is there on right panel on expanded screen 

**EXPECTED RESULTS:**
No extra space should be there. Two available options on the expanded screen should be aligned vertically, not horizontally
 
**SCREENSHOT:**

![v0 8 6_14](https://cloud.githubusercontent.com/assets/9950837/10997101/187d7d98-84ac-11e5-8d0e-39784cfd81ca.png)

**Comment by jheeffer** [comment]
1) Enter sidebar in default options
2) If no sidebar items in options: don't show wide sidebar but just buttonlist

**Comment by angieskazka** [comment]
i just tested and found that it's fixed already. thanks
