### ISSUE TITLE
v0.8.6_15: Value for year 100 is missing in pop by age chart

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#883]
**SEVERITY:**  Major

**MODULE:**  Pop by age Chart

**Platform:**
* Windows 7 / Chrome 48.0
* Windows 7 / Firefox  42.0
* MAC / Safari 9.0

**RELEASE:** v0.8.6

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.8.6/preview/popbyage.html
2)	Pop by age Chart will be loaded.
3)	Note that value for year 100 is missing

**ACTUAL RESULTS:**
Value for year 100 is missing in pop by age chart

**EXPECTED RESULTS:**
Value for year 100 should be available on the chart like it is available in v0.7.0

**SCREENSHOT:**

![v0 8 6_15 1](https://cloud.githubusercontent.com/assets/9950837/10997119/482e2254-84ac-11e5-95b9-4ddb6d10d535.png)

![v0 8 6_15 2](https://cloud.githubusercontent.com/assets/9950837/10997120/4834fb7e-84ac-11e5-8797-e07d5b1945f5.png)

**Comment by jheeffer** [comment]
This is not a bug: 0-99 contains 100 age-groups, i.e. it goes up to 100 but does not include it.
