### ISSUE TITLE
v0.8.6_17: Bars of bar chart are changed on same description

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#885]
**SEVERITY:**  Major

**MODULE:**  Bar Chart

**Platform:**
* Windows 7 / Chrome 48.0
* Windows 7 / Firefox  42.0
* MAC / Safari 9.0

**RELEASE:** v0.8.6

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.8.6/preview/barchart.html
2)	Bar Chart will be loaded.
3)	“Population” is on the Y axis
4)	Click Y axis description and select “GDP per capita”
5)	Bars are changed according to “GDP per capita”
6)	Again click Y axis description and select “Population”
7)	Note that bars of bar chart are changed on same description

**ACTUAL RESULTS:**
Bars of bar chart are changed on same description due to change of axis scale value.

**EXPECTED RESULTS:**
Scale values should remain same for any description

**SCREENSHOT:**

![v0 8 6_17 1](https://cloud.githubusercontent.com/assets/9950837/10997182/cd38807a-84ac-11e5-9a1f-8657453a8cee.png)

![v0 8 6_17 2](https://cloud.githubusercontent.com/assets/9950837/10997183/cd38f10e-84ac-11e5-8582-97558e12d6a0.png)

**Comment by k6Labz** [comment]
@angieskazka 
This issue is reproducing again 

**Platform:**
* Windows 7 / Chrome 46.0
* MAC / Safari 9.0

**Release:** v0.9.1

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.9.1/preview/barchart.html
2)	Bar Chart will be loaded.
3)	“Population” is on the Y axis
4)	Click Y axis description and select “Life Expectancy”
5)	Again click Y axis description and select “Population”
6)	Note that bars of bar chart are changed on same description

**Comment by angieskazka** [comment]
the problem is that the axis switches to linear when chosing lex and then it shows pop on linear scale when is switched back
i’m not sure if that’s even a problem

but having the min-max domain that it selects automatically is very wrong of course
it adjusts max for china, but china is not among entities =/
limit.max and limit.min are not considering that, they are calculating limits on the entire dataset
