### ISSUE TITLE
icons disappeared from top bar

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#89]
see, @arthurcamara1, some icons are missing
maybe because we did't include them when removing font awesome as a font. how do i add them back?

![image](https://cloud.githubusercontent.com/assets/3648190/6766139/8693b99e-cffa-11e4-804d-c5bf83a2d22c.png)

**Comment by arthurcamara1** [comment]
Funny, i thought i had fixed that. I'll check it out.

On Saturday, March 21, 2015, Angie the Fairytale <notifications@github.com>
wrote:

> see, @arthurcamara1 <https://github.com/arthurcamara1>, some icons are
> missing
> maybe because we did't include them when removing font awesome as a font.
> how do i add them back?
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/3648190/6766139/8693b99e-cffa-11e4-804d-c5bf83a2d22c.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Gapminder/vizabi/issues/89>.
>


-- 

*Arthur Camara*
*Software Engineer*
Gapminder Foundation
www.gapminder.org
