### ISSUE TITLE
Tools_v0.8.6 _18: Right panel is disappeared by clicking twice “Find” and “Color” options

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#899]
**SEVERITY:** Minor

**MODULE:** Tools page 

**Platform:** Windows 7 / Chrome 48.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://dev-tools.gapminderdev.org:3001/tools 
2)	Tools page is loaded.
3)	Click twice the “Color” icon in options
4)	Click twice the “Find” icon in options
5)	Note that right panel is disappeared

**ACTUAL RESULTS:**
Right panel is disappeared by clicking twice “Find” and “Color” options 

**EXPECTED RESULTS:** 
Right panel should not disappeared by clicking twice “Find” and “Color” options or the icons should not be available

**SCREENSHOT:**

![tools_v0 8 6 _18](https://cloud.githubusercontent.com/assets/9950837/11061713/c362a302-87ca-11e5-8fb0-586bc32c46f1.png)

**Comment by arthurcamara1** [comment]
If Find is **visble on the sidebar**, there shouldn't be a button for the same panel. The only visible buttons are those for which there are no sidebars

**Comment by angieskazka** [comment]
this is related to the latest changes in showing and hiding buttons...
