### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by amytych** [Gapminder/vizabi#9]
I see that Vizabi requires jQuery and d3 to work. And they are included in the built version of `visabi.js` But it is not mentioned anywhere in the docs. What if someone already has them on a page? It is definitely possible scenario with jQuery. Aside from possible version conflicts, there is no need for it to be loaded twice, I guess? Shouldn't that be clearly stated in the docs? And shouldn't there be a standalone version of `vizabi.js` if someone already has the dependencies on the page?

**Comment by angieskazka** [comment]
@arthurcamara1 made zero-dependency Vizabi recently, that can work using D3 included separately on the page. we will soon merge it into develop branch

and jquery we don't have for some time now
