### ISSUE TITLE
Tools_v0.8.6 _19: Expand icon label is not changed to “Restore” on expanded screen

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#900]
**SEVERITY:** Major

**MODULE:** Tools page 

**Platform:** Windows 7 / Chrome 48.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://dev-tools.gapminderdev.org:3001/tools 
2)	Tools page is loaded.
3)	Click “Expand”
4)	Note that expand icon label is not changed to “Restore” on expanded screen
5)	Also note that the icon is not clickable, we have to press “Esc” button to restore

**ACTUAL RESULTS:**
Expand icon label is not changed to “Restore” on expanded screen
 
**EXPECTED RESULTS:** 
Expand icon label should be changed to “Restore” on expanded screen 

**SCREENSHOT:**

![tools_v0 8 6 _19](https://cloud.githubusercontent.com/assets/9950837/11061735/eb7a8710-87ca-11e5-82d9-a5e28dced8a3.png)

**Comment by arthurcamara1** [comment]
Funny thing is, it seems to work fine on static.gapminderdev.org/vizabi/develop/preview and not on http://dev-tools.gapminderdev.org:3001/ :open_mouth:

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/919

**Comment by angieskazka** [comment]
still reproduced on http://dev-tools.gapminderdev.org:3001/

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Platform:** Windows 7 / Chrome 48.0

**Testing Environment - DEVELOP:** http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html

**But it is still reproducing on http://dev-tools.gapminderdev.org:3001/**

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/923

**Comment by angieskazka** [comment]
Fixed now, but produced another problem 

on preview page: go fullscreen then restore. container size is wrong (hidden under right pannel)

![image](https://cloud.githubusercontent.com/assets/3648190/11116809/3b102d3c-8935-11e5-942a-ea48811f5791.png)

reproduced on: 
OS X /Chrome 46
OS X / Safari 
OS X / Firefox
Win 7 / Firefox

but works fine on Win 7 / Chrome 46

**Comment by angieskazka** [comment]
and that fixed too
