### ISSUE TITLE
Tools_v0.8.6 _21: Scroll bar is missing

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#901]
**SEVERITY:** Minor

**MODULE:** Tools page 

**Platform:** Windows 7 / Chrome 48.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://dev-tools.gapminderdev.org:3001/tools 
2)	Tools page is loaded.
3)	Click dropdown available on right top
4)	Select “Geo name” or “Geo code”
5)	Note that there is no scroll bar to scroll down the color/x options

**ACTUAL RESULTS:**
Scroll bar is missing to scroll down the color/x options

**EXPECTED RESULTS:** 
Scroll bar should not missing to scroll down the color/x options in color options

**SCREENSHOT:**

![tools_v0 8 6 _21](https://cloud.githubusercontent.com/assets/9950837/11061788/464ddd40-87cb-11e5-8a66-670b3cd0427f.png)

**Comment by arthurcamara1** [comment]
I coudn't reproduce either. :open_mouth:  The color box grows here

**Comment by arthurcamara1** [comment]
By the way, you're testing on Chrome 48. Is that Canary? Mine is still 46, latest version

**Comment by k6Labz** [comment]
We are testing on Chrome - Version 48.0.2552.0 dev-m (64-bit).
It's not Canary as I think it specially designed for developers.

**Comment by jheeffer** [comment]
https://www.chromium.org/getting-involved/dev-channel

It is a pre-beta build of the browser and could contain bugs. On the one hand, you can prepare for the future, on the other hand the future might not be what this channel shows. I think we'd rather have it tested on the stable channel. What do you think @arthurcamara1?

**Comment by jheeffer** [comment]
On the issue: I downloaded chrome dev-channel and couldn't reproduce either. Is the issue still there and if so do you have a more detailed reproduction scenario?

![image](https://cloud.githubusercontent.com/assets/1596071/11094490/587e7752-8890-11e5-8ab9-9b5d6d346bf7.png)

**Comment by k6Labz** [comment]
@jheeffer 
**Retest Result:** Passed
**Platform:** Windows 7 / Chrome 48.0 (dev-channel)

**Comment by angieskazka** [comment]
¯\_(ツ)_/¯

**Comment by k6Labz** [comment]
@angieskazka 

**Retest Result:** Fail

**Platform:**  iPad Air 2 iOS(9.1) / Safari 

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.8.8/preview/popbyage.html 
2)	Pop by age chart is loaded.
3)     Click "Expand".
4)     Click "Color". A small pop up screen is displayed.
5)	Click drop down.
6)	Select “Geo name”.
7)	Note that there is no scroll bar to scroll down the color/x options.

**SCREENSHOT:**

![comment](https://cloud.githubusercontent.com/assets/9950837/11208108/0ad5fd9a-8d3b-11e5-91c9-e6add648e839.PNG)

**Comment by angieskazka** [comment]
![image](https://cloud.githubusercontent.com/assets/3648190/11489370/058daa06-97cf-11e5-9127-2a7fcb544fcd.png)
