### ISSUE TITLE
Tools_v0.8.6 _23: Some options are missing like “X and Y” and “Show”

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#903]
**SEVERITY:** Major

**MODULE:** Tools page 

**Platform:** Windows 7 / Chrome 48.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://dev-tools.gapminderdev.org:3001/tools/mountain 
2)	Tools page is loaded.
3)	Note that some options are missing like “X and Y” and “Show”

**ACTUAL RESULTS:**
Some options are missing like “X and Y” and “Show”

**EXPECTED RESULTS:** 
“X and Y” and “Show” options should be available with other options

**SCREENSHOT:**

![tools_v0 8 6 _23](https://cloud.githubusercontent.com/assets/9950837/11061834/a2471990-87cb-11e5-98e8-f5217ffbc2f6.png)

**Comment by arthurcamara1** [comment]
That's intentional. #840
