### ISSUE TITLE
Changing size removes trails

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#91]
After selecting a country, and drawing a trail, I tried changing size, but then the chart goes back to no selected bubbles. Something wrong with the model and state, probably

**Comment by angieskazka** [comment]
Thanks, we saw it too. @arthurcamara1 did you do anything with it? If no I will start

**Comment by angieskazka** [comment]
ok, i give up. @arthurcamara1 can take it over

I created a watch expression `myVizabi._tool.components[0].model.entities.select` and tried to find out if it would change any time. I traced it step by step through the code after i change one of the hooks or shift the bubble size slider. But the program seems to endlessly circulate between q.js, lodash.js events.js and don't get anywhere. None of this code i met on the way was comprehensible to me.

Same result i got when i investigated call stack from the point `"change:entities:select":` and upwards.

One thing is clear. If i disable modifying `model.size.max` like this
```
        slideHandler: function () {
           // this.model.size.max = +d3.event.target.value;
        }
```
then `select` stays intact. This shows that the mystery must be with the action of modifying a field in the state. But the chain of events behind modifying a simple field is not debuggable.

***
*Maybe calling array "select" is a bad idea and they use "select" for something else?* 

***

Personally i don't like that we are using this programming pattern. If i say `this.model.someValue = 1` i expect that a simple property would be assigned a value of 1. But in our case a huge amount of unexpected crazy stuff happens which i have no idea of.
Instead i suggest using a pattern that is adopted in d3:
```
// getting the value. returns 1
this.model.someValue()

// setting the value. returns model
this.model.someValue(1)
```

**Comment by arthurcamara1** [comment]
Thanks for investigating Angie, I'll use what you found out and figure out
the issue :)

On Monday, April 13, 2015, Angie the Fairytale <notifications@github.com>
wrote:

> Assigned #91 <https://github.com/Gapminder/vizabi/issues/91> to
> @arthurcamara1 <https://github.com/arthurcamara1>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Gapminder/vizabi/issues/91#event-280013575>.
>


-- 

*Arthur Camara*
*Software Engineer*
Gapminder Foundation
www.gapminder.org

**Comment by arthurcamara1** [comment]
The problems are here:
https://github.com/Gapminder/vizabi/blob/aaeb28e2c09fa63e4fa49e3c8bf8a10bee54e5f8/src/components/_examples/bubble-chart/bubble-chart.js#L299

and here:
https://github.com/Gapminder/vizabi/blob/aaeb28e2c09fa63e4fa49e3c8bf8a10bee54e5f8/src/components/_examples/bubble-chart/bubble-chart.js#L258

About your comment about the pattern, I don't agree that assignments are not supposed to trigger events. I believe this can be expected from a framework that binds things to variables. Like I mentioned to you, AngularJS follows a similar pattern, and transforming everything into functions would not solve it and would break one of the most useful things in our pattern:

```javascript
this.marker.size = 2; // triggers change:marker:size , change:marker and change
this.marker = 4; //now triggers change:marker, and change
this.marker = { size: 2, color: "#ffffff" }; // now size is back to the game and also color!
```

Moreover, functions could make those dynamic creations collide with methods, reserved function names, and so on.

But I'll think of a middle solution there. I do get your point that there needs to exist some sort of clarity between what gets to trigger events and what doesn't. Thanks for your input :+1:

**Comment by angieskazka** [comment]
Great @arthurcamara1! 
i restructured the functions and events in a bubble chars, now the issue is solved
