### ISSUE TITLE
Vizabi should not trigger changeHistory event on first load

### ISSUE THREAD

**Issue by arthurcamara1** [Gapminder/vizabi#917]
Right now, when we load Vizabi, it already triggers a  `changeHistory` event, which is used by the external page to update the URL.

As far as I'm aware of, this happens because of splash screen.

Such event should only be triggered when there's an actual change after first load (apart from splash) and probably only *after* user interaction.

**Comment by arthurcamara1** [comment]
@jheeffer Maybe we can look into this together or you can try to find your way through

**Comment by angieskazka** [comment]
still an issue, as far as i can see

right after load there is one step back
![image](https://cloud.githubusercontent.com/assets/3648190/11983955/ee1886e8-a9b7-11e5-88b7-584541837882.png)

current URL: http://dev-tools.gapminderdev.org:3001/tools/bubbles#_

previous URL: http://dev-tools.gapminderdev.org:3001/tools/bubbles

**Comment by angieskazka** [comment]
but it's definitely not an urgent thing, it's an optimisation of a tools page, not even vizabi itself

**Comment by jheeffer** [comment]
Is already a lot better, bút splash screen still triggers a url-change.

**Comment by jheeffer** [comment]
Fixed, but splashscreen is still hacky.
