### ISSUE TITLE
Full screen button

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#92]
a) Expand button should first say "Full screen",
 when in fullscreen: Expand button, should change; text "Leave full screen" and arrows of icon shoul dbe pointing to center

**Comment by angieskazka** [comment]
@arthurcamara1  i am trying to understand how buttons are built and took this issue on the way

@olarosling such long labels! Are you sure? 

![image](https://cloud.githubusercontent.com/assets/3648190/7202411/424caffc-e512-11e4-99ee-010e4731479b.png)
![image](https://cloud.githubusercontent.com/assets/3648190/7202421/67b9e0ca-e512-11e4-84f3-4c8241378dc5.png)


Should we pick one of suggested synonyms or allow several lines of text?
**Full screen**: Expand, Enlarge, Theater, Dominate, Fullscreen, Go big
**Leave full screen**: [labels not change, but icon does], Restore, Minify, Go small

**Comment by angieskazka** [comment]
allright, let it be "Go big" and "Go small" for now. Will reopen if any objections from @olarosling
