### ISSUE TITLE
v0.8.7 _01: “Lock” and “Trails” options are not available after selecting a bubble

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#920]
**SEVERITY:** Major

**MODULE:** Stage 

**Platform:** Windows 7 / Chrome 48.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://stage-tools.gapminderdev.org/tools 
2)	Tools page is loaded.
3)	Select any bubble
4)	Note that “Lock” and “Trails” options are not available after selecting the bubble

**ACTUAL RESULTS:**
“Lock” and “Trails” options are not available after selecting a bubble
 
**EXPECTED RESULTS:** 
“Lock” and “Trails” options should be available after selecting a bubble

**SCREENSHOT:**

![v0 8 7 _01](https://cloud.githubusercontent.com/assets/9950837/11111392/afe49252-892a-11e5-9362-0756f099661d.png)

**Comment by angieskazka** [comment]
related to #899
