### ISSUE TITLE
v0.8.7 _02: “Show” and “X and Y” options are missing

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#921]
**SEVERITY:** Major

**MODULE:** Stage 

**Platform:** Windows 7 / Chrome 48.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://stage-tools.gapminderdev.org/tools/mountain 
2)	Tools page mountain chart is loaded.
3)	Note that “Show” and “X and Y” options are missing

**ACTUAL RESULTS:**
“Show” and “X and Y” options are missing 

**EXPECTED RESULTS:** 
“Show” and “X and Y” options should be available on the chart

**SCREENSHOT:**

![v0 8 7 _02](https://cloud.githubusercontent.com/assets/9950837/11111404/cc994c30-892a-11e5-8ef5-85ea8b94020e.png)

**Comment by angieskazka** [comment]
related to #899
