### ISSUE TITLE
v0.8.7_03 : Size scale bar is disturbed by expanding screen

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#925]
**SEVERITY:**  Minor

**MODULE:**  Bubble Chart.

**Platform:**
* Windows 7 / Chrome 48.0
* Windows 7 / Firefox  43.0

**RELEASE:** v0.8.7

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.8.7/preview/bubblechart.html
2)	Bubble Chart will be loaded.
3)	Click “Size”
4)	Drag the max pointer to the right most side
5)	Click “Expand” without closing “Size” pop up screen
6)	Note that max pointer is at mid of the size scale bar. When we click “Restore” , the max pointer will remain at the center of size slide bar

**ACTUAL RESULTS:**
Size scale bar is disturbed by expanding screen 

**EXPECTED RESULTS:**
Size scale bar should remain same by expanding or restoring screen size 

**SCREENSHOT:**

![v0 8 7_03 1](https://cloud.githubusercontent.com/assets/9950837/11116905/75d7a1b2-8957-11e5-9835-ad03618399f7.png)

![v0 8 7_03 2](https://cloud.githubusercontent.com/assets/9950837/11116906/75d97744-8957-11e5-84ce-03ae353bad69.png)

**Comment by angieskazka** [comment]
can reproduce on v0.8.7, but not now. probably 1f9c1d958043f48ba520b585f0ba62c774af5760 fixed the issue
