### ISSUE TITLE
v0.8.7_05: X axis scale marking is disappeared  

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#927]
**SEVERITY:**  Major

**MODULE:**  Mountain Chart

**Platform:** Windows 7 / Chrome 48.0

**RELEASE:** v0.8.7

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.8.7/preview/mountainchart.html
2)	Mountain Chart will be loaded.
3)	Click “Landscape” under RESPOSIVENESS
4)	Click “Present” on the chart
5)	Note that X axis scale marking is disappeared  

**ACTUAL RESULTS:**
X axis scale marking is disappeared by clicking “Present” on landscape mod

**EXPECTED RESULTS:**
X axis scale marking should not disappeared by clicking “Present” on landscape mod

**SCREENSHOT:**

![v0 8 7_05](https://cloud.githubusercontent.com/assets/9950837/11116998/1a0db816-8958-11e5-85d8-2776deaab8c8.png)

**Comment by angieskazka** [comment]
fixed by d45aca844067d6170bb1dc4f0d7ffbad5c9ba1ae
