### ISSUE TITLE
v0.8.7_07: Boundary line of dropdown box is missing  

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#929]
**SEVERITY:**  Minor

**MODULE:**
* Mountain Chart
* Bubble chart
* Line chart
* Pop by age chart
* Bar chart

**Platform:**  Windows 7 / Firefox  43.0

**RELEASE:** v0.8.7

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.8.7/preview/mountainchart.html
2)	Mountain Chart will be loaded.
3)	Click “Color” 
4)	Click drop down arrow
5)	Note that right boundary line of dropdown box is missing  

**ACTUAL RESULTS:**
Right boundary line of dropdown box of colors is missing  

**EXPECTED RESULTS:**
All boundary lines should be marked properly

**SCREENSHOT:**

![v0 8 7_07](https://cloud.githubusercontent.com/assets/9950837/11117087/bfc18c2e-8958-11e5-92d2-058238fafa88.png)

**Comment by arthurcamara1** [comment]
This picker is/will be replaced. Let's put it on hold for now

**Comment by angieskazka** [comment]
this selector is removed now =)
