### ISSUE TITLE
Historychange event is triggered at wrong times

### ISSUE THREAD

**Issue by jheeffer** [Gapminder/vizabi#936]
A needupdate event now triggers the historychange event to the external page. The needupdate is triggered whenever dialogues should close (also when there's no dialog) and through setting a needupdate property in the entities model. A clever hack but it's not resulting in the correct behaviour and has unwanted side effects.

A more correct solution is refactoring of the events-system so that change events can be either persistent or not. A persistent change event would replace the needupdate event. This requires passing event objects instead of a string when propagating.

A persistent change event on tool level then triggers a historychange event which the browser can use to update the URL and/or browsing history.

Possibly the name historychange of the event to the external page should be changed (it doesn't describe the event which happened in Vizabi). 
Maybe just passing the change event to the page is the easiest and best.

This will also fix #916, #917 and will allow external pages to handle #932 as they wish.

**Comment by jheeffer** [comment]
If we change the event to the external page I guess that would mean we change the public api and thus going to 0.9 according to semver @arthurcamara1 @angieskazka?

**Comment by angieskazka** [comment]
can you also look into #932 together with the event issues?

**Comment by jheeffer** [comment]
Yep, think it's all part of this bigger thing event & public API thing, but I need your input on the API too, I don't want it to be a one-sided thing where it's just my ideas.

**Comment by angieskazka** [comment]
:+1:

**Comment by jheeffer** [comment]
@arthurcamara1 
I'm rethinking the event registration to have a eventType, targetPath and function, so that you can register with `this.model.on('change', 'marker.axis_x.min', function() {})` which will be translated to `this.model.marker.axis_x.min.on('change', function() {})`.

Question: what would be the right form for the 'many registrations in one go' object parameter? It's mainly used as this.model_binds, the predefined bindings in tools/components before the model is ready.

```javascript
this.model_binds = {
    // 1. event type with array to allow multiple path-function combinations
    change: [
        // 2. path single value, function array: bind multiple functions to one event
        {
            path: 'marker.axis_x.min',
            func: [ function1, function2 ]
        },
        // 3. path array, function single: bind one function to different events (of one eventType)
        {
            path: ['entities.show', 'entities2.show'],
            func: function3
        }
    ],
    // 4. medium: evenType with one object with path-function combination
    init: {
        path: 'marker.axis_y.max',
        func: function4
    },
    // 5. simple: evenType with the function to bind to it
    ready: function5
}
```

How much flexibility should we allow?
Should every value (path or function) be either a value or array of values?
Should event types be able to have functions, objects and arrays as values (1, 4 and 5).
And is the above even a good notation? Below you can compare it with a less flexible, simple but readable notation, containing the same info as the upper.

```javascript

// complex, flexible, concise
this.model_binds = {
    change: [
        {
            path: 'marker.axis_x.min',
            func: [ function1, function2 ]
        },
        {
            path: ['entities.show', 'entities2.show'],
            func: function3
        }
    ],
    init: {
        path: 'marker.axis_y.max',
        func: function4
    },
    ready: function5
}

// simple, not flexible, verbose
this.model_binds = [{
        type: 'change',
        path: 'marker_axis_x.min',
        func: function1
    },{
        type: 'change',
        path: 'marker_axis_x.min',
        func: function2
    },{
        type: 'change',
        path: 'entities.show',
        func: function3
    },{
        type: 'change',
        path: 'entities.show2',
        func: function3
    },{
        type: 'init',
        path: 'marker.axis_y.max',
        func: function4
    },{
        type: 'ready',
        func: function5
    }
}
```

**Comment by angieskazka** [comment]
1) that looks like an overly complicated syntax: adds 2 lines per function call and the need to remember "change", "path", "func" thing. 

but of course we can get used to it if it's needed

3) not sure if putting `ready` and `init` inside model_binds is cool. isn't it better to have less of nested things?

2) looks not related to the original issue, but rather like some by-optimisation

so, i'm not very excited, but i might not see all the benefits the new syntax suggests. 
i suggest wait and see what @arthurcamara1 says

**Comment by angieskazka** [comment]
to bind many functions to one change item we now do something like this:
so it's possible

```
      "change:entities:select": function() {
        if(!_this._readyOnce) return;
        _this.selectDataPoints();
        _this.redrawDataPoints();
        _this._trails.run(["resize", "recolor", "opacityHandler","findVisible", "reveal"]);
        _this.updateBubbleOpacity();
        _this._updateDoubtOpacity();
      },
```

**Comment by arthurcamara1** [comment]
So far, we've had the type and the path together as "change:state:marker". The type is change, the path is the rest. While keeping those two together seems to be semantically confusing, it has a few advantages:

1. We can write events as key-value pairs:

this.model.on({
     "change:state": function(){},
     "change:language": [func1, func2]
});

2. It's very simple to write, less verbose and shorter.

3. It's simple to compare, we just compare the full string to match events, no need to check type and path.

4. It ultimately involves less object manipulation.

So while I am convinced that fixing the events for updates and URL is needed, I'm not so convinced this syntax is an improvement of the syntax as a whole.

I agree with you that some changes should be marked as persistent, and also that persistent is a bette name than historyChange. But that could also be just another event with parameters or even a parameter passed when triggering each "change" event callback.

**Comment by arthurcamara1** [comment]
We could also opt for something like `change:state.marker.size`

**Comment by arthurcamara1** [comment]
@angieskazka @jheeffer

**Comment by jheeffer** [comment]
@angieskazka 
1) What would be a better syntax? The current syntax (on('change:marker:axis_x:max', func)) combines the event type and path in one string variable. We could leave it as syntactic sugar for setting the events, while using the separated version on a programming level. Preferably what Arthur says 'change:marker.axis_x.max'.

2) correct, while working on events, I figured this would be a good fix too. This will remove a lot of string functions that were used before when registering and triggering events.

3) ready and init are just examples for events that are actually in Vizabi and that are used at some places in the model_binds

**Comment by arthurcamara1** [comment]
I didn't understand point 2, @jheeffer

**Comment by jheeffer** [comment]
For example the splits/joins in
https://github.com/Gapminder/vizabi/blob/develop/src/base/events.js#L50-L68
https://github.com/Gapminder/vizabi/blob/develop/src/base/events.js#L120-L124

**Comment by jheeffer** [comment]
To your previous post @arthurcamara1 

1. Yes the key-value pair notation is very easy to read, concise and simple. That's why keeping it as syntactic sugar could be alright, for the API. But we'd pull it apart internally to type and path right away.

2. For comparison: when would you compare? I believe right now only in unbinding you're using a comparison of some sort. Unbind is (1) not used anywhere and (2) not working because it was written for the old way of registering (to 'this' instead of first descending down the path). That's why we should refactor it now to unbind(eventType[, path][, function]). This way you can:
1. unbind specific functions or all functions at once
2. do so on descendants
3. do so for any eventType. Possibly leaving out eventType could unbind all events altogether (though we have unbindall for that now, which can again be kept for syntactic sugar)

3. Not sure what you mean with object manipulation. There's no need to manipulate the objects, just read them out. While the other notation requires string-manipulation (splits/joins).

**Comment by jheeffer** [comment]
fixed with event refactoring https://github.com/Gapminder/vizabi/commit/e942f03007299f397d71e5578f37b14feed04185
