### ISSUE TITLE
v0.8.8_02: More space should be there under size scale bar 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#938]
**SEVERITY:** Minor

**MODULE:** Stage 

**Platform:** 
* Windows 7 / Chrome 48.0
* Windows 7 / Firefox 43.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://stage-tools.gapminderdev.org/tools/ 
2)	Tools page is loaded.
3)	Click “Options”
4)	Note that there is less space under size scale bar

**ACTUAL RESULTS:**
There is less space under size scale bar in options

**EXPECTED RESULTS:** 
More space should be there under size scale bar 

**SCREENSHOT:**

![v0 8 8_02](https://cloud.githubusercontent.com/assets/9950837/11139937/f5a30482-89f6-11e5-965d-da6f7812a096.png)

**Comment by jheeffer** [comment]
Should be done with a redesign of options that we talked about before.
