### ISSUE TITLE
hover in find-list

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#94]
In the find list, on desktop, when hovering the list of countrynames, the corresponding bubble chouls react in the chart, just like when it is hovered in the chart. Use the hover property of the entity-set state  property.
![image](https://cloud.githubusercontent.com/assets/496398/7112779/79842b82-e1cd-11e4-9276-371271fae6a5.png)

**Comment by arthurcamara1** [comment]
Sure, sounds good

On Mon, Apr 13, 2015 at 11:10 AM, olarosling <notifications@github.com>
wrote:

> Assigned #94 <https://github.com/Gapminder/vizabi/issues/94> to
> @arthurcamara1 <https://github.com/arthurcamara1>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Gapminder/vizabi/issues/94#event-279562511>.
>



-- 

*Arthur Camara*
*Software Engineer*
Gapminder Foundation
www.gapminder.org
