### ISSUE TITLE
Reduce size of urls derived from Vizabi's minState

### ISSUE THREAD

**Issue by arthurcamara1** [Gapminder/vizabi#942]
Currently Vizabi triggers an event called `historyUpdate`, which receives an object with the difference between the _current state_ and the _default state_ in order to produce the minimal URL possible.

However, this object includes information that is "default" but not included in the `default_options` object, but in metadata instead (like min/max and palette).

We need to figure out how to better set it up so that a URL like this:
```
http://www.gapminder.org/tools/mountain#_entities_show_geo@=arg;;;&marker_axis%2F_y_min:0&max:2568192312.136342&fakeMin:0&fakeMax:2568192312.136342;&axis%2F_x_fakeMin:0.11&fakeMax:500;&color_palette_asi=%23FF5872&eur=%23FFE700&ame=%237FEB00&afr=%2300D5E9&%2F_default=%23ffb600
```

Can be reduced to this:

```
http://www.gapminder.org/tools/mountain#_entities_show_geo@=arg;;;
```

**Comment by jheeffer** [comment]
When loading metadata, save it to the default state?

**Comment by arthurcamara1** [comment]
Good idea @jheeffer. :+1:  The problem now is how to preload metadata in a consistent way and how to define what's supposed to be saved or not to default state, otherwise it will be just a work around.

One way would be to define separately in metadata parts of state that should be stored - it should ideally even be separate from metadata, since it has nothing to do with metadata.

But I think this is a good start and will solve the problem right away for the tools page. Awesome :)

**Comment by arthurcamara1** [comment]
So, I solved this in a hacky way:

**BEFORE**
http://stage-tools.gapminderdev.org/tools/bubbles#_marker_axis%2F_y_min:0&max:550&fakeMin=0.0&fakeMax=550;&axis%2F_x_min:300&max:130000&fakeMin=300&fakeMax=130000

**AFTER**
http://dev-tools.gapminderdev.org:3001/tools/bubbles#_

we now need the right way (but not in this release): #961
