### ISSUE TITLE
Dialog content in sidebar is disappeared on Safari

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#943]
Vizabi v0.8.8
Max + OS X El Capitan + Safari 9

go to bubble chart
resize window to large profile, so that the side bar appears -- everything looks ok
resize back to medium
open color dialog in medium profile -- looks fine
resize window to large profile
note that the color dialog content box is disappeared

expected result: the color dialog content box should not be disappeared =)

![image](https://cloud.githubusercontent.com/assets/3648190/11163472/5b0cd7a4-8ad2-11e5-84fe-967308943eae.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1023
