### ISSUE TITLE
Further improvements of bubble map

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#949]
Thanks @jdk137  :clap: :heart_eyes: 
The bubble map starts to take the form and i certainly like what i see! Here are the further improvements

![image](https://cloud.githubusercontent.com/assets/3648190/11171906/13b18f32-8bfc-11e5-8e3b-84db4ec4b86c.png)

1) indicator is not translated. It should be =) 

![image](https://cloud.githubusercontent.com/assets/3648190/11171913/32c95ecc-8bfc-11e5-8ad5-8c0c8c5154fd.png)

2) Indicator should use tree menu on click. See how it's done in bubble chart

![image](https://cloud.githubusercontent.com/assets/3648190/11171950/6465549e-8bfd-11e5-8a9f-4692d2e4aa88.png)

3) Control opacity of bubbles with JS, not CSS. Copy and adapt the logic of updateBubbleOpacity() function (there are tricky combinations that's why we discarded CSS earlier).
One visible improvement: while one bubble is selected, other bubbles have to dim (become more transparent)

4) ~~Standardise your CSS to vizabi variables~~ oops, just did it

5) Adapt label system from bubble-chart: labels positioned relative to bubbles, not to cursor. The labels of selected bubbles stay on screen. Bubbles can be unselected by clicking a little cross in the corner of the label. User can drag labels to position them how preferred

![image](https://cloud.githubusercontent.com/assets/3648190/11171989/d969d21a-8bfd-11e5-81e4-08854f6dd85a.png)

Like in Gapminder World:
![image](https://cloud.githubusercontent.com/assets/3584238/11186982/ae90b888-8c84-11e5-95f9-2f81d9ec56ca.png)

6) If i select bubbles and set size to GDP, the selection text about population is not working anymore :-D
Replace "people" with the `unit` of the size hook

![image](https://cloud.githubusercontent.com/assets/3648190/11172015/899a916a-8bfe-11e5-99ac-800409faaa45.png)

7) Connected views: 
* Hover country in select list, bubble gets highlighted. 
* Hover region in color legend: all bubble of the region get highlighted
listen to `entities.highlight` array in bubble map. see bubble chart or mountain chart for example

![image](https://cloud.githubusercontent.com/assets/3648190/11180134/b7a9aa50-8c58-11e5-9767-08406e5b5b5b.png)

**estimated time: a week from now**

**Comment by arthurcamara1** [comment]
It would also be nice to keep the same ordering system from Mountain Chart for the list of countries.

This is Bubble Map (alphabetical):
![image](https://cloud.githubusercontent.com/assets/3584238/11180400/d6ebf16e-8c5a-11e5-8796-eb45126c8c86.png)

This is Mountain Chart (by region and desc ordered by population):
![image](https://cloud.githubusercontent.com/assets/3584238/11180404/de60abf6-8c5a-11e5-92d0-d37583c587e6.png)

**Comment by angieskazka** [comment]
@arthurcamara1 @jdk137 agree but let's wait sorting the list before @olarosling approves we should have one ;)

**Comment by arthurcamara1** [comment]
Two more improvement points:

- opacity of non-selected bubbles: when one bubble is selected, all the others become more transparent. Check out bubble chart for an example

- remove meridian and latitude lines. It would look something like this:

![image](https://cloud.githubusercontent.com/assets/3584238/11187100/527ed588-8c85-11e5-9ce4-fad30eee793a.png)

**Comment by angieskazka** [comment]
all done and finished in e874126fe16e7408bffa77ca106b36dbf1443fae
