### ISSUE TITLE
Keep labels on top when hovering

### ISSUE THREAD

**Issue by arthurcamara1** [Gapminder/vizabi#950]
When hovering a specific label, bring it to the top so that both the label and the close button "x" are in front of any other labels.

It would avoid close buttons to be cropped like this: 
![image](https://cloud.githubusercontent.com/assets/3584238/11180196/149839ac-8c59-11e5-9e88-bdc290ef4018.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1290
