### ISSUE TITLE
Unify labels in the code as a single helper

### ISSUE THREAD

**Issue by arthurcamara1** [Gapminder/vizabi#951]
We now have labels with different implementations across charts. Bubble Chart, ~~Mountain Chart~~, Bubble Map, they can all make use of the same label implementation since they all have almost identical features (draggable, appear on hover, etc).

~~The task here is to propose a good solution across multiple charts and implement it. Feel free to post suggestions / questions here before PR if you're unsure on how to solve it in the best way.~~

**Comment by angieskazka** [comment]
Take bubble chart label system as the basis, with all it's dragging and leash-connection methods 
Move it to "helpers" folder as a standalone file
Organise it like a D3 plugin (see for instance d3.axisWithLabelPicker.js)
Re-integrate it to bubble chart and bubble map
