### ISSUE TITLE
Rename use: "value" to use: "constant"

### ISSUE THREAD

**Issue by arthurcamara1** [Gapminder/vizabi#952]
Hooks are normally used to determine which properties or indicators are used in each model. The example below determines population values should be used for `axis_x`:

```javascript
axis_x: {
    use: "indicator",
    which: "pop"
}
```

**However**, we can also define use as "value", which determines that the hook has a **constant** value.

The example below, for instance, determines that the value for axis_x should always be 40

```javascript
axis_x: {
    use: "value",
    which: 40
}
```

"value" is not a very descriptive word. "constant" would be better. Rename it so that we would write the following for constant values:

```javascript
axis_x: {
    use: "constant",
    which: 40
}
```

**Comment by plward11** [comment]
I've been a longtime admirer of Gapminder's inspirational and empowering work. If it's acceptable, I'd like to contribute what I can to Vizabi.

I just issued a pull request for this issue. I sanity checked basic functionality of each chart on the following browser/platforms:

- Windows 7 / Chrome 46
- Windows 7 / Firefox 42
- Mac OS X Yosemite / Chrome 46
- Mac OS X Yosemite / Firefox 42
- Nexus 5 / Android 6.0 / Chrome 46

**Comment by angieskazka** [comment]
thanks a lot!

**Comment by plward11** [comment]
Happy to contribute! :)
