### ISSUE TITLE
v0.8.8_06: Warning text is not aligned with X axis description

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#954]
**SEVERITY:**  Minor

**MODULE:** Bubble chart

**Platform:**
* Windows 7 / Chrome 48.0
* Windows 7 / Firefox  43.0
* MAC / Safari 9.0

**RELEASE:** v0.8.8

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.8.8/preview/bubblechart.html
2)	Bubble Chart will be loaded.
3)	Note that warning text is not aligned with X axis description

**ACTUAL RESULTS:**
Warning text is not aligned with X axis description 

**EXPECTED RESULTS:**
Warning text should align with X axis description 

**SCREENSHOT:**

![v0 8 8_06](https://cloud.githubusercontent.com/assets/9950837/11181257/9b0d9a3a-8c82-11e5-825e-2ae1a789fff6.png)

**Comment by angieskazka** [comment]
same thing as with "?", need to check alignment on different platforms

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/989
