### ISSUE TITLE
v0.8.8_08: X axis scale marking is not according to check boxes

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#956]
**SEVERITY:**  Minor

**MODULE:** Mountain chart

**Platform:**
* Windows 7 / Chrome 48.0
* Windows 7 / Firefox  43.0

**RELEASE:** v0.8.8

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.8.8/preview/mountainchart.html
2)	Mountain Chart will be loaded.
3)	Click “X and Y”
4)	All check boxes are marked checked under “X-axis logarithmic stops”
5)	Close the small pop up screen
6)	Note that X axis scale marking is not according to check boxes

**ACTUAL RESULTS:**
X axis scale marking is not according to check boxes. Values for check box 5 are missing.

**EXPECTED RESULTS:**
X axis scale marking should be according to check boxes 

**SCREENSHOT:**

![v0 8 8_08 1](https://cloud.githubusercontent.com/assets/9950837/11181333/045fd32c-8c83-11e5-9872-569d4671de16.png)

![v0 8 8_08 2](https://cloud.githubusercontent.com/assets/9950837/11181334/04617f24-8c83-11e5-8df7-0ecdeb3b7910.png)

**Comment by angieskazka** [comment]
it's ok, they hide when they don't fit
where is my "it's not a bug, it's a feature" label? @valorkin
