### ISSUE TITLE
v0.8.8_10: Slider ball is not sync with the year

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#958]
**SEVERITY:**  Major

**MODULE:**
* Mountain chart
* Bubble chart
* Bar chart
* Line chart
* Bar chart

**Platform:**
* Windows 7 / Chrome 48.0
* Windows 7 / Firefox  43.0
* MAC / Safari 9.0

**RELEASE:** v0.8.8

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.8.8/preview/mountainchart.html
2)	Mountain Chart will be loaded.
3)	Drag the slider ball to the start
4)	Click play
5)	Hold the slider ball while playing and drag it to the end of slide bar on the right side. Do this rapidly. 
6)	Note that slider ball is at the end of slide bar but the year is at the start of slide bar

**ACTUAL RESULTS:**
Slider ball is at the end of slide bar but the year is at the start of slide bar. It happened by dragging slider ball to the end while playing.

**EXPECTED RESULTS:**
Year should be shown with the slider bar in any case

**SCREENSHOT:**

![v0 8 8_10](https://cloud.githubusercontent.com/assets/9950837/11181377/6cf612d4-8c83-11e5-8ecf-a53ef833a9ae.png)

**Comment by angieskazka** [comment]
Same as #962 Time slider year in wrong position when playing, then dragging 
Dab fixed this recently
