### ISSUE TITLE
v0.8.8_11: Chart is disturbed by clicking “Restore” (on Firefox)

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#959]
**SEVERITY:**  Major

**MODULE:**
* Mountain chart
* Bubble chart
* Bar chart
* Line chart
* Bar chart

**Platform:**  Windows 7 / Firefox  43.0

**RELEASE:** v0.8.8

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.8.8/preview/mountainchart.html
2)	Mountain Chart will be loaded.
3)	Click “Expand”
4)	Click play
5)	Click “Restore”
6)	Note that chart is disturbed by clicking “Restore” button while playing

**ACTUAL RESULTS:**
Chart is disturbed by clicking “Restore” button while playing 

**EXPECTED RESULTS:**
Chart should not disturbed in any case

**SCREENSHOT:**

![v0 8 8_11](https://cloud.githubusercontent.com/assets/9950837/11181405/a847bbf8-8c83-11e5-9282-0647786f5f1c.png)

**Comment by arthurcamara1** [comment]
Is it like that on toolspage as well? Might be a preview page issue

**Comment by angieskazka** [comment]
i guess it was fixed with animation interruption in time slider. not reproduced on my firefox / win7
