### ISSUE TITLE
trail-connector should be hidden at trailstart

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#96]
When having drawn a trail, and then moving back to the first year, I see a little colored line, which is the remaining part of the initial trail. The red line form China bubble in this screenshot
![image](https://cloud.githubusercontent.com/assets/496398/7134358/735d1172-e29c-11e4-8e0a-47a7f59cc885.png)

**Comment by angieskazka** [comment]
Yes, it's not yet fixed. Same :beetle: is when you press play and the connector appears earlier than expected, jumping in front of a leading bubble

**Comment by angieskazka** [comment]
Done for all cases except when time animation keyframes fall in between years =/ this is not trivial
Lets just assume that animation keyframes always correspond the trail segments and move on

Also the development triggered issue #108
