### ISSUE TITLE
v0.8.8_12: Tool tip of selected country is truncated

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#964]
**SEVERITY:** Major

**MODULE:** Bubble Chart

**Platform:**
* MAC / Safari 9.0
* Windows 7 / Chrome 48.0
* Windows 7 / Firefox 43.0

**RELEASE:** v0.8.8

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.8/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Click “Options”. A small pop up screen is displayed
4)	Scroll down and click the check box under presentation
5)	Click “Find” and select “Central African Republic”
6)	Note that tool tip of selected country is truncated

**ACTUAL RESULTS:**
Tool tip of selected country is truncated 

**EXPECTED RESULTS:** 
Tool tip of selected country should not be truncated 

**SCREENSHOT:**

![v0 8 8_12](https://cloud.githubusercontent.com/assets/9950837/11209200/91bef3ba-8d41-11e5-8ca3-249d6cd93aef.png)

**Comment by angieskazka** [comment]
we should disallow presentation mode on small profile: make buttons and checkboxes not clickable when small profile and grey them out (disabled state)

**Comment by angieskazka** [comment]
done
