### ISSUE TITLE
v0.8.8_13: Manual sorting of group is not working

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#965]
**SEVERITY:** Major

**MODULE:** Mountain Chart

**Platform:** MAC / Safari 9.0

**RELEASE:** v0.8.8

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.8/preview/mountainchart.html 
2)	Mountain chart page will be loaded
3)	Click “Stack”. A small pop up screen is displayed
4)	Hold any group given on the pop up screen and try to sort it according to your will
5)	Note that manual sorting of group is not working

**ACTUAL RESULTS:**
Manual sorting of group is not working 

**EXPECTED RESULTS:** 
Manual sorting of group should work 

**SCREENSHOT:**

![v0 8 8_13](https://cloud.githubusercontent.com/assets/9950837/11209263/eaf50122-8d41-11e5-8e70-09464dba74c5.png)

**Comment by angieskazka** [comment]
ok, now it does
