### ISSUE TITLE
v0.8.8_15: Axis values are missing for selected country

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#967]
**SUMMARY:**
**1)** Axis values are missing for selected country
**2)** ‘x’ close icon is missing on tool tip of selected country

**SEVERITY:** Major

**MODULE:** Bubble Chart

**Platform:** 
* iPad Air 2 iOS(9.1) / Safari
* iPhone 4(iOS 7.1) / Safari 

**RELEASE:** v0.8.8

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.8/preview/bubblechart.html
2)	Bubble chart page will be loaded
3)	Select a country like “United States”
4)	Tool tip is shown for the selected country
5)	Tap over the tool tip
6)	Note that no close icon is displayed by tapping the tooltip of selected country
7)	Also note that axis values are also missing for the selected country

**ACTUAL RESULTS:**
After selecting a country the axis values of that country are missing. And the cross icon is also missing on tooltip of selected country

**EXPECTED RESULTS:** 
After selecting a country the axis values should be available and cross icon should also be there on tooltip on tapping the tooltip

**SCREENSHOT:**

![v0 8 8_15](https://cloud.githubusercontent.com/assets/9950837/11209416/bc2d5622-8d42-11e5-8c44-87d754ea0525.PNG)

**Comment by angieskazka** [comment]
disabled on touch devices
