### ISSUE TITLE
Browser back button doesn't work, afteer I change color by region to color by indicator

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#969]
@olarosling

**Comment by arthurcamara1** [comment]
Related to https://github.com/Gapminder/vizabi/issues/936

@jheeffer is on it . We have discussed how this needs to be solved and solving #936 will solve this too.

**Comment by jheeffer** [comment]
Browser back button now brings you to previous page, after changing colour to indicator.

**Comment by jheeffer** [comment]
https://github.com/Gapminder/vizabi/commit/e942f03007299f397d71e5578f37b14feed04185
