### ISSUE TITLE
v0.8.8_16: Year on the slider ball is truncated

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#974]
**SEVERITY:** Major

**MODULE:**  Bubble Chart

**Platform:** iPhone-4G(iOS 7.1.2)/ Safari

**RELEASE:** v0.8.8

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.8/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Tap play
4)	Note that year on the slider ball is truncated

**ACTUAL RESULTS:**
Year on the slider ball is truncated 

**EXPECTED RESULTS:** 
Year on the slider ball should not be truncated 

**SCREENSHOT:**

![v0 8 8_16](https://cloud.githubusercontent.com/assets/9950837/11236832/e558e924-8dfd-11e5-8aea-ef1bfcce6b7a.PNG)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1013

**Comment by k6Labz** [comment]
Retest Result: Pass

Platform: iPhone-4G(iOS 7.1.2)/ Safari

Testing Environment: http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1097

**Comment by k6Labz** [comment]
**Retest Result:** Fail

**Platform:** iPhone-4G(iOS 7.1.2)/ Safari

**Testing Environment:** http://static.gapminderdev.org/vizabi/release/v0.9.2/preview/bubblechart.html

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1238
