### ISSUE TITLE
v0.8.8_17: Slider ball is not moving according to the year

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#975]
**SEVERITY:** Major

**MODULE:**  Bubble Chart

**Platform:** iPhone-4G(iOS 7.1.2)/ Safari

**RELEASE:** v0.8.8

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.8/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Select a bubble
4)	Tap play
5)	Note that slider ball is not moving according to the year

**ACTUAL RESULTS:**
Slider ball is not moving according to the year. Slider ball remains at the end of the slide bar.

**EXPECTED RESULTS:** 
Slider ball should move according to the year 

**SCREENSHOT:**

![v0 8 8_17](https://cloud.githubusercontent.com/assets/9950837/11236857/1810218e-8dfe-11e5-9ce8-3d1e43b055e4.PNG)

**Comment by sergey-filipenko** [comment]
Can not reproduce, retest please

**Comment by k6Labz** [comment]
It is reproducing on my device.
Retest Result: Fail

Platform: iPhone-4G(iOS 7.1.2)/ Safari

Testing Environment: http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html

**Comment by angieskazka** [comment]
@sergey-filipenko can it be a performance issue?

**Comment by sergey-filipenko** [comment]
@angieskazka not sure. I also use 4G for checking problem

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1104

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1105

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Platform:** iPhone-4G(iOS 7.1.2)/ Safari

**Testing Environment:** http://static.gapminderdev.org/vizabi/develop/preview/bubblemap.html
