### ISSUE TITLE
v0.8.8_19: Scroll bar is missing on data warning pop up

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#977]
**SEVERITY:** Minor

**MODULE:**  Bubble Chart

**Platform:** iPhone-4G(iOS 7.1.2)/ Safari

**RELEASE:** v0.8.8

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.8/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Tap Data warning which is available on the right bottom of the chart
4)	Small pop up screen is displayed
5)	Note that scroll bar is missing on data warning pop up

**ACTUAL RESULTS:**
Scroll bar is missing on data warning pop up 

**EXPECTED RESULTS:** 
Scroll bar should be available on data warning pop up

**SCREENSHOT:**

![v0 8 8_19](https://cloud.githubusercontent.com/assets/9950837/11236927/84a520ba-8dfe-11e5-8146-f692a5725541.PNG)

**Comment by arthurcamara1** [comment]
I think our scrollbars are never shown on ios. Can someone double check how we can solve?

**Comment by angieskazka** [comment]
i should have fixed it now, although it's a blind shot as i have no iOS
