### ISSUE TITLE
v0.8.8_20: Text is truncated on Stack pop up screen

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#978]
**SEVERITY:** Minor

**MODULE:**  Mountain Chart

**Platform:** iPhone-4G(iOS 7.1.2)/ Safari

**RELEASE:** v0.8.8

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.8/preview/mountainchart.html 
2)	Mountain chart page will be loaded
3)	Tap “Stack”
4)	Small pop up screen is displayed
5)	Note that word ‘Stack’ is truncated on the small pop up screen

**ACTUAL RESULTS:**
Word ‘Stack’ is truncated on the small pop up screen 

**EXPECTED RESULTS:** 
Text should not be truncated in any case

**SCREENSHOT:**

![v0 8 8_20](https://cloud.githubusercontent.com/assets/9950837/11236981/d16d9da0-8dfe-11e5-9a25-01fb7d6e9e48.PNG)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1075
