### ISSUE TITLE
v0.8.8_21: ‘?’ link is missing with the Y axis description

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#979]
**SEVERITY:** Minor

**MODULE:**  Mountain Chart

**Platform:** iPhone-4G(iOS 7.1.2)/ Safari

**RELEASE:** v0.8.8

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.8/preview/mountainchart.html 
2)	Mountain chart page will be loaded
3)	Note that ‘?’ link is missing with the Y axis description 

**ACTUAL RESULTS:**
‘?’ link is missing with the Y axis description

**EXPECTED RESULTS:** 
‘?’ link should be there with the Y axis description

**SCREENSHOT:**

![v0 8 8_21](https://cloud.githubusercontent.com/assets/9950837/11237026/17f613b0-8dff-11e5-8e29-d33563b55e62.PNG)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1005

**Comment by angieskazka** [comment]
should be fixed now

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Platform:** iPhone-4G(iOS 7.1.2)/ Safari

**Testing Environment:** http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html
