### ISSUE TITLE
v0.8.8_23: Lines are moving ahead from the circle

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#981]
**SEVERITY:** Minor

**MODULE:**  Line Chart

**Platform:** iPhone-4G(iOS 7.1.2)/ Safari

**RELEASE:** v0.8.8

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.8/preview/linechart.html 
2)	Line chart page will be loaded
3)	Tap play
4)	Select a line
5)	Tap in the middle of the slide bar
6)	Tap Play
7)	Note that lines are moving ahead from the circle

**ACTUAL RESULTS:**
Lines are moving ahead from the circle after selecting a line

**EXPECTED RESULTS:** 
Lines should not move ahead from the circle 

**SCREENSHOT:**

![v0 8 8_23](https://cloud.githubusercontent.com/assets/9950837/11237100/85a749ce-8dff-11e5-9dad-237c7a8b8973.PNG)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1256
