### ISSUE TITLE
v0.8.9_01: Heading should be added for better understanding in “Stack” pop up 

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#991]
**SEVERITY:** Minor

**MODULE:** Stage 

**Platform:** 
* Windows 7 / Chrome 46.0
* Windows 7 / Firefox 43.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: https://stage-tools.gapminderdev.org/tools/mountain 
2)	Tools page is loaded.
3)	Click “Stack”
4)	Heading should be added for better understanding in “Stack” pop up for first three radio buttons

**ACTUAL RESULTS:**
There is no heading for three radio buttons in “Stack” pop up screen

**EXPECTED RESULTS:** 
Heading should be added for better understanding in “Stack” pop up screen for first three radio buttons

**SCREENSHOT:**

![v0 8 9_01](https://cloud.githubusercontent.com/assets/9950837/11292508/dba49d50-8f70-11e5-9626-21ddb502207c.jpg)

**Comment by angieskazka** [comment]
it was there. i removed it because it was redundant:

## Stack
### Stack
[x] None  [x] Regions [x] World
