### ISSUE TITLE
v0.8.9_06: Menu tree is disappeared by hovering ‘GDP per capita’

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#999]
**SEVERITY:**  Minor

**MODULE:** Bubble chart

**Platform:**  Windows 7 / Chrome 46.0

**RELEASE:** v0.8.9

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.8.9/preview/bubblechart.html
2)	Bubble chart will be loaded.
3)	Click “Full” under RESPONSIVENESS
4)	Click “Color”
5)	Click dropdown box. Tree menu is displayed.
6)	Take mouse to the wealth. Sub options are displayed
7)	Now take mouse to first option ‘Income distribution’. Sub option ‘Gini coefficient’ is displayed 
8)	Now take mouse to the second option ‘GDP per capita’
9)	Note that wealth sub options are disappeared

**ACTUAL RESULTS:**
Menu tree is disappeared by hovering ‘GDP per capita’ after hovering ‘Income distribution’

**EXPECTED RESULTS:**
Tree menu options should not be disappeared by hovering effect

**SCREENSHOT:**

![v0 8 9_06](https://cloud.githubusercontent.com/assets/9950837/11335649/dd9d7cee-91ff-11e5-83be-54d7109b876d.png)

**Comment by angieskazka** [comment]
the sub panels should be very conservative to closing. they should only close if we open a sibling
also, please remove animation. it jumps back and forth

**Comment by sergey-filipenko** [comment]
fixed, retest please

**Comment by k6Labz** [comment]
**Retest Result:** Pass

**Platform:**  Windows 7 / Chrome 46.0

**RELEASE:** v0.8.9

**Testing Environment:** http://static.gapminderdev.org/vizabi/release/v0.8.9/preview/bubblechart.html
